In [1]:
import tracemalloc

from utils_v1 import *
import traceback


In [2]:
from icecream import ic

import numpy as np
from src.dataset import (
    MultipleDates, PAMultipleDates,
    MTMultipleDates, MSMultipleDates, PIMultipleDates
)

# from src.dataset_legacy import MTDeforestationTime
from src import training_generator as generator
from src.patchesHandler import PatchesHandler, PatchesHandlerMultipleDates, PatchesHandlerEvidential2

from src.manager.evidential import ManagerEvidential
from src.manager.multioutput import ManagerMCDropout, ManagerSingleRun, ManagerEvidential2
from mpl_toolkits.axes_grid1 import make_axes_locatable

import cv2
from src import metrics as _metric
import json
import pickle 
import src.manager.evidential as evidential
from src.Logger import Logger
import pdb
import gc


Tensorflow ver. 2.6.0


In [3]:

with open('config/config.json', 'r') as f:
    config = json.load(f)
    
print("Mode: {}. Site: {}. Training: {}. Training date: {}".format(
    config['mode'], config['site'], config['training'], config['training_date']))
print(config)


Mode: mcd. Site: MS. Training: False. Training date: earlier
{'training': False, 'inferring': True, 'site': 'MS', 'training_date': 'earlier', 'mode': 'mcd', 'training_times': 10, 'uncertainty_method': 'pred_entropy', 'loadInference': False, 'removePolygons': True, 'plotLandsat': False, 'plotPOI': False, 'training_experiment_id': 19, 'get_multiple_metrics': False, 'save_probabilities': False, 'addPastDeforestationInput': True, 'classes_mode': False, 'learning_rate': 0.0001, 'use_cloud_mask': False, 'mask_out_non_biome': False, 'log_filename': 'log_mcd_ms_earlier.pkl'}


In [4]:

if config['site'] == 'PA':
	if config['training_date'] == 'earlier':
		dates = [2017, 2018]
	else:
		dates = [2018, 2019]
	datasetClass = PAMultipleDates
elif config['site'] == 'MT':
	if config['training_date'] == 'earlier':
		dates = [2018, 2019]
	else:
		dates = [2019, 2020]
	datasetClass = MTMultipleDates
elif config['site'] == 'MS':
	if config['training_date'] == 'earlier':
		dates = [2018, 2019]
	else:
		dates = [2019, 2020]
	datasetClass = MSMultipleDates
elif config['site'] == 'PI':
	if config['training_date'] == 'earlier':
		dates = [2018, 2019]
	else:
		dates = [2019, 2020]
	datasetClass = PIMultipleDates
else:
	raise ValueError('Invalid site')

dataset = datasetClass(config = config,
			   dates = dates, 
	 	addPastDeforestationInput = config['addPastDeforestationInput'],
		borderBuffer = 2)	

if config['mode'] == 'ensemble':
	if config['training'] == True:
		config['mode'] = 'single_run'
	else:
		sys.exit("Ensure that training is True for ensemble mode. Use infer_ensemble.ipynb for inference.")

if config['training'] == False:
	if config['site'] == 'PA':
		if config['mode'] == 'mcd' or config['mode'] == 'single_run': # MCD will do 10 inference on each of the 10 repetitions = 100 runs
			if config['training_date'] == 'current': exp = 0
			elif config['training_date'] == 'earlier': exp = 1
				
		if config['mode'] == 'evidential2':
			if config['training_date'] == 'current': exp = 8; repetition_id = 0
			elif config['training_date'] == 'earlier': exp = 9; repetition_id = 0

	elif config['site'] == 'MT':

		if config['mode'] == 'mcd' or config['mode'] == 'single_run':
			if config['training_date'] == 'current': exp = 2
			elif config['training_date'] == 'earlier': exp = 3
		if config['mode'] == 'evidential2':
			if config['training_date'] == 'current': exp = 10; repetition_id = 0
			elif config['training_date'] == 'earlier': exp = 11; repetition_id = 0

	elif config['site'] == 'MS':

		if config['mode'] == 'mcd' or config['mode'] == 'single_run':
			if config['training_date'] == 'current': exp = 4
			elif config['training_date'] == 'earlier': 
				exp = 5
				exp = 18

		if config['mode'] == 'evidential2':
			if config['training_date'] == 'current': exp = 12; repetition_id = 0
			elif config['training_date'] == 'earlier': exp = 13; repetition_id = 0
	elif config['site'] == 'PI':

		if config['mode'] == 'mcd' or config['mode'] == 'single_run':
			if config['training_date'] == 'current': exp = 6
			elif config['training_date'] == 'earlier': exp = 7
		if config['mode'] == 'evidential2':
			if config['training_date'] == 'current': exp = 14; repetition_id = 0
			elif config['training_date'] == 'earlier': exp = 15; repetition_id = 0

else:
	exp = config['training_experiment_id']
ic(dates)


if issubclass(type(dataset), MultipleDates):
	patchesHandler = PatchesHandlerMultipleDates(
		dataset)
elif config['mode'] == 'evidential2':
	patchesHandler = PatchesHandlerEvidential2()
else:
	patchesHandler = PatchesHandler()



ic| list(self.date_ids): [0]
ic| self.image_channels: [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]]
ic| dates: [2018, 2019]
ic| self.input_image_shape: 21
ic| self.dataset.image_channels: [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]]


In [5]:


if config['mode'] == 'evidential2':
    config["inference_times"] = 1
    manager_class = ManagerEvidential2
    config['uncertainty_method'] = "pred_entropy"
    config['classes_mode'] = True
    
if config['mode'] == 'mcd':
    config["inference_times"] = 10
    manager_class = ManagerMCDropout
    config['uncertainty_method'] = "pred_entropy"
    config['classes_mode'] = False

elif config['mode'] == 'single_run':
    config["inference_times"] = 1
    manager_class = ManagerSingleRun
    config['uncertainty_method'] = "pred_entropy_single"
    config['classes_mode'] = False



In [6]:
exp

18

In [7]:
logger = Logger()


In [8]:
if config['training'] == True:
    

    manager = manager_class(config, dataset, patchesHandler, logger)
    print("manager.config['dropout_training']", manager.config['dropout_training'])
    manager.defineExperiment(exp) # fixed
    
    manager.setExperimentPath()
    manager.createLogFolders()

    manager.loadDataset()

    # %%
    if config["training"] == True:
        manager.run()


In [9]:



if config['site'] == 'PA':
	dates = [2018, 2019]
	datasetClass = PAMultipleDates
elif config['site'] == 'MT':
	dates = [2019, 2020]
	datasetClass = MTMultipleDates
elif config['site'] == 'MS':
	dates = [2019, 2020]
	datasetClass = MSMultipleDates
elif config['site'] == 'PI':
	dates = [2019, 2020]
	datasetClass = PIMultipleDates
else:
	raise ValueError('Invalid site')

dataset = datasetClass(config = config,
			   dates = dates, 
	 	addPastDeforestationInput = config['addPastDeforestationInput'],
		borderBuffer = 2)


ic(dates)

if issubclass(type(dataset), MultipleDates):
	patchesHandler = PatchesHandlerMultipleDates(
		dataset)
elif config['mode'] == 'evidential2':
	patchesHandler = PatchesHandlerEvidential2()
else:
	patchesHandler = PatchesHandler()


ic| list(self.date_ids): [0]
ic| self.image_channels: [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]]
ic| dates: [2019, 2020]
ic| self.input_image_shape: 21
ic| self.dataset.image_channels: [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]]


In [10]:
manager_class

src.manager.multioutput.ManagerMCDropout

In [11]:
exp

18

In [12]:
repetition_ids = manager_class(config, dataset, patchesHandler, logger).get_repetition_ids(exp)  
repetition_n = len(repetition_ids)
print("repetition_ids {}, repetition_n {}".format(repetition_ids, repetition_n))


repetition_ids [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], repetition_n 10


In [13]:
if config['inferring'] == True:
    results = []
    error_count = 0

    # while idx < len(repetition_n):
    for idx in range(repetition_n): # 10 repetitions
    # for idx in range(0, 4): # 10 repetitions


        print("Beginning run number {}".format(idx))
        logger = Logger()
        manager = manager_class(config, dataset, patchesHandler, logger)

        print("manager.config", manager.config)

        manager.defineExperiment(exp) # fixed
        manager.defineRepetitionId(idx) # varying from 0 to 10
        manager.setExperimentPath()
        manager.createLogFolders()

        manager.loadDataset()

        # %%
        if config['get_multiple_metrics'] == False:
            predictor_fcn = manager.run_predictor
        else:
            predictor_fcn = manager.run_predictor_multiple_metrics
        result = predictor_fcn()
        print("Result idx {}: {}".format(idx, result))
        results.append(result)


        with open(manager.default_log_name, 'wb') as f:
            pickle.dump(results, f)
        print("Grid execution idx: {}".format(idx))
        del manager
        gc.collect()
        # idx += 1
    

Beginning run number 0
manager.config {'training': False, 'inferring': True, 'site': 'MS', 'training_date': 'earlier', 'mode': 'mcd', 'training_times': 10, 'uncertainty_method': 'pred_entropy', 'loadInference': False, 'removePolygons': True, 'plotLandsat': False, 'plotPOI': False, 'training_experiment_id': 19, 'get_multiple_metrics': False, 'save_probabilities': False, 'addPastDeforestationInput': True, 'classes_mode': False, 'learning_rate': 0.0001, 'use_cloud_mask': False, 'mask_out_non_biome': False, 'log_filename': 'log_mcd_ms_earlier.pkl', 'inference_times': 10, 'dropout_training': True}
D:/Jorge/datasets/deforestation/MS/deforestation_past_years.tif
Loaded deforestation past years


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([334024764,   8717093,   6541094,   3824922,   2096535,   1305948,
                                                                      1003721,    903906,    318788,    701575,    310887,    440417,
                                                                       316180,    560438,    600838,    776899], dtype=int64))


Label where deforestation past years is actual date (2020) = 1


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([334024764,   8717093,   6541094,   3824922,   2096535,   1305948,
                                                                      1003721,    903906,    318788,    701575,    310887,    440417,
                                                                       316180,    560438,    600838,    776899], dtype=int64))


Past deforestation different from 0 (no deforestation)


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([334024764,   8717093,   6541094,   3824922,   2096535,   1305948,
                                                                      1003721,    903906,    318788,    701575,    310887,    440417,
                                                                       316180,    560438,    600838,    776899], dtype=int64))


Past deforestation before 2008 is 2
D:/Jorge/datasets/deforestation/MS/deforestation_before_2000_MS.tif


ic| np.unique(label_past_deforestation_before_2008, return_counts=True): (array([  0, 208], dtype=uint8), array([126708038, 235735967], dtype=int64))
ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([334024764,   8717093,   6541094,   3824922,   2096535,   1305948,
                                                                      1003721,    903906,    318788,    701575,    310887,    440417,
                                                                       316180,    560438,    600838,    776899], dtype=int64))
ic| label_per_date.shape: (18605, 19481, 1)


Removing bufer................
Mask label shape:  
 (18605, 19481, 1) 
 Unique values:  
 [0 1 2]
Tiles size:  3721 3896
Mask size:  (18605, 19480)


ic| image_stack.shape: (18605, 19481, 21)


Image shape:  (18605, 19481, 21)
mask:  (18605, 19480)
image stack:  (18605, 19480, 21)
ref : (18605, 19480, 1)
Training tiles:  [2, 4, 5, 6, 7, 12, 14, 15, 18, 21, 23, 24]
Validation tiles:  [9, 11, 25]
Test tiles:  [1, 3, 8, 10, 13, 16, 17, 19, 20, 22]
-35.0 -8.0


ic| self.path_models+ '/' + self.method +'_'+str(self.repetition_id)+'.h5': 'D:/Jorge/datasets/deforestation/experiments/MS/exp18/models/resunet_0.h5'


Dropout training mode: True
time:  0
time:  1
time:  2
time:  3
time:  4
time:  5
time:  6
time:  7
time:  8
time:  9
(36877090,)
(array([0, 1], dtype=uint8), array([36581631,   295459], dtype=int64))
(18605, 19480)
(array([0., 1.], dtype=float32), array([362014119,    411281], dtype=int64))


ic| self.predicted_unpad.shape: (18605, 19480)
    self.predicted.shape: (18605, 19480)
ic| predicted_test.shape: (144970160,)
ic| predicted_test.shape: (36877090,)
ic| np.unique(predicted, return_counts=True): (array([0., 1.], dtype=float32), array([362014119,    411281], dtype=int64))
    np.unique(predicted_larger_than_min_area, return_counts=True): (array([0., 1.], dtype=float32), array([362052733,    372667], dtype=int64))
ic| np.unique(ignored_polygons, return_counts=True): (array([0., 1.], dtype=float32), array([362386786,     38614], dtype=int64))
ic| self.f1: 86.05, self.precision: 97.66, self.recall: 76.9
ic| self.label_mask_val.shape: (43491048,)
ic| self.label_mask_val_valid.shape: (10772905,)
ic| f1_val: 60.17
    precision_val: 100.0
    recall_val: 43.03
    mAP_val: 49.41


(array([0., 1.], dtype=float32), array([362279778,    145622], dtype=int64))
[0. 1.]
K = 1, pred_mean shape (18640, 19488, 1)


ic| self.label_mask.shape: (18605, 19480)
ic| self.mask_amazon_ts.shape: (18605, 19480)
ic| self.label_mask_test.shape: (144970160,)
ic| self.error_mask_test.shape: (36859162,)
ic| bounds: (0.0015, 0.3663794801235199)
c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\scipy\optimize\_minimize.py:783: RuntimeWarning: Method 'bounded' does not support relative tolerance in x; defaulting to absolute tolerance.
  warn("Method 'bounded' does not support relative tolerance in x; "


0.1408715596097929
threshold 0.1408715596097929


ic| label_current_deforestation_test_classified_incorrect.shape: (912289,)
    predicted_test_classified_incorrect.shape: (912289,)
ic| TP_H + FN_H + FP_H + TN_H: 912289
    len(label_mask_current_deforestation_test): 36859162
ic| TP_H + FN_H + FP_H + TN_H: 912289
    len(label_mask_current_deforestation_test): 36859162


[0.98135892 0.85374638 0.59260712 0.02475067 0.96097533 0.5766681
 0.04165674]
0.22700792051372695
threshold 0.22700792051372695


ic| label_current_deforestation_test_classified_incorrect.shape: (388399,)
    predicted_test_classified_incorrect.shape: (388399,)
ic| TP_H + FN_H + FP_H + TN_H: 388399
    len(label_mask_current_deforestation_test): 36859162
ic| TP_H + FN_H + FP_H + TN_H: 388399
    len(label_mask_current_deforestation_test): 36859162


[0.97938019 0.84826585 0.67120938 0.01053738 0.95799034 0.4684854
 0.07771258]
0.08763636090393405
threshold 0.08763636090393405


ic| label_current_deforestation_test_classified_incorrect.shape: (1717877,)
    predicted_test_classified_incorrect.shape: (1717877,)
ic| TP_H + FN_H + FP_H + TN_H: 1717877
    len(label_mask_current_deforestation_test): 36859162
ic| TP_H + FN_H + FP_H + TN_H: 1717877
    len(label_mask_current_deforestation_test): 36859162


[0.98416824 0.85996826 0.53248359 0.04660651 0.96000282 0.6210748
 0.0254378 ]
0.15354770529833614
threshold 0.15354770529833614


ic| label_current_deforestation_test_classified_incorrect.shape: (802190,)
    predicted_test_classified_incorrect.shape: (802190,)
ic| TP_H + FN_H + FP_H + TN_H: 802190
    len(label_mask_current_deforestation_test): 36859162
ic| TP_H + FN_H + FP_H + TN_H: 802190
    len(label_mask_current_deforestation_test): 36859162


[0.98083974 0.85281328 0.60468322 0.02176365 0.96134157 0.56473382
 0.04592478]
0.12991333141050812
threshold 0.12991333141050812


ic| label_current_deforestation_test_classified_incorrect.shape: (1023088,)
    predicted_test_classified_incorrect.shape: (1023088,)
ic| TP_H + FN_H + FP_H + TN_H: 1023088
    len(label_mask_current_deforestation_test): 36859162
ic| TP_H + FN_H + FP_H + TN_H: 1023088
    len(label_mask_current_deforestation_test): 36859162


[0.98178185 0.85545866 0.58173933 0.02775668 0.96087445 0.58523325
 0.03832885]
0.11376496561837368
threshold 0.11376496561837368


ic| label_current_deforestation_test_classified_incorrect.shape: (1221852,)
    predicted_test_classified_incorrect.shape: (1221852,)
ic| TP_H + FN_H + FP_H + TN_H: 1221852
    len(label_mask_current_deforestation_test): 36859162
ic| TP_H + FN_H + FP_H + TN_H: 1221852
    len(label_mask_current_deforestation_test): 36859162


[0.98263444 0.85776826 0.56465989 0.03314921 0.96033028 0.59797795
 0.03355138]
0.12414023890864863
threshold 0.12414023890864863


ic| label_current_deforestation_test_classified_incorrect.shape: (1088591,)
    predicted_test_classified_incorrect.shape: (1088591,)
ic| TP_H + FN_H + FP_H + TN_H: 1088591
    len(label_mask_current_deforestation_test): 36859162
ic| TP_H + FN_H + FP_H + TN_H: 1088591
    len(label_mask_current_deforestation_test): 36859162


[0.98204756 0.85617797 0.57569434 0.0295338  0.96075657 0.59005204
 0.03658236]
0.12263880499860769
threshold 0.12263880499860769


ic| label_current_deforestation_test_classified_incorrect.shape: (1106708,)
    predicted_test_classified_incorrect.shape: (1106708,)
ic| TP_H + FN_H + FP_H + TN_H: 1106708
    len(label_mask_current_deforestation_test): 36859162
ic| TP_H + FN_H + FP_H + TN_H: 1106708
    len(label_mask_current_deforestation_test): 36859162


[0.98210425 0.856417   0.57412146 0.03002532 0.96076485 0.5912002
 0.03613456]
0.1192492999660656
threshold 0.1192492999660656


ic| label_current_deforestation_test_classified_incorrect.shape: (1148916,)
    predicted_test_classified_incorrect.shape: (1148916,)
ic| TP_H + FN_H + FP_H + TN_H: 1148916
    len(label_mask_current_deforestation_test): 36859162
ic| TP_H + FN_H + FP_H + TN_H: 1148916
    len(label_mask_current_deforestation_test): 36859162


[0.98225496 0.85685973 0.57043752 0.03117043 0.96073787 0.59400449
 0.03512421]
0.12225236642644452
threshold 0.12225236642644452


ic| label_current_deforestation_test_classified_incorrect.shape: (1111327,)
    predicted_test_classified_incorrect.shape: (1111327,)
ic| TP_H + FN_H + FP_H + TN_H: 1111327
    len(label_mask_current_deforestation_test): 36859162
ic| TP_H + FN_H + FP_H + TN_H: 1111327
    len(label_mask_current_deforestation_test): 36859162


[0.98212131 0.85647865 0.57372564 0.03015063 0.96075919 0.59148515
 0.03602289]
0.12294095462305954
threshold 0.12294095462305954


ic| label_current_deforestation_test_classified_incorrect.shape: (1102987,)
    predicted_test_classified_incorrect.shape: (1102987,)
ic| TP_H + FN_H + FP_H + TN_H: 1102987
    len(label_mask_current_deforestation_test): 36859162
ic| TP_H + FN_H + FP_H + TN_H: 1102987
    len(label_mask_current_deforestation_test): 36859162


[0.98209664 0.85637973 0.57444437 0.02992436 0.9607517  0.59094888
 0.03622848]
0.12267305917936826
threshold 0.12267305917936826


ic| label_current_deforestation_test_classified_incorrect.shape: (1106294,)
    predicted_test_classified_incorrect.shape: (1106294,)
ic| TP_H + FN_H + FP_H + TN_H: 1106294
    len(label_mask_current_deforestation_test): 36859162
ic| TP_H + FN_H + FP_H + TN_H: 1106294
    len(label_mask_current_deforestation_test): 36859162


[0.98209375 0.85640744 0.57415966 0.03001408 0.96079036 0.59117774
 0.03614225]
0.1227447633263292
threshold 0.1227447633263292


ic| label_current_deforestation_test_classified_incorrect.shape: (1105428,)
    predicted_test_classified_incorrect.shape: (1105428,)
ic| TP_H + FN_H + FP_H + TN_H: 1105428
    len(label_mask_current_deforestation_test): 36859162
ic| TP_H + FN_H + FP_H + TN_H: 1105428
    len(label_mask_current_deforestation_test): 36859162


[0.98209546 0.85640603 0.57421521 0.02999059 0.96077961 0.5911275
 0.03616706]
0.12281970173338327
threshold 0.12281970173338327


ic| label_current_deforestation_test_classified_incorrect.shape: (1104519,)
    predicted_test_classified_incorrect.shape: (1104519,)
ic| TP_H + FN_H + FP_H + TN_H: 1104519
    len(label_mask_current_deforestation_test): 36859162
ic| TP_H + FN_H + FP_H + TN_H: 1104519
    len(label_mask_current_deforestation_test): 36859162


[0.98209175 0.85639873 0.57428465 0.02996593 0.96078263 0.59107246
 0.03619054]
0.1227780984802616
threshold 0.1227780984802616


ic| label_current_deforestation_test_classified_incorrect.shape: (1104995,)
    predicted_test_classified_incorrect.shape: (1104995,)
ic| TP_H + FN_H + FP_H + TN_H: 1104995
    len(label_mask_current_deforestation_test): 36859162
ic| TP_H + FN_H + FP_H + TN_H: 1104995
    len(label_mask_current_deforestation_test): 36859162


[0.9820962  0.85640237 0.57423952 0.02997884 0.96077491 0.5911098
 0.03617902]
0.12271142817239682
threshold 0.12271142817239682


ic| label_current_deforestation_test_classified_incorrect.shape: (1105859,)
    predicted_test_classified_incorrect.shape: (1105859,)
ic| TP_H + FN_H + FP_H + TN_H: 1105859
    len(label_mask_current_deforestation_test): 36859162
ic| TP_H + FN_H + FP_H + TN_H: 1105859
    len(label_mask_current_deforestation_test): 36859162


[0.9820946  0.85641339 0.57418743 0.03000228 0.96078499 0.59114328
 0.03615608]


ic| self.threshold_optimal: 0.12271142817239682


threshold:  0.12271142817239682
threshold 0.12271142817239682


ic| label_current_deforestation_test_classified_incorrect.shape: (1105859,)
    predicted_test_classified_incorrect.shape: (1105859,)
ic| TP_H + FN_H + FP_H + TN_H: 1105859
    len(label_mask_current_deforestation_test): 36859162
ic| TP_H + FN_H + FP_H + TN_H: 1105859
    len(label_mask_current_deforestation_test): 36859162


[0.9820946  0.85641339 0.57418743 0.03000228 0.96078499 0.59114328
 0.03615608]
threshold 0.12271142817239682
(36859162,) (36859162,)


ic| self.m_optimal: {'AA': array([0.03000228]),
                     'UEO': array([0.03615608]),
                     'f1': 86.05,
                     'f1_H': array([0.73194309]),
                     'f1_L': array([0.91495819]),
                     'precision_H': array([0.96078499]),
                     'precision_L': array([0.9820946]),
                     'recall_H': array([0.59114328]),
                     'recall_L': array([0.85641339]),
                     'recall_Ltotal': array([0.57418743])}
ic| self.m_audited_optimal: {'f1': array([0.94423937]),
                             'precision': array([0.98854901]),
                             'recall': array([0.90373151])}


cm_audited [[36568140     3015]
 [   27726   260281]]
[0.98854901 0.90373151]
Result idx 0: {'uncertainty_result': {'metrics': {'precision_L': array([0.9820946]), 'recall_L': array([0.85641339]), 'recall_Ltotal': array([0.57418743]), 'AA': array([0.03000228]), 'precision_H': array([0.96078499]), 'recall_H': array([0.59114328]), 'UEO': array([0.03615608]), 'f1_L': array([0.91495819]), 'f1_H': array([0.73194309]), 'f1': 86.05}, 'metrics_audited': {'precision': array([0.98854901]), 'recall': array([0.90373151]), 'f1': array([0.94423937])}, 'exp': 18}}
Grid execution idx: 0
Beginning run number 1
manager.config {'training': False, 'inferring': True, 'site': 'MS', 'training_date': 'earlier', 'mode': 'mcd', 'training_times': 10, 'uncertainty_method': 'pred_entropy', 'loadInference': False, 'removePolygons': True, 'plotLandsat': False, 'plotPOI': False, 'training_experiment_id': 19, 'get_multiple_metrics': False, 'save_probabilities': False, 'addPastDeforestationInput': True, 'classes_mode': 

ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([334024764,   8717093,   6541094,   3824922,   2096535,   1305948,
                                                                      1003721,    903906,    318788,    701575,    310887,    440417,
                                                                       316180,    560438,    600838,    776899], dtype=int64))


Label where deforestation past years is actual date (2020) = 1


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([334024764,   8717093,   6541094,   3824922,   2096535,   1305948,
                                                                      1003721,    903906,    318788,    701575,    310887,    440417,
                                                                       316180,    560438,    600838,    776899], dtype=int64))


Past deforestation different from 0 (no deforestation)


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([334024764,   8717093,   6541094,   3824922,   2096535,   1305948,
                                                                      1003721,    903906,    318788,    701575,    310887,    440417,
                                                                       316180,    560438,    600838,    776899], dtype=int64))


Past deforestation before 2008 is 2
D:/Jorge/datasets/deforestation/MS/deforestation_before_2000_MS.tif


ic| np.unique(label_past_deforestation_before_2008, return_counts=True): (array([  0, 208], dtype=uint8), array([126708038, 235735967], dtype=int64))
ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([334024764,   8717093,   6541094,   3824922,   2096535,   1305948,
                                                                      1003721,    903906,    318788,    701575,    310887,    440417,
                                                                       316180,    560438,    600838,    776899], dtype=int64))
ic| label_per_date.shape: (18605, 19481, 1)


Removing bufer................
Mask label shape:  
 (18605, 19481, 1) 
 Unique values:  
 [0 1 2]
Tiles size:  3721 3896
Mask size:  (18605, 19480)


ic| image_stack.shape: (18605, 19481, 21)


Image shape:  (18605, 19481, 21)
mask:  (18605, 19480)
image stack:  (18605, 19480, 21)
ref : (18605, 19480, 1)
Training tiles:  [2, 4, 5, 6, 7, 12, 14, 15, 18, 21, 23, 24]
Validation tiles:  [9, 11, 25]
Test tiles:  [1, 3, 8, 10, 13, 16, 17, 19, 20, 22]
-35.0 -8.0


ic| self.path_models+ '/' + self.method +'_'+str(self.repetition_id)+'.h5': 'D:/Jorge/datasets/deforestation/experiments/MS/exp18/models/resunet_1.h5'


Dropout training mode: True
time:  0
time:  1
time:  2
time:  3
time:  4
time:  5
time:  6
time:  7
time:  8
time:  9
(36877090,)
(array([0, 1], dtype=uint8), array([36581631,   295459], dtype=int64))
(18605, 19480)
(array([0., 1.], dtype=float32), array([362039061,    386339], dtype=int64))


ic| self.predicted_unpad.shape: (18605, 19480)
    self.predicted.shape: (18605, 19480)
ic| predicted_test.shape: (144970160,)
ic| predicted_test.shape: (36877090,)
ic| np.unique(predicted, return_counts=True): (array([0., 1.], dtype=float32), array([362039061,    386339], dtype=int64))
    np.unique(predicted_larger_than_min_area, return_counts=True): (array([0., 1.], dtype=float32), array([362060547,    364853], dtype=int64))
ic| np.unique(ignored_polygons, return_counts=True): (array([0., 1.], dtype=float32), array([362403914,     21486], dtype=int64))
ic| self.f1: 86.2, self.precision: 98.36, self.recall: 76.71
ic| self.label_mask_val.shape: (43491048,)
ic| self.label_mask_val_valid.shape: (10774893,)
ic| f1_val: 49.26
    precision_val: 100.0
    recall_val: 32.67
    mAP_val: 50.02


(array([0., 1.], dtype=float32), array([362275260,    150140], dtype=int64))
[0. 1.]
K = 1, pred_mean shape (18640, 19488, 1)


ic| self.label_mask.shape: (18605, 19480)
ic| self.mask_amazon_ts.shape: (18605, 19480)
ic| self.label_mask_test.shape: (144970160,)
ic| self.error_mask_test.shape: (36865805,)
ic| bounds: (0.0015001614539399953, 0.3663794801235199)
c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\scipy\optimize\_minimize.py:783: RuntimeWarning: Method 'bounded' does not support relative tolerance in x; defaulting to absolute tolerance.
  warn("Method 'bounded' does not support relative tolerance in x; "


0.14087165939381543
threshold 0.14087165939381543


ic| label_current_deforestation_test_classified_incorrect.shape: (485597,)
    predicted_test_classified_incorrect.shape: (485597,)
ic| TP_H + FN_H + FP_H + TN_H: 485597
    len(label_mask_current_deforestation_test): 36865805
ic| TP_H + FN_H + FP_H + TN_H: 485597
    len(label_mask_current_deforestation_test): 36865805


[0.99026445 0.874548   0.61053511 0.01317202 0.95859257 0.51852745
 0.08557995]
0.22700798218364443
threshold 0.22700798218364443


ic| label_current_deforestation_test_classified_incorrect.shape: (118700,)
    predicted_test_classified_incorrect.shape: (118700,)
ic| TP_H + FN_H + FP_H + TN_H: 118700
    len(label_mask_current_deforestation_test): 36865805
ic| TP_H + FN_H + FP_H + TN_H: 118700
    len(label_mask_current_deforestation_test): 36865805


[0.98771329 0.84884539 0.69046909 0.00321979 0.94831509 0.41055996
 0.21017014]
0.08763648424376896
threshold 0.08763648424376896


ic| label_current_deforestation_test_classified_incorrect.shape: (1405040,)
    predicted_test_classified_incorrect.shape: (1405040,)
ic| TP_H + FN_H + FP_H + TN_H: 1405040
    len(label_mask_current_deforestation_test): 36865805
ic| TP_H + FN_H + FP_H + TN_H: 1405040
    len(label_mask_current_deforestation_test): 36865805


[0.99490122 0.88918356 0.54060849 0.03811228 0.95773636 0.5776848
 0.03552031]
0.05473533660398647
threshold 0.05473533660398647


ic| label_current_deforestation_test_classified_incorrect.shape: (2698669,)
    predicted_test_classified_incorrect.shape: (2698669,)
ic| TP_H + FN_H + FP_H + TN_H: 2698669
    len(label_mask_current_deforestation_test): 36865805
ic| TP_H + FN_H + FP_H + TN_H: 2698669
    len(label_mask_current_deforestation_test): 36865805


[0.99869558 0.90395029 0.47521742 0.0732025  0.9600543  0.61535031
 0.02068025]
0.10797051175403292
threshold 0.10797051175403292


ic| label_current_deforestation_test_classified_incorrect.shape: (950182,)
    predicted_test_classified_incorrect.shape: (950182,)
ic| TP_H + FN_H + FP_H + TN_H: 950182
    len(label_mask_current_deforestation_test): 36865805
ic| TP_H + FN_H + FP_H + TN_H: 950182
    len(label_mask_current_deforestation_test): 36865805


[0.9929141  0.88386937 0.5699509  0.02577407 0.95774577 0.55501098
 0.04942284]
0.10666403120582361
threshold 0.10666403120582361


ic| label_current_deforestation_test_classified_incorrect.shape: (974668,)
    predicted_test_classified_incorrect.shape: (974668,)
ic| TP_H + FN_H + FP_H + TN_H: 974668
    len(label_mask_current_deforestation_test): 36865805
ic| TP_H + FN_H + FP_H + TN_H: 974668
    len(label_mask_current_deforestation_test): 36865805


[0.99303111 0.88421547 0.56822406 0.02643827 0.95772931 0.55641804
 0.04837878]
0.10040293233084147
threshold 0.10040293233084147


ic| label_current_deforestation_test_classified_incorrect.shape: (1100509,)
    predicted_test_classified_incorrect.shape: (1100509,)
ic| TP_H + FN_H + FP_H + TN_H: 1100509
    len(label_mask_current_deforestation_test): 36865805
ic| TP_H + FN_H + FP_H + TN_H: 1100509
    len(label_mask_current_deforestation_test): 36865805


[0.99371603 0.8858894  0.55985686 0.02985176 0.95738409 0.56303764
 0.04369226]
0.09552658307719085
threshold 0.09552658307719085


ic| label_current_deforestation_test_classified_incorrect.shape: (1208966,)
    predicted_test_classified_incorrect.shape: (1208966,)
ic| TP_H + FN_H + FP_H + TN_H: 1208966
    len(label_mask_current_deforestation_test): 36865805
ic| TP_H + FN_H + FP_H + TN_H: 1208966
    len(label_mask_current_deforestation_test): 36865805


[0.99414705 0.88709731 0.55305006 0.0327937  0.95746397 0.56835427
 0.04033234]
0.1007422505257983
threshold 0.1007422505257983


ic| label_current_deforestation_test_classified_incorrect.shape: (1093445,)
    predicted_test_classified_incorrect.shape: (1093445,)
ic| TP_H + FN_H + FP_H + TN_H: 1093445
    len(label_mask_current_deforestation_test): 36865805
ic| TP_H + FN_H + FP_H + TN_H: 1093445
    len(label_mask_current_deforestation_test): 36865805


[0.99369665 0.88580137 0.56031111 0.02966014 0.95735594 0.56268343
 0.0439325 ]
0.09924253512463689
threshold 0.09924253512463689


ic| label_current_deforestation_test_classified_incorrect.shape: (1125317,)
    predicted_test_classified_incorrect.shape: (1125317,)
ic| TP_H + FN_H + FP_H + TN_H: 1125317
    len(label_mask_current_deforestation_test): 36865805
ic| TP_H + FN_H + FP_H + TN_H: 1125317
    len(label_mask_current_deforestation_test): 36865805


[0.99380136 0.8860894  0.55816123 0.03052468 0.95745661 0.56449104
 0.04285737]
0.09995970003852174
threshold 0.09995970003852174


ic| label_current_deforestation_test_classified_incorrect.shape: (1109947,)
    predicted_test_classified_incorrect.shape: (1109947,)
ic| TP_H + FN_H + FP_H + TN_H: 1109947
    len(label_mask_current_deforestation_test): 36865805
ic| TP_H + FN_H + FP_H + TN_H: 1109947
    len(label_mask_current_deforestation_test): 36865805


[0.99375216 0.88595065 0.55925351 0.03010777 0.95739549 0.56356729
 0.04336662]
0.10010582819869092
threshold 0.10010582819869092


ic| label_current_deforestation_test_classified_incorrect.shape: (1106845,)
    predicted_test_classified_incorrect.shape: (1106845,)
ic| TP_H + FN_H + FP_H + TN_H: 1106845
    len(label_mask_current_deforestation_test): 36865805
ic| TP_H + FN_H + FP_H + TN_H: 1106845
    len(label_mask_current_deforestation_test): 36865805


[0.99375431 0.88595167 0.55944769 0.03002362 0.95735734 0.56337445
 0.04347934]
0.10016098043596831
threshold 0.10016098043596831


ic| label_current_deforestation_test_classified_incorrect.shape: (1105685,)
    predicted_test_classified_incorrect.shape: (1105685,)
ic| TP_H + FN_H + FP_H + TN_H: 1105685
    len(label_mask_current_deforestation_test): 36865805
ic| TP_H + FN_H + FP_H + TN_H: 1105685
    len(label_mask_current_deforestation_test): 36865805


[0.99374896 0.88594473 0.55951704 0.02999216 0.95735901 0.56331348
 0.04351945]
0.10023278564269184
threshold 0.10023278564269184


ic| label_current_deforestation_test_classified_incorrect.shape: (1104145,)
    predicted_test_classified_incorrect.shape: (1104145,)
ic| TP_H + FN_H + FP_H + TN_H: 1104145
    len(label_mask_current_deforestation_test): 36865805
ic| TP_H + FN_H + FP_H + TN_H: 1104145
    len(label_mask_current_deforestation_test): 36865805


[0.99374427 0.88594358 0.55964534 0.02995038 0.95734908 0.56318787
 0.04357341]
0.10019431525492907
threshold 0.10019431525492907


ic| label_current_deforestation_test_classified_incorrect.shape: (1104968,)
    predicted_test_classified_incorrect.shape: (1104968,)
ic| TP_H + FN_H + FP_H + TN_H: 1104968
    len(label_mask_current_deforestation_test): 36865805
ic| TP_H + FN_H + FP_H + TN_H: 1104968
    len(label_mask_current_deforestation_test): 36865805
ic| self.threshold_optimal: 0.10016098043596831


[0.99374935 0.88594127 0.55955172 0.02997271 0.95735219 0.56328298
 0.04354529]
threshold:  0.10016098043596831
threshold 0.10016098043596831


ic| label_current_deforestation_test_classified_incorrect.shape: (1105685,)
    predicted_test_classified_incorrect.shape: (1105685,)
ic| TP_H + FN_H + FP_H + TN_H: 1105685
    len(label_mask_current_deforestation_test): 36865805
ic| TP_H + FN_H + FP_H + TN_H: 1105685
    len(label_mask_current_deforestation_test): 36865805


In [ ]:
error_count

0

In [ ]:
print(results)

[{'uncertainty_result': {'metrics': {'precision_L': array([0.53195804]), 'recall_L': array([0.69958021]), 'recall_Ltotal': array([0.61956172]), 'AA': array([0.0299989]), 'precision_H': array([0.10644846]), 'recall_H': array([0.26529932]), 'UEO': array([0.09367737]), 'f1_L': array([0.60436177]), 'f1_H': array([0.15193476]), 'f1': 53.06}, 'metrics_audited': {'precision': array([0.57381291]), 'recall': array([0.73394245]), 'f1': array([0.64407406])}, 'exp': 15}}, {'uncertainty_result': {'metrics': {'precision_L': array([0.44728461]), 'recall_L': array([0.65520344]), 'recall_Ltotal': array([0.57612883]), 'AA': array([0.03000089]), 'precision_H': array([0.10036852]), 'recall_H': array([0.35776325]), 'UEO': array([0.12158722]), 'f1_L': array([0.53163826]), 'f1_H': array([0.15675912]), 'f1': 45.57}, 'metrics_audited': {'precision': array([0.49463568]), 'recall': array([0.69681594]), 'f1': array([0.57857158])}, 'exp': 15}}, {'uncertainty_result': {'metrics': {'precision_L': array([0.64663261])

In [ ]:
print(len(results))

4


In [ ]:
results[0]

{'uncertainty_result': {'metrics': {'precision_L': array([0.53195804]),
   'recall_L': array([0.69958021]),
   'recall_Ltotal': array([0.61956172]),
   'AA': array([0.0299989]),
   'precision_H': array([0.10644846]),
   'recall_H': array([0.26529932]),
   'UEO': array([0.09367737]),
   'f1_L': array([0.60436177]),
   'f1_H': array([0.15193476]),
   'f1': 53.06},
  'metrics_audited': {'precision': array([0.57381291]),
   'recall': array([0.73394245]),
   'f1': array([0.64407406])},
  'exp': 15}}

In [ ]:
manager.f1

54.34

In [ ]:
print(manager.f1)

54.34
