In [1]:
import tracemalloc

from utils_v1 import *
import traceback


In [2]:
from icecream import ic

import numpy as np
from src.dataset import (
    MultipleDates, PAMultipleDates,
    MTMultipleDates, MSMultipleDates, PIMultipleDates
)

# from src.dataset_legacy import MTDeforestationTime
from src import training_generator as generator
from src.patchesHandler import PatchesHandler, PatchesHandlerMultipleDates, PatchesHandlerEvidential2

from src.manager.evidential import ManagerEvidential
from src.manager.multioutput import ManagerMCDropout, ManagerSingleRun, ManagerEvidential2
from mpl_toolkits.axes_grid1 import make_axes_locatable

import cv2
from src import metrics as _metric
import json
import pickle 
import src.manager.evidential as evidential
from src.Logger import Logger
import pdb
import gc


Tensorflow ver. 2.6.0


In [3]:

with open('config/config.json', 'r') as f:
    config = json.load(f)
    
print("Mode: {}. Site: {}. Training: {}. Training date: {}".format(
    config['mode'], config['site'], config['training'], config['training_date']))
print(config)


Mode: evidential2. Site: PI. Training: True. Training date: current
{'training': True, 'inferring': True, 'site': 'PI', 'training_date': 'current', 'mode': 'evidential2', 'training_times': 3, 'uncertainty_method': 'pred_entropy', 'loadInference': False, 'removePolygons': True, 'plotLandsat': False, 'plotPOI': False, 'training_experiment_id': 46, 'get_multiple_metrics': False, 'start_repetition_id': 0, 'end_repetition_id': 3, 'save_probabilities': False, 'addPastDeforestationInput': True, 'classes_mode': True, 'learning_rate': 0.0001, 'use_cloud_mask': False, 'mask_out_non_biome': True, 'log_filename': 'log.pkl'}


In [4]:

if config['site'] == 'PA':
	if config['training_date'] == 'earlier':
		dates = [2017, 2018]
	else:
		dates = [2018, 2019]
	datasetClass = PAMultipleDates
elif config['site'] == 'MT':
	if config['training_date'] == 'earlier':
		dates = [2018, 2019]
	else:
		dates = [2019, 2020]
	datasetClass = MTMultipleDates
elif config['site'] == 'MS':
	if config['training_date'] == 'earlier':
		dates = [2018, 2019]
	else:
		dates = [2019, 2020]
	datasetClass = MSMultipleDates
elif config['site'] == 'PI':
	if config['training_date'] == 'earlier':
		dates = [2018, 2019]
	else:
		dates = [2019, 2020]
	datasetClass = PIMultipleDates
else:
	raise ValueError('Invalid site')

dataset = datasetClass(config = config,
			   dates = dates, 
	 	addPastDeforestationInput = config['addPastDeforestationInput'],
		borderBuffer = 2)	

if config['mode'] == 'ensemble':
	if config['training'] == True:
		config['mode'] = 'single_run'
	else:
		sys.exit("Ensure that training is True for ensemble mode. Use infer_ensemble.ipynb for inference.")

if config['training'] == False:
	if config['site'] == 'PA':
		if config['mode'] == 'mcd' or config['mode'] == 'single_run': # MCD will do 10 inference on each of the 10 repetitions = 100 runs
			if config['training_date'] == 'current': exp = 0
			elif config['training_date'] == 'earlier': exp = 1
				
		if config['mode'] == 'evidential2':
			if config['training_date'] == 'current': exp = 8; repetition_id = 0
			elif config['training_date'] == 'earlier': exp = 48; repetition_id = 0

	elif config['site'] == 'MT':

		if config['mode'] == 'mcd' or config['mode'] == 'single_run':
			if config['training_date'] == 'current': exp = 2
			elif config['training_date'] == 'earlier': exp = 3
		if config['mode'] == 'evidential2':
			if config['training_date'] == 'current': exp = 10; repetition_id = 0
			elif config['training_date'] == 'earlier': exp = 42; repetition_id = 0

	elif config['site'] == 'MS':

		if config['mode'] == 'mcd' or config['mode'] == 'single_run':
			if config['training_date'] == 'current': exp = 40
			elif config['training_date'] == 'earlier': 
				exp = 37

		if config['mode'] == 'evidential2':
			if config['training_date'] == 'current': exp = 12; repetition_id = 0
			elif config['training_date'] == 'earlier': exp = 39; repetition_id = 0
	elif config['site'] == 'PI':

		if config['mode'] == 'mcd' or config['mode'] == 'single_run':
			if config['training_date'] == 'current': exp = 44
			elif config['training_date'] == 'earlier': exp = 27
		if config['mode'] == 'evidential2':
			if config['training_date'] == 'current': exp = 45; repetition_id = 0
			elif config['training_date'] == 'earlier': exp = 39; repetition_id = 0

else:
	exp = config['training_experiment_id']
ic(dates)


if issubclass(type(dataset), MultipleDates):
	patchesHandler = PatchesHandlerMultipleDates(
		dataset)
elif config['mode'] == 'evidential2':
	patchesHandler = PatchesHandlerEvidential2()
else:
	patchesHandler = PatchesHandler()



ic| list(self.date_ids): [0]
ic| self.image_channels: [[0, 1, 2, 3, 4, 5, 6, 7, 8]]
ic| dates: [2019, 2020]
ic| self.input_image_shape: 9
ic| self.dataset.image_channels: [[0, 1, 2, 3, 4, 5, 6, 7, 8]]


In [5]:


if config['mode'] == 'evidential2':
    config["inference_times"] = 1
    manager_class = ManagerEvidential2
    config['uncertainty_method'] = "pred_entropy"
    config['classes_mode'] = True
    
if config['mode'] == 'mcd':
    config["inference_times"] = 10
    manager_class = ManagerMCDropout
    config['uncertainty_method'] = "pred_entropy"
    config['classes_mode'] = False

elif config['mode'] == 'single_run':
    config["inference_times"] = 1
    manager_class = ManagerSingleRun
    config['uncertainty_method'] = "pred_entropy_single"
    config['classes_mode'] = False



In [6]:
exp

46

In [7]:
logger = Logger()


In [8]:
if config['training'] == True:
    

    manager = manager_class(config, dataset, patchesHandler, logger)
    print("manager.config['dropout_training']", manager.config['dropout_training'])
    manager.defineExperiment(exp) # fixed
    
    manager.setExperimentPath()
    manager.createLogFolders()

    manager.loadDataset()

    # %%
    if config["training"] == True:
        manager.run()


manager.config['dropout_training'] False
D:/Jorge/datasets/deforestation/PI/deforestation_past_years.tif
Loaded deforestation past years


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([340580606,   4312043,   6953620,   5659916,   7162776,   6261432,
                                                                      8191420,   3233962,   3270293,   3044419,   1817289,   2359424,
                                                                      2201926,   3050229,   2901307,   2418575], dtype=int64))


Label where deforestation past years is actual date (2020) = 1


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([340580606,   4312043,   6953620,   5659916,   7162776,   6261432,
                                                                      8191420,   3233962,   3270293,   3044419,   1817289,   2359424,
                                                                      2201926,   3050229,   2901307,   2418575], dtype=int64))


Past deforestation different from 0 (no deforestation)


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([340580606,   4312043,   6953620,   5659916,   7162776,   6261432,
                                                                      8191420,   3233962,   3270293,   3044419,   1817289,   2359424,
                                                                      2201926,   3050229,   2901307,   2418575], dtype=int64))


Past deforestation before 2008 is 2
D:/Jorge/datasets/deforestation/PI/deforestation_before_2000_PI.tif


ic| np.unique(label_past_deforestation_before_2008, return_counts=True): (array([  0, 208], dtype=uint8), array([385251297,  18167940], dtype=int64))
ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([340580606,   4312043,   6953620,   5659916,   7162776,   6261432,
                                                                      8191420,   3233962,   3270293,   3044419,   1817289,   2359424,
                                                                      2201926,   3050229,   2901307,   2418575], dtype=int64))


D:/Jorge/datasets/sentinel2/PI/biome_limits.tif


ic| label_per_date.shape: (19357, 20841, 1)


Removing bufer................
Mask label shape:  
 (19357, 20841, 1) 
 Unique values:  
 [0 1 2]
Tiles size:  3871 4168
Mask size:  (19355, 20840)


ic| image_stack.shape: (19357, 20841, 9)


Image shape:  (19357, 20841, 9)
mask:  (19355, 20840)
image stack:  (19355, 20840, 9)
ref : (19355, 20840, 1)
Training tiles:  [2, 4, 5, 6, 7, 12, 14, 15, 18, 21, 23, 25]
Validation tiles:  [9, 11, 24]
Test tiles:  [1, 3, 8, 10, 13, 16, 17, 19, 20, 22]


ic| im_idx_row.shape: (19355, 20840, 1)
    im_idx_col.shape: (19355, 20840, 1)
ic| im_idx_row.dtype: dtype('uint16')
    im_idx_col.dtype: dtype('uint16')
ic| im_idx.shape: (19355, 20840, 2), im_idx.dtype: dtype('uint16')
ic| coords.shape: (506, 546, 1, 128, 128, 2)
    coords.dtype: dtype('uint16')
ic| coords.shape: (276276, 2), coords.dtype: dtype('uint16')
ic| self.coords_train.shape: (128251, 3)
    self.coords_val.shape: (31475, 3)


training samples:  (7680, 3) validation samples:  (1810, 3)
time:  0


c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\keras\optimizer_v2\optimizer_v2.py:374: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  warnings.warn(


Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_enc_net (InputLayer)      [(None, 128, 128, 9) 0                                            
__________________________________________________________________________________________________
res1_net1 (Conv2D)              (None, 128, 128, 16) 1312        input_enc_net[0][0]              
__________________________________________________________________________________________________
drop_net1 (SpatialDropout2D)    (None, 128, 128, 16) 0           res1_net1[0][0]                  
__________________________________________________________________________________________________
res2_net1 (Conv2D)              (None, 128, 128, 16) 2320        drop_net1[0][0]                  
______________________________________________________________________________________________

c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py:494: CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.
  warnings.warn('Custom mask layers require a config and must override '


720/720 [==============================] - 35s 48ms/step - loss: 0.2788 - accuracy: 0.6214 - val_loss: 0.3060 - val_accuracy: 0.6294

Epoch 00001: val_loss did not improve from 0.29242
Early stop count: 1
Epoch: 3
Anneling Coeficient [0.2]
720/720 [==============================] - 35s 48ms/step - loss: 0.2670 - accuracy: 0.6224 - val_loss: 0.2897 - val_accuracy: 0.6288

Epoch 00001: val_loss improved from 0.29242 to 0.28970, saving model to D:/Jorge/datasets/deforestation/experiments/PI/exp46/models\resunet_0.h5
New best val loss. Val loss: 0.2897. Early stop count: 0
Epoch: 4
Anneling Coeficient [0.3]
720/720 [==============================] - 35s 48ms/step - loss: 0.2586 - accuracy: 0.6221 - val_loss: 0.2858 - val_accuracy: 0.6282

Epoch 00001: val_loss improved from 0.28970 to 0.28580, saving model to D:/Jorge/datasets/deforestation/experiments/PI/exp46/models\resunet_0.h5
New best val loss. Val loss: 0.2858. Early stop count: 0
Epoch: 5
Anneling Coeficient [0.4]
720/720 [=========

In [9]:



if config['site'] == 'PA':
	dates = [2018, 2019]
	datasetClass = PAMultipleDates
elif config['site'] == 'MT':
	dates = [2019, 2020]
	datasetClass = MTMultipleDates
elif config['site'] == 'MS':
	dates = [2019, 2020]
	datasetClass = MSMultipleDates
elif config['site'] == 'PI':
	dates = [2019, 2020]
	datasetClass = PIMultipleDates
else:
	raise ValueError('Invalid site')

dataset = datasetClass(config = config,
			   dates = dates, 
	 	addPastDeforestationInput = config['addPastDeforestationInput'],
		borderBuffer = 2)


ic(dates)

if issubclass(type(dataset), MultipleDates):
	patchesHandler = PatchesHandlerMultipleDates(
		dataset)
elif config['mode'] == 'evidential2':
	patchesHandler = PatchesHandlerEvidential2()
else:
	patchesHandler = PatchesHandler()


ic| list(self.date_ids): [0]
ic| self.image_channels: [[0, 1, 2, 3, 4, 5, 6, 7, 8]]
ic| dates: [2019, 2020]
ic| self.input_image_shape: 9
ic| self.dataset.image_channels: [[0, 1, 2, 3, 4, 5, 6, 7, 8]]


In [10]:
manager_class

src.manager.multioutput.ManagerEvidential2

In [11]:
exp

46

In [12]:
repetition_ids = manager_class(config, dataset, patchesHandler, logger).get_repetition_ids(exp)  
repetition_n = len(repetition_ids)
print("repetition_ids {}, repetition_n {}".format(repetition_ids, repetition_n))


repetition_ids [0, 1, 2], repetition_n 3


In [13]:
config['start_repetition_id']

0

In [14]:
if config['inferring'] == True:
    results = []
    error_count = 0

    # while idx < len(repetition_n):
    # for idx in range(config['start_repetition_id'], repetition_n): # 10 repetitions
    for idx in range(config['start_repetition_id'], config['end_repetition_id']): # 10 repetitions

    # for idx in range(0, 4): # 10 repetitions


        print("Beginning run number {}".format(idx))
        logger = Logger()
        manager = manager_class(config, dataset, patchesHandler, logger)

        print("manager.config", manager.config)

        manager.defineExperiment(exp) # fixed
        manager.defineRepetitionId(idx) # varying from 0 to 10
        manager.setExperimentPath()
        manager.createLogFolders()

        manager.loadDataset()

        # %%
        if config['get_multiple_metrics'] == False:
            predictor_fcn = manager.run_predictor
        else:
            predictor_fcn = manager.run_predictor_multiple_metrics
        result = predictor_fcn()
        print("Result idx {}: {}".format(idx, result))
        results.append(result)

        with open(manager.default_log_name, 'wb') as f:
            pickle.dump(results, f)
        print("Grid execution idx: {}".format(idx))
        del manager
        gc.collect()
        # idx += 1
    

Beginning run number 0
manager.config {'training': True, 'inferring': True, 'site': 'PI', 'training_date': 'current', 'mode': 'evidential2', 'training_times': 3, 'uncertainty_method': 'pred_entropy', 'loadInference': False, 'removePolygons': True, 'plotLandsat': False, 'plotPOI': False, 'training_experiment_id': 46, 'get_multiple_metrics': False, 'start_repetition_id': 0, 'end_repetition_id': 3, 'save_probabilities': False, 'addPastDeforestationInput': True, 'classes_mode': True, 'learning_rate': 0.0001, 'use_cloud_mask': False, 'mask_out_non_biome': True, 'log_filename': 'log.pkl', 'inference_times': 1, 'dropout_training': False}
D:/Jorge/datasets/deforestation/PI/deforestation_past_years.tif
Loaded deforestation past years


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([340580606,   4312043,   6953620,   5659916,   7162776,   6261432,
                                                                      8191420,   3233962,   3270293,   3044419,   1817289,   2359424,
                                                                      2201926,   3050229,   2901307,   2418575], dtype=int64))


Label where deforestation past years is actual date (2020) = 1


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([340580606,   4312043,   6953620,   5659916,   7162776,   6261432,
                                                                      8191420,   3233962,   3270293,   3044419,   1817289,   2359424,
                                                                      2201926,   3050229,   2901307,   2418575], dtype=int64))


Past deforestation different from 0 (no deforestation)


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([340580606,   4312043,   6953620,   5659916,   7162776,   6261432,
                                                                      8191420,   3233962,   3270293,   3044419,   1817289,   2359424,
                                                                      2201926,   3050229,   2901307,   2418575], dtype=int64))


Past deforestation before 2008 is 2
D:/Jorge/datasets/deforestation/PI/deforestation_before_2000_PI.tif


ic| np.unique(label_past_deforestation_before_2008, return_counts=True): (array([  0, 208], dtype=uint8), array([385251297,  18167940], dtype=int64))
ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([340580606,   4312043,   6953620,   5659916,   7162776,   6261432,
                                                                      8191420,   3233962,   3270293,   3044419,   1817289,   2359424,
                                                                      2201926,   3050229,   2901307,   2418575], dtype=int64))


D:/Jorge/datasets/sentinel2/PI/biome_limits.tif


ic| label_per_date.shape: (19357, 20841, 1)


Removing bufer................
Mask label shape:  
 (19357, 20841, 1) 
 Unique values:  
 [0 1 2]
Tiles size:  3871 4168
Mask size:  (19355, 20840)


ic| image_stack.shape: (19357, 20841, 9)


Image shape:  (19357, 20841, 9)
mask:  (19355, 20840)
image stack:  (19355, 20840, 9)
ref : (19355, 20840, 1)
Training tiles:  [2, 4, 5, 6, 7, 12, 14, 15, 18, 21, 23, 25]
Validation tiles:  [9, 11, 24]
Test tiles:  [1, 3, 8, 10, 13, 16, 17, 19, 20, 22]
-5.0 -24.0


ic| self.path_models+ '/' + self.method +'_'+str(self.repetition_id)+'.h5': 'D:/Jorge/datasets/deforestation/experiments/PI/exp46/models/resunet_0.h5'


Dropout training mode: False
time:  0
alpha.shape (19360, 20864, 2)
S.shape (19360, 20864)
K 2
u.shape (19360, 20864)
belief.shape (19360, 20864, 2)
Inference runtime 215.47
(89644896,)
(array([0, 1], dtype=uint8), array([88315686,  1329210], dtype=int64))
(19355, 20840, 2)


ic| predicted_test.shape: (161343280,)
ic| predicted_test.shape: (89644896,)
ic| np.unique(predicted, return_counts=True): (array([0, 1], dtype=int8), array([396529835,   6828365], dtype=int64))
    np.unique(predicted_larger_than_min_area, return_counts=True): (array([0, 1], dtype=int8), array([396938842,   6419358], dtype=int64))
ic| np.unique(ignored_polygons, return_counts=True): (array([0, 1], dtype=int8), array([402949193,    409007], dtype=int64))
ic| self.f1: 52.28, self.precision: 36.8, self.recall: 90.19
ic| self.label_mask_val.shape: (48402984,)
ic| self.label_mask_val_valid.shape: (36704301,)
ic| f1_val: 29.71
    precision_val: 18.91
    recall_val: 69.23
    mAP_val: 40.11


(array([0, 1], dtype=int16), array([398774740,   4583460], dtype=int64))
[0 1]


ic| self.label_mask.shape: (19355, 20840)
ic| self.mask_test.shape: (19355, 20840)
ic| self.label_mask_test.shape: (161343280,)
ic| self.error_mask_test.shape: (89512393,)
ic| bounds: (0.00010578750008484349, 0.4985)


(0.00010578750008484349, 0.4985)
0.19047543687881469
threshold 0.19047543687881469


c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\scipy\optimize\_minimize.py:783: RuntimeWarning: Method 'bounded' does not support relative tolerance in x; defaulting to absolute tolerance.
  warn("Method 'bounded' does not support relative tolerance in x; "
ic| label_current_deforestation_test_classified_incorrect.shape: (15924551,)
    predicted_test_classified_incorrect.shape: (15924551,)
ic| TP_H + FN_H + FP_H + TN_H: 15924551
    len(label_mask_current_deforestation_test): 89512393
ic| TP_H + FN_H + FP_H + TN_H: 15924551
    len(label_mask_current_deforestation_test): 89512393


[1.         0.96846658 0.15469502 0.17790331 0.32545562 0.88929875
 0.13558796]
0.30813035062127003
threshold 0.30813035062127003


ic| label_current_deforestation_test_classified_incorrect.shape: (10729450,)
    predicted_test_classified_incorrect.shape: (10729450,)
ic| TP_H + FN_H + FP_H + TN_H: 10729450
    len(label_mask_current_deforestation_test): 89512393
ic| TP_H + FN_H + FP_H + TN_H: 10729450
    len(label_mask_current_deforestation_test): 89512393


[0.99416694 0.96754926 0.32281719 0.11986553 0.27240305 0.86909603
 0.2000678 ]
0.38084508625754454
threshold 0.38084508625754454


ic| label_current_deforestation_test_classified_incorrect.shape: (8406878,)
    predicted_test_classified_incorrect.shape: (8406878,)
ic| TP_H + FN_H + FP_H + TN_H: 8406878
    len(label_mask_current_deforestation_test): 89512393
ic| TP_H + FN_H + FP_H + TN_H: 8406878
    len(label_mask_current_deforestation_test): 89512393


[0.96568725 0.96533161 0.47416949 0.09391859 0.21828731 0.84075014
 0.25109668]
0.42578526436372544
threshold 0.42578526436372544


ic| label_current_deforestation_test_classified_incorrect.shape: (6694686,)
    predicted_test_classified_incorrect.shape: (6694686,)
ic| TP_H + FN_H + FP_H + TN_H: 6694686
    len(label_mask_current_deforestation_test): 89512393
ic| TP_H + FN_H + FP_H + TN_H: 6694686
    len(label_mask_current_deforestation_test): 89512393


[0.85903627 0.97070697 0.77834174 0.0747906  0.08002029 0.62371947
 0.28544561]
0.4535598218938191
threshold 0.4535598218938191


ic| label_current_deforestation_test_classified_incorrect.shape: (5223308,)
    predicted_test_classified_incorrect.shape: (5223308,)
ic| TP_H + FN_H + FP_H + TN_H: 5223308
    len(label_mask_current_deforestation_test): 89512393
ic| TP_H + FN_H + FP_H + TN_H: 5223308
    len(label_mask_current_deforestation_test): 89512393


[0.57905225 0.96626576 0.84017308 0.0583529  0.06178614 0.47336203
 0.21837039]
0.47072544246990633
threshold 0.47072544246990633


ic| label_current_deforestation_test_classified_incorrect.shape: (4098490,)
    predicted_test_classified_incorrect.shape: (4098490,)
ic| TP_H + FN_H + FP_H + TN_H: 4098490
    len(label_mask_current_deforestation_test): 89512393
ic| TP_H + FN_H + FP_H + TN_H: 4098490
    len(label_mask_current_deforestation_test): 89512393


[0.45777843 0.96178758 0.86631294 0.04578684 0.06382399 0.35894216
 0.14040595]
0.4813343794239128
threshold 0.4813343794239128


ic| label_current_deforestation_test_classified_incorrect.shape: (3428601,)
    predicted_test_classified_incorrect.shape: (3428601,)
ic| TP_H + FN_H + FP_H + TN_H: 3428601
    len(label_mask_current_deforestation_test): 89512393
ic| TP_H + FN_H + FP_H + TN_H: 3428601
    len(label_mask_current_deforestation_test): 89512393


[0.41738706 0.95814247 0.88058831 0.03830309 0.06263863 0.26384337
 0.09788652]
0.48789106304599356
threshold 0.48789106304599356


ic| label_current_deforestation_test_classified_incorrect.shape: (3009325,)
    predicted_test_classified_incorrect.shape: (3009325,)
ic| TP_H + FN_H + FP_H + TN_H: 3009325
    len(label_mask_current_deforestation_test): 89512393
ic| TP_H + FN_H + FP_H + TN_H: 3009325
    len(label_mask_current_deforestation_test): 89512393


[0.39802831 0.9554705  0.88875056 0.03361909 0.06057148 0.18894355
 0.07113467]
0.4919433163779192
threshold 0.4919433163779192


ic| label_current_deforestation_test_classified_incorrect.shape: (2743133,)
    predicted_test_classified_incorrect.shape: (2743133,)
ic| TP_H + FN_H + FP_H + TN_H: 2743133
    len(label_mask_current_deforestation_test): 89512393
ic| TP_H + FN_H + FP_H + TN_H: 2743133
    len(label_mask_current_deforestation_test): 89512393


[0.38736303 0.95356685 0.89344619 0.03064529 0.05892428 0.13478879
 0.05372729]
0.4944477466680743
threshold 0.4944477466680743


ic| label_current_deforestation_test_classified_incorrect.shape: (2571178,)
    predicted_test_classified_incorrect.shape: (2571178,)
ic| TP_H + FN_H + FP_H + TN_H: 2571178
    len(label_mask_current_deforestation_test): 89512393
ic| TP_H + FN_H + FP_H + TN_H: 2571178
    len(label_mask_current_deforestation_test): 89512393


[0.38101113 0.95219645 0.89622951 0.02872427 0.05803937 0.09723012
 0.04220027]
0.49235820758655174
threshold 0.49235820758655174


ic| label_current_deforestation_test_classified_incorrect.shape: (2715212,)
    predicted_test_classified_incorrect.shape: (2715212,)
ic| TP_H + FN_H + FP_H + TN_H: 2715212
    len(label_mask_current_deforestation_test): 89512393
ic| TP_H + FN_H + FP_H + TN_H: 2715212
    len(label_mask_current_deforestation_test): 89512393


[0.38630225 0.95333666 0.89391742 0.03033336 0.05873291 0.1287864
 0.05186051]
0.4929334606223665
threshold 0.4929334606223665


ic| label_current_deforestation_test_classified_incorrect.shape: (2675742,)
    predicted_test_classified_incorrect.shape: (2675742,)
ic| TP_H + FN_H + FP_H + TN_H: 2675742
    len(label_mask_current_deforestation_test): 89512393
ic| TP_H + FN_H + FP_H + TN_H: 2675742
    len(label_mask_current_deforestation_test): 89512393


[0.38482136 0.95301541 0.89458247 0.02989242 0.05841133 0.12006942
 0.04921042]
0.49351186642313716
threshold 0.49351186642313716


ic| label_current_deforestation_test_classified_incorrect.shape: (2635932,)
    predicted_test_classified_incorrect.shape: (2635932,)
ic| TP_H + FN_H + FP_H + TN_H: 2635932
    len(label_mask_current_deforestation_test): 89512393
ic| TP_H + FN_H + FP_H + TN_H: 2635932
    len(label_mask_current_deforestation_test): 89512393


[0.38335823 0.95270223 0.89521028 0.02944768 0.05829101 0.11159112
 0.04656238]
0.4928407721861649
threshold 0.4928407721861649


ic| label_current_deforestation_test_classified_incorrect.shape: (2682202,)
    predicted_test_classified_incorrect.shape: (2682202,)
ic| TP_H + FN_H + FP_H + TN_H: 2682202
    len(label_mask_current_deforestation_test): 89512393
ic| TP_H + FN_H + FP_H + TN_H: 2682202
    len(label_mask_current_deforestation_test): 89512393


[0.38506485 0.95306317 0.89448822 0.02996459 0.05836506 0.1213178
 0.04964128]
0.4927266991128238
threshold 0.4927266991128238


ic| label_current_deforestation_test_classified_incorrect.shape: (2689953,)
    predicted_test_classified_incorrect.shape: (2689953,)
ic| TP_H + FN_H + FP_H + TN_H: 2689953
    len(label_mask_current_deforestation_test): 89512393
ic| TP_H + FN_H + FP_H + TN_H: 2689953
    len(label_mask_current_deforestation_test): 89512393


[0.38535057 0.95313206 0.89435293 0.03005118 0.05847501 0.12309892
 0.05015908]
0.4927993216513211
threshold 0.4927993216513211


ic| label_current_deforestation_test_classified_incorrect.shape: (2685014,)
    predicted_test_classified_incorrect.shape: (2685014,)
ic| TP_H + FN_H + FP_H + TN_H: 2685014
    len(label_mask_current_deforestation_test): 89512393
ic| TP_H + FN_H + FP_H + TN_H: 2685014
    len(label_mask_current_deforestation_test): 89512393


[0.38517005 0.95308119 0.89444718 0.029996   0.05834787 0.12186504
 0.04982616]
0.49276598100859265
threshold 0.49276598100859265


ic| label_current_deforestation_test_classified_incorrect.shape: (2687255,)
    predicted_test_classified_incorrect.shape: (2687255,)
ic| TP_H + FN_H + FP_H + TN_H: 2687255
    len(label_mask_current_deforestation_test): 89512393
ic| TP_H + FN_H + FP_H + TN_H: 2687255
    len(label_mask_current_deforestation_test): 89512393
ic| self.threshold_optimal: 0.4927993216513211


[0.38525691 0.95310538 0.89440614 0.03002104 0.05838101 0.12239911
 0.04998572]
threshold:  0.4927993216513211
threshold 0.4927993216513211


ic| label_current_deforestation_test_classified_incorrect.shape: (2685014,)
    predicted_test_classified_incorrect.shape: (2685014,)
ic| TP_H + FN_H + FP_H + TN_H: 2685014
    len(label_mask_current_deforestation_test): 89512393
ic| TP_H + FN_H + FP_H + TN_H: 2685014
    len(label_mask_current_deforestation_test): 89512393


[0.38517005 0.95308119 0.89444718 0.029996   0.05834787 0.12186504
 0.04982616]
threshold 0.4927993216513211
(89512393,) (89512393,)


ic| self.m_optimal: {'AA': array([0.029996]),
                     'UEO': array([0.04982616]),
                     'f1': 52.28,
                     'f1_H': array([0.07891295]),
                     'f1_L': array([0.54862394]),
                     'precision_H': array([0.05834787]),
                     'precision_L': array([0.38517005]),
                     'recall_H': array([0.12186504]),
                     'recall_L': array([0.95308119]),
                     'recall_Ltotal': array([0.89444718])}
ic| self.m_audited_optimal: {'f1': array([0.56503709]),
                             'precision': array([0.40103786]),
                             'recall': array([0.95596766])}


cm_audited [[86318200  1878501]
 [   57933  1257759]]
[0.40103786 0.95596766]
Result idx 0: {'uncertainty_result': {'metrics': {'precision_L': array([0.38517005]), 'recall_L': array([0.95308119]), 'recall_Ltotal': array([0.89444718]), 'AA': array([0.029996]), 'precision_H': array([0.05834787]), 'recall_H': array([0.12186504]), 'UEO': array([0.04982616]), 'f1_L': array([0.54862394]), 'f1_H': array([0.07891295]), 'f1': 52.28}, 'metrics_audited': {'precision': array([0.40103786]), 'recall': array([0.95596766]), 'f1': array([0.56503709])}, 'exp': 46}}
Grid execution idx: 0
Beginning run number 1
manager.config {'training': True, 'inferring': True, 'site': 'PI', 'training_date': 'current', 'mode': 'evidential2', 'training_times': 3, 'uncertainty_method': 'pred_entropy', 'loadInference': False, 'removePolygons': True, 'plotLandsat': False, 'plotPOI': False, 'training_experiment_id': 46, 'get_multiple_metrics': False, 'start_repetition_id': 0, 'end_repetition_id': 3, 'save_probabilities': Fal

ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([340580606,   4312043,   6953620,   5659916,   7162776,   6261432,
                                                                      8191420,   3233962,   3270293,   3044419,   1817289,   2359424,
                                                                      2201926,   3050229,   2901307,   2418575], dtype=int64))


Label where deforestation past years is actual date (2020) = 1


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([340580606,   4312043,   6953620,   5659916,   7162776,   6261432,
                                                                      8191420,   3233962,   3270293,   3044419,   1817289,   2359424,
                                                                      2201926,   3050229,   2901307,   2418575], dtype=int64))


Past deforestation different from 0 (no deforestation)


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([340580606,   4312043,   6953620,   5659916,   7162776,   6261432,
                                                                      8191420,   3233962,   3270293,   3044419,   1817289,   2359424,
                                                                      2201926,   3050229,   2901307,   2418575], dtype=int64))


Past deforestation before 2008 is 2
D:/Jorge/datasets/deforestation/PI/deforestation_before_2000_PI.tif


ic| np.unique(label_past_deforestation_before_2008, return_counts=True): (array([  0, 208], dtype=uint8), array([385251297,  18167940], dtype=int64))
ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([340580606,   4312043,   6953620,   5659916,   7162776,   6261432,
                                                                      8191420,   3233962,   3270293,   3044419,   1817289,   2359424,
                                                                      2201926,   3050229,   2901307,   2418575], dtype=int64))


D:/Jorge/datasets/sentinel2/PI/biome_limits.tif


ic| label_per_date.shape: (19357, 20841, 1)


Removing bufer................
Mask label shape:  
 (19357, 20841, 1) 
 Unique values:  
 [0 1 2]
Tiles size:  3871 4168
Mask size:  (19355, 20840)


ic| image_stack.shape: (19357, 20841, 9)


Image shape:  (19357, 20841, 9)
mask:  (19355, 20840)
image stack:  (19355, 20840, 9)
ref : (19355, 20840, 1)
Training tiles:  [2, 4, 5, 6, 7, 12, 14, 15, 18, 21, 23, 25]
Validation tiles:  [9, 11, 24]
Test tiles:  [1, 3, 8, 10, 13, 16, 17, 19, 20, 22]
-5.0 -24.0


ic| self.path_models+ '/' + self.method +'_'+str(self.repetition_id)+'.h5': 'D:/Jorge/datasets/deforestation/experiments/PI/exp46/models/resunet_1.h5'


Dropout training mode: False
time:  0
alpha.shape (19360, 20864, 2)
S.shape (19360, 20864)
K 2
u.shape (19360, 20864)
belief.shape (19360, 20864, 2)
Inference runtime 188.99
(89644896,)
(array([0, 1], dtype=uint8), array([88315686,  1329210], dtype=int64))
(19355, 20840, 2)


ic| predicted_test.shape: (161343280,)
ic| predicted_test.shape: (89644896,)
ic| np.unique(predicted, return_counts=True): (array([0, 1], dtype=int8), array([395993211,   7364989], dtype=int64))
    np.unique(predicted_larger_than_min_area, return_counts=True): (array([0, 1], dtype=int8), array([396386572,   6971628], dtype=int64))
ic| np.unique(ignored_polygons, return_counts=True): (array([0, 1], dtype=int8), array([402964839,    393361], dtype=int64))
ic| self.f1: 47.17, self.precision: 32.42, self.recall: 86.55
ic| self.label_mask_val.shape: (48402984,)
ic| self.label_mask_val_valid.shape: (36721217,)
ic| f1_val: 18.44
    precision_val: 11.6
    recall_val: 45.01
    mAP_val: 17.82


(array([0, 1], dtype=int16), array([397858486,   5499714], dtype=int64))
[0 1]


ic| self.label_mask.shape: (19355, 20840)
ic| self.mask_test.shape: (19355, 20840)
ic| self.label_mask_test.shape: (161343280,)
ic| self.error_mask_test.shape: (89476788,)
ic| bounds: (0.00010578750008484349, 0.4985)


(0.00010578750008484349, 0.4985)
0.19047543687881469
threshold 0.19047543687881469


c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\scipy\optimize\_minimize.py:783: RuntimeWarning: Method 'bounded' does not support relative tolerance in x; defaulting to absolute tolerance.
  warn("Method 'bounded' does not support relative tolerance in x; "
ic| label_current_deforestation_test_classified_incorrect.shape: (19903302,)
    predicted_test_classified_incorrect.shape: (19903302,)
ic| TP_H + FN_H + FP_H + TN_H: 19903302
    len(label_mask_current_deforestation_test): 89476788
ic| TP_H + FN_H + FP_H + TN_H: 19903302
    len(label_mask_current_deforestation_test): 89476788


[0.99132908 0.98881911 0.32332715 0.22244095 0.23132926 0.80556594
 0.12765325]
0.30813035062127003
threshold 0.30813035062127003


ic| label_current_deforestation_test_classified_incorrect.shape: (13601177,)
    predicted_test_classified_incorrect.shape: (13601177,)
ic| TP_H + FN_H + FP_H + TN_H: 13601177
    len(label_mask_current_deforestation_test): 89476788
ic| TP_H + FN_H + FP_H + TN_H: 13601177
    len(label_mask_current_deforestation_test): 89476788


[0.90435004 0.98390531 0.48305897 0.15200788 0.17906642 0.75127355
 0.18077202]
0.38084508625754454
threshold 0.38084508625754454


ic| label_current_deforestation_test_classified_incorrect.shape: (11052978,)
    predicted_test_classified_incorrect.shape: (11052978,)
ic| TP_H + FN_H + FP_H + TN_H: 11052978
    len(label_mask_current_deforestation_test): 89476788
ic| TP_H + FN_H + FP_H + TN_H: 11052978
    len(label_mask_current_deforestation_test): 89476788


[0.80068682 0.98288918 0.66736076 0.123529   0.10789171 0.61717349
 0.2052436 ]
0.42578526436372544
threshold 0.42578526436372544


ic| label_current_deforestation_test_classified_incorrect.shape: (9602221,)
    predicted_test_classified_incorrect.shape: (9602221,)
ic| TP_H + FN_H + FP_H + TN_H: 9602221
    len(label_mask_current_deforestation_test): 89476788
ic| TP_H + FN_H + FP_H + TN_H: 9602221
    len(label_mask_current_deforestation_test): 89476788


[0.68555008 0.98063904 0.7635751  0.10731522 0.06549535 0.46041008
 0.20528229]
0.4535598218938191
threshold 0.4535598218938191


ic| label_current_deforestation_test_classified_incorrect.shape: (8461176,)
    predicted_test_classified_incorrect.shape: (8461176,)
ic| TP_H + FN_H + FP_H + TN_H: 8461176
    len(label_mask_current_deforestation_test): 89476788
ic| TP_H + FN_H + FP_H + TN_H: 8461176
    len(label_mask_current_deforestation_test): 89476788


[0.56101864 0.97786267 0.80934646 0.0945628  0.045747   0.32576914
 0.1817087 ]
0.47072544246990633
threshold 0.47072544246990633


ic| label_current_deforestation_test_classified_incorrect.shape: (7503346,)
    predicted_test_classified_incorrect.shape: (7503346,)
ic| TP_H + FN_H + FP_H + TN_H: 7503346
    len(label_mask_current_deforestation_test): 89476788
ic| TP_H + FN_H + FP_H + TN_H: 7503346
    len(label_mask_current_deforestation_test): 89476788


[0.4617484  0.97548466 0.83139854 0.08385802 0.03921413 0.2307815
 0.14173362]
0.4813343794239128
threshold 0.4813343794239128


ic| label_current_deforestation_test_classified_incorrect.shape: (6783022,)
    predicted_test_classified_incorrect.shape: (6783022,)
ic| TP_H + FN_H + FP_H + TN_H: 6783022
    len(label_mask_current_deforestation_test): 89476788
ic| TP_H + FN_H + FP_H + TN_H: 6783022
    len(label_mask_current_deforestation_test): 89476788


[0.40307681 0.97352102 0.84435899 0.07580762 0.03674109 0.15924341
 0.10349203]
0.48789106304599356
threshold 0.48789106304599356


ic| label_current_deforestation_test_classified_incorrect.shape: (6293343,)
    predicted_test_classified_incorrect.shape: (6293343,)
ic| TP_H + FN_H + FP_H + TN_H: 6293343
    len(label_mask_current_deforestation_test): 89476788
ic| TP_H + FN_H + FP_H + TN_H: 6293343
    len(label_mask_current_deforestation_test): 89476788


[0.37087121 0.97207643 0.85215518 0.07033492 0.03582629 0.10806414
 0.07495739]
0.4919433163779192
threshold 0.4919433163779192


ic| label_current_deforestation_test_classified_incorrect.shape: (5979658,)
    predicted_test_classified_incorrect.shape: (5979658,)
ic| TP_H + FN_H + FP_H + TN_H: 5979658
    len(label_mask_current_deforestation_test): 89476788
ic| TP_H + FN_H + FP_H + TN_H: 5979658
    len(label_mask_current_deforestation_test): 89476788


[0.35302113 0.97101495 0.85672571 0.06682915 0.03605532 0.07443387
 0.05587525]
0.4944477466680743
threshold 0.4944477466680743


ic| label_current_deforestation_test_classified_incorrect.shape: (5783839,)
    predicted_test_classified_incorrect.shape: (5783839,)
ic| TP_H + FN_H + FP_H + TN_H: 5783839
    len(label_mask_current_deforestation_test): 89476788
ic| TP_H + FN_H + FP_H + TN_H: 5783839
    len(label_mask_current_deforestation_test): 89476788


[0.34294107 0.97039957 0.85956746 0.06464066 0.03623232 0.05182582
 0.04377826]
0.4959955697098449
threshold 0.4959955697098449


ic| label_current_deforestation_test_classified_incorrect.shape: (5663398,)
    predicted_test_classified_incorrect.shape: (5663398,)
ic| TP_H + FN_H + FP_H + TN_H: 5663398
    len(label_mask_current_deforestation_test): 89476788
ic| TP_H + FN_H + FP_H + TN_H: 5663398
    len(label_mask_current_deforestation_test): 89476788


[0.33717203 0.96996866 0.8611974  0.06329461 0.0370889  0.03824929
 0.03638217]
0.49695217695822935
threshold 0.49695217695822935


ic| label_current_deforestation_test_classified_incorrect.shape: (5589235,)
    predicted_test_classified_incorrect.shape: (5589235,)
ic| TP_H + FN_H + FP_H + TN_H: 5589235
    len(label_mask_current_deforestation_test): 89476788
ic| TP_H + FN_H + FP_H + TN_H: 5589235
    len(label_mask_current_deforestation_test): 89476788


[0.33378684 0.96969661 0.86225184 0.06246575 0.03735996 0.02919423
 0.03183518]
0.49754339275161547
threshold 0.49754339275161547


ic| label_current_deforestation_test_classified_incorrect.shape: (5543771,)
    predicted_test_classified_incorrect.shape: (5543771,)
ic| TP_H + FN_H + FP_H + TN_H: 5543771
    len(label_mask_current_deforestation_test): 89476788
ic| TP_H + FN_H + FP_H + TN_H: 5543771
    len(label_mask_current_deforestation_test): 89476788


[0.33177558 0.96949451 0.86290868 0.06195764 0.03739152 0.02344879
 0.02905313]
0.49790878420661383
threshold 0.49790878420661383


ic| label_current_deforestation_test_classified_incorrect.shape: (5515655,)
    predicted_test_classified_incorrect.shape: (5515655,)
ic| TP_H + FN_H + FP_H + TN_H: 5515655
    len(label_mask_current_deforestation_test): 89476788
ic| TP_H + FN_H + FP_H + TN_H: 5515655
    len(label_mask_current_deforestation_test): 89476788


[0.33056162 0.96938472 0.86330324 0.06164342 0.03751551 0.01995207
 0.02735314]
0.49813460854500163
threshold 0.49813460854500163


ic| label_current_deforestation_test_classified_incorrect.shape: (5498351,)
    predicted_test_classified_incorrect.shape: (5498351,)
ic| TP_H + FN_H + FP_H + TN_H: 5498351
    len(label_mask_current_deforestation_test): 89476788
ic| TP_H + FN_H + FP_H + TN_H: 5498351
    len(label_mask_current_deforestation_test): 89476788


[0.32982423 0.96931578 0.86353587 0.06145003 0.03776473 0.0178758
 0.02631374]
0.49827417566161225
threshold 0.49827417566161225


ic| label_current_deforestation_test_classified_incorrect.shape: (5487759,)
    predicted_test_classified_incorrect.shape: (5487759,)
ic| TP_H + FN_H + FP_H + TN_H: 5487759
    len(label_mask_current_deforestation_test): 89476788
ic| TP_H + FN_H + FP_H + TN_H: 5487759
    len(label_mask_current_deforestation_test): 89476788


[0.32938558 0.96926923 0.86369704 0.06133165 0.03753368 0.0164304
 0.02568389]
0.49836043288338944
threshold 0.49836043288338944


ic| label_current_deforestation_test_classified_incorrect.shape: (5481061,)
    predicted_test_classified_incorrect.shape: (5481061,)
ic| TP_H + FN_H + FP_H + TN_H: 5481061
    len(label_mask_current_deforestation_test): 89476788
ic| TP_H + FN_H + FP_H + TN_H: 5481061
    len(label_mask_current_deforestation_test): 89476788


[0.32910441 0.96924072 0.86378143 0.06125679 0.03773998 0.01567194
 0.02528541]
0.49841374277822287
threshold 0.49841374277822287


ic| label_current_deforestation_test_classified_incorrect.shape: (5476919,)
    predicted_test_classified_incorrect.shape: (5476919,)
ic| TP_H + FN_H + FP_H + TN_H: 5476919
    len(label_mask_current_deforestation_test): 89476788
ic| TP_H + FN_H + FP_H + TN_H: 5476919
    len(label_mask_current_deforestation_test): 89476788


[0.32893074 0.96922788 0.86384073 0.0612105  0.03773552 0.01513711
 0.02503694]
0.4984470835042267
threshold 0.4984470835042267


ic| label_current_deforestation_test_classified_incorrect.shape: (5474329,)
    predicted_test_classified_incorrect.shape: (5474329,)
ic| TP_H + FN_H + FP_H + TN_H: 5474329
    len(label_mask_current_deforestation_test): 89476788
ic| TP_H + FN_H + FP_H + TN_H: 5474329
    len(label_mask_current_deforestation_test): 89476788
ic| self.threshold_optimal: 0.4984470835042267


[0.32882319 0.96921517 0.8638795  0.06118155 0.03769077 0.01478756
 0.02488145]
threshold:  0.4984470835042267
threshold 0.4984470835042267


ic| label_current_deforestation_test_classified_incorrect.shape: (5474329,)
    predicted_test_classified_incorrect.shape: (5474329,)
ic| TP_H + FN_H + FP_H + TN_H: 5474329
    len(label_mask_current_deforestation_test): 89476788
ic| TP_H + FN_H + FP_H + TN_H: 5474329
    len(label_mask_current_deforestation_test): 89476788


[0.32882319 0.96921517 0.8638795  0.06118155 0.03769077 0.01478756
 0.02488145]
threshold 0.4984470835042267
(89476788,) (89476788,)


ic| self.m_optimal: {'AA': array([0.06118155]),
                     'UEO': array([0.02488145]),
                     'f1': 47.17,
                     'f1_H': array([0.02124132]),
                     'f1_L': array([0.49104931]),
                     'precision_H': array([0.03769077]),
                     'precision_L': array([0.32882319]),
                     'recall_H': array([0.01478756]),
                     'recall_L': array([0.96921517]),
                     'recall_Ltotal': array([0.8638795])}
ic| self.m_audited_optimal: {'f1': array([0.52066143]),
                             'precision': array([0.35548546]),
                             'recall': array([0.97256091])}


cm_audited [[85841974  2319428]
 [   36093  1279293]]
[0.35548546 0.97256091]
Result idx 1: {'uncertainty_result': {'metrics': {'precision_L': array([0.32882319]), 'recall_L': array([0.96921517]), 'recall_Ltotal': array([0.8638795]), 'AA': array([0.06118155]), 'precision_H': array([0.03769077]), 'recall_H': array([0.01478756]), 'UEO': array([0.02488145]), 'f1_L': array([0.49104931]), 'f1_H': array([0.02124132]), 'f1': 47.17}, 'metrics_audited': {'precision': array([0.35548546]), 'recall': array([0.97256091]), 'f1': array([0.52066143])}, 'exp': 46}}
Grid execution idx: 1
Beginning run number 2
manager.config {'training': True, 'inferring': True, 'site': 'PI', 'training_date': 'current', 'mode': 'evidential2', 'training_times': 3, 'uncertainty_method': 'pred_entropy', 'loadInference': False, 'removePolygons': True, 'plotLandsat': False, 'plotPOI': False, 'training_experiment_id': 46, 'get_multiple_metrics': False, 'start_repetition_id': 0, 'end_repetition_id': 3, 'save_probabilities': Fa

ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([340580606,   4312043,   6953620,   5659916,   7162776,   6261432,
                                                                      8191420,   3233962,   3270293,   3044419,   1817289,   2359424,
                                                                      2201926,   3050229,   2901307,   2418575], dtype=int64))


Label where deforestation past years is actual date (2020) = 1


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([340580606,   4312043,   6953620,   5659916,   7162776,   6261432,
                                                                      8191420,   3233962,   3270293,   3044419,   1817289,   2359424,
                                                                      2201926,   3050229,   2901307,   2418575], dtype=int64))


Past deforestation different from 0 (no deforestation)


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([340580606,   4312043,   6953620,   5659916,   7162776,   6261432,
                                                                      8191420,   3233962,   3270293,   3044419,   1817289,   2359424,
                                                                      2201926,   3050229,   2901307,   2418575], dtype=int64))


Past deforestation before 2008 is 2
D:/Jorge/datasets/deforestation/PI/deforestation_before_2000_PI.tif


ic| np.unique(label_past_deforestation_before_2008, return_counts=True): (array([  0, 208], dtype=uint8), array([385251297,  18167940], dtype=int64))
ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([340580606,   4312043,   6953620,   5659916,   7162776,   6261432,
                                                                      8191420,   3233962,   3270293,   3044419,   1817289,   2359424,
                                                                      2201926,   3050229,   2901307,   2418575], dtype=int64))


D:/Jorge/datasets/sentinel2/PI/biome_limits.tif


KeyboardInterrupt: 

In [ ]:
error_count

0

In [ ]:
print(results)

[{'uncertainty_result': {'metrics': {'precision_L': array([0.70563854]), 'recall_L': array([0.96048301]), 'recall_Ltotal': array([0.87069108]), 'AA': array([0.02999895]), 'precision_H': array([0.15253552]), 'recall_H': array([0.44877206]), 'UEO': array([0.11639467]), 'f1_L': array([0.81357069]), 'f1_H': array([0.22768274]), 'f1': 72.75}, 'metrics_audited': {'precision': array([0.72636998]), 'recall': array([0.9641773]), 'f1': array([0.8285476])}, 'exp': 44}}, {'uncertainty_result': {'metrics': {'precision_L': array([0.56326273]), 'recall_L': array([0.95704665]), 'recall_Ltotal': array([0.86589904]), 'AA': array([0.02999832]), 'precision_H': array([0.10471903]), 'recall_H': array([0.39042686]), 'UEO': array([0.13660256]), 'f1_L': array([0.70915659]), 'f1_H': array([0.16514375]), 'f1': 62.45}, 'metrics_audited': {'precision': array([0.58874108]), 'recall': array([0.96113746]), 'f1': array([0.73020058])}, 'exp': 44}}, {'uncertainty_result': {'metrics': {'precision_L': array([0.64202204]),

In [ ]:
print(len(results))

10


In [ ]:
results[7]

{'uncertainty_result': {'metrics': {'precision_L': array([0.58988893]),
   'recall_L': array([0.98461672]),
   'recall_Ltotal': array([0.90728721]),
   'AA': array([0.02999981]),
   'precision_H': array([0.09141104]),
   'recall_H': array([0.44125552]),
   'UEO': array([0.14428742]),
   'f1_L': array([0.7377738]),
   'f1_H': array([0.15144794]),
   'f1': 64.58},
  'metrics_audited': {'precision': array([0.60981293]),
   'recall': array([0.98582489]),
   'f1': array([0.75351531])},
  'exp': 44}}