In [1]:
import tracemalloc

from utils_v1 import *
import traceback


In [2]:
from icecream import ic

import numpy as np
from src.dataset import (
    MultipleDates, PAMultipleDates,
    MTMultipleDates, MSMultipleDates, PIMultipleDates
)

# from src.dataset_legacy import MTDeforestationTime
from src import training_generator as generator
from src.patchesHandler import PatchesHandler, PatchesHandlerMultipleDates, PatchesHandlerEvidential2

from src.manager.evidential import ManagerEvidential
from src.manager.multioutput import ManagerMCDropout, ManagerSingleRun, ManagerEvidential2
from mpl_toolkits.axes_grid1 import make_axes_locatable

import cv2
from src import metrics as _metric
import json
import pickle 
import src.manager.evidential as evidential
from src.Logger import Logger
import pdb


Tensorflow ver. 2.6.0


In [3]:

with open('config/config.json', 'r') as f:
    config = json.load(f)
    
print("Mode: {}. Site: {}. Training: {}. Training date: {}".format(
    config['mode'], config['site'], config['training'], config['training_date']))
print(config)


Mode: evidential2. Site: PI. Training: False. Training date: earlier
{'training': False, 'inferring': True, 'site': 'PI', 'training_date': 'earlier', 'mode': 'evidential2', 'training_times': 10, 'uncertainty_method': 'pred_entropy', 'loadInference': False, 'removePolygons': True, 'plotLandsat': False, 'plotPOI': False, 'training_experiment_id': 15, 'get_multiple_metrics': False, 'save_probabilities': False, 'addPastDeforestationInput': True, 'classes_mode': True, 'learning_rate': 0.0001, 'use_cloud_mask': False, 'log_filename': 'log_mcd_pi_earlier.pkl'}


In [4]:

if config['site'] == 'PA':
	if config['training_date'] == 'earlier':
		dates = [2017, 2018]
	else:
		dates = [2018, 2019]
	datasetClass = PAMultipleDates
elif config['site'] == 'MT':
	if config['training_date'] == 'earlier':
		dates = [2018, 2019]
	else:
		dates = [2019, 2020]
	datasetClass = MTMultipleDates
elif config['site'] == 'MS':
	if config['training_date'] == 'earlier':
		dates = [2018, 2019]
	else:
		dates = [2019, 2020]
	datasetClass = MSMultipleDates
elif config['site'] == 'PI':
	if config['training_date'] == 'earlier':
		dates = [2018, 2019]
	else:
		dates = [2019, 2020]
	datasetClass = PIMultipleDates
else:
	raise ValueError('Invalid site')

dataset = datasetClass(config = config,
			   dates = dates, 
	 	addPastDeforestationInput = config['addPastDeforestationInput'],
		borderBuffer = 2)	

if config['mode'] == 'ensemble':
	if config['training'] == True:
		config['mode'] = 'single_run'
	else:
		sys.exit("Ensure that training is True for ensemble mode. Use infer_ensemble.ipynb for inference.")

if config['training'] == False:
	if config['site'] == 'PA':
		if config['mode'] == 'mcd' or config['mode'] == 'single_run': # MCD will do 10 inference on each of the 10 repetitions = 100 runs
			if config['training_date'] == 'current': exp = 0
			elif config['training_date'] == 'earlier': exp = 1
				
		if config['mode'] == 'evidential2':
			if config['training_date'] == 'current': exp = 8; repetition_id = 0
			elif config['training_date'] == 'earlier': exp = 9; repetition_id = 0

	elif config['site'] == 'MT':

		if config['mode'] == 'mcd' or config['mode'] == 'single_run':
			if config['training_date'] == 'current': exp = 2
			elif config['training_date'] == 'earlier': exp = 3
		if config['mode'] == 'evidential2':
			if config['training_date'] == 'current': exp = 10; repetition_id = 0
			elif config['training_date'] == 'earlier': exp = 11; repetition_id = 0

	elif config['site'] == 'MS':

		if config['mode'] == 'mcd' or config['mode'] == 'single_run':
			if config['training_date'] == 'current': exp = 4
			elif config['training_date'] == 'earlier': exp = 5
		if config['mode'] == 'evidential2':
			if config['training_date'] == 'current': exp = 12; repetition_id = 0
			elif config['training_date'] == 'earlier': exp = 13; repetition_id = 0
	elif config['site'] == 'PI':

		if config['mode'] == 'mcd' or config['mode'] == 'single_run':
			if config['training_date'] == 'current': exp = 6
			elif config['training_date'] == 'earlier': exp = 7
		if config['mode'] == 'evidential2':
			if config['training_date'] == 'current': exp = 14; repetition_id = 0
			elif config['training_date'] == 'earlier': exp = 15; repetition_id = 0

else:
	exp = config['training_experiment_id']
ic(dates)


if issubclass(type(dataset), MultipleDates):
	patchesHandler = PatchesHandlerMultipleDates(
		dataset)
elif config['mode'] == 'evidential2':
	patchesHandler = PatchesHandlerEvidential2()
else:
	patchesHandler = PatchesHandler()



ic| list(self.date_ids): [0]
ic| self.image_channels: [[0, 1, 2, 3, 4, 5, 6, 7, 8]]
ic| dates: [2018, 2019]
ic| self.input_image_shape: 9
ic| self.dataset.image_channels: [[0, 1, 2, 3, 4, 5, 6, 7, 8]]


In [5]:


if config['mode'] == 'evidential2':
    config["inference_times"] = 1
    manager_class = ManagerEvidential2
    config['uncertainty_method'] = "pred_entropy"
    config['classes_mode'] = True
    
if config['mode'] == 'mcd':
    config["inference_times"] = 10
    manager_class = ManagerMCDropout
    config['uncertainty_method'] = "pred_entropy"
    config['classes_mode'] = False

elif config['mode'] == 'single_run':
    config["inference_times"] = 1
    manager_class = ManagerSingleRun
    config['uncertainty_method'] = "pred_entropy_single"
    config['classes_mode'] = False



In [6]:
exp

15

In [7]:
logger = Logger()


In [8]:
if config['training'] == True:
    

    manager = manager_class(config, dataset, patchesHandler, logger)
    print("manager.config['dropout_training']", manager.config['dropout_training'])
    manager.defineExperiment(exp) # fixed
    
    manager.setExperimentPath()
    manager.createLogFolders()

    manager.loadDataset()

    # %%
    if config["training"] == True:
        manager.run()


In [9]:



if config['site'] == 'PA':
	dates = [2018, 2019]
	datasetClass = PAMultipleDates
elif config['site'] == 'MT':
	dates = [2019, 2020]
	datasetClass = MTMultipleDates
elif config['site'] == 'MS':
	dates = [2019, 2020]
	datasetClass = MSMultipleDates
elif config['site'] == 'PI':
	dates = [2019, 2020]
	datasetClass = PIMultipleDates
else:
	raise ValueError('Invalid site')

dataset = datasetClass(config = config,
			   dates = dates, 
	 	addPastDeforestationInput = config['addPastDeforestationInput'],
		borderBuffer = 2)


ic(dates)

if issubclass(type(dataset), MultipleDates):
	patchesHandler = PatchesHandlerMultipleDates(
		dataset)
elif config['mode'] == 'evidential2':
	patchesHandler = PatchesHandlerEvidential2()
else:
	patchesHandler = PatchesHandler()


ic| list(self.date_ids): [0]
ic| self.image_channels: [[0, 1, 2, 3, 4, 5, 6, 7, 8]]
ic| dates: [2019, 2020]
ic| self.input_image_shape: 9
ic| self.dataset.image_channels: [[0, 1, 2, 3, 4, 5, 6, 7, 8]]


In [10]:
manager_class

src.manager.multioutput.ManagerEvidential2

In [11]:
exp

15

In [12]:
repetition_ids = manager_class(config, dataset, patchesHandler, logger).get_repetition_ids(exp)  
repetition_n = len(repetition_ids)
print("repetition_ids {}, repetition_n {}".format(repetition_ids, repetition_n))


repetition_ids [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], repetition_n 10


In [13]:
if config['inferring'] == True:
    results = []
    error_count = 0

    # while idx < len(repetition_n):
    for idx in range(repetition_n): # 10 repetitions
    # for idx in range(0, 4): # 10 repetitions


        print("Beginning run number {}".format(idx))
        logger = Logger()
        manager = manager_class(config, dataset, patchesHandler, logger)

        print("manager.config", manager.config)

        manager.defineExperiment(exp) # fixed
        manager.defineRepetitionId(idx) # varying from 0 to 10
        manager.setExperimentPath()
        manager.createLogFolders()

        manager.loadDataset()

        # %%
        if config['get_multiple_metrics'] == False:
            predictor_fcn = manager.run_predictor
        else:
            predictor_fcn = manager.run_predictor_multiple_metrics
        result = predictor_fcn()
        print("Result idx {}: {}".format(idx, result))
        results.append(result)


        with open(manager.default_log_name, 'wb') as f:
            pickle.dump(results, f)
        print("Grid execution idx: {}".format(idx))
        # idx += 1
    

Beginning run number 0
manager.config {'training': False, 'inferring': True, 'site': 'PI', 'training_date': 'earlier', 'mode': 'evidential2', 'training_times': 10, 'uncertainty_method': 'pred_entropy', 'loadInference': False, 'removePolygons': True, 'plotLandsat': False, 'plotPOI': False, 'training_experiment_id': 15, 'get_multiple_metrics': False, 'save_probabilities': False, 'addPastDeforestationInput': True, 'classes_mode': True, 'learning_rate': 0.0001, 'use_cloud_mask': False, 'log_filename': 'log_mcd_pi_earlier.pkl', 'inference_times': 1, 'dropout_training': False}
D:/Jorge/datasets/deforestation/PI/deforestation_past_years.tif
Loaded deforestation past years


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([340580606,   4312043,   6953620,   5659916,   7162776,   6261432,
                                                                      8191420,   3233962,   3270293,   3044419,   1817289,   2359424,
                                                                      2201926,   3050229,   2901307,   2418575], dtype=int64))


Label where deforestation past years is actual date (2020) = 1


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([340580606,   4312043,   6953620,   5659916,   7162776,   6261432,
                                                                      8191420,   3233962,   3270293,   3044419,   1817289,   2359424,
                                                                      2201926,   3050229,   2901307,   2418575], dtype=int64))


Past deforestation different from 0 (no deforestation)


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([340580606,   4312043,   6953620,   5659916,   7162776,   6261432,
                                                                      8191420,   3233962,   3270293,   3044419,   1817289,   2359424,
                                                                      2201926,   3050229,   2901307,   2418575], dtype=int64))


Past deforestation before 2008 is 2
D:/Jorge/datasets/deforestation/PI/deforestation_before_2000_PI.tif


ic| np.unique(label_past_deforestation_before_2008, return_counts=True): (array([  0, 208], dtype=uint8), array([385251297,  18167940], dtype=int64))
ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([340580606,   4312043,   6953620,   5659916,   7162776,   6261432,
                                                                      8191420,   3233962,   3270293,   3044419,   1817289,   2359424,
                                                                      2201926,   3050229,   2901307,   2418575], dtype=int64))
ic| label_per_date.shape: (19357, 20841, 1)


Removing bufer................
Mask label shape:  
 (19357, 20841, 1) 
 Unique values:  
 [0 1 2]
Tiles size:  3871 4168
Mask size:  (19355, 20840)


ic| image_stack.shape: (19357, 20841, 9)


Image shape:  (19357, 20841, 9)
mask:  (19355, 20840)
image stack:  (19355, 20840, 9)
ref : (19355, 20840, 1)
Training tiles:  [2, 4, 5, 6, 7, 12, 14, 15, 18, 21, 23, 25]
Validation tiles:  [9, 11, 24]
Test tiles:  [1, 3, 8, 10, 13, 16, 17, 19, 20, 22]
-5.0 -24.0


ic| self.path_models+ '/' + self.method +'_'+str(self.repetition_id)+'.h5': 'D:/Jorge/datasets/deforestation/experiments/PI/exp15/models/resunet_0.h5'


Dropout training mode: False
time:  0
alpha.shape (19360, 20864, 2)
S.shape (19360, 20864)
K 2
u.shape (19360, 20864)
belief.shape (19360, 20864, 2)
(122722628,)
(array([0, 1], dtype=uint8), array([121393418,   1329210], dtype=int64))
(19355, 20840, 2)


ic| predicted_test.shape: (161343280,)
ic| predicted_test.shape: (122722628,)
ic| np.unique(predicted, return_counts=True): (array([0, 1], dtype=int8), array([397329670,   6028530], dtype=int64))
    np.unique(predicted_larger_than_min_area, return_counts=True): (array([0, 1], dtype=int8), array([397796104,   5562096], dtype=int64))
ic| np.unique(ignored_polygons, return_counts=True): (array([0, 1], dtype=int8), array([402891766,    466434], dtype=int64))
ic| self.f1: 53.06, self.precision: 44.83, self.recall: 64.99
ic| self.label_mask_val.shape: (48402984,)
ic| self.label_mask_val_valid.shape: (42320690,)
ic| f1_val: 21.01
    precision_val: 13.27
    recall_val: 50.44
    mAP_val: 25.98


(array([0, 1], dtype=int16), array([398435994,   4922206], dtype=int64))
[0 1]


ic| self.label_mask.shape: (19355, 20840)
ic| self.mask_amazon_ts.shape: (19355, 20840)
ic| self.label_mask_test.shape: (161343280,)
ic| self.error_mask_test.shape: (122562412,)
ic| bounds: (0.0015907875000848435, 0.4985)
c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\scipy\optimize\_minimize.py:783: RuntimeWarning: Method 'bounded' does not support relative tolerance in x; defaulting to absolute tolerance.
  warn("Method 'bounded' does not support relative tolerance in x; "


0.1913932173521083
threshold 0.1913932173521083


ic| label_current_deforestation_test_classified_incorrect.shape: (6866221,)
    predicted_test_classified_incorrect.shape: (6866221,)
ic| TP_H + FN_H + FP_H + TN_H: 6866221
    len(label_mask_current_deforestation_test): 122562412
ic| TP_H + FN_H + FP_H + TN_H: 6866221
    len(label_mask_current_deforestation_test): 122562412


[0.63872116 0.70392319 0.57798107 0.05602224 0.13201103 0.40201183
 0.09983981]
0.3086975701479765
threshold 0.3086975701479765


ic| label_current_deforestation_test_classified_incorrect.shape: (4542166,)
    predicted_test_classified_incorrect.shape: (4542166,)
ic| TP_H + FN_H + FP_H + TN_H: 4542166
    len(label_mask_current_deforestation_test): 122562412
ic| TP_H + FN_H + FP_H + TN_H: 4542166
    len(label_mask_current_deforestation_test): 122562412


[0.5632294  0.70146712 0.60756099 0.03706002 0.11412727 0.31631827
 0.10017104]
0.3811956472041318
threshold 0.3811956472041318


ic| label_current_deforestation_test_classified_incorrect.shape: (3459753,)
    predicted_test_classified_incorrect.shape: (3459753,)
ic| TP_H + FN_H + FP_H + TN_H: 3459753
    len(label_mask_current_deforestation_test): 122562412
ic| TP_H + FN_H + FP_H + TN_H: 3459753
    len(label_mask_current_deforestation_test): 122562412


[0.52329756 0.69902686 0.62266451 0.0282285  0.10483298 0.24937844
 0.09054269]
0.42299128417748205
threshold 0.42299128417748205


ic| label_current_deforestation_test_classified_incorrect.shape: (2941294,)
    predicted_test_classified_incorrect.shape: (2941294,)
ic| TP_H + FN_H + FP_H + TN_H: 2941294
    len(label_mask_current_deforestation_test): 122562412
ic| TP_H + FN_H + FP_H + TN_H: 2941294
    len(label_mask_current_deforestation_test): 122562412


[0.50043354 0.69763442 0.63097042 0.02399834 0.10024434 0.19816849
 0.07834826]
0.3688829399806771
threshold 0.3688829399806771


ic| label_current_deforestation_test_classified_incorrect.shape: (3626616,)
    predicted_test_classified_incorrect.shape: (3626616,)
ic| TP_H + FN_H + FP_H + TN_H: 3626616
    len(label_mask_current_deforestation_test): 122562412
ic| TP_H + FN_H + FP_H + TN_H: 3626616
    len(label_mask_current_deforestation_test): 122562412


[0.53001548 0.69945928 0.6202636  0.02958995 0.10606731 0.26181027
 0.09304544]
0.3458941743300681
threshold 0.3458941743300681


ic| label_current_deforestation_test_classified_incorrect.shape: (3957433,)
    predicted_test_classified_incorrect.shape: (3957433,)
ic| TP_H + FN_H + FP_H + TN_H: 3957433
    len(label_mask_current_deforestation_test): 122562412
ic| TP_H + FN_H + FP_H + TN_H: 3957433
    len(label_mask_current_deforestation_test): 122562412


[0.54250687 0.7003132  0.61565557 0.03228912 0.10876333 0.2833368
 0.09661069]
0.3648907039077019
threshold 0.3648907039077019


ic| label_current_deforestation_test_classified_incorrect.shape: (3682644,)
    predicted_test_classified_incorrect.shape: (3682644,)
ic| TP_H + FN_H + FP_H + TN_H: 3682644
    len(label_mask_current_deforestation_test): 122562412
ic| TP_H + FN_H + FP_H + TN_H: 3682644
    len(label_mask_current_deforestation_test): 122562412


[0.53217836 0.69959754 0.61946712 0.03004709 0.1065337  0.26576124
 0.09375047]
0.35763467527733844
threshold 0.35763467527733844


ic| label_current_deforestation_test_classified_incorrect.shape: (3785267,)
    predicted_test_classified_incorrect.shape: (3785267,)
ic| TP_H + FN_H + FP_H + TN_H: 3785267
    len(label_mask_current_deforestation_test): 122562412
ic| TP_H + FN_H + FP_H + TN_H: 3785267
    len(label_mask_current_deforestation_test): 122562412


[0.5360803  0.69986107 0.61800841 0.0308844  0.10743027 0.27273973
 0.09493179]
0.36440842418963904
threshold 0.36440842418963904


ic| label_current_deforestation_test_classified_incorrect.shape: (3689450,)
    predicted_test_classified_incorrect.shape: (3689450,)
ic| TP_H + FN_H + FP_H + TN_H: 3689450
    len(label_mask_current_deforestation_test): 122562412
ic| TP_H + FN_H + FP_H + TN_H: 3689450
    len(label_mask_current_deforestation_test): 122562412


[0.53243889 0.69961841 0.61936336 0.03010262 0.1066116  0.26626097
 0.09383694]
0.36589971506479535
threshold 0.36589971506479535


ic| label_current_deforestation_test_classified_incorrect.shape: (3668408,)
    predicted_test_classified_incorrect.shape: (3668408,)
ic| TP_H + FN_H + FP_H + TN_H: 3668408
    len(label_mask_current_deforestation_test): 122562412
ic| TP_H + FN_H + FP_H + TN_H: 3668408
    len(label_mask_current_deforestation_test): 122562412


[0.53162866 0.69955937 0.61967616 0.02993094 0.10639669 0.2647385
 0.09357027]
0.36527611187468373
threshold 0.36527611187468373


ic| label_current_deforestation_test_classified_incorrect.shape: (3677189,)
    predicted_test_classified_incorrect.shape: (3677189,)
ic| TP_H + FN_H + FP_H + TN_H: 3677189
    len(label_mask_current_deforestation_test): 122562412
ic| TP_H + FN_H + FP_H + TN_H: 3677189
    len(label_mask_current_deforestation_test): 122562412


[0.53197088 0.69958142 0.61955638 0.03000258 0.10645295 0.26532477
 0.09367954]
0.3653457462087763
threshold 0.3653457462087763


ic| label_current_deforestation_test_classified_incorrect.shape: (3676243,)
    predicted_test_classified_incorrect.shape: (3676243,)
ic| TP_H + FN_H + FP_H + TN_H: 3676243
    len(label_mask_current_deforestation_test): 122562412
ic| TP_H + FN_H + FP_H + TN_H: 3676243
    len(label_mask_current_deforestation_test): 122562412


[0.53194086 0.69957824 0.61957011 0.02999486 0.10643896 0.26525956
 0.0936717 ]
0.3652427731234301
threshold 0.3652427731234301


ic| label_current_deforestation_test_classified_incorrect.shape: (3677666,)
    predicted_test_classified_incorrect.shape: (3677666,)
ic| TP_H + FN_H + FP_H + TN_H: 3677666
    len(label_mask_current_deforestation_test): 122562412
ic| TP_H + FN_H + FP_H + TN_H: 3677666
    len(label_mask_current_deforestation_test): 122562412


[0.53198794 0.69958537 0.61955027 0.03000648 0.10645613 0.26534627
 0.09368534]
0.36530945062593734
threshold 0.36530945062593734


ic| label_current_deforestation_test_classified_incorrect.shape: (3676738,)
    predicted_test_classified_incorrect.shape: (3676738,)
ic| TP_H + FN_H + FP_H + TN_H: 3676738
    len(label_mask_current_deforestation_test): 122562412
ic| TP_H + FN_H + FP_H + TN_H: 3676738
    len(label_mask_current_deforestation_test): 122562412
ic| self.threshold_optimal: 0.36530945062593734


[0.53195804 0.69958021 0.61956172 0.0299989  0.10644846 0.26529932
 0.09367737]
threshold:  0.36530945062593734
threshold 0.36530945062593734


ic| label_current_deforestation_test_classified_incorrect.shape: (3676738,)
    predicted_test_classified_incorrect.shape: (3676738,)
ic| TP_H + FN_H + FP_H + TN_H: 3676738
    len(label_mask_current_deforestation_test): 122562412
ic| TP_H + FN_H + FP_H + TN_H: 3676738
    len(label_mask_current_deforestation_test): 122562412


[0.53195804 0.69958021 0.61956172 0.0299989  0.10644846 0.26529932
 0.09367737]
threshold 0.36530945062593734
(122562412,) (122562412,)


ic| self.m_optimal: {'AA': array([0.0299989]),
                     'UEO': array([0.09367737]),
                     'f1': 53.06,
                     'f1_H': array([0.15193476]),
                     'f1_L': array([0.60436177]),
                     'precision_H': array([0.10644846]),
                     'precision_L': array([0.53195804]),
                     'recall_H': array([0.26529932]),
                     'recall_L': array([0.69958021]),
                     'recall_Ltotal': array([0.61956172])}
ic| self.m_audited_optimal: {'f1': array([0.64407406]),
                             'precision': array([0.57381291]),
                             'recall': array([0.73394245])}


cm_audited [[120537140    714518]
 [   348736    962018]]
[0.57381291 0.73394245]
Result idx 0: {'uncertainty_result': {'metrics': {'precision_L': array([0.53195804]), 'recall_L': array([0.69958021]), 'recall_Ltotal': array([0.61956172]), 'AA': array([0.0299989]), 'precision_H': array([0.10644846]), 'recall_H': array([0.26529932]), 'UEO': array([0.09367737]), 'f1_L': array([0.60436177]), 'f1_H': array([0.15193476]), 'f1': 53.06}, 'metrics_audited': {'precision': array([0.57381291]), 'recall': array([0.73394245]), 'f1': array([0.64407406])}, 'exp': 15}}
Grid execution idx: 0
Beginning run number 1
manager.config {'training': False, 'inferring': True, 'site': 'PI', 'training_date': 'earlier', 'mode': 'evidential2', 'training_times': 10, 'uncertainty_method': 'pred_entropy', 'loadInference': False, 'removePolygons': True, 'plotLandsat': False, 'plotPOI': False, 'training_experiment_id': 15, 'get_multiple_metrics': False, 'save_probabilities': False, 'addPastDeforestationInput': True, 'cla

ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([340580606,   4312043,   6953620,   5659916,   7162776,   6261432,
                                                                      8191420,   3233962,   3270293,   3044419,   1817289,   2359424,
                                                                      2201926,   3050229,   2901307,   2418575], dtype=int64))


Label where deforestation past years is actual date (2020) = 1


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([340580606,   4312043,   6953620,   5659916,   7162776,   6261432,
                                                                      8191420,   3233962,   3270293,   3044419,   1817289,   2359424,
                                                                      2201926,   3050229,   2901307,   2418575], dtype=int64))


Past deforestation different from 0 (no deforestation)


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([340580606,   4312043,   6953620,   5659916,   7162776,   6261432,
                                                                      8191420,   3233962,   3270293,   3044419,   1817289,   2359424,
                                                                      2201926,   3050229,   2901307,   2418575], dtype=int64))


Past deforestation before 2008 is 2
D:/Jorge/datasets/deforestation/PI/deforestation_before_2000_PI.tif


ic| np.unique(label_past_deforestation_before_2008, return_counts=True): (array([  0, 208], dtype=uint8), array([385251297,  18167940], dtype=int64))
ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([340580606,   4312043,   6953620,   5659916,   7162776,   6261432,
                                                                      8191420,   3233962,   3270293,   3044419,   1817289,   2359424,
                                                                      2201926,   3050229,   2901307,   2418575], dtype=int64))
ic| label_per_date.shape: (19357, 20841, 1)


Removing bufer................
Mask label shape:  
 (19357, 20841, 1) 
 Unique values:  
 [0 1 2]
Tiles size:  3871 4168
Mask size:  (19355, 20840)


ic| image_stack.shape: (19357, 20841, 9)


Image shape:  (19357, 20841, 9)
mask:  (19355, 20840)
image stack:  (19355, 20840, 9)
ref : (19355, 20840, 1)
Training tiles:  [2, 4, 5, 6, 7, 12, 14, 15, 18, 21, 23, 25]
Validation tiles:  [9, 11, 24]
Test tiles:  [1, 3, 8, 10, 13, 16, 17, 19, 20, 22]
-5.0 -24.0


ic| self.path_models+ '/' + self.method +'_'+str(self.repetition_id)+'.h5': 'D:/Jorge/datasets/deforestation/experiments/PI/exp15/models/resunet_1.h5'


Dropout training mode: False
time:  0
alpha.shape (19360, 20864, 2)
S.shape (19360, 20864)
K 2
u.shape (19360, 20864)
belief.shape (19360, 20864, 2)
(122722628,)
(array([0, 1], dtype=uint8), array([121393418,   1329210], dtype=int64))
(19355, 20840, 2)


ic| predicted_test.shape: (161343280,)
ic| predicted_test.shape: (122722628,)
ic| np.unique(predicted, return_counts=True): (array([0, 1], dtype=int8), array([395418698,   7939502], dtype=int64))
    np.unique(predicted_larger_than_min_area, return_counts=True): (array([0, 1], dtype=int8), array([395874772,   7483428], dtype=int64))
ic| np.unique(ignored_polygons, return_counts=True): (array([0, 1], dtype=int8), array([402902126,    456074], dtype=int64))
ic| self.f1: 45.57, self.precision: 36.04, self.recall: 61.93
ic| self.label_mask_val.shape: (48402984,)
ic| self.label_mask_val_valid.shape: (42323804,)
ic| f1_val: 17.04
    precision_val: 10.0
    recall_val: 57.41
    mAP_val: 24.46


(array([0, 1], dtype=int16), array([396574808,   6783392], dtype=int64))
[0 1]


ic| self.label_mask.shape: (19355, 20840)
ic| self.mask_amazon_ts.shape: (19355, 20840)
ic| self.label_mask_test.shape: (161343280,)
ic| self.error_mask_test.shape: (122569923,)
ic| bounds: (0.0015907875000848435, 0.4985)
c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\scipy\optimize\_minimize.py:783: RuntimeWarning: Method 'bounded' does not support relative tolerance in x; defaulting to absolute tolerance.
  warn("Method 'bounded' does not support relative tolerance in x; "


0.1913932173521083
threshold 0.1913932173521083


ic| label_current_deforestation_test_classified_incorrect.shape: (5648239,)
    predicted_test_classified_incorrect.shape: (5648239,)
ic| TP_H + FN_H + FP_H + TN_H: 5648239
    len(label_mask_current_deforestation_test): 122569923
ic| TP_H + FN_H + FP_H + TN_H: 5648239
    len(label_mask_current_deforestation_test): 122569923


[0.5038396  0.66472336 0.55105517 0.04608177 0.10928285 0.39912735
 0.12847494]
0.3086975701479765
threshold 0.3086975701479765


ic| label_current_deforestation_test_classified_incorrect.shape: (3548194,)
    predicted_test_classified_incorrect.shape: (3548194,)
ic| TP_H + FN_H + FP_H + TN_H: 3548194
    len(label_mask_current_deforestation_test): 122569923
ic| TP_H + FN_H + FP_H + TN_H: 3548194
    len(label_mask_current_deforestation_test): 122569923


[0.44254065 0.65469589 0.57814443 0.02894833 0.09994943 0.3520308
 0.11936162]
0.3811956472041318
threshold 0.3811956472041318


ic| label_current_deforestation_test_classified_incorrect.shape: (2816276,)
    predicted_test_classified_incorrect.shape: (2816276,)
ic| TP_H + FN_H + FP_H + TN_H: 2816276
    len(label_mask_current_deforestation_test): 122569923
ic| TP_H + FN_H + FP_H + TN_H: 2816276
    len(label_mask_current_deforestation_test): 122569923


[0.41187097 0.65392104 0.59293793 0.02297689 0.09463663 0.28274705
 0.09644726]
0.3078118738633758
threshold 0.3078118738633758


ic| label_current_deforestation_test_classified_incorrect.shape: (3559239,)
    predicted_test_classified_incorrect.shape: (3559239,)
ic| TP_H + FN_H + FP_H + TN_H: 3559239
    len(label_mask_current_deforestation_test): 122569923
ic| TP_H + FN_H + FP_H + TN_H: 3559239
    len(label_mask_current_deforestation_test): 122569923


[0.44293176 0.65473165 0.57795523 0.02903844 0.10002491 0.35263196
 0.11955312]
0.26334390400067087
threshold 0.26334390400067087


ic| label_current_deforestation_test_classified_incorrect.shape: (4207060,)
    predicted_test_classified_incorrect.shape: (4207060,)
ic| TP_H + FN_H + FP_H + TN_H: 4207060
    len(label_mask_current_deforestation_test): 122569923
ic| TP_H + FN_H + FP_H + TN_H: 4207060
    len(label_mask_current_deforestation_test): 122569923


[0.46441847 0.65791551 0.56845095 0.03432375 0.10289562 0.37398593
 0.12702461]
0.2952456326120713
threshold 0.2952456326120713


ic| label_current_deforestation_test_classified_incorrect.shape: (3723928,)
    predicted_test_classified_incorrect.shape: (3723928,)
ic| TP_H + FN_H + FP_H + TN_H: 3723928
    len(label_mask_current_deforestation_test): 122569923
ic| TP_H + FN_H + FP_H + TN_H: 3723928
    len(label_mask_current_deforestation_test): 122569923


[0.4488959  0.65542047 0.57539263 0.03038207 0.10061494 0.35964836
 0.12226936]
0.2959528125568814
threshold 0.2959528125568814


ic| label_current_deforestation_test_classified_incorrect.shape: (3714284,)
    predicted_test_classified_incorrect.shape: (3714284,)
ic| TP_H + FN_H + FP_H + TN_H: 3714284
    len(label_mask_current_deforestation_test): 122569923
ic| TP_H + FN_H + FP_H + TN_H: 3714284
    len(label_mask_current_deforestation_test): 122569923


[0.44856903 0.65536146 0.57555131 0.03030339 0.10054803 0.35929385
 0.12212629]
0.29979125638622095
threshold 0.29979125638622095


ic| label_current_deforestation_test_classified_incorrect.shape: (3662808,)
    predicted_test_classified_incorrect.shape: (3662808,)
ic| TP_H + FN_H + FP_H + TN_H: 3662808
    len(label_mask_current_deforestation_test): 122569923
ic| TP_H + FN_H + FP_H + TN_H: 3662808
    len(label_mask_current_deforestation_test): 122569923


[0.4467723  0.65512837 0.57634321 0.02988342 0.10032655 0.35725387
 0.12136204]
0.2996391322085721
threshold 0.2996391322085721


ic| label_current_deforestation_test_classified_incorrect.shape: (3664786,)
    predicted_test_classified_incorrect.shape: (3664786,)
ic| TP_H + FN_H + FP_H + TN_H: 3664786
    len(label_mask_current_deforestation_test): 122569923
ic| TP_H + FN_H + FP_H + TN_H: 3664786
    len(label_mask_current_deforestation_test): 122569923


[0.44683883 0.65513596 0.5763104  0.02989955 0.10034095 0.35734757
 0.12139052]
0.2984516853192931
threshold 0.2984516853192931


ic| label_current_deforestation_test_classified_incorrect.shape: (3680536,)
    predicted_test_classified_incorrect.shape: (3680536,)
ic| TP_H + FN_H + FP_H + TN_H: 3680536
    len(label_mask_current_deforestation_test): 122569923
ic| TP_H + FN_H + FP_H + TN_H: 3680536
    len(label_mask_current_deforestation_test): 122569923


[0.44740647 0.65522136 0.57608611 0.03002805 0.10036371 0.35785258
 0.12163851]
0.29749720085761316
threshold 0.29749720085761316


ic| label_current_deforestation_test_classified_incorrect.shape: (3693312,)
    predicted_test_classified_incorrect.shape: (3693312,)
ic| TP_H + FN_H + FP_H + TN_H: 3693312
    len(label_mask_current_deforestation_test): 122569923
ic| TP_H + FN_H + FP_H + TN_H: 3693312
    len(label_mask_current_deforestation_test): 122569923


[0.44785355 0.65527563 0.57587936 0.03013229 0.10043634 0.35841204
 0.12183318]
0.2981403123342725
threshold 0.2981403123342725


ic| label_current_deforestation_test_classified_incorrect.shape: (3684635,)
    predicted_test_classified_incorrect.shape: (3684635,)
ic| TP_H + FN_H + FP_H + TN_H: 3684635
    len(label_mask_current_deforestation_test): 122569923
ic| TP_H + FN_H + FP_H + TN_H: 3684635
    len(label_mask_current_deforestation_test): 122569923


[0.44755204 0.65524385 0.5760144  0.03006149 0.10039524 0.35803248
 0.12170774]
0.2987740466383068
threshold 0.2987740466383068


ic| label_current_deforestation_test_classified_incorrect.shape: (3676239,)
    predicted_test_classified_incorrect.shape: (3676239,)
ic| TP_H + FN_H + FP_H + TN_H: 3676239
    len(label_mask_current_deforestation_test): 122569923
ic| TP_H + FN_H + FP_H + TN_H: 3676239
    len(label_mask_current_deforestation_test): 122569923


[0.44724602 0.65519342 0.57613951 0.02999299 0.1003752  0.35776295
 0.12156861]
0.29910447992297107
threshold 0.29910447992297107


ic| label_current_deforestation_test_classified_incorrect.shape: (3671900,)
    predicted_test_classified_incorrect.shape: (3671900,)
ic| TP_H + FN_H + FP_H + TN_H: 3671900
    len(label_mask_current_deforestation_test): 122569923
ic| TP_H + FN_H + FP_H + TN_H: 3671900
    len(label_mask_current_deforestation_test): 122569923


[0.44709296 0.65517415 0.57620055 0.02995759 0.10036806 0.35760986
 0.12150525]
0.298736457252559
threshold 0.298736457252559


ic| label_current_deforestation_test_classified_incorrect.shape: (3676757,)
    predicted_test_classified_incorrect.shape: (3676757,)
ic| TP_H + FN_H + FP_H + TN_H: 3676757
    len(label_mask_current_deforestation_test): 122569923
ic| TP_H + FN_H + FP_H + TN_H: 3676757
    len(label_mask_current_deforestation_test): 122569923


[0.44726577 0.65520128 0.57613494 0.02999722 0.10037017 0.35774887
 0.12157821]
0.2986651738827542
threshold 0.2986651738827542


ic| label_current_deforestation_test_classified_incorrect.shape: (3677714,)
    predicted_test_classified_incorrect.shape: (3677714,)
ic| TP_H + FN_H + FP_H + TN_H: 3677714
    len(label_mask_current_deforestation_test): 122569923
ic| TP_H + FN_H + FP_H + TN_H: 3677714
    len(label_mask_current_deforestation_test): 122569923


[0.44730504 0.65520446 0.57612273 0.03000503 0.1003658  0.35778216
 0.12159574]
0.2987031194882479
threshold 0.2987031194882479


ic| label_current_deforestation_test_classified_incorrect.shape: (3677207,)
    predicted_test_classified_incorrect.shape: (3677207,)
ic| TP_H + FN_H + FP_H + TN_H: 3677207
    len(label_mask_current_deforestation_test): 122569923
ic| TP_H + FN_H + FP_H + TN_H: 3677207
    len(label_mask_current_deforestation_test): 122569923
ic| self.threshold_optimal: 0.2987031194882479


[0.44728461 0.65520344 0.57612883 0.03000089 0.10036852 0.35776325
 0.12158722]
threshold:  0.2987031194882479
threshold 0.2987031194882479


ic| label_current_deforestation_test_classified_incorrect.shape: (3677207,)
    predicted_test_classified_incorrect.shape: (3677207,)
ic| TP_H + FN_H + FP_H + TN_H: 3677207
    len(label_mask_current_deforestation_test): 122569923
ic| TP_H + FN_H + FP_H + TN_H: 3677207
    len(label_mask_current_deforestation_test): 122569923


[0.44728461 0.65520344 0.57612883 0.03000089 0.10036852 0.35776325
 0.12158722]
threshold 0.2987031194882479
(122569923,) (122569923,)


ic| self.m_optimal: {'AA': array([0.03000089]),
                     'UEO': array([0.12158722]),
                     'f1': 45.57,
                     'f1_H': array([0.15675912]),
                     'f1_L': array([0.53163826]),
                     'precision_H': array([0.10036852]),
                     'precision_L': array([0.44728461]),
                     'recall_H': array([0.35776325]),
                     'recall_L': array([0.65520344]),
                     'recall_Ltotal': array([0.57612883])}
ic| self.m_audited_optimal: {'f1': array([0.57857158]),
                             'precision': array([0.49463568]),
                             'recall': array([0.69681594])}


cm_audited [[120325963    933182]
 [   397407    913371]]
[0.49463568 0.69681594]
Result idx 1: {'uncertainty_result': {'metrics': {'precision_L': array([0.44728461]), 'recall_L': array([0.65520344]), 'recall_Ltotal': array([0.57612883]), 'AA': array([0.03000089]), 'precision_H': array([0.10036852]), 'recall_H': array([0.35776325]), 'UEO': array([0.12158722]), 'f1_L': array([0.53163826]), 'f1_H': array([0.15675912]), 'f1': 45.57}, 'metrics_audited': {'precision': array([0.49463568]), 'recall': array([0.69681594]), 'f1': array([0.57857158])}, 'exp': 15}}
Grid execution idx: 1
Beginning run number 2
manager.config {'training': False, 'inferring': True, 'site': 'PI', 'training_date': 'earlier', 'mode': 'evidential2', 'training_times': 10, 'uncertainty_method': 'pred_entropy', 'loadInference': False, 'removePolygons': True, 'plotLandsat': False, 'plotPOI': False, 'training_experiment_id': 15, 'get_multiple_metrics': False, 'save_probabilities': False, 'addPastDeforestationInput': True, 'cl

ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([340580606,   4312043,   6953620,   5659916,   7162776,   6261432,
                                                                      8191420,   3233962,   3270293,   3044419,   1817289,   2359424,
                                                                      2201926,   3050229,   2901307,   2418575], dtype=int64))


Label where deforestation past years is actual date (2020) = 1


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([340580606,   4312043,   6953620,   5659916,   7162776,   6261432,
                                                                      8191420,   3233962,   3270293,   3044419,   1817289,   2359424,
                                                                      2201926,   3050229,   2901307,   2418575], dtype=int64))


Past deforestation different from 0 (no deforestation)


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([340580606,   4312043,   6953620,   5659916,   7162776,   6261432,
                                                                      8191420,   3233962,   3270293,   3044419,   1817289,   2359424,
                                                                      2201926,   3050229,   2901307,   2418575], dtype=int64))


Past deforestation before 2008 is 2
D:/Jorge/datasets/deforestation/PI/deforestation_before_2000_PI.tif


ic| np.unique(label_past_deforestation_before_2008, return_counts=True): (array([  0, 208], dtype=uint8), array([385251297,  18167940], dtype=int64))
ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([340580606,   4312043,   6953620,   5659916,   7162776,   6261432,
                                                                      8191420,   3233962,   3270293,   3044419,   1817289,   2359424,
                                                                      2201926,   3050229,   2901307,   2418575], dtype=int64))
ic| label_per_date.shape: (19357, 20841, 1)


Removing bufer................
Mask label shape:  
 (19357, 20841, 1) 
 Unique values:  
 [0 1 2]
Tiles size:  3871 4168
Mask size:  (19355, 20840)


ic| image_stack.shape: (19357, 20841, 9)


Image shape:  (19357, 20841, 9)
mask:  (19355, 20840)
image stack:  (19355, 20840, 9)
ref : (19355, 20840, 1)
Training tiles:  [2, 4, 5, 6, 7, 12, 14, 15, 18, 21, 23, 25]
Validation tiles:  [9, 11, 24]
Test tiles:  [1, 3, 8, 10, 13, 16, 17, 19, 20, 22]
-5.0 -24.0


ic| self.path_models+ '/' + self.method +'_'+str(self.repetition_id)+'.h5': 'D:/Jorge/datasets/deforestation/experiments/PI/exp15/models/resunet_2.h5'


Dropout training mode: False
time:  0
alpha.shape (19360, 20864, 2)
S.shape (19360, 20864)
K 2
u.shape (19360, 20864)
belief.shape (19360, 20864, 2)
(122722628,)
(array([0, 1], dtype=uint8), array([121393418,   1329210], dtype=int64))
(19355, 20840, 2)


ic| predicted_test.shape: (161343280,)
ic| predicted_test.shape: (122722628,)
ic| np.unique(predicted, return_counts=True): (array([0, 1], dtype=int8), array([398723128,   4635072], dtype=int64))
    np.unique(predicted_larger_than_min_area, return_counts=True): (array([0, 1], dtype=int8), array([399103366,   4254834], dtype=int64))
ic| np.unique(ignored_polygons, return_counts=True): (array([0, 1], dtype=int8), array([402977962,    380238], dtype=int64))
ic| self.f1: 55.94, self.precision: 53.7, self.recall: 58.38
ic| self.label_mask_val.shape: (48402984,)
ic| self.label_mask_val_valid.shape: (42334440,)
ic| f1_val: 28.62
    precision_val: 19.59
    recall_val: 53.05
    mAP_val: 24.86


(array([0, 1], dtype=int16), array([399713056,   3645144], dtype=int64))
[0 1]


ic| self.label_mask.shape: (19355, 20840)
ic| self.mask_amazon_ts.shape: (19355, 20840)
ic| self.label_mask_test.shape: (161343280,)
ic| self.error_mask_test.shape: (122594254,)
ic| bounds: (0.0015907875000848435, 0.4985)
c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\scipy\optimize\_minimize.py:783: RuntimeWarning: Method 'bounded' does not support relative tolerance in x; defaulting to absolute tolerance.
  warn("Method 'bounded' does not support relative tolerance in x; "


0.1913932173521083
threshold 0.1913932173521083


ic| label_current_deforestation_test_classified_incorrect.shape: (5488271,)
    predicted_test_classified_incorrect.shape: (5488271,)
ic| TP_H + FN_H + FP_H + TN_H: 5488271
    len(label_mask_current_deforestation_test): 122594254
ic| TP_H + FN_H + FP_H + TN_H: 5488271
    len(label_mask_current_deforestation_test): 122594254


[0.71244937 0.63510703 0.51146053 0.04476777 0.19581973 0.37136525
 0.08951466]
0.3086975701479765
threshold 0.3086975701479765


ic| label_current_deforestation_test_classified_incorrect.shape: (3527758,)
    predicted_test_classified_incorrect.shape: (3527758,)
ic| TP_H + FN_H + FP_H + TN_H: 3527758
    len(label_mask_current_deforestation_test): 122594254
ic| TP_H + FN_H + FP_H + TN_H: 3527758
    len(label_mask_current_deforestation_test): 122594254


[0.63942293 0.62944827 0.54347851 0.02877588 0.16985438 0.2949319
 0.08841775]
0.3811956472041318
threshold 0.3811956472041318


ic| label_current_deforestation_test_classified_incorrect.shape: (2771679,)
    predicted_test_classified_incorrect.shape: (2771679,)
ic| TP_H + FN_H + FP_H + TN_H: 2771679
    len(label_mask_current_deforestation_test): 122594254
ic| TP_H + FN_H + FP_H + TN_H: 2771679
    len(label_mask_current_deforestation_test): 122594254


[0.60060402 0.62862978 0.5589653  0.02260856 0.15850081 0.22374096
 0.0773265 ]
0.30468684719351974
threshold 0.30468684719351974


ic| label_current_deforestation_test_classified_incorrect.shape: (3576335,)
    predicted_test_classified_incorrect.shape: (3576335,)
ic| TP_H + FN_H + FP_H + TN_H: 3576335
    len(label_mask_current_deforestation_test): 122594254
ic| TP_H + FN_H + FP_H + TN_H: 3576335
    len(label_mask_current_deforestation_test): 122594254


[0.64179209 0.62957698 0.54259039 0.02917213 0.17035149 0.29797177
 0.08884814]
0.26141253130294995
threshold 0.26141253130294995


ic| label_current_deforestation_test_classified_incorrect.shape: (4178584,)
    predicted_test_classified_incorrect.shape: (4178584,)
ic| TP_H + FN_H + FP_H + TN_H: 4178584
    len(label_mask_current_deforestation_test): 122594254
ic| TP_H + FN_H + FP_H + TN_H: 4178584
    len(label_mask_current_deforestation_test): 122594254


[0.66883395 0.63134622 0.53192154 0.03408466 0.17764588 0.32917508
 0.09193165]
0.2932724254652065
threshold 0.2932724254652065


ic| label_current_deforestation_test_classified_incorrect.shape: (3722137,)
    predicted_test_classified_incorrect.shape: (3722137,)
ic| TP_H + FN_H + FP_H + TN_H: 3722137
    len(label_mask_current_deforestation_test): 122594254
ic| TP_H + FN_H + FP_H + TN_H: 3722137
    len(label_mask_current_deforestation_test): 122594254


[0.64875893 0.62986401 0.53985209 0.03036143 0.17220533 0.30724955
 0.0899517 ]
0.29353923862229353
threshold 0.29353923862229353


ic| label_current_deforestation_test_classified_incorrect.shape: (3718586,)
    predicted_test_classified_incorrect.shape: (3718586,)
ic| TP_H + FN_H + FP_H + TN_H: 3718586
    len(label_mask_current_deforestation_test): 122594254
ic| TP_H + FN_H + FP_H + TN_H: 3718586
    len(label_mask_current_deforestation_test): 122594254


[0.64860895 0.62985143 0.53991765 0.03033247 0.17214636 0.30705122
 0.08993266]
0.2974553291202235
threshold 0.2974553291202235


ic| label_current_deforestation_test_classified_incorrect.shape: (3667448,)
    predicted_test_classified_incorrect.shape: (3667448,)
ic| TP_H + FN_H + FP_H + TN_H: 3667448
    len(label_mask_current_deforestation_test): 122594254
ic| TP_H + FN_H + FP_H + TN_H: 3667448
    len(label_mask_current_deforestation_test): 122594254


[0.64613733 0.62975038 0.54085456 0.02991533 0.17158989 0.30394937
 0.08955901]
0.3002175232339635
threshold 0.3002175232339635


ic| label_current_deforestation_test_classified_incorrect.shape: (3632282,)
    predicted_test_classified_incorrect.shape: (3632282,)
ic| TP_H + FN_H + FP_H + TN_H: 3632282
    len(label_mask_current_deforestation_test): 122594254
ic| TP_H + FN_H + FP_H + TN_H: 3632282
    len(label_mask_current_deforestation_test): 122594254


[0.64446878 0.62968594 0.54151398 0.02962848 0.17113626 0.30170405
 0.0893006 ]
0.2984197762894348
threshold 0.2984197762894348


ic| label_current_deforestation_test_classified_incorrect.shape: (3654869,)
    predicted_test_classified_incorrect.shape: (3654869,)
ic| TP_H + FN_H + FP_H + TN_H: 3654869
    len(label_mask_current_deforestation_test): 122594254
ic| TP_H + FN_H + FP_H + TN_H: 3654869
    len(label_mask_current_deforestation_test): 122594254


[0.64556765 0.62972167 0.54108097 0.02981273 0.17143128 0.3032018
 0.08947988]
0.2964073837222931
threshold 0.2964073837222931


ic| label_current_deforestation_test_classified_incorrect.shape: (3680973,)
    predicted_test_classified_incorrect.shape: (3680973,)
ic| TP_H + FN_H + FP_H + TN_H: 3680973
    len(label_mask_current_deforestation_test): 122594254
ic| TP_H + FN_H + FP_H + TN_H: 3680973
    len(label_mask_current_deforestation_test): 122594254


[0.64681186 0.62977945 0.54061595 0.03002566 0.17169146 0.30473621
 0.08966596]
0.29531184977875974
threshold 0.29531184977875974


ic| label_current_deforestation_test_classified_incorrect.shape: (3695223,)
    predicted_test_classified_incorrect.shape: (3695223,)
ic| TP_H + FN_H + FP_H + TN_H: 3695223
    len(label_mask_current_deforestation_test): 122594254
ic| TP_H + FN_H + FP_H + TN_H: 3695223
    len(label_mask_current_deforestation_test): 122594254


[0.64751248 0.62981575 0.54039792 0.03014189 0.17171104 0.30542266
 0.08976345]
0.29655977083565027
threshold 0.29655977083565027


ic| label_current_deforestation_test_classified_incorrect.shape: (3679024,)
    predicted_test_classified_incorrect.shape: (3679024,)
ic| TP_H + FN_H + FP_H + TN_H: 3679024
    len(label_mask_current_deforestation_test): 122594254
ic| TP_H + FN_H + FP_H + TN_H: 3679024
    len(label_mask_current_deforestation_test): 122594254


[0.64668754 0.6297726  0.54064416 0.03000976 0.17171883 0.30465346
 0.08964053]
0.2967743906327615
threshold 0.2967743906327615


ic| label_current_deforestation_test_classified_incorrect.shape: (3676200,)
    predicted_test_classified_incorrect.shape: (3676200,)
ic| TP_H + FN_H + FP_H + TN_H: 3676200
    len(label_mask_current_deforestation_test): 122594254
ic| TP_H + FN_H + FP_H + TN_H: 3676200
    len(label_mask_current_deforestation_test): 122594254


[0.64654909 0.62976476 0.54069599 0.02998672 0.1716896  0.30448727
 0.08961775]
0.29664174830348816
threshold 0.29664174830348816


ic| label_current_deforestation_test_classified_incorrect.shape: (3677952,)
    predicted_test_classified_incorrect.shape: (3677952,)
ic| TP_H + FN_H + FP_H + TN_H: 3677952
    len(label_mask_current_deforestation_test): 122594254
ic| TP_H + FN_H + FP_H + TN_H: 3677952
    len(label_mask_current_deforestation_test): 122594254


[0.64663261 0.62976983 0.54066626 0.03000101 0.17170272 0.30458092
 0.08963013]
0.29667508603672965
threshold 0.29667508603672965


ic| label_current_deforestation_test_classified_incorrect.shape: (3677507,)
    predicted_test_classified_incorrect.shape: (3677507,)
ic| TP_H + FN_H + FP_H + TN_H: 3677507
    len(label_mask_current_deforestation_test): 122594254
ic| TP_H + FN_H + FP_H + TN_H: 3677507
    len(label_mask_current_deforestation_test): 122594254


[0.64661172 0.62976986 0.54067541 0.02999738 0.17169443 0.30454744
 0.08962711]
0.29660841057024667
threshold 0.29660841057024667


ic| label_current_deforestation_test_classified_incorrect.shape: (3678391,)
    predicted_test_classified_incorrect.shape: (3678391,)
ic| TP_H + FN_H + FP_H + TN_H: 3678391
    len(label_mask_current_deforestation_test): 122594254
ic| TP_H + FN_H + FP_H + TN_H: 3678391
    len(label_mask_current_deforestation_test): 122594254
ic| self.threshold_optimal: 0.29664174830348816


[0.64665254 0.62977329 0.54065483 0.0300046  0.17171855 0.3046125
 0.08963521]
threshold:  0.29664174830348816
threshold 0.29664174830348816


ic| label_current_deforestation_test_classified_incorrect.shape: (3677952,)
    predicted_test_classified_incorrect.shape: (3677952,)
ic| TP_H + FN_H + FP_H + TN_H: 3677952
    len(label_mask_current_deforestation_test): 122594254
ic| TP_H + FN_H + FP_H + TN_H: 3677952
    len(label_mask_current_deforestation_test): 122594254


[0.64663261 0.62976983 0.54066626 0.03000101 0.17170272 0.30458092
 0.08963013]
threshold 0.29664174830348816
(122594254,) (122594254,)


ic| self.m_optimal: {'AA': array([0.03000101]),
                     'UEO': array([0.08963013]),
                     'f1': 55.94,
                     'f1_H': array([0.219606]),
                     'f1_L': array([0.63808983]),
                     'precision_H': array([0.17170272]),
                     'precision_L': array([0.64663261]),
                     'recall_H': array([0.30458092]),
                     'recall_L': array([0.62976983]),
                     'recall_Ltotal': array([0.54066626])}
ic| self.m_audited_optimal: {'f1': array([0.68987471]),
                             'precision': array([0.69777409]),
                             'recall': array([0.68215219])}


cm_audited [[120894918    387573]
 [   416941    894822]]
[0.69777409 0.68215219]
Result idx 2: {'uncertainty_result': {'metrics': {'precision_L': array([0.64663261]), 'recall_L': array([0.62976983]), 'recall_Ltotal': array([0.54066626]), 'AA': array([0.03000101]), 'precision_H': array([0.17170272]), 'recall_H': array([0.30458092]), 'UEO': array([0.08963013]), 'f1_L': array([0.63808983]), 'f1_H': array([0.219606]), 'f1': 55.94}, 'metrics_audited': {'precision': array([0.69777409]), 'recall': array([0.68215219]), 'f1': array([0.68987471])}, 'exp': 15}}
Grid execution idx: 2
Beginning run number 3
manager.config {'training': False, 'inferring': True, 'site': 'PI', 'training_date': 'earlier', 'mode': 'evidential2', 'training_times': 10, 'uncertainty_method': 'pred_entropy', 'loadInference': False, 'removePolygons': True, 'plotLandsat': False, 'plotPOI': False, 'training_experiment_id': 15, 'get_multiple_metrics': False, 'save_probabilities': False, 'addPastDeforestationInput': True, 'clas

ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([340580606,   4312043,   6953620,   5659916,   7162776,   6261432,
                                                                      8191420,   3233962,   3270293,   3044419,   1817289,   2359424,
                                                                      2201926,   3050229,   2901307,   2418575], dtype=int64))


Label where deforestation past years is actual date (2020) = 1


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([340580606,   4312043,   6953620,   5659916,   7162776,   6261432,
                                                                      8191420,   3233962,   3270293,   3044419,   1817289,   2359424,
                                                                      2201926,   3050229,   2901307,   2418575], dtype=int64))


Past deforestation different from 0 (no deforestation)


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([340580606,   4312043,   6953620,   5659916,   7162776,   6261432,
                                                                      8191420,   3233962,   3270293,   3044419,   1817289,   2359424,
                                                                      2201926,   3050229,   2901307,   2418575], dtype=int64))


Past deforestation before 2008 is 2
D:/Jorge/datasets/deforestation/PI/deforestation_before_2000_PI.tif


ic| np.unique(label_past_deforestation_before_2008, return_counts=True): (array([  0, 208], dtype=uint8), array([385251297,  18167940], dtype=int64))
ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([340580606,   4312043,   6953620,   5659916,   7162776,   6261432,
                                                                      8191420,   3233962,   3270293,   3044419,   1817289,   2359424,
                                                                      2201926,   3050229,   2901307,   2418575], dtype=int64))
ic| label_per_date.shape: (19357, 20841, 1)


Removing bufer................
Mask label shape:  
 (19357, 20841, 1) 
 Unique values:  
 [0 1 2]
Tiles size:  3871 4168
Mask size:  (19355, 20840)


ic| image_stack.shape: (19357, 20841, 9)


Image shape:  (19357, 20841, 9)
mask:  (19355, 20840)
image stack:  (19355, 20840, 9)
ref : (19355, 20840, 1)
Training tiles:  [2, 4, 5, 6, 7, 12, 14, 15, 18, 21, 23, 25]
Validation tiles:  [9, 11, 24]
Test tiles:  [1, 3, 8, 10, 13, 16, 17, 19, 20, 22]
-5.0 -24.0


ic| self.path_models+ '/' + self.method +'_'+str(self.repetition_id)+'.h5': 'D:/Jorge/datasets/deforestation/experiments/PI/exp15/models/resunet_3.h5'


Dropout training mode: False
time:  0
alpha.shape (19360, 20864, 2)
S.shape (19360, 20864)
K 2
u.shape (19360, 20864)
belief.shape (19360, 20864, 2)
(122722628,)
(array([0, 1], dtype=uint8), array([121393418,   1329210], dtype=int64))
(19355, 20840, 2)


ic| predicted_test.shape: (161343280,)
ic| predicted_test.shape: (122722628,)
ic| np.unique(predicted, return_counts=True): (array([0, 1], dtype=int8), array([398066040,   5292160], dtype=int64))
    np.unique(predicted_larger_than_min_area, return_counts=True): (array([0, 1], dtype=int8), array([398595483,   4762717], dtype=int64))
ic| np.unique(ignored_polygons, return_counts=True): (array([0, 1], dtype=int8), array([402828757,    529443], dtype=int64))
ic| self.f1: 54.34, self.precision: 47.84, self.recall: 62.88
ic| self.label_mask_val.shape: (48402984,)
ic| self.label_mask_val_valid.shape: (42319419,)
ic| f1_val: 25.12
    precision_val: 16.7
    recall_val: 50.72
    mAP_val: 30.08


(array([0, 1], dtype=int16), array([399189963,   4168237], dtype=int64))
[0 1]


ic| self.label_mask.shape: (19355, 20840)
ic| self.mask_amazon_ts.shape: (19355, 20840)
ic| self.label_mask_test.shape: (161343280,)
ic| self.error_mask_test.shape: (122544147,)
ic| bounds: (0.0015907875000848435, 0.4985)
c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\scipy\optimize\_minimize.py:783: RuntimeWarning: Method 'bounded' does not support relative tolerance in x; defaulting to absolute tolerance.
  warn("Method 'bounded' does not support relative tolerance in x; "


0.1913932173521083
threshold 0.1913932173521083


ic| label_current_deforestation_test_classified_incorrect.shape: (11694687,)
    predicted_test_classified_incorrect.shape: (11694687,)
ic| TP_H + FN_H + FP_H + TN_H: 11694687
    len(label_mask_current_deforestation_test): 122544147
ic| TP_H + FN_H + FP_H + TN_H: 11694687
    len(label_mask_current_deforestation_test): 122544147


[0.86608236 0.70975355 0.42333049 0.09543244 0.24890522 0.50915347
 0.089301  ]
0.3086975701479765
threshold 0.3086975701479765


ic| label_current_deforestation_test_classified_incorrect.shape: (7390922,)
    predicted_test_classified_incorrect.shape: (7390922,)
ic| TP_H + FN_H + FP_H + TN_H: 7390922
    len(label_mask_current_deforestation_test): 122544147
ic| TP_H + FN_H + FP_H + TN_H: 7390922
    len(label_mask_current_deforestation_test): 122544147


[0.7282925  0.71959579 0.52299471 0.06031232 0.17747544 0.38726965
 0.10893958]
0.3811956472041318
threshold 0.3811956472041318


ic| label_current_deforestation_test_classified_incorrect.shape: (5497771,)
    predicted_test_classified_incorrect.shape: (5497771,)
ic| TP_H + FN_H + FP_H + TN_H: 5497771
    len(label_mask_current_deforestation_test): 122544147
ic| TP_H + FN_H + FP_H + TN_H: 5497771
    len(label_mask_current_deforestation_test): 122544147


[0.63367701 0.7147772  0.56336182 0.0448636  0.15388438 0.30891384
 0.10667965]
0.4260019229438447
threshold 0.4260019229438447


ic| label_current_deforestation_test_classified_incorrect.shape: (4565053,)
    predicted_test_classified_incorrect.shape: (4565053,)
ic| TP_H + FN_H + FP_H + TN_H: 4565053
    len(label_mask_current_deforestation_test): 122544147
ic| TP_H + FN_H + FP_H + TN_H: 4565053
    len(label_mask_current_deforestation_test): 122544147


[0.57621121 0.71305729 0.58491414 0.03725231 0.14668972 0.24420905
 0.09427775]
0.4536937242602871
threshold 0.4536937242602871


ic| label_current_deforestation_test_classified_incorrect.shape: (4008643,)
    predicted_test_classified_incorrect.shape: (4008643,)
ic| TP_H + FN_H + FP_H + TN_H: 4008643
    len(label_mask_current_deforestation_test): 122544147
ic| TP_H + FN_H + FP_H + TN_H: 4008643
    len(label_mask_current_deforestation_test): 122544147


[0.54017255 0.71270973 0.59923429 0.03271183 0.14426542 0.1856997
 0.08005766]
0.4708081986835576
threshold 0.4708081986835576


ic| label_current_deforestation_test_classified_incorrect.shape: (3643881,)
    predicted_test_classified_incorrect.shape: (3643881,)
ic| TP_H + FN_H + FP_H + TN_H: 3643881
    len(label_mask_current_deforestation_test): 122544147
ic| TP_H + FN_H + FP_H + TN_H: 3643881
    len(label_mask_current_deforestation_test): 122544147


[0.51791954 0.71238606 0.60906742 0.02973525 0.14269006 0.13606258
 0.06787128]
0.48138552557672953
threshold 0.48138552557672953


ic| label_current_deforestation_test_classified_incorrect.shape: (3400718,)
    predicted_test_classified_incorrect.shape: (3400718,)
ic| TP_H + FN_H + FP_H + TN_H: 3400718
    len(label_mask_current_deforestation_test): 122544147
ic| TP_H + FN_H + FP_H + TN_H: 3400718
    len(label_mask_current_deforestation_test): 122544147


[0.50371535 0.7120927  0.6157823  0.02775096 0.14180878 0.09625539
 0.05826039]
0.46823958850231867
threshold 0.46823958850231867


ic| label_current_deforestation_test_classified_incorrect.shape: (3700552,)
    predicted_test_classified_incorrect.shape: (3700552,)
ic| TP_H + FN_H + FP_H + TN_H: 3700552
    len(label_mask_current_deforestation_test): 122544147
ic| TP_H + FN_H + FP_H + TN_H: 3700552
    len(label_mask_current_deforestation_test): 122544147


[0.52130758 0.71243442 0.60748731 0.0301977  0.14307298 0.14468696
 0.06994479]
0.46846157005380895
threshold 0.46846157005380895


ic| label_current_deforestation_test_classified_incorrect.shape: (3695694,)
    predicted_test_classified_incorrect.shape: (3695694,)
ic| TP_H + FN_H + FP_H + TN_H: 3695694
    len(label_mask_current_deforestation_test): 122544147
ic| TP_H + FN_H + FP_H + TN_H: 3695694
    len(label_mask_current_deforestation_test): 122544147


[0.52101871 0.71243253 0.60761778 0.03015806 0.1430581  0.14398249
 0.06977393]
0.46937427577840696
threshold 0.46937427577840696


ic| label_current_deforestation_test_classified_incorrect.shape: (3675575,)
    predicted_test_classified_incorrect.shape: (3675575,)
ic| TP_H + FN_H + FP_H + TN_H: 3675575
    len(label_mask_current_deforestation_test): 122544147
ic| TP_H + FN_H + FP_H + TN_H: 3675575
    len(label_mask_current_deforestation_test): 122544147


[0.5197759  0.71240459 0.60818695 0.02999388 0.14296373 0.14091103
 0.06901083]
0.4699219855909275
threshold 0.4699219855909275


ic| label_current_deforestation_test_classified_incorrect.shape: (3663347,)
    predicted_test_classified_incorrect.shape: (3663347,)
ic| TP_H + FN_H + FP_H + TN_H: 3663347
    len(label_mask_current_deforestation_test): 122544147
ic| TP_H + FN_H + FP_H + TN_H: 3663347
    len(label_mask_current_deforestation_test): 122544147


[0.51903091 0.71238526 0.60852266 0.0298941  0.14294166 0.13908629
 0.06855204]
0.4692665808120346
threshold 0.4692665808120346


ic| label_current_deforestation_test_classified_incorrect.shape: (3677972,)
    predicted_test_classified_incorrect.shape: (3677972,)
ic| TP_H + FN_H + FP_H + TN_H: 3677972
    len(label_mask_current_deforestation_test): 122544147
ic| TP_H + FN_H + FP_H + TN_H: 3677972
    len(label_mask_current_deforestation_test): 122544147


[0.5199122  0.71240625 0.60810684 0.03001344 0.1430621  0.14134808
 0.0690987 ]
0.4694095522204295
threshold 0.4694095522204295


ic| label_current_deforestation_test_classified_incorrect.shape: (3674833,)
    predicted_test_classified_incorrect.shape: (3674833,)
ic| TP_H + FN_H + FP_H + TN_H: 3674833
    len(label_mask_current_deforestation_test): 122544147
ic| TP_H + FN_H + FP_H + TN_H: 3674833
    len(label_mask_current_deforestation_test): 122544147


[0.51972484 0.71240196 0.60820374 0.02998783 0.14299335 0.140822
 0.06898009]
0.4693407249983777
threshold 0.4693407249983777


ic| label_current_deforestation_test_classified_incorrect.shape: (3676371,)
    predicted_test_classified_incorrect.shape: (3676371,)
ic| TP_H + FN_H + FP_H + TN_H: 3676371
    len(label_mask_current_deforestation_test): 122544147
ic| TP_H + FN_H + FP_H + TN_H: 3676371
    len(label_mask_current_deforestation_test): 122544147


[0.519821   0.71240449 0.60815643 0.03000038 0.14301646 0.14107845
 0.06904123]
0.4693073847035964
threshold 0.4693073847035964


ic| label_current_deforestation_test_classified_incorrect.shape: (3677122,)
    predicted_test_classified_incorrect.shape: (3677122,)
ic| TP_H + FN_H + FP_H + TN_H: 3677122
    len(label_mask_current_deforestation_test): 122544147
ic| TP_H + FN_H + FP_H + TN_H: 3677122
    len(label_mask_current_deforestation_test): 122544147
ic| self.threshold_optimal: 0.4693407249983777


[0.51986082 0.71240327 0.60813202 0.03000651 0.14305026 0.14121363
 0.06906595]
threshold:  0.4693407249983777
threshold 0.4693407249983777


ic| label_current_deforestation_test_classified_incorrect.shape: (3676371,)
    predicted_test_classified_incorrect.shape: (3676371,)
ic| TP_H + FN_H + FP_H + TN_H: 3676371
    len(label_mask_current_deforestation_test): 122544147
ic| TP_H + FN_H + FP_H + TN_H: 3676371
    len(label_mask_current_deforestation_test): 122544147


[0.519821   0.71240449 0.60815643 0.03000038 0.14301646 0.14107845
 0.06904123]
threshold 0.4693407249983777
(122544147,) (122544147,)


ic| self.m_optimal: {'AA': array([0.03000038]),
                     'UEO': array([0.06904123]),
                     'f1': 54.34,
                     'f1_H': array([0.14204085]),
                     'f1_L': array([0.60106339]),
                     'precision_H': array([0.14301646]),
                     'precision_L': array([0.519821]),
                     'recall_H': array([0.14107845]),
                     'recall_L': array([0.71240449]),
                     'recall_Ltotal': array([0.60815643])}
ic| self.m_audited_optimal: {'f1': array([0.65146989]),
                             'precision': array([0.57320369]),
                             'recall': array([0.75448911])}


cm_audited [[120497170    736306]
 [   321784    988887]]
[0.57320369 0.75448911]
Result idx 3: {'uncertainty_result': {'metrics': {'precision_L': array([0.519821]), 'recall_L': array([0.71240449]), 'recall_Ltotal': array([0.60815643]), 'AA': array([0.03000038]), 'precision_H': array([0.14301646]), 'recall_H': array([0.14107845]), 'UEO': array([0.06904123]), 'f1_L': array([0.60106339]), 'f1_H': array([0.14204085]), 'f1': 54.34}, 'metrics_audited': {'precision': array([0.57320369]), 'recall': array([0.75448911]), 'f1': array([0.65146989])}, 'exp': 15}}
Grid execution idx: 3


In [14]:
error_count

0

In [15]:
print(results)

[{'uncertainty_result': {'metrics': {'precision_L': array([0.53195804]), 'recall_L': array([0.69958021]), 'recall_Ltotal': array([0.61956172]), 'AA': array([0.0299989]), 'precision_H': array([0.10644846]), 'recall_H': array([0.26529932]), 'UEO': array([0.09367737]), 'f1_L': array([0.60436177]), 'f1_H': array([0.15193476]), 'f1': 53.06}, 'metrics_audited': {'precision': array([0.57381291]), 'recall': array([0.73394245]), 'f1': array([0.64407406])}, 'exp': 15}}, {'uncertainty_result': {'metrics': {'precision_L': array([0.44728461]), 'recall_L': array([0.65520344]), 'recall_Ltotal': array([0.57612883]), 'AA': array([0.03000089]), 'precision_H': array([0.10036852]), 'recall_H': array([0.35776325]), 'UEO': array([0.12158722]), 'f1_L': array([0.53163826]), 'f1_H': array([0.15675912]), 'f1': 45.57}, 'metrics_audited': {'precision': array([0.49463568]), 'recall': array([0.69681594]), 'f1': array([0.57857158])}, 'exp': 15}}, {'uncertainty_result': {'metrics': {'precision_L': array([0.64663261])

In [16]:
print(len(results))

4


In [17]:
results[0]

{'uncertainty_result': {'metrics': {'precision_L': array([0.53195804]),
   'recall_L': array([0.69958021]),
   'recall_Ltotal': array([0.61956172]),
   'AA': array([0.0299989]),
   'precision_H': array([0.10644846]),
   'recall_H': array([0.26529932]),
   'UEO': array([0.09367737]),
   'f1_L': array([0.60436177]),
   'f1_H': array([0.15193476]),
   'f1': 53.06},
  'metrics_audited': {'precision': array([0.57381291]),
   'recall': array([0.73394245]),
   'f1': array([0.64407406])},
  'exp': 15}}

In [18]:
manager.f1

54.34

In [19]:
print(manager.f1)

54.34
