In [1]:
import tracemalloc

from utils_v1 import *
import traceback


In [2]:
from icecream import ic

import numpy as np
from src.dataset import (
    MultipleDates, PAMultipleDates,
    MTMultipleDates, MSMultipleDates, PIMultipleDates
)

# from src.dataset_legacy import MTDeforestationTime
from src import training_generator as generator
from src.patchesHandler import PatchesHandler, PatchesHandlerMultipleDates, PatchesHandlerEvidential2

from src.manager.evidential import ManagerEvidential
from src.manager.multioutput import ManagerMCDropout, ManagerSingleRun, ManagerEvidential2
from mpl_toolkits.axes_grid1 import make_axes_locatable

import cv2
from src import metrics as _metric
import json
import pickle 
import src.manager.evidential as evidential
from src.Logger import Logger
import pdb
import gc


Tensorflow ver. 2.6.0


In [3]:

with open('config/config.json', 'r') as f:
    config = json.load(f)
    
print("Mode: {}. Site: {}. Training: {}. Training date: {}".format(
    config['mode'], config['site'], config['training'], config['training_date']))
print(config)


Mode: evidential2. Site: MS. Training: False. Training date: earlier
{'training': False, 'inferring': True, 'site': 'MS', 'training_date': 'earlier', 'mode': 'evidential2', 'training_times': 10, 'uncertainty_method': 'pred_entropy', 'loadInference': False, 'removePolygons': True, 'plotLandsat': False, 'plotPOI': False, 'training_experiment_id': 39, 'get_multiple_metrics': False, 'start_repetition_id': 4, 'save_probabilities': False, 'addPastDeforestationInput': True, 'classes_mode': True, 'learning_rate': 0.0001, 'use_cloud_mask': False, 'mask_out_non_biome': False, 'log_filename': 'log.pkl'}


In [4]:

if config['site'] == 'PA':
	if config['training_date'] == 'earlier':
		dates = [2017, 2018]
	else:
		dates = [2018, 2019]
	datasetClass = PAMultipleDates
elif config['site'] == 'MT':
	if config['training_date'] == 'earlier':
		dates = [2018, 2019]
	else:
		dates = [2019, 2020]
	datasetClass = MTMultipleDates
elif config['site'] == 'MS':
	if config['training_date'] == 'earlier':
		dates = [2018, 2019]
	else:
		dates = [2019, 2020]
	datasetClass = MSMultipleDates
elif config['site'] == 'PI':
	if config['training_date'] == 'earlier':
		dates = [2018, 2019]
	else:
		dates = [2019, 2020]
	datasetClass = PIMultipleDates
else:
	raise ValueError('Invalid site')

dataset = datasetClass(config = config,
			   dates = dates, 
	 	addPastDeforestationInput = config['addPastDeforestationInput'],
		borderBuffer = 2)	

if config['mode'] == 'ensemble':
	if config['training'] == True:
		config['mode'] = 'single_run'
	else:
		sys.exit("Ensure that training is True for ensemble mode. Use infer_ensemble.ipynb for inference.")

if config['training'] == False:
	if config['site'] == 'PA':
		if config['mode'] == 'mcd' or config['mode'] == 'single_run': # MCD will do 10 inference on each of the 10 repetitions = 100 runs
			if config['training_date'] == 'current': exp = 0
			elif config['training_date'] == 'earlier': exp = 1
				
		if config['mode'] == 'evidential2':
			if config['training_date'] == 'current': exp = 8; repetition_id = 0
			elif config['training_date'] == 'earlier': exp = 9; repetition_id = 0

	elif config['site'] == 'MT':

		if config['mode'] == 'mcd' or config['mode'] == 'single_run':
			if config['training_date'] == 'current': exp = 2
			elif config['training_date'] == 'earlier': exp = 3
		if config['mode'] == 'evidential2':
			if config['training_date'] == 'current': exp = 10; repetition_id = 0
			elif config['training_date'] == 'earlier': exp = 11; repetition_id = 0

	elif config['site'] == 'MS':

		if config['mode'] == 'mcd' or config['mode'] == 'single_run':
			if config['training_date'] == 'current': exp = 4
			elif config['training_date'] == 'earlier': 
				exp = 37

		if config['mode'] == 'evidential2':
			if config['training_date'] == 'current': exp = 12; repetition_id = 0
			elif config['training_date'] == 'earlier': exp = 39; repetition_id = 0
	elif config['site'] == 'PI':

		if config['mode'] == 'mcd' or config['mode'] == 'single_run':
			if config['training_date'] == 'current': exp = 6
			elif config['training_date'] == 'earlier': exp = 27
		if config['mode'] == 'evidential2':
			if config['training_date'] == 'current': exp = 14; repetition_id = 0
			elif config['training_date'] == 'earlier': exp = 39; repetition_id = 0

else:
	exp = config['training_experiment_id']
ic(dates)


if issubclass(type(dataset), MultipleDates):
	patchesHandler = PatchesHandlerMultipleDates(
		dataset)
elif config['mode'] == 'evidential2':
	patchesHandler = PatchesHandlerEvidential2()
else:
	patchesHandler = PatchesHandler()



ic| list(self.date_ids): [0]
ic| self.image_channels: [[0, 1, 2, 3, 4, 5, 6, 7, 8]]
ic| dates: [2018, 2019]
ic| self.input_image_shape: 9
ic| self.dataset.image_channels: [[0, 1, 2, 3, 4, 5, 6, 7, 8]]


In [5]:


if config['mode'] == 'evidential2':
    config["inference_times"] = 1
    manager_class = ManagerEvidential2
    config['uncertainty_method'] = "pred_entropy"
    config['classes_mode'] = True
    
if config['mode'] == 'mcd':
    config["inference_times"] = 10
    manager_class = ManagerMCDropout
    config['uncertainty_method'] = "pred_entropy"
    config['classes_mode'] = False

elif config['mode'] == 'single_run':
    config["inference_times"] = 1
    manager_class = ManagerSingleRun
    config['uncertainty_method'] = "pred_entropy_single"
    config['classes_mode'] = False



In [6]:
exp

39

In [7]:
logger = Logger()


In [8]:
if config['training'] == True:
    

    manager = manager_class(config, dataset, patchesHandler, logger)
    print("manager.config['dropout_training']", manager.config['dropout_training'])
    manager.defineExperiment(exp) # fixed
    
    manager.setExperimentPath()
    manager.createLogFolders()

    manager.loadDataset()

    # %%
    if config["training"] == True:
        manager.run()


In [9]:



if config['site'] == 'PA':
	dates = [2018, 2019]
	datasetClass = PAMultipleDates
elif config['site'] == 'MT':
	dates = [2019, 2020]
	datasetClass = MTMultipleDates
elif config['site'] == 'MS':
	dates = [2019, 2020]
	datasetClass = MSMultipleDates
elif config['site'] == 'PI':
	dates = [2019, 2020]
	datasetClass = PIMultipleDates
else:
	raise ValueError('Invalid site')

dataset = datasetClass(config = config,
			   dates = dates, 
	 	addPastDeforestationInput = config['addPastDeforestationInput'],
		borderBuffer = 2)


ic(dates)

if issubclass(type(dataset), MultipleDates):
	patchesHandler = PatchesHandlerMultipleDates(
		dataset)
elif config['mode'] == 'evidential2':
	patchesHandler = PatchesHandlerEvidential2()
else:
	patchesHandler = PatchesHandler()


ic| list(self.date_ids): [0]
ic| self.image_channels: [[0, 1, 2, 3, 4, 5, 6, 7, 8]]
ic| dates: [2019, 2020]
ic| self.input_image_shape: 9
ic| self.dataset.image_channels: [[0, 1, 2, 3, 4, 5, 6, 7, 8]]


In [10]:
manager_class

src.manager.multioutput.ManagerEvidential2

In [11]:
exp

39

In [12]:
repetition_ids = manager_class(config, dataset, patchesHandler, logger).get_repetition_ids(exp)  
repetition_n = len(repetition_ids)
print("repetition_ids {}, repetition_n {}".format(repetition_ids, repetition_n))


repetition_ids [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], repetition_n 10


In [13]:
config['start_repetition_id']

4

In [14]:
if config['inferring'] == True:
    results = []
    error_count = 0

    # while idx < len(repetition_n):
    for idx in range(config['start_repetition_id'], repetition_n): # 10 repetitions
    # for idx in range(0, 4): # 10 repetitions


        print("Beginning run number {}".format(idx))
        logger = Logger()
        manager = manager_class(config, dataset, patchesHandler, logger)

        print("manager.config", manager.config)

        manager.defineExperiment(exp) # fixed
        manager.defineRepetitionId(idx) # varying from 0 to 10
        manager.setExperimentPath()
        manager.createLogFolders()

        manager.loadDataset()

        # %%
        if config['get_multiple_metrics'] == False:
            predictor_fcn = manager.run_predictor
        else:
            predictor_fcn = manager.run_predictor_multiple_metrics
        result = predictor_fcn()
        print("Result idx {}: {}".format(idx, result))
        results.append(result)

        with open(manager.default_log_name, 'wb') as f:
            pickle.dump(results, f)
        print("Grid execution idx: {}".format(idx))
        del manager
        gc.collect()
        # idx += 1
    

Beginning run number 4
manager.config {'training': False, 'inferring': True, 'site': 'MS', 'training_date': 'earlier', 'mode': 'evidential2', 'training_times': 10, 'uncertainty_method': 'pred_entropy', 'loadInference': False, 'removePolygons': True, 'plotLandsat': False, 'plotPOI': False, 'training_experiment_id': 39, 'get_multiple_metrics': False, 'start_repetition_id': 4, 'save_probabilities': False, 'addPastDeforestationInput': True, 'classes_mode': True, 'learning_rate': 0.0001, 'use_cloud_mask': False, 'mask_out_non_biome': False, 'log_filename': 'log.pkl', 'inference_times': 1, 'dropout_training': False}
D:/Jorge/datasets/deforestation/MS/deforestation_past_years.tif
Loaded deforestation past years


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([334024764,   8717093,   6541094,   3824922,   2096535,   1305948,
                                                                      1003721,    903906,    318788,    701575,    310887,    440417,
                                                                       316180,    560438,    600838,    776899], dtype=int64))


Label where deforestation past years is actual date (2020) = 1


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([334024764,   8717093,   6541094,   3824922,   2096535,   1305948,
                                                                      1003721,    903906,    318788,    701575,    310887,    440417,
                                                                       316180,    560438,    600838,    776899], dtype=int64))


Past deforestation different from 0 (no deforestation)


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([334024764,   8717093,   6541094,   3824922,   2096535,   1305948,
                                                                      1003721,    903906,    318788,    701575,    310887,    440417,
                                                                       316180,    560438,    600838,    776899], dtype=int64))


Past deforestation before 2008 is 2
D:/Jorge/datasets/deforestation/MS/deforestation_before_2000_MS.tif


ic| np.unique(label_past_deforestation_before_2008, return_counts=True): (array([  0, 208], dtype=uint8), array([126708038, 235735967], dtype=int64))
ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([334024764,   8717093,   6541094,   3824922,   2096535,   1305948,
                                                                      1003721,    903906,    318788,    701575,    310887,    440417,
                                                                       316180,    560438,    600838,    776899], dtype=int64))
ic| label_per_date.shape: (18605, 19481, 1)


Removing bufer................
Mask label shape:  
 (18605, 19481, 1) 
 Unique values:  
 [0 1 2]
Tiles size:  3721 3896
Mask size:  (18605, 19480)


ic| image_stack.shape: (18605, 19481, 9)


Image shape:  (18605, 19481, 9)
mask:  (18605, 19480)
image stack:  (18605, 19480, 9)
ref : (18605, 19480, 1)
Training tiles:  [2, 4, 5, 6, 7, 12, 14, 15, 18, 21, 23, 24]
Validation tiles:  [9, 11, 25]
Test tiles:  [1, 3, 8, 10, 13, 16, 17, 19, 20, 22]
-35.0 -8.0


ic| self.path_models+ '/' + self.method +'_'+str(self.repetition_id)+'.h5': 'D:/Jorge/datasets/deforestation/experiments/MS/exp39/models/resunet_4.h5'


Dropout training mode: False
time:  0
alpha.shape (18640, 19488, 2)
S.shape (18640, 19488)
K 2
u.shape (18640, 19488)
belief.shape (18640, 19488, 2)
Inference runtime 137.29
(36877090,)
(array([0, 1], dtype=uint8), array([36581631,   295459], dtype=int64))
(18605, 19480, 2)


ic| predicted_test.shape: (144970160,)
ic| predicted_test.shape: (36877090,)
ic| np.unique(predicted, return_counts=True): (array([0, 1], dtype=int8), array([362035679,    389721], dtype=int64))
    np.unique(predicted_larger_than_min_area, return_counts=True): (array([0, 1], dtype=int8), array([362059237,    366163], dtype=int64))
ic| np.unique(ignored_polygons, return_counts=True): (array([0, 1], dtype=int8), array([362401842,     23558], dtype=int64))
ic| self.f1: 86.15, self.precision: 98.3, self.recall: 76.67
ic| self.label_mask_val.shape: (43491048,)
ic| self.label_mask_val_valid.shape: (10775227,)
ic| f1_val: 47.41
    precision_val: 100.0
    recall_val: 31.07
    mAP_val: 32.05


(array([0, 1], dtype=int16), array([362276146,    149254], dtype=int64))
[0 1]


ic| self.label_mask.shape: (18605, 19480)
ic| self.mask_test.shape: (18605, 19480)
ic| self.label_mask_test.shape: (144970160,)
ic| self.error_mask_test.shape: (36864681,)
ic| bounds: (0.00010578750008484349, 0.4985)


(0.00010578750008484349, 0.4985)
0.19047543687881469
threshold 0.19047543687881469


c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\scipy\optimize\_minimize.py:783: RuntimeWarning: Method 'bounded' does not support relative tolerance in x; defaulting to absolute tolerance.
  warn("Method 'bounded' does not support relative tolerance in x; "
ic| label_current_deforestation_test_classified_incorrect.shape: (2881317,)
    predicted_test_classified_incorrect.shape: (2881317,)
ic| TP_H + FN_H + FP_H + TN_H: 2881317
    len(label_mask_current_deforestation_test): 36864681
ic| TP_H + FN_H + FP_H + TN_H: 2881317
    len(label_mask_current_deforestation_test): 36864681


[0.99935671 0.85202702 0.45807374 0.07815928 0.95973553 0.66757448
 0.01654114]
0.30813035062127003
threshold 0.30813035062127003


ic| label_current_deforestation_test_classified_incorrect.shape: (1518732,)
    predicted_test_classified_incorrect.shape: (1518732,)
ic| TP_H + FN_H + FP_H + TN_H: 1518732
    len(label_mask_current_deforestation_test): 36864681
ic| TP_H + FN_H + FP_H + TN_H: 1518732
    len(label_mask_current_deforestation_test): 36864681


[0.99113929 0.86424091 0.58360276 0.04119748 0.95800896 0.5639856
 0.02788455]
0.38084508625754454
threshold 0.38084508625754454


ic| label_current_deforestation_test_classified_incorrect.shape: (962431,)
    predicted_test_classified_incorrect.shape: (962431,)
ic| TP_H + FN_H + FP_H + TN_H: 962431
    len(label_mask_current_deforestation_test): 36864681
ic| TP_H + FN_H + FP_H + TN_H: 962431
    len(label_mask_current_deforestation_test): 36864681


[0.98836123 0.86691284 0.65722175 0.02610713 0.95213825 0.45278013
 0.03999308]
0.38923231921357604
threshold 0.38923231921357604


ic| label_current_deforestation_test_classified_incorrect.shape: (911211,)
    predicted_test_classified_incorrect.shape: (911211,)
ic| TP_H + FN_H + FP_H + TN_H: 911211
    len(label_mask_current_deforestation_test): 36864681
ic| TP_H + FN_H + FP_H + TN_H: 911211
    len(label_mask_current_deforestation_test): 36864681


[0.98796477 0.86690677 0.66550224 0.02471772 0.9517039  0.4357642
 0.04164259]
0.35979542213018467
threshold 0.35979542213018467


ic| label_current_deforestation_test_classified_incorrect.shape: (1101832,)
    predicted_test_classified_incorrect.shape: (1101832,)
ic| TP_H + FN_H + FP_H + TN_H: 1101832
    len(label_mask_current_deforestation_test): 36864681
ic| TP_H + FN_H + FP_H + TN_H: 1101832
    len(label_mask_current_deforestation_test): 36864681


[0.98920335 0.86636771 0.63534974 0.02988855 0.95417559 0.49274721
 0.03604866]
0.3400611208449731
threshold 0.3400611208449731


ic| label_current_deforestation_test_classified_incorrect.shape: (1248189,)
    predicted_test_classified_incorrect.shape: (1248189,)
ic| TP_H + FN_H + FP_H + TN_H: 1248189
    len(label_mask_current_deforestation_test): 36864681
ic| TP_H + FN_H + FP_H + TN_H: 1248189
    len(label_mask_current_deforestation_test): 36864681


[0.98988117 0.86559166 0.61525386 0.03385867 0.95610194 0.52379753
 0.0326455 ]
0.3604068249087031
threshold 0.3604068249087031


ic| label_current_deforestation_test_classified_incorrect.shape: (1097515,)
    predicted_test_classified_incorrect.shape: (1097515,)
ic| TP_H + FN_H + FP_H + TN_H: 1097515
    len(label_mask_current_deforestation_test): 36864681
ic| TP_H + FN_H + FP_H + TN_H: 1097515
    len(label_mask_current_deforestation_test): 36864681


[0.98917764 0.86633843 0.63604354 0.02977145 0.95411264 0.49166765
 0.0361453 ]
0.35499269969223457
threshold 0.35499269969223457


ic| label_current_deforestation_test_classified_incorrect.shape: (1136157,)
    predicted_test_classified_incorrect.shape: (1136157,)
ic| TP_H + FN_H + FP_H + TN_H: 1136157
    len(label_mask_current_deforestation_test): 36864681
ic| TP_H + FN_H + FP_H + TN_H: 1136157
    len(label_mask_current_deforestation_test): 36864681


[0.98934833 0.86624793 0.63055906 0.03081966 0.95474002 0.50052275
 0.03518839]
0.3579609453974195
threshold 0.3579609453974195


ic| label_current_deforestation_test_classified_incorrect.shape: (1114850,)
    predicted_test_classified_incorrect.shape: (1114850,)
ic| TP_H + FN_H + FP_H + TN_H: 1114850
    len(label_mask_current_deforestation_test): 36864681
ic| TP_H + FN_H + FP_H + TN_H: 1114850
    len(label_mask_current_deforestation_test): 36864681


[0.9892476  0.86631374 0.63352505 0.03024168 0.95444265 0.49575916
 0.03571301]
0.35920889759559305
threshold 0.35920889759559305


ic| label_current_deforestation_test_classified_incorrect.shape: (1106021,)
    predicted_test_classified_incorrect.shape: (1106021,)
ic| TP_H + FN_H + FP_H + TN_H: 1106021
    len(label_mask_current_deforestation_test): 36864681
ic| TP_H + FN_H + FP_H + TN_H: 1106021
    len(label_mask_current_deforestation_test): 36864681


[0.98920848 0.86636015 0.63470104 0.03000219 0.95431867 0.49380522
 0.03594311]
0.3587322222722259
threshold 0.3587322222722259


ic| label_current_deforestation_test_classified_incorrect.shape: (1109435,)
    predicted_test_classified_incorrect.shape: (1109435,)
ic| TP_H + FN_H + FP_H + TN_H: 1109435
    len(label_mask_current_deforestation_test): 36864681
ic| TP_H + FN_H + FP_H + TN_H: 1109435
    len(label_mask_current_deforestation_test): 36864681


[0.98921764 0.86635521 0.6342917  0.03009479 0.95438184 0.49447006
 0.03585362]
0.35924223625685536
threshold 0.35924223625685536


ic| label_current_deforestation_test_classified_incorrect.shape: (1105788,)
    predicted_test_classified_incorrect.shape: (1105788,)
ic| TP_H + FN_H + FP_H + TN_H: 1105788
    len(label_mask_current_deforestation_test): 36864681
ic| TP_H + FN_H + FP_H + TN_H: 1105788
    len(label_mask_current_deforestation_test): 36864681


[0.98920883 0.86635574 0.63472186 0.02999587 0.95431179 0.49377863
 0.03594866]
0.3591665755131029
threshold 0.3591665755131029


ic| label_current_deforestation_test_classified_incorrect.shape: (1106295,)
    predicted_test_classified_incorrect.shape: (1106295,)
ic| TP_H + FN_H + FP_H + TN_H: 1106295
    len(label_mask_current_deforestation_test): 36864681
ic| TP_H + FN_H + FP_H + TN_H: 1106295
    len(label_mask_current_deforestation_test): 36864681
ic| self.threshold_optimal: 0.35920889759559305


[0.98920766 0.86636359 0.63465248 0.03000962 0.9543347  0.49387792
 0.03593718]
threshold:  0.35920889759559305
threshold 0.35920889759559305


ic| label_current_deforestation_test_classified_incorrect.shape: (1106021,)
    predicted_test_classified_incorrect.shape: (1106021,)
ic| TP_H + FN_H + FP_H + TN_H: 1106021
    len(label_mask_current_deforestation_test): 36864681
ic| TP_H + FN_H + FP_H + TN_H: 1106021
    len(label_mask_current_deforestation_test): 36864681


[0.98920848 0.86636015 0.63470104 0.03000219 0.95431867 0.49380522
 0.03594311]
threshold 0.35920889759559305
(36864681,) (36864681,)


ic| self.m_optimal: {'AA': array([0.03000219]),
                     'UEO': array([0.03594311]),
                     'f1': 86.15,
                     'f1_H': array([0.65083871]),
                     'f1_L': array([0.92371771]),
                     'precision_H': array([0.95431867]),
                     'precision_L': array([0.98920848]),
                     'recall_H': array([0.49380522]),
                     'recall_L': array([0.86636015]),
                     'recall_Ltotal': array([0.63470104])}
ic| self.m_audited_optimal: {'f1': array([0.94508721]),
                             'precision': array([0.99238287]),
                             'recall': array([0.90209458])}


cm_audited [[36574417     1996]
 [   28223   260045]]
[0.99238287 0.90209458]
Result idx 4: {'uncertainty_result': {'metrics': {'precision_L': array([0.98920848]), 'recall_L': array([0.86636015]), 'recall_Ltotal': array([0.63470104]), 'AA': array([0.03000219]), 'precision_H': array([0.95431867]), 'recall_H': array([0.49380522]), 'UEO': array([0.03594311]), 'f1_L': array([0.92371771]), 'f1_H': array([0.65083871]), 'f1': 86.15}, 'metrics_audited': {'precision': array([0.99238287]), 'recall': array([0.90209458]), 'f1': array([0.94508721])}, 'exp': 39}}
Grid execution idx: 4
Beginning run number 5
manager.config {'training': False, 'inferring': True, 'site': 'MS', 'training_date': 'earlier', 'mode': 'evidential2', 'training_times': 10, 'uncertainty_method': 'pred_entropy', 'loadInference': False, 'removePolygons': True, 'plotLandsat': False, 'plotPOI': False, 'training_experiment_id': 39, 'get_multiple_metrics': False, 'start_repetition_id': 4, 'save_probabilities': False, 'addPastDeforest

ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([334024764,   8717093,   6541094,   3824922,   2096535,   1305948,
                                                                      1003721,    903906,    318788,    701575,    310887,    440417,
                                                                       316180,    560438,    600838,    776899], dtype=int64))


Label where deforestation past years is actual date (2020) = 1


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([334024764,   8717093,   6541094,   3824922,   2096535,   1305948,
                                                                      1003721,    903906,    318788,    701575,    310887,    440417,
                                                                       316180,    560438,    600838,    776899], dtype=int64))


Past deforestation different from 0 (no deforestation)


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([334024764,   8717093,   6541094,   3824922,   2096535,   1305948,
                                                                      1003721,    903906,    318788,    701575,    310887,    440417,
                                                                       316180,    560438,    600838,    776899], dtype=int64))


Past deforestation before 2008 is 2
D:/Jorge/datasets/deforestation/MS/deforestation_before_2000_MS.tif


ic| np.unique(label_past_deforestation_before_2008, return_counts=True): (array([  0, 208], dtype=uint8), array([126708038, 235735967], dtype=int64))
ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([334024764,   8717093,   6541094,   3824922,   2096535,   1305948,
                                                                      1003721,    903906,    318788,    701575,    310887,    440417,
                                                                       316180,    560438,    600838,    776899], dtype=int64))
ic| label_per_date.shape: (18605, 19481, 1)


Removing bufer................
Mask label shape:  
 (18605, 19481, 1) 
 Unique values:  
 [0 1 2]
Tiles size:  3721 3896
Mask size:  (18605, 19480)


ic| image_stack.shape: (18605, 19481, 9)


Image shape:  (18605, 19481, 9)
mask:  (18605, 19480)
image stack:  (18605, 19480, 9)
ref : (18605, 19480, 1)
Training tiles:  [2, 4, 5, 6, 7, 12, 14, 15, 18, 21, 23, 24]
Validation tiles:  [9, 11, 25]
Test tiles:  [1, 3, 8, 10, 13, 16, 17, 19, 20, 22]
-35.0 -8.0


ic| self.path_models+ '/' + self.method +'_'+str(self.repetition_id)+'.h5': 'D:/Jorge/datasets/deforestation/experiments/MS/exp39/models/resunet_5.h5'


Dropout training mode: False
time:  0
alpha.shape (18640, 19488, 2)
S.shape (18640, 19488)
K 2
u.shape (18640, 19488)
belief.shape (18640, 19488, 2)
Inference runtime 140.07
(36877090,)
(array([0, 1], dtype=uint8), array([36581631,   295459], dtype=int64))
(18605, 19480, 2)


ic| predicted_test.shape: (144970160,)
ic| predicted_test.shape: (36877090,)
ic| np.unique(predicted, return_counts=True): (array([0, 1], dtype=int8), array([361973601,    451799], dtype=int64))
    np.unique(predicted_larger_than_min_area, return_counts=True): (array([0, 1], dtype=int8), array([362000844,    424556], dtype=int64))
ic| np.unique(ignored_polygons, return_counts=True): (array([0, 1], dtype=int8), array([362398157,     27243], dtype=int64))
ic| self.f1: 85.68, self.precision: 97.89, self.recall: 76.17
ic| self.label_mask_val.shape: (43491048,)
ic| self.label_mask_val_valid.shape: (10773906,)
ic| f1_val: 65.49
    precision_val: 100.0
    recall_val: 48.69
    mAP_val: 50.13


(array([0, 1], dtype=int16), array([362219173,    206227], dtype=int64))
[0 1]


ic| self.label_mask.shape: (18605, 19480)
ic| self.mask_test.shape: (18605, 19480)
ic| self.label_mask_test.shape: (144970160,)
ic| self.error_mask_test.shape: (36863532,)
ic| bounds: (0.00010578750008484349, 0.4985)


(0.00010578750008484349, 0.4985)
0.19047543687881469
threshold 0.19047543687881469


c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\scipy\optimize\_minimize.py:783: RuntimeWarning: Method 'bounded' does not support relative tolerance in x; defaulting to absolute tolerance.
  warn("Method 'bounded' does not support relative tolerance in x; "
ic| label_current_deforestation_test_classified_incorrect.shape: (1199016,)
    predicted_test_classified_incorrect.shape: (1199016,)
ic| TP_H + FN_H + FP_H + TN_H: 1199016
    len(label_mask_current_deforestation_test): 36863532
ic| TP_H + FN_H + FP_H + TN_H: 1199016
    len(label_mask_current_deforestation_test): 36863532


[0.9884104  0.84908725 0.63280236 0.0325258  0.93501233 0.50608726
 0.03149537]
0.30813035062127003
threshold 0.30813035062127003


ic| label_current_deforestation_test_classified_incorrect.shape: (641523,)
    predicted_test_classified_incorrect.shape: (641523,)
ic| TP_H + FN_H + FP_H + TN_H: 641523
    len(label_mask_current_deforestation_test): 36863532
ic| TP_H + FN_H + FP_H + TN_H: 641523
    len(label_mask_current_deforestation_test): 36863532


[0.98594389 0.84836596 0.680319   0.01740265 0.92414635 0.41092412
 0.05234827]
0.11776070124254019
threshold 0.11776070124254019


ic| label_current_deforestation_test_classified_incorrect.shape: (2008946,)
    predicted_test_classified_incorrect.shape: (2008946,)
ic| TP_H + FN_H + FP_H + TN_H: 2008946
    len(label_mask_current_deforestation_test): 36863532
ic| TP_H + FN_H + FP_H + TN_H: 2008946
    len(label_mask_current_deforestation_test): 36863532


[0.99039946 0.84914043 0.59403423 0.05449684 0.94042917 0.55814195
 0.02024958]
0.22828955251970462
threshold 0.22828955251970462


ic| label_current_deforestation_test_classified_incorrect.shape: (958746,)
    predicted_test_classified_incorrect.shape: (958746,)
ic| TP_H + FN_H + FP_H + TN_H: 958746
    len(label_mask_current_deforestation_test): 36863532
ic| TP_H + FN_H + FP_H + TN_H: 958746
    len(label_mask_current_deforestation_test): 36863532


[0.9877734  0.84912005 0.64905057 0.02600798 0.93103053 0.47816677
 0.03806764]
0.17632788140900704
threshold 0.17632788140900704


ic| label_current_deforestation_test_classified_incorrect.shape: (1314512,)
    predicted_test_classified_incorrect.shape: (1314512,)
ic| TP_H + FN_H + FP_H + TN_H: 1314512
    len(label_mask_current_deforestation_test): 36863532
ic| TP_H + FN_H + FP_H + TN_H: 1314512
    len(label_mask_current_deforestation_test): 36863532


[0.98874583 0.84919123 0.62628435 0.03565887 0.93605697 0.51594402
 0.02913772]
0.2055113588407583
threshold 0.2055113588407583


ic| label_current_deforestation_test_classified_incorrect.shape: (1092904,)
    predicted_test_classified_incorrect.shape: (1092904,)
ic| TP_H + FN_H + FP_H + TN_H: 1092904
    len(label_mask_current_deforestation_test): 36863532
ic| TP_H + FN_H + FP_H + TN_H: 1092904
    len(label_mask_current_deforestation_test): 36863532


[0.98815093 0.84919633 0.63961176 0.02964729 0.93341465 0.49474335
 0.03409912]
0.20697332382641526
threshold 0.20697332382641526


ic| label_current_deforestation_test_classified_incorrect.shape: (1083313,)
    predicted_test_classified_incorrect.shape: (1083313,)
ic| TP_H + FN_H + FP_H + TN_H: 1083313
    len(label_mask_current_deforestation_test): 36863532
ic| TP_H + FN_H + FP_H + TN_H: 1083313
    len(label_mask_current_deforestation_test): 36863532


[0.98812124 0.84920157 0.64030207 0.02938712 0.93326045 0.49356272
 0.03435273]
0.20169024166930016
threshold 0.20169024166930016


ic| label_current_deforestation_test_classified_incorrect.shape: (1118153,)
    predicted_test_classified_incorrect.shape: (1118153,)
ic| TP_H + FN_H + FP_H + TN_H: 1118153
    len(label_mask_current_deforestation_test): 36863532
ic| TP_H + FN_H + FP_H + TN_H: 1118153
    len(label_mask_current_deforestation_test): 36863532


[0.98821974 0.84914731 0.63786345 0.03033223 0.93382853 0.49776241
 0.03343851]
0.19740656741652984
threshold 0.19740656741652984


ic| label_current_deforestation_test_classified_incorrect.shape: (1147752,)
    predicted_test_classified_incorrect.shape: (1147752,)
ic| TP_H + FN_H + FP_H + TN_H: 1147752
    len(label_mask_current_deforestation_test): 36863532
ic| TP_H + FN_H + FP_H + TN_H: 1147752
    len(label_mask_current_deforestation_test): 36863532


[0.98831856 0.84912328 0.63598679 0.03113516 0.93414948 0.50089829
 0.03270201]
0.20351878005823862
threshold 0.20351878005823862


ic| label_current_deforestation_test_classified_incorrect.shape: (1106113,)
    predicted_test_classified_incorrect.shape: (1106113,)
ic| TP_H + FN_H + FP_H + TN_H: 1106113
    len(label_mask_current_deforestation_test): 36863532
ic| TP_H + FN_H + FP_H + TN_H: 1106113
    len(label_mask_current_deforestation_test): 36863532


[0.98818832 0.8491584  0.63875842 0.03000562 0.93360023 0.49624797
 0.03374425]
0.20357177777616434
threshold 0.20357177777616434


ic| label_current_deforestation_test_classified_incorrect.shape: (1105770,)
    predicted_test_classified_incorrect.shape: (1105770,)
ic| TP_H + FN_H + FP_H + TN_H: 1105770
    len(label_mask_current_deforestation_test): 36863532
ic| TP_H + FN_H + FP_H + TN_H: 1105770
    len(label_mask_current_deforestation_test): 36863532


[0.98818321 0.84916049 0.63876883 0.02999631 0.93361958 0.49622681
 0.03375349]
0.20378591888483305
threshold 0.20378591888483305


ic| label_current_deforestation_test_classified_incorrect.shape: (1104300,)
    predicted_test_classified_incorrect.shape: (1104300,)
ic| TP_H + FN_H + FP_H + TN_H: 1104300
    len(label_mask_current_deforestation_test): 36863532
ic| TP_H + FN_H + FP_H + TN_H: 1104300
    len(label_mask_current_deforestation_test): 36863532


[0.9881747  0.84916778 0.6388833  0.02995643 0.93361105 0.49602174
 0.0337916 ]
0.2036051141289551
threshold 0.2036051141289551


ic| label_current_deforestation_test_classified_incorrect.shape: (1105557,)
    predicted_test_classified_incorrect.shape: (1105557,)
ic| TP_H + FN_H + FP_H + TN_H: 1105557
    len(label_mask_current_deforestation_test): 36863532
ic| TP_H + FN_H + FP_H + TN_H: 1105557
    len(label_mask_current_deforestation_test): 36863532
ic| self.threshold_optimal: 0.20357177777616434


[0.9881834  0.84916258 0.63877923 0.02999053 0.93361433 0.49620565
 0.0337598 ]
threshold:  0.20357177777616434
threshold 0.20357177777616434


ic| label_current_deforestation_test_classified_incorrect.shape: (1105770,)
    predicted_test_classified_incorrect.shape: (1105770,)
ic| TP_H + FN_H + FP_H + TN_H: 1105770
    len(label_mask_current_deforestation_test): 36863532
ic| TP_H + FN_H + FP_H + TN_H: 1105770
    len(label_mask_current_deforestation_test): 36863532


[0.98818321 0.84916049 0.63876883 0.02999631 0.93361958 0.49622681
 0.03375349]
threshold 0.20357177777616434
(36863532,) (36863532,)


ic| self.m_optimal: {'AA': array([0.02999631]),
                     'UEO': array([0.03375349]),
                     'f1': 85.68,
                     'f1_H': array([0.64802355]),
                     'f1_L': array([0.91341227]),
                     'precision_H': array([0.93361958]),
                     'precision_L': array([0.98818321]),
                     'recall_H': array([0.49622681]),
                     'recall_L': array([0.84916049]),
                     'recall_Ltotal': array([0.63876883])}
ic| self.m_audited_optimal: {'f1': array([0.93606423]),
                             'precision': array([0.9914575]),
                             'recall': array([0.88653314])}


cm_audited [[36573052     2202]
 [   32710   255568]]
[0.9914575  0.88653314]
Result idx 5: {'uncertainty_result': {'metrics': {'precision_L': array([0.98818321]), 'recall_L': array([0.84916049]), 'recall_Ltotal': array([0.63876883]), 'AA': array([0.02999631]), 'precision_H': array([0.93361958]), 'recall_H': array([0.49622681]), 'UEO': array([0.03375349]), 'f1_L': array([0.91341227]), 'f1_H': array([0.64802355]), 'f1': 85.68}, 'metrics_audited': {'precision': array([0.9914575]), 'recall': array([0.88653314]), 'f1': array([0.93606423])}, 'exp': 39}}
Grid execution idx: 5
Beginning run number 6
manager.config {'training': False, 'inferring': True, 'site': 'MS', 'training_date': 'earlier', 'mode': 'evidential2', 'training_times': 10, 'uncertainty_method': 'pred_entropy', 'loadInference': False, 'removePolygons': True, 'plotLandsat': False, 'plotPOI': False, 'training_experiment_id': 39, 'get_multiple_metrics': False, 'start_repetition_id': 4, 'save_probabilities': False, 'addPastDeforesta

ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([334024764,   8717093,   6541094,   3824922,   2096535,   1305948,
                                                                      1003721,    903906,    318788,    701575,    310887,    440417,
                                                                       316180,    560438,    600838,    776899], dtype=int64))


Label where deforestation past years is actual date (2020) = 1


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([334024764,   8717093,   6541094,   3824922,   2096535,   1305948,
                                                                      1003721,    903906,    318788,    701575,    310887,    440417,
                                                                       316180,    560438,    600838,    776899], dtype=int64))


Past deforestation different from 0 (no deforestation)


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([334024764,   8717093,   6541094,   3824922,   2096535,   1305948,
                                                                      1003721,    903906,    318788,    701575,    310887,    440417,
                                                                       316180,    560438,    600838,    776899], dtype=int64))


Past deforestation before 2008 is 2
D:/Jorge/datasets/deforestation/MS/deforestation_before_2000_MS.tif


ic| np.unique(label_past_deforestation_before_2008, return_counts=True): (array([  0, 208], dtype=uint8), array([126708038, 235735967], dtype=int64))
ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([334024764,   8717093,   6541094,   3824922,   2096535,   1305948,
                                                                      1003721,    903906,    318788,    701575,    310887,    440417,
                                                                       316180,    560438,    600838,    776899], dtype=int64))
ic| label_per_date.shape: (18605, 19481, 1)


Removing bufer................
Mask label shape:  
 (18605, 19481, 1) 
 Unique values:  
 [0 1 2]
Tiles size:  3721 3896
Mask size:  (18605, 19480)


ic| image_stack.shape: (18605, 19481, 9)


Image shape:  (18605, 19481, 9)
mask:  (18605, 19480)
image stack:  (18605, 19480, 9)
ref : (18605, 19480, 1)
Training tiles:  [2, 4, 5, 6, 7, 12, 14, 15, 18, 21, 23, 24]
Validation tiles:  [9, 11, 25]
Test tiles:  [1, 3, 8, 10, 13, 16, 17, 19, 20, 22]
-35.0 -8.0


ic| self.path_models+ '/' + self.method +'_'+str(self.repetition_id)+'.h5': 'D:/Jorge/datasets/deforestation/experiments/MS/exp39/models/resunet_6.h5'


Dropout training mode: False
time:  0
alpha.shape (18640, 19488, 2)
S.shape (18640, 19488)
K 2
u.shape (18640, 19488)
belief.shape (18640, 19488, 2)
Inference runtime 139.9
(36877090,)
(array([0, 1], dtype=uint8), array([36581631,   295459], dtype=int64))
(18605, 19480, 2)


ic| predicted_test.shape: (144970160,)
ic| predicted_test.shape: (36877090,)
ic| np.unique(predicted, return_counts=True): (array([0, 1], dtype=int8), array([361990463,    434937], dtype=int64))
    np.unique(predicted_larger_than_min_area, return_counts=True): (array([0, 1], dtype=int8), array([362015729,    409671], dtype=int64))
ic| np.unique(ignored_polygons, return_counts=True): (array([0, 1], dtype=int8), array([362400134,     25266], dtype=int64))
ic| self.f1: 80.35, self.precision: 85.52, self.recall: 75.77
ic| self.label_mask_val.shape: (43491048,)
ic| self.label_mask_val_valid.shape: (10773687,)
ic| f1_val: 33.77
    precision_val: 37.83
    recall_val: 30.49
    mAP_val: 30.91


(array([0, 1], dtype=int16), array([362223644,    201756], dtype=int64))
[0 1]


ic| self.label_mask.shape: (18605, 19480)
ic| self.mask_test.shape: (18605, 19480)
ic| self.label_mask_test.shape: (144970160,)
ic| self.error_mask_test.shape: (36863907,)
ic| bounds: (0.00010578750008484349, 0.4985)


(0.00010578750008484349, 0.4985)
0.19047543687881469
threshold 0.19047543687881469


c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\scipy\optimize\_minimize.py:783: RuntimeWarning: Method 'bounded' does not support relative tolerance in x; defaulting to absolute tolerance.
  warn("Method 'bounded' does not support relative tolerance in x; "
ic| label_current_deforestation_test_classified_incorrect.shape: (2691904,)
    predicted_test_classified_incorrect.shape: (2691904,)
ic| TP_H + FN_H + FP_H + TN_H: 2691904
    len(label_mask_current_deforestation_test): 36863907
ic| TP_H + FN_H + FP_H + TN_H: 2691904
    len(label_mask_current_deforestation_test): 36863907


[0.99456535 0.87055421 0.56877743 0.07302275 0.60141494 0.54489906
 0.03008643]
0.30813035062127003
threshold 0.30813035062127003


ic| label_current_deforestation_test_classified_incorrect.shape: (1260121,)
    predicted_test_classified_incorrect.shape: (1260121,)
ic| TP_H + FN_H + FP_H + TN_H: 1260121
    len(label_mask_current_deforestation_test): 36863907
ic| TP_H + FN_H + FP_H + TN_H: 1260121
    len(label_mask_current_deforestation_test): 36863907


[0.9899793  0.86502555 0.64555674 0.03418306 0.47937015 0.44187379
 0.05893675]
0.38084508625754454
threshold 0.38084508625754454


ic| label_current_deforestation_test_classified_incorrect.shape: (814076,)
    predicted_test_classified_incorrect.shape: (814076,)
ic| TP_H + FN_H + FP_H + TN_H: 814076
    len(label_mask_current_deforestation_test): 36863907
ic| TP_H + FN_H + FP_H + TN_H: 814076
    len(label_mask_current_deforestation_test): 36863907


[0.98827845 0.86322375 0.68721014 0.02208328 0.3696568  0.34553756
 0.08641431]
0.3316753612534143
threshold 0.3316753612534143


ic| label_current_deforestation_test_classified_incorrect.shape: (1088967,)
    predicted_test_classified_incorrect.shape: (1088967,)
ic| TP_H + FN_H + FP_H + TN_H: 1088967
    len(label_mask_current_deforestation_test): 36863907
ic| TP_H + FN_H + FP_H + TN_H: 1088967
    len(label_mask_current_deforestation_test): 36863907


[0.98938922 0.86426122 0.6593143  0.02954019 0.44792094 0.41474984
 0.06701941]
0.33846159766451417
threshold 0.33846159766451417


ic| label_current_deforestation_test_classified_incorrect.shape: (1044784,)
    predicted_test_classified_incorrect.shape: (1044784,)
ic| TP_H + FN_H + FP_H + TN_H: 1044784
    len(label_mask_current_deforestation_test): 36863907
ic| TP_H + FN_H + FP_H + TN_H: 1044784
    len(label_mask_current_deforestation_test): 36863907


[0.98924515 0.86410048 0.66312143 0.02834165 0.43846104 0.40649088
 0.06951718]
0.3270670396747571
threshold 0.3270670396747571


ic| label_current_deforestation_test_classified_incorrect.shape: (1120327,)
    predicted_test_classified_incorrect.shape: (1120327,)
ic| TP_H + FN_H + FP_H + TN_H: 1120327
    len(label_mask_current_deforestation_test): 36863907
ic| TP_H + FN_H + FP_H + TN_H: 1120327
    len(label_mask_current_deforestation_test): 36863907


[0.98951107 0.86434068 0.65660778 0.03039089 0.45441671 0.42048646
 0.06535725]
0.3288441806235494
threshold 0.3288441806235494


ic| label_current_deforestation_test_classified_incorrect.shape: (1108080,)
    predicted_test_classified_incorrect.shape: (1108080,)
ic| TP_H + FN_H + FP_H + TN_H: 1108080
    len(label_mask_current_deforestation_test): 36863907
ic| TP_H + FN_H + FP_H + TN_H: 1108080
    len(label_mask_current_deforestation_test): 36863907


[0.98945072 0.86429608 0.6576807  0.03005867 0.45187781 0.41825079
 0.06598932]
0.3292663497656411
threshold 0.3292663497656411


ic| label_current_deforestation_test_classified_incorrect.shape: (1105211,)
    predicted_test_classified_incorrect.shape: (1105211,)
ic| TP_H + FN_H + FP_H + TN_H: 1105211
    len(label_mask_current_deforestation_test): 36863907
ic| TP_H + FN_H + FP_H + TN_H: 1105211
    len(label_mask_current_deforestation_test): 36863907


[0.98943391 0.8642915  0.65791951 0.02998084 0.45131385 0.4177417
 0.06614082]
0.33018651027468154
threshold 0.33018651027468154


ic| label_current_deforestation_test_classified_incorrect.shape: (1099015,)
    predicted_test_classified_incorrect.shape: (1099015,)
ic| TP_H + FN_H + FP_H + TN_H: 1099015
    len(label_mask_current_deforestation_test): 36863907
ic| TP_H + FN_H + FP_H + TN_H: 1099015
    len(label_mask_current_deforestation_test): 36863907


[0.98940148 0.86427958 0.65846981 0.02981277 0.45000079 0.41656614
 0.06646925]
0.32929968798278364
threshold 0.32929968798278364


ic| label_current_deforestation_test_classified_incorrect.shape: (1104964,)
    predicted_test_classified_incorrect.shape: (1104964,)
ic| TP_H + FN_H + FP_H + TN_H: 1104964
    len(label_mask_current_deforestation_test): 36863907
ic| TP_H + FN_H + FP_H + TN_H: 1104964
    len(label_mask_current_deforestation_test): 36863907


[0.98943418 0.86428672 0.65793682 0.02997414 0.45127089 0.41771161
 0.06615332]
0.3291276283852343
threshold 0.3291276283852343


ic| label_current_deforestation_test_classified_incorrect.shape: (1106135,)
    predicted_test_classified_incorrect.shape: (1106135,)
ic| TP_H + FN_H + FP_H + TN_H: 1106135
    len(label_mask_current_deforestation_test): 36863907
ic| TP_H + FN_H + FP_H + TN_H: 1106135
    len(label_mask_current_deforestation_test): 36863907


[0.98944322 0.86429611 0.65785721 0.03000591 0.45145433 0.41786936
 0.06609274]
0.32901936097430573
threshold 0.32901936097430573


ic| label_current_deforestation_test_classified_incorrect.shape: (1106877,)
    predicted_test_classified_incorrect.shape: (1106877,)
ic| TP_H + FN_H + FP_H + TN_H: 1106877
    len(label_mask_current_deforestation_test): 36863907
ic| TP_H + FN_H + FP_H + TN_H: 1106877
    len(label_mask_current_deforestation_test): 36863907


[0.9894419  0.86429702 0.65777415 0.03002604 0.45166035 0.41804751
 0.06605342]
0.3290942901701493
threshold 0.3290942901701493


ic| label_current_deforestation_test_classified_incorrect.shape: (1106366,)
    predicted_test_classified_incorrect.shape: (1106366,)
ic| TP_H + FN_H + FP_H + TN_H: 1106366
    len(label_mask_current_deforestation_test): 36863907
ic| TP_H + FN_H + FP_H + TN_H: 1106366
    len(label_mask_current_deforestation_test): 36863907


[0.98944289 0.86430813 0.65783645 0.03001217 0.45150585 0.41789574
 0.06608307]
0.32916800305130656
threshold 0.32916800305130656


ic| label_current_deforestation_test_classified_incorrect.shape: (1105871,)
    predicted_test_classified_incorrect.shape: (1105871,)
ic| TP_H + FN_H + FP_H + TN_H: 1105871
    len(label_mask_current_deforestation_test): 36863907
ic| TP_H + FN_H + FP_H + TN_H: 1105871
    len(label_mask_current_deforestation_test): 36863907


[0.98944349 0.86429526 0.65787452 0.02999875 0.45141139 0.41783323
 0.06610714]
0.3292055681535005
threshold 0.3292055681535005


ic| label_current_deforestation_test_classified_incorrect.shape: (1105622,)
    predicted_test_classified_incorrect.shape: (1105622,)
ic| TP_H + FN_H + FP_H + TN_H: 1105622
    len(label_mask_current_deforestation_test): 36863907
ic| TP_H + FN_H + FP_H + TN_H: 1105622
    len(label_mask_current_deforestation_test): 36863907
ic| self.threshold_optimal: 0.32916800305130656


[0.98943867 0.86429111 0.65789528 0.02999199 0.45136692 0.41779472
 0.0661188 ]
threshold:  0.32916800305130656
threshold 0.32916800305130656


ic| label_current_deforestation_test_classified_incorrect.shape: (1105871,)
    predicted_test_classified_incorrect.shape: (1105871,)
ic| TP_H + FN_H + FP_H + TN_H: 1105871
    len(label_mask_current_deforestation_test): 36863907
ic| TP_H + FN_H + FP_H + TN_H: 1105871
    len(label_mask_current_deforestation_test): 36863907


[0.98944349 0.86429526 0.65787452 0.02999875 0.45141139 0.41783323
 0.06610714]
threshold 0.32916800305130656
(36863907,) (36863907,)


ic| self.m_optimal: {'AA': array([0.02999875]),
                     'UEO': array([0.06610714]),
                     'f1': 80.35,
                     'f1_H': array([0.43397377]),
                     'f1_L': array([0.92264492]),
                     'precision_H': array([0.45141139]),
                     'precision_L': array([0.98944349]),
                     'recall_H': array([0.41783323]),
                     'recall_L': array([0.86429526]),
                     'recall_Ltotal': array([0.65787452])}
ic| self.m_audited_optimal: {'f1': array([0.94205404]),
                             'precision': array([0.99223331]),
                             'recall': array([0.8967058])}


cm_audited [[36572947     2028]
 [   29845   259087]]
[0.99223331 0.8967058 ]
Result idx 6: {'uncertainty_result': {'metrics': {'precision_L': array([0.98944349]), 'recall_L': array([0.86429526]), 'recall_Ltotal': array([0.65787452]), 'AA': array([0.02999875]), 'precision_H': array([0.45141139]), 'recall_H': array([0.41783323]), 'UEO': array([0.06610714]), 'f1_L': array([0.92264492]), 'f1_H': array([0.43397377]), 'f1': 80.35}, 'metrics_audited': {'precision': array([0.99223331]), 'recall': array([0.8967058]), 'f1': array([0.94205404])}, 'exp': 39}}
Grid execution idx: 6
Beginning run number 7
manager.config {'training': False, 'inferring': True, 'site': 'MS', 'training_date': 'earlier', 'mode': 'evidential2', 'training_times': 10, 'uncertainty_method': 'pred_entropy', 'loadInference': False, 'removePolygons': True, 'plotLandsat': False, 'plotPOI': False, 'training_experiment_id': 39, 'get_multiple_metrics': False, 'start_repetition_id': 4, 'save_probabilities': False, 'addPastDeforesta

ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([334024764,   8717093,   6541094,   3824922,   2096535,   1305948,
                                                                      1003721,    903906,    318788,    701575,    310887,    440417,
                                                                       316180,    560438,    600838,    776899], dtype=int64))


Label where deforestation past years is actual date (2020) = 1


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([334024764,   8717093,   6541094,   3824922,   2096535,   1305948,
                                                                      1003721,    903906,    318788,    701575,    310887,    440417,
                                                                       316180,    560438,    600838,    776899], dtype=int64))


Past deforestation different from 0 (no deforestation)


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([334024764,   8717093,   6541094,   3824922,   2096535,   1305948,
                                                                      1003721,    903906,    318788,    701575,    310887,    440417,
                                                                       316180,    560438,    600838,    776899], dtype=int64))


Past deforestation before 2008 is 2
D:/Jorge/datasets/deforestation/MS/deforestation_before_2000_MS.tif


ic| np.unique(label_past_deforestation_before_2008, return_counts=True): (array([  0, 208], dtype=uint8), array([126708038, 235735967], dtype=int64))
ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2002, 2004, 2006, 2008, 2010, 2012, 2013, 2014, 2015, 2016,
                                                                    2017, 2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([334024764,   8717093,   6541094,   3824922,   2096535,   1305948,
                                                                      1003721,    903906,    318788,    701575,    310887,    440417,
                                                                       316180,    560438,    600838,    776899], dtype=int64))
ic| label_per_date.shape: (18605, 19481, 1)


Removing bufer................
Mask label shape:  
 (18605, 19481, 1) 
 Unique values:  
 [0 1 2]
Tiles size:  3721 3896
Mask size:  (18605, 19480)


ic| image_stack.shape: (18605, 19481, 9)


Image shape:  (18605, 19481, 9)
mask:  (18605, 19480)
image stack:  (18605, 19480, 9)
ref : (18605, 19480, 1)
Training tiles:  [2, 4, 5, 6, 7, 12, 14, 15, 18, 21, 23, 24]
Validation tiles:  [9, 11, 25]
Test tiles:  [1, 3, 8, 10, 13, 16, 17, 19, 20, 22]
-35.0 -8.0


ic| self.path_models+ '/' + self.method +'_'+str(self.repetition_id)+'.h5': 'D:/Jorge/datasets/deforestation/experiments/MS/exp39/models/resunet_7.h5'


Dropout training mode: False
time:  0
alpha.shape (18640, 19488, 2)
S.shape (18640, 19488)
K 2
u.shape (18640, 19488)
belief.shape (18640, 19488, 2)
Inference runtime 140.62
(36877090,)
(array([0, 1], dtype=uint8), array([36581631,   295459], dtype=int64))
(18605, 19480, 2)


ic| predicted_test.shape: (144970160,)
ic| predicted_test.shape: (36877090,)


In [ ]:
error_count

0

In [ ]:
print(results)

[{'uncertainty_result': {'metrics': {'precision_L': array([0.81588878]), 'recall_L': array([0.90360463]), 'recall_Ltotal': array([0.7227319]), 'AA': array([0.02999761]), 'precision_H': array([0.24574504]), 'recall_H': array([0.53130907]), 'UEO': array([0.10305995]), 'f1_L': array([0.8575094]), 'f1_H': array([0.33605528]), 'f1': 71.52}, 'metrics_audited': {'precision': array([0.84982389]), 'recall': array([0.9228999]), 'f1': array([0.88485571])}, 'exp': 38}}, {'uncertainty_result': {'metrics': {'precision_L': array([nan]), 'recall_L': array([0.]), 'recall_Ltotal': array([0.]), 'AA': array([0.99999965]), 'precision_H': array([nan]), 'recall_H': array([0.]), 'UEO': array([0.00801175]), 'f1_L': array([nan]), 'f1_H': array([nan]), 'f1': 0.0}, 'metrics_audited': {'precision': array([1.]), 'recall': array([0.99996954]), 'f1': array([0.99998477])}, 'exp': 38}}, {'uncertainty_result': {'metrics': {'precision_L': array([0.90079848]), 'recall_L': array([0.87851248]), 'recall_Ltotal': array([0.823

In [ ]:
print(len(results))

5


In [ ]:
results[7]

IndexError: list index out of range