In [1]:
import tracemalloc

from utils_v1 import *
import traceback


In [2]:
from icecream import ic

import numpy as np
from src.dataset import (
    MultipleDates, PAMultipleDates,
    MTMultipleDates
)

# from src.dataset_legacy import MTDeforestationTime
from src import training_generator as generator
from src.patchesHandler import PatchesHandler, PatchesHandlerMultipleDates, PatchesHandlerEvidential

from src.manager.evidential import ManagerEvidential
from src.manager.multioutput import ManagerMCDropout, ManagerSingleRun, ManagerEvidential2
from mpl_toolkits.axes_grid1 import make_axes_locatable

import cv2
from src import metrics as _metric
import json
import pickle 
import src.manager.evidential as evidential
from src.Logger import Logger
import pdb


Tensorflow ver. 2.6.0


In [3]:

with open('config.json', 'r') as f:
    config = json.load(f)
    
print("Mode: {}. Site: {}. Training: {}. Training date: {}".format(
    config['mode'], config['site'], config['training'], config['training_date']))
print(config)


Mode: evidential2. Site: PA. Training: True. Training date: current
{'training': True, 'inferring': True, 'site': 'PA', 'training_date': 'current', 'mode': 'evidential2', 'training_times': 10, 'learning_rate': 0.0001, 'weights': [0.1, 0.9, 0], 'save_probabilities': False, 'loadInference': False, 'addPastDeforestationInput': True, 'Uncertainty': {}, 'uncertainty_method': 'pred_entropy'}


In [4]:


#dates = [2018, 2019]

if config['site'] == 'PA':
	if config['training_date'] == "earlier":
		dates = [2017, 2018]
	else:
		dates = [2018, 2019]

	dataset = PAMultipleDates(config = config,
		dates = dates, # dates = [2016,2017,2018,2019]
		addPastDeforestationInput = True,
		borderBuffer = 2)


	if config['mode'] == 'ensemble':
		if config['training'] == True:
			config['mode'] = 'single_run'
		else:
			sys.exit("Ensure that training is True for ensemble mode. Use infer_ensemble.ipynb for inference.")

	if config['mode'] == 'mcd' or config['mode'] == 'single_run': # MCD will do 10 inference on each of the 10 repetitions = 100 runs
		if config['training_date'] == 'current': exp = 0
			# exp_ids = [103, 104, 105, 106, 107, 118, 119, 120, 121, 122]
			
		elif config['training_date'] == 'earlier': exp = 1
			# exp_ids = [123, 124, 125, 126, 127, 128, 129, 131, 1122, 1121]
			
	if config['mode'] == 'evidential2':
		if config['training_date'] == 'current': exp = 17; repetition_id = 0
		elif config['training_date'] == 'earlier': exp = 6; repetition_id = 0

else:
	if config['training_date'] == "earlier":
		dates = [2018, 2019]
	else:
		dates = [2019, 2020]

	dataset = MTMultipleDates(config = config,
		dates = dates, # dates = [2016,2017,2018,2019]
		addPastDeforestationInput = True,
		borderBuffer = 2)	
	if config['mode'] == 'evidential':	

		# MT
		# exp_id_base = 196
		# early date
		exp_id_base = 206
		# early date inference
		exp_id_base = 210
		exp_id_base = 210 if config['training_date'] == 'earlier' else 206

	elif config['mode'] == 'mcd' or config['mode'] == 'single_run':
		if config['training_date'] == 'current': exp = 2
#			exp_ids = [108, 109, 110, 111, 112, 113, 114, 115, 116, 117]
		elif config['training_date'] == 'earlier': exp = 3
#			exp_ids = [130, 132, 133, 134, 135, 136, 137, 1125, 1124, 1123]

ic(dates)


if issubclass(type(dataset), MultipleDates):
	if config['mode'] == 'evidential':
		patchesHandler = PatchesHandlerEvidential(
			dataset)
	else:
		patchesHandler = PatchesHandlerMultipleDates(
			dataset)
		
else:
	patchesHandler = PatchesHandler()



ic| list(self.date_ids): [0]
ic| self.image_channels: [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]]
ic| dates: [2018, 2019]
ic| self.input_image_shape: 21
ic| self.dataset.image_channels: [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]]


In [5]:


if config['mode'] == 'evidential2':
    config["inference_times"] = 1
    manager_class = ManagerEvidential2
    config['uncertainty_method'] = "pred_entropy"
    config['classes_mode'] = True
    
if config['mode'] == 'mcd':
    config["inference_times"] = 10
    manager_class = ManagerMCDropout
    config['uncertainty_method'] = "pred_entropy"
    config['classes_mode'] = False

elif config['mode'] == 'single_run':
    config["inference_times"] = 1
    manager_class = ManagerSingleRun
    config['uncertainty_method'] = "pred_entropy_single"
    config['classes_mode'] = False



In [6]:
exp

17

In [ ]:
if config['training'] == True:
    idx = 0
    error_count = 0
    
    while idx < config["training_times"]:
        try:

            print("Beginning run number {}".format(idx))
            logger = Logger()
            manager = manager_class(config, dataset, patchesHandler, logger)
            print("manager.config['dropout_training']", manager.config['dropout_training'])
            manager.defineExperiment(exp) # fixed
            manager.defineRepetitionId(idx) # varying from 0 to 10
            
            manager.setExperimentPath()
            manager.createLogFolders()

            manager.loadDataset()

            # %%
            if config["training"] == True:
                manager.run()
            idx += 1
            print("Grid execution idx: {}".format(idx))            
        except Exception as e: 
            print(traceback.format_exc())
            error_count += 1
            if error_count > 10:
                sys.exit()
            print("Execution error in idx {}. Retrying...".format(idx))
            continue


Beginning run number 0
manager.config['dropout_training'] False
D:/Jorge/datasets/deforestation/PA/deforestation_past_years.tif
Loaded deforestation past years


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Label where deforestation past years is actual date (2019) = 1


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation different from 0 (no deforestation)


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation before 2008 is 2
D:/Jorge/datasets/deforestation/PA/deforestation_before_2008_PA.tif


ic| np.unique(label_past_deforestation_before_2008, return_counts=True): (array([  0, 215], dtype=uint8), array([124211220,  38957970], dtype=int64))
ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Traceback (most recent call last):
  File "C:\Users\jchamorro\AppData\Local\Temp\ipykernel_19660\1756826738.py", line 18, in <cell line: 1>
    manager.loadDataset()
  File "d:\Jorge\deforestation_uncertainty\src\manager\base.py", line 168, in loadDataset
    self.loadLabel()
  File "d:\Jorge\deforestation_uncertainty\src\manager\base.py", line 74, in loadLabel
    self.label_mask = self.dataset.loadLabel()
  File "d:\Jorge\deforestation_uncertainty\src\dataset.py", line 471, in loadLabel
    if self.config['use_cloud_mask'] == True:
KeyError: 'use_cloud_mask'

Execution error in idx 0. Retrying...
Beginning run number 0
manager.config['dropout_training'] False
D:/Jorge/datasets/deforestation/PA/deforestation_past_years.tif
Loaded deforestation past years


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Label where deforestation past years is actual date (2019) = 1


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation different from 0 (no deforestation)


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation before 2008 is 2
D:/Jorge/datasets/deforestation/PA/deforestation_before_2008_PA.tif


ic| np.unique(label_past_deforestation_before_2008, return_counts=True): (array([  0, 215], dtype=uint8), array([124211220,  38957970], dtype=int64))
ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Traceback (most recent call last):
  File "C:\Users\jchamorro\AppData\Local\Temp\ipykernel_19660\1756826738.py", line 18, in <cell line: 1>
    manager.loadDataset()
  File "d:\Jorge\deforestation_uncertainty\src\manager\base.py", line 168, in loadDataset
    self.loadLabel()
  File "d:\Jorge\deforestation_uncertainty\src\manager\base.py", line 74, in loadLabel
    self.label_mask = self.dataset.loadLabel()
  File "d:\Jorge\deforestation_uncertainty\src\dataset.py", line 471, in loadLabel
    if self.config['use_cloud_mask'] == True:
KeyError: 'use_cloud_mask'

Execution error in idx 0. Retrying...
Beginning run number 0
manager.config['dropout_training'] False
D:/Jorge/datasets/deforestation/PA/deforestation_past_years.tif
Loaded deforestation past years


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Label where deforestation past years is actual date (2019) = 1


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation different from 0 (no deforestation)


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation before 2008 is 2
D:/Jorge/datasets/deforestation/PA/deforestation_before_2008_PA.tif


ic| np.unique(label_past_deforestation_before_2008, return_counts=True): (array([  0, 215], dtype=uint8), array([124211220,  38957970], dtype=int64))
ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Traceback (most recent call last):
  File "C:\Users\jchamorro\AppData\Local\Temp\ipykernel_19660\1756826738.py", line 18, in <cell line: 1>
    manager.loadDataset()
  File "d:\Jorge\deforestation_uncertainty\src\manager\base.py", line 168, in loadDataset
    self.loadLabel()
  File "d:\Jorge\deforestation_uncertainty\src\manager\base.py", line 74, in loadLabel
    self.label_mask = self.dataset.loadLabel()
  File "d:\Jorge\deforestation_uncertainty\src\dataset.py", line 471, in loadLabel
    if self.config['use_cloud_mask'] == True:
KeyError: 'use_cloud_mask'

Execution error in idx 0. Retrying...
Beginning run number 0
manager.config['dropout_training'] False
D:/Jorge/datasets/deforestation/PA/deforestation_past_years.tif
Loaded deforestation past years


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Label where deforestation past years is actual date (2019) = 1


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation different from 0 (no deforestation)


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation before 2008 is 2
D:/Jorge/datasets/deforestation/PA/deforestation_before_2008_PA.tif


ic| np.unique(label_past_deforestation_before_2008, return_counts=True): (array([  0, 215], dtype=uint8), array([124211220,  38957970], dtype=int64))
ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Traceback (most recent call last):
  File "C:\Users\jchamorro\AppData\Local\Temp\ipykernel_19660\1756826738.py", line 18, in <cell line: 1>
    manager.loadDataset()
  File "d:\Jorge\deforestation_uncertainty\src\manager\base.py", line 168, in loadDataset
    self.loadLabel()
  File "d:\Jorge\deforestation_uncertainty\src\manager\base.py", line 74, in loadLabel
    self.label_mask = self.dataset.loadLabel()
  File "d:\Jorge\deforestation_uncertainty\src\dataset.py", line 471, in loadLabel
    if self.config['use_cloud_mask'] == True:
KeyError: 'use_cloud_mask'

Execution error in idx 0. Retrying...
Beginning run number 0
manager.config['dropout_training'] False
D:/Jorge/datasets/deforestation/PA/deforestation_past_years.tif
Loaded deforestation past years


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Label where deforestation past years is actual date (2019) = 1


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation different from 0 (no deforestation)


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation before 2008 is 2
D:/Jorge/datasets/deforestation/PA/deforestation_before_2008_PA.tif


ic| np.unique(label_past_deforestation_before_2008, return_counts=True): (array([  0, 215], dtype=uint8), array([124211220,  38957970], dtype=int64))
ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Traceback (most recent call last):
  File "C:\Users\jchamorro\AppData\Local\Temp\ipykernel_19660\1756826738.py", line 18, in <cell line: 1>
    manager.loadDataset()
  File "d:\Jorge\deforestation_uncertainty\src\manager\base.py", line 168, in loadDataset
    self.loadLabel()
  File "d:\Jorge\deforestation_uncertainty\src\manager\base.py", line 74, in loadLabel
    self.label_mask = self.dataset.loadLabel()
  File "d:\Jorge\deforestation_uncertainty\src\dataset.py", line 471, in loadLabel
    if self.config['use_cloud_mask'] == True:
KeyError: 'use_cloud_mask'

Execution error in idx 0. Retrying...
Beginning run number 0
manager.config['dropout_training'] False
D:/Jorge/datasets/deforestation/PA/deforestation_past_years.tif
Loaded deforestation past years


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Label where deforestation past years is actual date (2019) = 1


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation different from 0 (no deforestation)


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation before 2008 is 2
D:/Jorge/datasets/deforestation/PA/deforestation_before_2008_PA.tif


ic| np.unique(label_past_deforestation_before_2008, return_counts=True): (array([  0, 215], dtype=uint8), array([124211220,  38957970], dtype=int64))
ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Traceback (most recent call last):
  File "C:\Users\jchamorro\AppData\Local\Temp\ipykernel_19660\1756826738.py", line 18, in <cell line: 1>
    manager.loadDataset()
  File "d:\Jorge\deforestation_uncertainty\src\manager\base.py", line 168, in loadDataset
    self.loadLabel()
  File "d:\Jorge\deforestation_uncertainty\src\manager\base.py", line 74, in loadLabel
    self.label_mask = self.dataset.loadLabel()
  File "d:\Jorge\deforestation_uncertainty\src\dataset.py", line 471, in loadLabel
    if self.config['use_cloud_mask'] == True:
KeyError: 'use_cloud_mask'

Execution error in idx 0. Retrying...
Beginning run number 0
manager.config['dropout_training'] False
D:/Jorge/datasets/deforestation/PA/deforestation_past_years.tif
Loaded deforestation past years


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Label where deforestation past years is actual date (2019) = 1


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation different from 0 (no deforestation)


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation before 2008 is 2
D:/Jorge/datasets/deforestation/PA/deforestation_before_2008_PA.tif


ic| np.unique(label_past_deforestation_before_2008, return_counts=True): (array([  0, 215], dtype=uint8), array([124211220,  38957970], dtype=int64))
ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Traceback (most recent call last):
  File "C:\Users\jchamorro\AppData\Local\Temp\ipykernel_19660\1756826738.py", line 18, in <cell line: 1>
    manager.loadDataset()
  File "d:\Jorge\deforestation_uncertainty\src\manager\base.py", line 168, in loadDataset
    self.loadLabel()
  File "d:\Jorge\deforestation_uncertainty\src\manager\base.py", line 74, in loadLabel
    self.label_mask = self.dataset.loadLabel()
  File "d:\Jorge\deforestation_uncertainty\src\dataset.py", line 471, in loadLabel
    if self.config['use_cloud_mask'] == True:
KeyError: 'use_cloud_mask'

Execution error in idx 0. Retrying...
Beginning run number 0
manager.config['dropout_training'] False
D:/Jorge/datasets/deforestation/PA/deforestation_past_years.tif
Loaded deforestation past years


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Label where deforestation past years is actual date (2019) = 1


In [ ]:

if config['site'] == 'PA':

	dates = [2018, 2019]

	dataset = PAMultipleDates(dates = dates, # dates = [2016,2017,2018,2019]
		addPastDeforestationInput = True,
		borderBuffer = 2)	

elif config['site'] == 'MT':

	dates = [2019, 2020]

	dataset = MTMultipleDates(dates = dates, # dates = [2016,2017,2018,2019]
		addPastDeforestationInput = True,
		borderBuffer = 2)	


ic(dates)

if issubclass(type(dataset), MultipleDates):
	if config['mode'] == 'evidential':
		patchesHandler = PatchesHandlerEvidential(
			dataset)
	else:
		patchesHandler = PatchesHandlerMultipleDates(
			dataset)
		
else:
	patchesHandler = PatchesHandler()



ic| list(self.date_ids): [0]
ic| self.image_channels: [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]]
ic| dates: [2018, 2019]
ic| self.input_image_shape: 21
ic| self.dataset.image_channels: [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]]


In [ ]:
manager_class

src.trainer.multioutput.TrainerSingleRun

In [ ]:
repetition_ids = manager_class(config, dataset, patchesHandler, logger).get_repetition_ids(exp)  
repetition_n = len(repetition_ids)
print("repetition_ids {}, repetition_n {}".format(repetition_ids, repetition_n))


In [ ]:
if config['inferring'] == True:
    idx = 0
    results = []
    error_count = 0

    while idx < len(repetition_n):
    # for experiment_value, exp_id in zip(experiment_values, exp_ids):
        try:

            print("Beginning run number {}".format(idx))
            logger = Logger()
            manager = manager_class(config, dataset, patchesHandler, logger)
            print("manager.config", manager.config)

            manager.defineExperiment(exp) # fixed
            manager.defineRepetitionId(idx) # varying from 0 to 10
            manager.setExperimentPath()
            manager.createLogFolders()

            manager.loadDataset()

            # %%
            result = manager.run_predictor()
            print("Result idx {}: {}".format(idx, result))
            results.append(result)


            with open(manager.default_log_name, 'wb') as f:
                pickle.dump(results, f)
            print("Grid execution idx: {}".format(idx))
            idx += 1
            print("Grid execution idx: {}".format(idx))
            error_count = 0
        except Exception as e: 
            print(traceback.format_exc())
            error_count += 1
            if error_count > 10:
                sys.exit()
            print("Execution error in idx {}. Retrying...".format(idx))
            continue

Beginning run number 0
trainer.config {'training': False, 'inferring': True, 'site': 'PA', 'training_date': 'current', 'mode': 'single_run', 'learning_rate': 0.0001, 'weights': [0.1, 0.9, 0], 'save_probabilities': False, 'loadInference': False, 'addPastDeforestationInput': True, 'Uncertainty': {}, 'uncertainty_method': 'pred_entropy_single', 'inference_times': 1, 'classes_mode': False, 'dropout_training': False}
D:/Jorge/datasets/deforestation/PA/deforestation_past_years.tif
Loaded deforestation past years


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Label where deforestation past years is actual date (2019) = 1


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation different from 0 (no deforestation)


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation before 2008 is 2
D:/Jorge/datasets/deforestation/deforestation_before_2008/deforestation_before_2008_para.tif


ic| np.unique(label_past_deforestation_before_2008, return_counts=True): (array([  0, 215], dtype=uint8), array([124211220,  38957970], dtype=int64))
ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))
ic| label_per_date.shape: (17730, 9203, 1)


Removing bufer................
Mask label shape:  
 (17730, 9203, 1) 
 Unique values:  
 [0 1 2]
Tiles size:  3546 2300
Mask size:  (17730, 9200)


ic| image_stack.shape: (17730, 9203, 21)


Image shape:  (17730, 9203, 21)
mask:  (17730, 9200)
image stack:  (17730, 9200, 21)
ref : (17730, 9200, 1)
Training tiles:  [1, 3, 5, 8, 11, 13, 14, 20]
Validation tiles:  [6, 19]
Test tiles:  [2, 4, 7, 9, 10, 12, 15, 16, 17, 18]
-30.0 -16.0


ic| self.path_models+ '/' + self.method +'_'+str(0)+'.h5': 'D:/Jorge/datasets/deforestation/experiments/exp103/models/resunet_0.h5'


Dropout training mode: False
time:  0
(54236371,)
(array([0, 1], dtype=uint8), array([53470765,   765606], dtype=int64))
(17730, 9200)
Single entropy
(array([0., 1.], dtype=float32), array([161073907,   2042093], dtype=int64))


ic| self.predicted_unpad.shape: (17730, 9200)
    self.predicted.shape: (17730, 9200)
ic| predicted_test.shape: (81558000,)
ic| predicted_test.shape: (54236371,)
ic| np.unique(predicted, return_counts=True): (array([0., 1.], dtype=float32), array([161191379,   1924621], dtype=int64))
    np.unique(predicted_larger_than_min_area, return_counts=True): (array([0., 1.], dtype=float32), array([161384703,   1731297], dtype=int64))
ic| np.unique(ignored_polygons, return_counts=True): (array([0., 1.], dtype=float32), array([162922676,    193324], dtype=int64))
ic| self.f1: 84.54, self.precision: 87.17, self.recall: 82.06
ic| self.label_mask_val.shape: (16311600,)
ic| self.label_mask_val_valid.shape: (9430607,)
ic| f1_val: 87.09
    precision_val: 84.22
    recall_val: 90.17
    mAP_val: 91.87


D:/Jorge/datasets/deforestation/PA/deforestation_past_years.tif
Loaded deforestation past years


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Label where deforestation past years is actual date (2019) = 1


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation different from 0 (no deforestation)


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation before 2008 is 2
D:/Jorge/datasets/deforestation/deforestation_before_2008/deforestation_before_2008_para.tif


ic| np.unique(label_past_deforestation_before_2008, return_counts=True): (array([  0, 215], dtype=uint8), array([124211220,  38957970], dtype=int64))
ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))
ic| label_per_date.shape: (17730, 9203, 1)


(array([0., 1.], dtype=float32), array([162506439,    609561], dtype=int64))
[0. 1.]


ic| pred_entropy.shape: (17760, 9216)
ic| self.label_mask.shape: (17730, 9200)
ic| self.mask_amazon_ts.shape: (17730, 9200)
ic| self.label_mask_test.shape: (81558000,)
ic| self.error_mask_test.shape: (54145132,)
ic| trainer.dataset.previewLims1: array([2200, 3200, 6900, 7900])
    trainer.dataset.previewLims2: array([ 500, 1500, 3500, 4500])
ic| np.unique(trainer.mask_amazon_ts[lims[0]:lims[1], lims[2]:lims[3]]): array([1], dtype=uint8)
ic| np.unique(trainer.mask_amazon_ts[lims[0]:lims[1], lims[2]:lims[3]], return_counts=True): (array([1], dtype=uint8), array([1000000], dtype=int64))
Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).
Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).
Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).


(54145132,) (54145132,)
0.841080483916035
ECE. Starting bin 0...
ECE. Starting bin 1...
ECE. Starting bin 2...
ECE. Starting bin 3...
ECE. Starting bin 4...
ECE. Starting bin 5...
ECE. Starting bin 6...
ECE. Starting bin 7...
ECE. Starting bin 8...
ECE. Starting bin 9...


ic| bounds: (0.0015, 0.3663794801235199)


0.004285987396271022
0.1408715596097929
threshold 0.1408715596097929


c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\scipy\optimize\_minimize.py:783: RuntimeWarning: Method 'bounded' does not support relative tolerance in x; defaulting to absolute tolerance.
  warn("Method 'bounded' does not support relative tolerance in x; "
ic| label_current_deforestation_test_classified_incorrect.shape: (1219929,)
    predicted_test_classified_incorrect.shape: (1219929,)
ic| TP_H + FN_H + FP_H + TN_H: 1219929
    len(label_mask_current_deforestation_test): 54145132
ic| TP_H + FN_H + FP_H + TN_H: 1219929
    len(label_mask_current_deforestation_test): 54145132


[0.97035925 0.9333513  0.60674357 0.02253072 0.67654021 0.61128061
 0.13863523]
0.22700792051372695
threshold 0.22700792051372695


ic| label_current_deforestation_test_classified_incorrect.shape: (813225,)
    predicted_test_classified_incorrect.shape: (813225,)
ic| TP_H + FN_H + FP_H + TN_H: 813225
    len(label_mask_current_deforestation_test): 54145132
ic| TP_H + FN_H + FP_H + TN_H: 813225
    len(label_mask_current_deforestation_test): 54145132


[0.93900553 0.92200914 0.70939126 0.01501936 0.598218   0.48246513
 0.16029901]
0.08763636090393405
threshold 0.08763636090393405


ic| label_current_deforestation_test_classified_incorrect.shape: (1599767,)
    predicted_test_classified_incorrect.shape: (1599767,)
ic| TP_H + FN_H + FP_H + TN_H: 1599767
    len(label_mask_current_deforestation_test): 54145132
ic| TP_H + FN_H + FP_H + TN_H: 1599767
    len(label_mask_current_deforestation_test): 54145132


[0.98764588 0.93820913 0.52002304 0.02954591 0.72453098 0.6744607
 0.11718088]
0.05473519870585886
threshold 0.05473519870585886


ic| label_current_deforestation_test_classified_incorrect.shape: (1988680,)
    predicted_test_classified_incorrect.shape: (1988680,)
ic| TP_H + FN_H + FP_H + TN_H: 1988680
    len(label_mask_current_deforestation_test): 54145132
ic| TP_H + FN_H + FP_H + TN_H: 1988680
    len(label_mask_current_deforestation_test): 54145132


[0.9948642  0.93911858 0.43334868 0.03672869 0.7656169  0.71914321
 0.0987822 ]
0.09665514614523395
threshold 0.09665514614523395


ic| label_current_deforestation_test_classified_incorrect.shape: (1521475,)
    predicted_test_classified_incorrect.shape: (1521475,)
ic| TP_H + FN_H + FP_H + TN_H: 1521475
    len(label_mask_current_deforestation_test): 54145132
ic| TP_H + FN_H + FP_H + TN_H: 1521475
    len(label_mask_current_deforestation_test): 54145132


[0.98471904 0.93737986 0.53716313 0.02809994 0.7159568  0.66397526
 0.12124983]
0.08257280939840696
threshold 0.08257280939840696


ic| label_current_deforestation_test_classified_incorrect.shape: (1647560,)
    predicted_test_classified_incorrect.shape: (1647560,)
ic| TP_H + FN_H + FP_H + TN_H: 1647560
    len(label_mask_current_deforestation_test): 54145132
ic| TP_H + FN_H + FP_H + TN_H: 1647560
    len(label_mask_current_deforestation_test): 54145132


[0.98906635 0.93856852 0.50929944 0.03042859 0.72997089 0.68074542
 0.11471758]
0.08487620878441943
threshold 0.08487620878441943


ic| label_current_deforestation_test_classified_incorrect.shape: (1625387,)
    predicted_test_classified_incorrect.shape: (1625387,)
ic| TP_H + FN_H + FP_H + TN_H: 1625387
    len(label_mask_current_deforestation_test): 54145132
ic| TP_H + FN_H + FP_H + TN_H: 1625387
    len(label_mask_current_deforestation_test): 54145132


[0.98842651 0.93846078 0.51435631 0.03001908 0.7274085  0.67776636
 0.11586478]
0.08506656373605025
threshold 0.08506656373605025


ic| label_current_deforestation_test_classified_incorrect.shape: (1623564,)
    predicted_test_classified_incorrect.shape: (1623564,)
ic| TP_H + FN_H + FP_H + TN_H: 1623564
    len(label_mask_current_deforestation_test): 54145132
ic| TP_H + FN_H + FP_H + TN_H: 1623564
    len(label_mask_current_deforestation_test): 54145132


[0.98835535 0.9384306  0.51475021 0.02998541 0.72722605 0.67755047
 0.11595003]
0.08516209148125282
threshold 0.08516209148125282


ic| label_current_deforestation_test_classified_incorrect.shape: (1622647,)
    predicted_test_classified_incorrect.shape: (1622647,)
ic| TP_H + FN_H + FP_H + TN_H: 1622647
    len(label_mask_current_deforestation_test): 54145132
ic| TP_H + FN_H + FP_H + TN_H: 1622647
    len(label_mask_current_deforestation_test): 54145132


[0.98833451 0.93842045 0.51497025 0.02996847 0.72710678 0.67742382
 0.11599751]
0.08498816897513024
threshold 0.08498816897513024


ic| label_current_deforestation_test_classified_incorrect.shape: (1624292,)
    predicted_test_classified_incorrect.shape: (1624292,)
ic| TP_H + FN_H + FP_H + TN_H: 1624292
    len(label_mask_current_deforestation_test): 54145132
ic| TP_H + FN_H + FP_H + TN_H: 1624292
    len(label_mask_current_deforestation_test): 54145132


[0.98837792 0.93844698 0.51460623 0.02999886 0.72729591 0.67762473
 0.11591518]
0.08495483438121865
threshold 0.08495483438121865


ic| label_current_deforestation_test_classified_incorrect.shape: (1624621,)
    predicted_test_classified_incorrect.shape: (1624621,)
ic| TP_H + FN_H + FP_H + TN_H: 1624621
    len(label_mask_current_deforestation_test): 54145132
ic| TP_H + FN_H + FP_H + TN_H: 1624621
    len(label_mask_current_deforestation_test): 54145132


[0.98838647 0.93844976 0.51452745 0.03000493 0.72733757 0.67767077
 0.1158982 ]
0.08502150356904184
threshold 0.08502150356904184


ic| label_current_deforestation_test_classified_incorrect.shape: (1623985,)
    predicted_test_classified_incorrect.shape: (1623985,)
ic| TP_H + FN_H + FP_H + TN_H: 1623985
    len(label_mask_current_deforestation_test): 54145132
ic| TP_H + FN_H + FP_H + TN_H: 1623985
    len(label_mask_current_deforestation_test): 54145132
ic| self.threshold_optimal: 0.08498816897513024


[0.98837161 0.93844485 0.51467007 0.02999319 0.72726157 0.67758731
 0.11593198]
threshold 0.08498816897513024


ic| label_current_deforestation_test_classified_incorrect.shape: (1624292,)
    predicted_test_classified_incorrect.shape: (1624292,)
ic| TP_H + FN_H + FP_H + TN_H: 1624292
    len(label_mask_current_deforestation_test): 54145132
ic| TP_H + FN_H + FP_H + TN_H: 1624292
    len(label_mask_current_deforestation_test): 54145132


[0.98837792 0.93844698 0.51460623 0.02999886 0.72729591 0.67762473
 0.11591518]
threshold 0.08498816897513024
(54145132,) (54145132,)


ic| self.m_optimal: {'AA': array([0.02999886]),
                     'UEO': array([0.11591518]),
                     'f1': 84.54,
                     'f1_H': array([0.70158226]),
                     'f1_L': array([0.9627655]),
                     'precision_H': array([0.72729591]),
                     'precision_L': array([0.98837792]),
                     'recall_H': array([0.67762473]),
                     'recall_L': array([0.93844698]),
                     'recall_Ltotal': array([0.51460623])}
ic| self.m_audited_optimal: {'f1': array([0.97981831]),
                             'precision': array([0.99377647]),
                             'recall': array([0.96624682])}


cm_audited [[53404450     4455]
 [   24850   711377]]
[0.99377647 0.96624682]
Result idx 0: {'other_uncertainty_metrics': {'sUEO': 0.841080483916035, 'ece_score': 0.004285987396271022}, 'uncertainty_result': {'metrics': {'precision_L': array([0.98837792]), 'recall_L': array([0.93844698]), 'recall_Ltotal': array([0.51460623]), 'AA': array([0.02999886]), 'precision_H': array([0.72729591]), 'recall_H': array([0.67762473]), 'UEO': array([0.11591518]), 'f1_L': array([0.9627655]), 'f1_H': array([0.70158226]), 'f1': 84.54}, 'metrics_audited': {'precision': array([0.99377647]), 'recall': array([0.96624682]), 'f1': array([0.97981831])}, 'exp': 103}}
Grid execution idx: 0
Grid execution idx: 1
Beginning run number 1
trainer.config {'training': False, 'inferring': True, 'site': 'PA', 'training_date': 'current', 'mode': 'single_run', 'learning_rate': 0.0001, 'weights': [0.1, 0.9, 0], 'save_probabilities': False, 'loadInference': False, 'addPastDeforestationInput': True, 'Uncertainty': {}, 'uncerta

ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Label where deforestation past years is actual date (2019) = 1


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation different from 0 (no deforestation)


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation before 2008 is 2
D:/Jorge/datasets/deforestation/deforestation_before_2008/deforestation_before_2008_para.tif


ic| np.unique(label_past_deforestation_before_2008, return_counts=True): (array([  0, 215], dtype=uint8), array([124211220,  38957970], dtype=int64))
ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))
ic| label_per_date.shape: (17730, 9203, 1)


Removing bufer................
Mask label shape:  
 (17730, 9203, 1) 
 Unique values:  
 [0 1 2]
Tiles size:  3546 2300
Mask size:  (17730, 9200)


ic| image_stack.shape: (17730, 9203, 21)


Image shape:  (17730, 9203, 21)
mask:  (17730, 9200)
image stack:  (17730, 9200, 21)
ref : (17730, 9200, 1)
Training tiles:  [1, 3, 5, 8, 11, 13, 14, 20]
Validation tiles:  [6, 19]
Test tiles:  [2, 4, 7, 9, 10, 12, 15, 16, 17, 18]
-30.0 -16.0


ic| self.path_models+ '/' + self.method +'_'+str(0)+'.h5': 'D:/Jorge/datasets/deforestation/experiments/exp104/models/resunet_0.h5'


Dropout training mode: False
time:  0
(54236371,)
(array([0, 1], dtype=uint8), array([53470765,   765606], dtype=int64))
(17730, 9200)
Single entropy
(array([0., 1.], dtype=float32), array([160910243,   2205757], dtype=int64))


ic| self.predicted_unpad.shape: (17730, 9200)
    self.predicted.shape: (17730, 9200)
ic| predicted_test.shape: (81558000,)
ic| predicted_test.shape: (54236371,)
ic| np.unique(predicted, return_counts=True): (array([0., 1.], dtype=float32), array([161018218,   2097782], dtype=int64))
    np.unique(predicted_larger_than_min_area, return_counts=True): (array([0., 1.], dtype=float32), array([161237653,   1878347], dtype=int64))
ic| np.unique(ignored_polygons, return_counts=True): (array([0., 1.], dtype=float32), array([162896565,    219435], dtype=int64))
ic| self.f1: 81.95, self.precision: 80.33, self.recall: 83.63
ic| self.label_mask_val.shape: (16311600,)
ic| self.label_mask_val_valid.shape: (9423838,)
ic| f1_val: 85.56
    precision_val: 80.7
    recall_val: 91.04
    mAP_val: 85.46


D:/Jorge/datasets/deforestation/PA/deforestation_past_years.tif
Loaded deforestation past years


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Label where deforestation past years is actual date (2019) = 1


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation different from 0 (no deforestation)


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation before 2008 is 2
D:/Jorge/datasets/deforestation/deforestation_before_2008/deforestation_before_2008_para.tif


ic| np.unique(label_past_deforestation_before_2008, return_counts=True): (array([  0, 215], dtype=uint8), array([124211220,  38957970], dtype=int64))
ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))
ic| label_per_date.shape: (17730, 9203, 1)


(array([0., 1.], dtype=float32), array([162438489,    677511], dtype=int64))
[0. 1.]


ic| pred_entropy.shape: (17760, 9216)
ic| self.label_mask.shape: (17730, 9200)
ic| self.mask_amazon_ts.shape: (17730, 9200)
ic| self.label_mask_test.shape: (81558000,)
ic| self.error_mask_test.shape: (54127510,)
ic| trainer.dataset.previewLims1: array([2200, 3200, 6900, 7900])
    trainer.dataset.previewLims2: array([ 500, 1500, 3500, 4500])
ic| np.unique(trainer.mask_amazon_ts[lims[0]:lims[1], lims[2]:lims[3]]): array([1], dtype=uint8)
ic| np.unique(trainer.mask_amazon_ts[lims[0]:lims[1], lims[2]:lims[3]], return_counts=True): (array([1], dtype=uint8), array([1000000], dtype=int64))
Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).
Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).
Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).


(54127510,) (54127510,)
0.8141570958729208
ECE. Starting bin 0...
ECE. Starting bin 1...
ECE. Starting bin 2...
ECE. Starting bin 3...
ECE. Starting bin 4...
ECE. Starting bin 5...
ECE. Starting bin 6...
ECE. Starting bin 7...
ECE. Starting bin 8...
ECE. Starting bin 9...


ic| bounds: (0.0015, 0.3663794801235199)


0.0053843853543005735
0.1408715596097929
threshold 0.1408715596097929


c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\scipy\optimize\_minimize.py:783: RuntimeWarning: Method 'bounded' does not support relative tolerance in x; defaulting to absolute tolerance.
  warn("Method 'bounded' does not support relative tolerance in x; "
ic| label_current_deforestation_test_classified_incorrect.shape: (1593153,)
    predicted_test_classified_incorrect.shape: (1593153,)
ic| TP_H + FN_H + FP_H + TN_H: 1593153
    len(label_mask_current_deforestation_test): 54127510
ic| TP_H + FN_H + FP_H + TN_H: 1593153
    len(label_mask_current_deforestation_test): 54127510


[0.95145138 0.94738973 0.61278463 0.02943333 0.56295306 0.63292943
 0.13543126]
0.22700792051372695
threshold 0.22700792051372695


ic| label_current_deforestation_test_classified_incorrect.shape: (1051381,)
    predicted_test_classified_incorrect.shape: (1051381,)
ic| TP_H + FN_H + FP_H + TN_H: 1051381
    len(label_mask_current_deforestation_test): 54127510
ic| TP_H + FN_H + FP_H + TN_H: 1051381
    len(label_mask_current_deforestation_test): 54127510


[0.89546155 0.93849393 0.72554129 0.01942415 0.47980243 0.48823717
 0.1507989 ]
0.08763636090393405
threshold 0.08763636090393405


ic| label_current_deforestation_test_classified_incorrect.shape: (2058173,)
    predicted_test_classified_incorrect.shape: (2058173,)
ic| TP_H + FN_H + FP_H + TN_H: 2058173
    len(label_mask_current_deforestation_test): 54127510
ic| TP_H + FN_H + FP_H + TN_H: 2058173
    len(label_mask_current_deforestation_test): 54127510


[0.97683317 0.94992008 0.50671536 0.03802453 0.63094616 0.70645544
 0.115845  ]
0.15234481420637816
threshold 0.15234481420637816


ic| label_current_deforestation_test_classified_incorrect.shape: (1510921,)
    predicted_test_classified_incorrect.shape: (1510921,)
ic| TP_H + FN_H + FP_H + TN_H: 1510921
    len(label_mask_current_deforestation_test): 54127510
ic| TP_H + FN_H + FP_H + TN_H: 1510921
    len(label_mask_current_deforestation_test): 54127510


[0.94495177 0.94643021 0.63130251 0.02791411 0.54957179 0.61575368
 0.13871356]
0.13088686765562862
threshold 0.13088686765562862


ic| label_current_deforestation_test_classified_incorrect.shape: (1667986,)
    predicted_test_classified_incorrect.shape: (1667986,)
ic| TP_H + FN_H + FP_H + TN_H: 1667986
    len(label_mask_current_deforestation_test): 54127510
ic| TP_H + FN_H + FP_H + TN_H: 1667986
    len(label_mask_current_deforestation_test): 54127510


[0.95688632 0.94803772 0.59608524 0.03081586 0.57446795 0.64712691
 0.13231485]
0.13758073275823626
threshold 0.13758073275823626


ic| label_current_deforestation_test_classified_incorrect.shape: (1617412,)
    predicted_test_classified_incorrect.shape: (1617412,)
ic| TP_H + FN_H + FP_H + TN_H: 1617412
    len(label_mask_current_deforestation_test): 54127510
ic| TP_H + FN_H + FP_H + TN_H: 1617412
    len(label_mask_current_deforestation_test): 54127510


[0.95325882 0.94761824 0.60736323 0.02988151 0.56674591 0.63766855
 0.13442842]
0.13639756732335104
threshold 0.13639756732335104


ic| label_current_deforestation_test_classified_incorrect.shape: (1626109,)
    predicted_test_classified_incorrect.shape: (1626109,)
ic| TP_H + FN_H + FP_H + TN_H: 1626109
    len(label_mask_current_deforestation_test): 54127510
ic| TP_H + FN_H + FP_H + TN_H: 1626109
    len(label_mask_current_deforestation_test): 54127510


[0.95388366 0.94768248 0.60535783 0.03004219 0.56816618 0.63940797
 0.13406166]
0.1349775634569797
threshold 0.1349775634569797


ic| label_current_deforestation_test_classified_incorrect.shape: (1636791,)
    predicted_test_classified_incorrect.shape: (1636791,)
ic| TP_H + FN_H + FP_H + TN_H: 1636791
    len(label_mask_current_deforestation_test): 54127510
ic| TP_H + FN_H + FP_H + TN_H: 1636791
    len(label_mask_current_deforestation_test): 54127510


[0.95472895 0.94777876 0.602995   0.03023954 0.56972263 0.64140719
 0.13363977]
0.13657663795587063
threshold 0.13657663795587063


ic| label_current_deforestation_test_classified_incorrect.shape: (1624767,)
    predicted_test_classified_incorrect.shape: (1624767,)
ic| TP_H + FN_H + FP_H + TN_H: 1624767
    len(label_mask_current_deforestation_test): 54127510
ic| TP_H + FN_H + FP_H + TN_H: 1624767
    len(label_mask_current_deforestation_test): 54127510


[0.95378914 0.94767524 0.60566478 0.0300174  0.56794859 0.63913995
 0.13411979]
0.13682962639606971
threshold 0.13682962639606971


ic| label_current_deforestation_test_classified_incorrect.shape: (1622950,)
    predicted_test_classified_incorrect.shape: (1622950,)
ic| TP_H + FN_H + FP_H + TN_H: 1622950
    len(label_mask_current_deforestation_test): 54127510
ic| TP_H + FN_H + FP_H + TN_H: 1622950
    len(label_mask_current_deforestation_test): 54127510


[0.95367582 0.94767086 0.60610542 0.02998383 0.56761484 0.63874716
 0.13420396]
0.13711652349725104
threshold 0.13711652349725104


ic| label_current_deforestation_test_classified_incorrect.shape: (1620845,)
    predicted_test_classified_incorrect.shape: (1620845,)
ic| TP_H + FN_H + FP_H + TN_H: 1620845
    len(label_mask_current_deforestation_test): 54127510
ic| TP_H + FN_H + FP_H + TN_H: 1620845
    len(label_mask_current_deforestation_test): 54127510


[0.95348837 0.94764806 0.60659244 0.02994494 0.56730325 0.63833336
 0.13427817]
0.13671097251628261
threshold 0.13671097251628261


ic| label_current_deforestation_test_classified_incorrect.shape: (1623823,)
    predicted_test_classified_incorrect.shape: (1623823,)
ic| TP_H + FN_H + FP_H + TN_H: 1623823
    len(label_mask_current_deforestation_test): 54127510
ic| TP_H + FN_H + FP_H + TN_H: 1623823
    len(label_mask_current_deforestation_test): 54127510


[0.95372597 0.9476741  0.60592261 0.02999996 0.56775046 0.63890854
 0.13416097]
0.13667763715519787
threshold 0.13667763715519787


ic| label_current_deforestation_test_classified_incorrect.shape: (1624046,)
    predicted_test_classified_incorrect.shape: (1624046,)
ic| TP_H + FN_H + FP_H + TN_H: 1624046
    len(label_mask_current_deforestation_test): 54127510
ic| TP_H + FN_H + FP_H + TN_H: 1624046
    len(label_mask_current_deforestation_test): 54127510


[0.95373874 0.94766975 0.60584485 0.03000408 0.56781609 0.63898397
 0.13414985]
0.13674430787736735
threshold 0.13674430787736735


ic| label_current_deforestation_test_classified_incorrect.shape: (1623590,)
    predicted_test_classified_incorrect.shape: (1623590,)
ic| TP_H + FN_H + FP_H + TN_H: 1623590
    len(label_mask_current_deforestation_test): 54127510
ic| TP_H + FN_H + FP_H + TN_H: 1623590
    len(label_mask_current_deforestation_test): 54127510
ic| self.threshold_optimal: 0.13671097251628261


[0.95370828 0.94767116 0.60596081 0.02999565 0.56772886 0.63887754
 0.13417086]
threshold 0.13671097251628261


ic| label_current_deforestation_test_classified_incorrect.shape: (1623823,)
    predicted_test_classified_incorrect.shape: (1623823,)
ic| TP_H + FN_H + FP_H + TN_H: 1623823
    len(label_mask_current_deforestation_test): 54127510
ic| TP_H + FN_H + FP_H + TN_H: 1623823
    len(label_mask_current_deforestation_test): 54127510


[0.95372597 0.9476741  0.60592261 0.02999996 0.56775046 0.63890854
 0.13416097]
threshold 0.13671097251628261
(54127510,) (54127510,)


ic| self.m_optimal: {'AA': array([0.02999996]),
                     'UEO': array([0.13416097]),
                     'f1': 81.95,
                     'f1_H': array([0.60123136]),
                     'f1_L': array([0.9506904]),
                     'precision_H': array([0.56775046]),
                     'precision_L': array([0.95372597]),
                     'recall_H': array([0.63890854]),
                     'recall_L': array([0.9476741]),
                     'recall_Ltotal': array([0.60592261])}
ic| self.m_audited_optimal: {'f1': array([0.96850864]),
                             'precision': array([0.97048135]),
                             'recall': array([0.96654393])}


cm_audited [[53372939    21550]
 [   24524   708497]]
[0.97048135 0.96654393]
Result idx 1: {'other_uncertainty_metrics': {'sUEO': 0.8141570958729208, 'ece_score': 0.0053843853543005735}, 'uncertainty_result': {'metrics': {'precision_L': array([0.95372597]), 'recall_L': array([0.9476741]), 'recall_Ltotal': array([0.60592261]), 'AA': array([0.02999996]), 'precision_H': array([0.56775046]), 'recall_H': array([0.63890854]), 'UEO': array([0.13416097]), 'f1_L': array([0.9506904]), 'f1_H': array([0.60123136]), 'f1': 81.95}, 'metrics_audited': {'precision': array([0.97048135]), 'recall': array([0.96654393]), 'f1': array([0.96850864])}, 'exp': 104}}
Grid execution idx: 1
Grid execution idx: 2
Beginning run number 2
trainer.config {'training': False, 'inferring': True, 'site': 'PA', 'training_date': 'current', 'mode': 'single_run', 'learning_rate': 0.0001, 'weights': [0.1, 0.9, 0], 'save_probabilities': False, 'loadInference': False, 'addPastDeforestationInput': True, 'Uncertainty': {}, 'uncert

ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Label where deforestation past years is actual date (2019) = 1


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation different from 0 (no deforestation)


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation before 2008 is 2
D:/Jorge/datasets/deforestation/deforestation_before_2008/deforestation_before_2008_para.tif


ic| np.unique(label_past_deforestation_before_2008, return_counts=True): (array([  0, 215], dtype=uint8), array([124211220,  38957970], dtype=int64))
ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))
ic| label_per_date.shape: (17730, 9203, 1)


Removing bufer................
Mask label shape:  
 (17730, 9203, 1) 
 Unique values:  
 [0 1 2]
Tiles size:  3546 2300
Mask size:  (17730, 9200)


ic| image_stack.shape: (17730, 9203, 21)


Image shape:  (17730, 9203, 21)
mask:  (17730, 9200)
image stack:  (17730, 9200, 21)
ref : (17730, 9200, 1)
Training tiles:  [1, 3, 5, 8, 11, 13, 14, 20]
Validation tiles:  [6, 19]
Test tiles:  [2, 4, 7, 9, 10, 12, 15, 16, 17, 18]
-30.0 -16.0


ic| self.path_models+ '/' + self.method +'_'+str(0)+'.h5': 'D:/Jorge/datasets/deforestation/experiments/exp105/models/resunet_0.h5'


Dropout training mode: False
time:  0
(54236371,)
(array([0, 1], dtype=uint8), array([53470765,   765606], dtype=int64))
(17730, 9200)
Single entropy
(array([0., 1.], dtype=float32), array([160969212,   2146788], dtype=int64))


ic| self.predicted_unpad.shape: (17730, 9200)
    self.predicted.shape: (17730, 9200)
ic| predicted_test.shape: (81558000,)
ic| predicted_test.shape: (54236371,)
ic| np.unique(predicted, return_counts=True): (array([0., 1.], dtype=float32), array([161086764,   2029236], dtype=int64))
    np.unique(predicted_larger_than_min_area, return_counts=True): (array([0., 1.], dtype=float32), array([161306413,   1809587], dtype=int64))
ic| np.unique(ignored_polygons, return_counts=True): (array([0., 1.], dtype=float32), array([162896351,    219649], dtype=int64))
ic| self.f1: 86.02, self.precision: 86.88, self.recall: 85.18
ic| self.label_mask_val.shape: (16311600,)
ic| self.label_mask_val_valid.shape: (9426726,)
ic| f1_val: 87.15
    precision_val: 83.58
    recall_val: 91.03
    mAP_val: 90.11


D:/Jorge/datasets/deforestation/PA/deforestation_past_years.tif
Loaded deforestation past years


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Label where deforestation past years is actual date (2019) = 1


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation different from 0 (no deforestation)


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation before 2008 is 2
D:/Jorge/datasets/deforestation/deforestation_before_2008/deforestation_before_2008_para.tif


ic| np.unique(label_past_deforestation_before_2008, return_counts=True): (array([  0, 215], dtype=uint8), array([124211220,  38957970], dtype=int64))
ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))
ic| label_per_date.shape: (17730, 9203, 1)


(array([0., 1.], dtype=float32), array([162579301,    536699], dtype=int64))
[0. 1.]


ic| pred_entropy.shape: (17760, 9216)
ic| self.label_mask.shape: (17730, 9200)
ic| self.mask_amazon_ts.shape: (17730, 9200)
ic| self.label_mask_test.shape: (81558000,)
ic| self.error_mask_test.shape: (54124102,)
ic| trainer.dataset.previewLims1: array([2200, 3200, 6900, 7900])
    trainer.dataset.previewLims2: array([ 500, 1500, 3500, 4500])
ic| np.unique(trainer.mask_amazon_ts[lims[0]:lims[1], lims[2]:lims[3]]): array([1], dtype=uint8)
ic| np.unique(trainer.mask_amazon_ts[lims[0]:lims[1], lims[2]:lims[3]], return_counts=True): (array([1], dtype=uint8), array([1000000], dtype=int64))
Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).
Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).
Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).


(54124102,) (54124102,)
0.8569092307938756
ECE. Starting bin 0...
ECE. Starting bin 1...
ECE. Starting bin 2...
ECE. Starting bin 3...
ECE. Starting bin 4...
ECE. Starting bin 5...
ECE. Starting bin 6...
ECE. Starting bin 7...
ECE. Starting bin 8...
ECE. Starting bin 9...


ic| bounds: (0.0015, 0.3663794801235199)


0.003562886009663188
0.1408715596097929
threshold 0.1408715596097929


c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\scipy\optimize\_minimize.py:783: RuntimeWarning: Method 'bounded' does not support relative tolerance in x; defaulting to absolute tolerance.
  warn("Method 'bounded' does not support relative tolerance in x; "
ic| label_current_deforestation_test_classified_incorrect.shape: (1054094,)
    predicted_test_classified_incorrect.shape: (1054094,)
ic| TP_H + FN_H + FP_H + TN_H: 1054094
    len(label_mask_current_deforestation_test): 54124102
ic| TP_H + FN_H + FP_H + TN_H: 1054094
    len(label_mask_current_deforestation_test): 54124102


[0.95497173 0.94746587 0.68887556 0.0194755  0.62896214 0.59711311
 0.13729292]
0.22700792051372695
threshold 0.22700792051372695


ic| label_current_deforestation_test_classified_incorrect.shape: (695674,)
    predicted_test_classified_incorrect.shape: (695674,)
ic| TP_H + FN_H + FP_H + TN_H: 695674
    len(label_mask_current_deforestation_test): 54124102
ic| TP_H + FN_H + FP_H + TN_H: 695674
    len(label_mask_current_deforestation_test): 54124102


[0.91866566 0.93898329 0.76871467 0.01285331 0.57852933 0.45843842
 0.14948367]
0.08763636090393405
threshold 0.08763636090393405


ic| label_current_deforestation_test_classified_incorrect.shape: (1403735,)
    predicted_test_classified_incorrect.shape: (1403735,)
ic| TP_H + FN_H + FP_H + TN_H: 1403735
    len(label_mask_current_deforestation_test): 54124102
ic| TP_H + FN_H + FP_H + TN_H: 1403735
    len(label_mask_current_deforestation_test): 54124102


[0.97795257 0.95142097 0.6057442  0.02593549 0.68159677 0.67735285
 0.11909948]
0.05473519870585886
threshold 0.05473519870585886


ic| label_current_deforestation_test_classified_incorrect.shape: (1764071,)
    predicted_test_classified_incorrect.shape: (1764071,)
ic| TP_H + FN_H + FP_H + TN_H: 1764071
    len(label_mask_current_deforestation_test): 54124102
ic| TP_H + FN_H + FP_H + TN_H: 1764071
    len(label_mask_current_deforestation_test): 54124102


[0.98996536 0.95130444 0.50647322 0.03259308 0.73662274 0.73860236
 0.10132527]
0.04604867810963195
threshold 0.04604867810963195


ic| label_current_deforestation_test_classified_incorrect.shape: (1900875,)
    predicted_test_classified_incorrect.shape: (1900875,)
ic| TP_H + FN_H + FP_H + TN_H: 1900875
    len(label_mask_current_deforestation_test): 54124102
ic| TP_H + FN_H + FP_H + TN_H: 1900875
    len(label_mask_current_deforestation_test): 54124102


[0.99250904 0.94995554 0.46533231 0.03512068 0.75546679 0.7576392
 0.09539236]
0.06841558457390301
threshold 0.06841558457390301


ic| label_current_deforestation_test_classified_incorrect.shape: (1591977,)
    predicted_test_classified_incorrect.shape: (1591977,)
ic| TP_H + FN_H + FP_H + TN_H: 1591977
    len(label_mask_current_deforestation_test): 54124102
ic| TP_H + FN_H + FP_H + TN_H: 1591977
    len(label_mask_current_deforestation_test): 54124102


[0.9854154  0.95190512 0.5553725  0.02941346 0.7111815  0.71170279
 0.10948032]
0.0689401420404715
threshold 0.0689401420404715


ic| label_current_deforestation_test_classified_incorrect.shape: (1586260,)
    predicted_test_classified_incorrect.shape: (1586260,)
ic| TP_H + FN_H + FP_H + TN_H: 1586260
    len(label_mask_current_deforestation_test): 54124102
ic| TP_H + FN_H + FP_H + TN_H: 1586260
    len(label_mask_current_deforestation_test): 54124102


[0.9852424  0.95192274 0.55701048 0.02930783 0.71025343 0.71068789
 0.10976928]
0.0645685637043089
threshold 0.0645685637043089


ic| label_current_deforestation_test_classified_incorrect.shape: (1636212,)
    predicted_test_classified_incorrect.shape: (1636212,)
ic| TP_H + FN_H + FP_H + TN_H: 1636212
    len(label_mask_current_deforestation_test): 54124102
ic| TP_H + FN_H + FP_H + TN_H: 1636212
    len(label_mask_current_deforestation_test): 54124102


[0.98668073 0.95185889 0.54316702 0.03023075 0.71791222 0.71892196
 0.10729256]
0.06463538360486197
threshold 0.06463538360486197


ic| label_current_deforestation_test_classified_incorrect.shape: (1635374,)
    predicted_test_classified_incorrect.shape: (1635374,)
ic| TP_H + FN_H + FP_H + TN_H: 1635374
    len(label_mask_current_deforestation_test): 54124102
ic| TP_H + FN_H + FP_H + TN_H: 1635374
    len(label_mask_current_deforestation_test): 54124102


[0.9866573  0.95186081 0.54340451 0.03021526 0.71778353 0.71878459
 0.10733336]
0.0659528722981361
threshold 0.0659528722981361


ic| label_current_deforestation_test_classified_incorrect.shape: (1619960,)
    predicted_test_classified_incorrect.shape: (1619960,)
ic| TP_H + FN_H + FP_H + TN_H: 1619960
    len(label_mask_current_deforestation_test): 54124102
ic| TP_H + FN_H + FP_H + TN_H: 1619960
    len(label_mask_current_deforestation_test): 54124102


[0.98624271 0.95188851 0.54762635 0.02993047 0.71547162 0.7163221
 0.10809698]
0.06591953798656358
threshold 0.06591953798656358


ic| label_current_deforestation_test_classified_incorrect.shape: (1620365,)
    predicted_test_classified_incorrect.shape: (1620365,)
ic| TP_H + FN_H + FP_H + TN_H: 1620365
    len(label_mask_current_deforestation_test): 54124102
ic| TP_H + FN_H + FP_H + TN_H: 1620365
    len(label_mask_current_deforestation_test): 54124102


[0.98624967 0.95188392 0.54751778 0.02993796 0.71553512 0.71639002
 0.10807442]
0.06550608231352673
threshold 0.06550608231352673


ic| label_current_deforestation_test_classified_incorrect.shape: (1625175,)
    predicted_test_classified_incorrect.shape: (1625175,)
ic| TP_H + FN_H + FP_H + TN_H: 1625175
    len(label_mask_current_deforestation_test): 54124102
ic| TP_H + FN_H + FP_H + TN_H: 1625175
    len(label_mask_current_deforestation_test): 54124102


[0.98638301 0.95188279 0.54626928 0.03002683 0.71621278 0.71711603
 0.10783608]
0.06517350500077743
threshold 0.06517350500077743


ic| label_current_deforestation_test_classified_incorrect.shape: (1629015,)
    predicted_test_classified_incorrect.shape: (1629015,)
ic| TP_H + FN_H + FP_H + TN_H: 1629015
    len(label_mask_current_deforestation_test): 54124102
ic| TP_H + FN_H + FP_H + TN_H: 1629015
    len(label_mask_current_deforestation_test): 54124102


[0.98647053 0.951872   0.54520127 0.03009777 0.7168145  0.71774347
 0.10764075]
0.0655762083707567
threshold 0.0655762083707567


ic| label_current_deforestation_test_classified_incorrect.shape: (1624352,)
    predicted_test_classified_incorrect.shape: (1624352,)
ic| TP_H + FN_H + FP_H + TN_H: 1624352
    len(label_mask_current_deforestation_test): 54124102
ic| TP_H + FN_H + FP_H + TN_H: 1624352
    len(label_mask_current_deforestation_test): 54124102


[0.98635925 0.95188039 0.54648234 0.03001162 0.71609834 0.71699508
 0.10787576]
0.06566439457501204
threshold 0.06566439457501204


ic| label_current_deforestation_test_classified_incorrect.shape: (1623320,)
    predicted_test_classified_incorrect.shape: (1623320,)
ic| TP_H + FN_H + FP_H + TN_H: 1623320
    len(label_mask_current_deforestation_test): 54124102
ic| TP_H + FN_H + FP_H + TN_H: 1623320
    len(label_mask_current_deforestation_test): 54124102


[0.9863345  0.95187378 0.5467524  0.02999255 0.71594807 0.71684523
 0.1079258 ]
0.06569772888230574
threshold 0.06569772888230574


ic| label_current_deforestation_test_classified_incorrect.shape: (1622954,)
    predicted_test_classified_incorrect.shape: (1622954,)
ic| TP_H + FN_H + FP_H + TN_H: 1622954
    len(label_mask_current_deforestation_test): 54124102
ic| TP_H + FN_H + FP_H + TN_H: 1622954
    len(label_mask_current_deforestation_test): 54124102


[0.98632464 0.95187454 0.54684196 0.02998579 0.71589975 0.71679248
 0.10794438]
0.06563106026771834
threshold 0.06563106026771834


ic| label_current_deforestation_test_classified_incorrect.shape: (1623688,)
    predicted_test_classified_incorrect.shape: (1623688,)
ic| TP_H + FN_H + FP_H + TN_H: 1623688
    len(label_mask_current_deforestation_test): 54124102
ic| TP_H + FN_H + FP_H + TN_H: 1623688
    len(label_mask_current_deforestation_test): 54124102
ic| self.threshold_optimal: 0.06563106026771834


[0.98634186 0.95187718 0.54665876 0.02999935 0.71600135 0.71689608
 0.10790777]
threshold 0.06563106026771834


ic| label_current_deforestation_test_classified_incorrect.shape: (1623688,)
    predicted_test_classified_incorrect.shape: (1623688,)
ic| TP_H + FN_H + FP_H + TN_H: 1623688
    len(label_mask_current_deforestation_test): 54124102
ic| TP_H + FN_H + FP_H + TN_H: 1623688
    len(label_mask_current_deforestation_test): 54124102


[0.98634186 0.95187718 0.54665876 0.02999935 0.71600135 0.71689608
 0.10790777]
threshold 0.06563106026771834
(54124102,) (54124102,)


ic| self.m_optimal: {'AA': array([0.02999935]),
                     'UEO': array([0.10790777]),
                     'f1': 86.02,
                     'f1_H': array([0.71644844]),
                     'f1_L': array([0.9688031]),
                     'precision_H': array([0.71600135]),
                     'precision_L': array([0.98634186]),
                     'recall_H': array([0.71689608]),
                     'recall_L': array([0.95187718]),
                     'recall_Ltotal': array([0.54665876])}
ic| self.m_audited_optimal: {'f1': array([0.98221836]),
                             'precision': array([0.99227525]),
                             'recall': array([0.97236328])}


cm_audited [[53381642     5578]
 [   20365   716517]]
[0.99227525 0.97236328]
Result idx 2: {'other_uncertainty_metrics': {'sUEO': 0.8569092307938756, 'ece_score': 0.003562886009663188}, 'uncertainty_result': {'metrics': {'precision_L': array([0.98634186]), 'recall_L': array([0.95187718]), 'recall_Ltotal': array([0.54665876]), 'AA': array([0.02999935]), 'precision_H': array([0.71600135]), 'recall_H': array([0.71689608]), 'UEO': array([0.10790777]), 'f1_L': array([0.9688031]), 'f1_H': array([0.71644844]), 'f1': 86.02}, 'metrics_audited': {'precision': array([0.99227525]), 'recall': array([0.97236328]), 'f1': array([0.98221836])}, 'exp': 105}}
Grid execution idx: 2
Grid execution idx: 3
Beginning run number 3
trainer.config {'training': False, 'inferring': True, 'site': 'PA', 'training_date': 'current', 'mode': 'single_run', 'learning_rate': 0.0001, 'weights': [0.1, 0.9, 0], 'save_probabilities': False, 'loadInference': False, 'addPastDeforestationInput': True, 'Uncertainty': {}, 'uncert

ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Label where deforestation past years is actual date (2019) = 1


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation different from 0 (no deforestation)


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation before 2008 is 2
D:/Jorge/datasets/deforestation/deforestation_before_2008/deforestation_before_2008_para.tif


ic| np.unique(label_past_deforestation_before_2008, return_counts=True): (array([  0, 215], dtype=uint8), array([124211220,  38957970], dtype=int64))
ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))
ic| label_per_date.shape: (17730, 9203, 1)


Removing bufer................
Mask label shape:  
 (17730, 9203, 1) 
 Unique values:  
 [0 1 2]
Tiles size:  3546 2300
Mask size:  (17730, 9200)


ic| image_stack.shape: (17730, 9203, 21)


Image shape:  (17730, 9203, 21)
mask:  (17730, 9200)
image stack:  (17730, 9200, 21)
ref : (17730, 9200, 1)
Training tiles:  [1, 3, 5, 8, 11, 13, 14, 20]
Validation tiles:  [6, 19]
Test tiles:  [2, 4, 7, 9, 10, 12, 15, 16, 17, 18]
-30.0 -16.0


ic| self.path_models+ '/' + self.method +'_'+str(0)+'.h5': 'D:/Jorge/datasets/deforestation/experiments/exp106/models/resunet_0.h5'


Dropout training mode: False
time:  0
(54236371,)
(array([0, 1], dtype=uint8), array([53470765,   765606], dtype=int64))
(17730, 9200)
Single entropy
(array([0., 1.], dtype=float32), array([161053226,   2062774], dtype=int64))


ic| self.predicted_unpad.shape: (17730, 9200)
    self.predicted.shape: (17730, 9200)
ic| predicted_test.shape: (81558000,)
ic| predicted_test.shape: (54236371,)
ic| np.unique(predicted, return_counts=True): (array([0., 1.], dtype=float32), array([161159400,   1956600], dtype=int64))
    np.unique(predicted_larger_than_min_area, return_counts=True): (array([0., 1.], dtype=float32), array([161359279,   1756721], dtype=int64))
ic| np.unique(ignored_polygons, return_counts=True): (array([0., 1.], dtype=float32), array([162916121,    199879], dtype=int64))
ic| self.f1: 85.33, self.precision: 87.15, self.recall: 83.59
ic| self.label_mask_val.shape: (16311600,)
ic| self.label_mask_val_valid.shape: (9430852,)
ic| f1_val: 86.34
    precision_val: 82.67
    recall_val: 90.35
    mAP_val: 92.91


D:/Jorge/datasets/deforestation/PA/deforestation_past_years.tif
Loaded deforestation past years


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Label where deforestation past years is actual date (2019) = 1


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation different from 0 (no deforestation)


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation before 2008 is 2
D:/Jorge/datasets/deforestation/deforestation_before_2008/deforestation_before_2008_para.tif


ic| np.unique(label_past_deforestation_before_2008, return_counts=True): (array([  0, 215], dtype=uint8), array([124211220,  38957970], dtype=int64))
ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))
ic| label_per_date.shape: (17730, 9203, 1)


(array([0., 1.], dtype=float32), array([162534673,    581327], dtype=int64))
[0. 1.]


ic| pred_entropy.shape: (17760, 9216)
ic| self.label_mask.shape: (17730, 9200)
ic| self.mask_amazon_ts.shape: (17730, 9200)
ic| self.label_mask_test.shape: (81558000,)
ic| self.error_mask_test.shape: (54135604,)
ic| trainer.dataset.previewLims1: array([2200, 3200, 6900, 7900])
    trainer.dataset.previewLims2: array([ 500, 1500, 3500, 4500])
ic| np.unique(trainer.mask_amazon_ts[lims[0]:lims[1], lims[2]:lims[3]]): array([1], dtype=uint8)
ic| np.unique(trainer.mask_amazon_ts[lims[0]:lims[1], lims[2]:lims[3]], return_counts=True): (array([1], dtype=uint8), array([1000000], dtype=int64))
Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).
Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).
Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).


(54135604,) (54135604,)
0.8275843097139371
ECE. Starting bin 0...
ECE. Starting bin 1...
ECE. Starting bin 2...
ECE. Starting bin 3...
ECE. Starting bin 4...


In [ ]:
error_count

0

In [ ]:
print(results)

[{'other_uncertainty_metrics': {'sUEO': 0.7995724287077376, 'ece_score': 0.004703061421809009}, 'uncertainty_result': {'metrics': {'precision_L': array([0.75129831]), 'recall_L': array([0.97057467]), 'recall_Ltotal': array([0.61832539]), 'AA': array([0.02999947]), 'precision_H': array([0.65686753]), 'recall_H': array([0.67027312]), 'UEO': array([0.13832113]), 'f1_L': array([0.84697433]), 'f1_H': array([0.66350262]), 'f1': 78.56}, 'metrics_audited': {'precision': array([0.82740766]), 'recall': array([0.98125396]), 'f1': array([0.89778766])}, 'exp': 108}}, {'other_uncertainty_metrics': {'sUEO': 0.8040191984323906, 'ece_score': 0.004066924262362896}, 'uncertainty_result': {'metrics': {'precision_L': array([0.80184449]), 'recall_L': array([0.9597654]), 'recall_Ltotal': array([0.66484832]), 'AA': array([0.02999988]), 'precision_H': array([0.54334729]), 'recall_H': array([0.61293739]), 'UEO': array([0.15867725]), 'f1_L': array([0.87372647]), 'f1_H': array([0.57604823]), 'f1': 78.43}, 'metric

In [ ]:
print(len(results))

10


In [ ]:
results[0]

{'other_uncertainty_metrics': {'sUEO': 0.7995724287077376,
  'ece_score': 0.004703061421809009},
 'uncertainty_result': {'metrics': {'precision_L': array([0.75129831]),
   'recall_L': array([0.97057467]),
   'recall_Ltotal': array([0.61832539]),
   'AA': array([0.02999947]),
   'precision_H': array([0.65686753]),
   'recall_H': array([0.67027312]),
   'UEO': array([0.13832113]),
   'f1_L': array([0.84697433]),
   'f1_H': array([0.66350262]),
   'f1': 78.56},
  'metrics_audited': {'precision': array([0.82740766]),
   'recall': array([0.98125396]),
   'f1': array([0.89778766])},
  'exp': 108}}

In [ ]:
manager.f1

81.35

In [ ]:
print(manager.f1)

81.35
