In [1]:
from utils_v1 import *


In [2]:
from icecream import ic

import numpy as np
from src.dataset import (
    MultipleDates,
    PA, PADeforestationTime, PADistanceMap, PAMultipleDates,
    MTDeforestationTime,
    MTMultipleDates
)

# from src.dataset_legacy import MTDeforestationTime
from src import training_generator as generator
from src.patchesHandler import PatchesHandler, PatchesHandlerMultipleDates, PatchesHandlerEvidential

from src.trainer.evidential import TrainerEvidential

from mpl_toolkits.axes_grid1 import make_axes_locatable

import cv2
from src import metrics as _metric
import json
import pickle 



In [3]:

config = {
	"training": False,
	"save_probabilities": False,
	"loadInference": False,
	"addPastDeforestationInput": True,
	"inference_times": 1,
	"Uncertainty": {
		"annealing_step": 10*375/2 # 1875
	}
}




'''
if config["training"] == True:
	dates = [2017, 2018]
else:
	dates = [2018, 2019]
if config["training"] == True:
	dates = [2018, 2019]
else:
	dates = [2019, 2020]
'''
dates = [2018, 2019]
ic(dates)
dataset = PAMultipleDates(dates = dates, # dates = [2017, 2018, 2019]. [2018, 2019]. [2015, 2016, 2017, 2018]
	addPastDeforestationInput = config['addPastDeforestationInput'],
	borderBuffer = 2)	
# dataset = MTMultipleDates(dates = dates, # dates = [2016,2017,2018,2019]
# 	addPastDeforestationInput = addPastDeforestationInput,
# 	borderBuffer = 2)	
# dataset = MTDeforestationTime()	
# [2016, 2017, 2018]


if issubclass(type(dataset), MultipleDates):
	patchesHandler = PatchesHandlerEvidential(
		dataset)
else:
	patchesHandler = PatchesHandler()



ic| dates: [2018, 2019]
ic| list(self.date_ids): [0]
ic| self.image_channels: [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]]
ic| self.input_image_shape: 21
ic| self.dataset.image_channels: [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]]


In [4]:
[10*375//1, 10*375//1.5, 10*375//2, 10*375//3, 10*375//4]


[3750, 2500.0, 1875, 1250, 937]

In [ ]:
# if config["training"] == True:
# experiment_values = [10*375//1, 10*375//1.5, 10*375//2, 10*375//3, 10*375//4]
# experiment_values = [10*375//3, 10*375//3, 10*375//3, 10*375//3, 10*375//3]
# experiment_values = [10*375//2, 10*375//2, 10*375//2, 10*375//2, 10*375//2, 10*375//2, 10*375//2]
experiment_values = [10*375, 10*375, 10*375, 10*375, 10*375, 10*375, 10*375, 10*375, 10*375, 10*375]

experiment_values = [int(x) for x in experiment_values]
results = []

#exp_id_base = 148
# exp_id_base = 155
exp_id_base = 159


exp_ids = range(exp_id_base, exp_id_base+len(experiment_values))


In [ ]:
exp_ids

In [5]:


for experiment_value, exp_id in zip(experiment_values, exp_ids):
    config = {
        "training": True,
        "save_probabilities": False,
        "loadInference": False,
        "addPastDeforestationInput": True,
        "inference_times": 1,
        "Uncertainty": {
            "annealing_step": experiment_value# 10*375/2 # 1875
        }
    }

    trainer = TrainerEvidential(config, dataset, patchesHandler)

    trainer.defineExperiment(exp_id)

    trainer.setExperimentPath()
    trainer.createLogFolders()

    trainer.loadDataset()

    # %%
    if config["training"] == True:
        trainer.run()

    # %%
    result = trainer.run_predictor()
    results.append(result)


    with open('log.pkl', 'wb') as f:
        pickle.dump(results, f)

D:/Jorge/datasets/deforestation/Para/deforestation_past_years.tif
Loaded deforestation past years


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Label where deforestation past years is actual date (2019) = 1


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation different from 0 (no deforestation)


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation before 2008 is 2
D:/Jorge/datasets/deforestation/deforestation_before_2008/deforestation_before_2008_para.tif


ic| np.unique(label_past_deforestation_before_2008, return_counts=True): (array([  0, 215], dtype=uint8), array([124211220,  38957970], dtype=int64))
ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))
ic| label_per_date.shape: (17730, 9203, 1)


Mask label shape:  
 (17730, 9203, 1) 
 Unique values:  
 [0 1 2]
Tiles size:  3546 2300
Mask size:  (17730, 9200)


ic| image_stack.shape: (17730, 9203, 21)


Image shape:  (17730, 9203, 21)
mask:  (17730, 9200)
image stack:  (17730, 9200, 21)
ref : (17730, 9200, 1)
Training tiles:  [1, 3, 5, 8, 11, 13, 14, 20]
Validation tiles:  [6, 19]
Test tiles:  [2, 4, 7, 9, 10, 12, 15, 16, 17, 18]


ic| im_idx_row.shape: (17730, 9200, 1)
    im_idx_col.shape: (17730, 9200, 1)
ic| im_idx_row.dtype: dtype('uint16')
    im_idx_col.dtype: dtype('uint16')
ic| im_idx.shape: (17730, 9200, 2), im_idx.dtype: dtype('uint16')
ic| coords.shape: (464, 239, 1, 128, 128, 2)
    coords.dtype: dtype('uint16')
ic| coords.shape: (110896, 2), coords.dtype: dtype('uint16')
ic| self.coords_train.shape: (41812, 3)
    self.coords_val.shape: (10260, 3)


training samples:  (3753, 3) validation samples:  (1032, 3)
time:  0
Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_enc_net (InputLayer)      [(None, 128, 128, 21 0                                            
__________________________________________________________________________________________________
res1_net1 (Conv2D)              (None, 128, 128, 16) 3040        input_enc_net[0][0]              
__________________________________________________________________________________________________
drop_net1 (Dropout)             (None, 128, 128, 16) 0           res1_net1[0][0]                  
__________________________________________________________________________________________________
res2_net1 (Conv2D)              (None, 128, 128, 16) 2320        drop_net1[0][0]                  
_________________________

c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\keras\optimizer_v2\optimizer_v2.py:374: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  warnings.warn(
c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\keras\engine\training.py:1969: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  warnings.warn('`Model.fit_generator` is deprecated and '


Epoch 1/100
self.global_step 0.0
alpha Tensor("loss/add:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("loss/truediv:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("add:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("truediv:0", shape=(None, 128, 128, 1), dtype=float32)
K.int_shape(KL_reg) Tensor("mul_6:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("add_7:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("truediv_5:0", shape=(None, 128, 128, 1), dtype=float32)
K.int_shape(KL_reg) Tensor("mul_12:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("loss/add:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("loss/truediv:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("add:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("truediv:0", shape=(None, 128, 128, 1), dtype=float32)
K.int_shape(KL_reg) Tensor("mul_6:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("add_7:0", shape=(None, 128, 128, 3), dtype=float

c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py:494: CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.
  warnings.warn('Custom mask layers require a config and must override '


351/351 [==============================] - 32s 90ms/step - loss: 0.1370 - accuracy: 0.9255 - KL_term: 0.0122 - loglikelihood_term: 0.1247 - evidential_success: 78.7712 - evidential_fail: 10.7019 - acc: 0.9255 - annealing_coef: 0.0933 - global_step_get: 350.0000 - annealing_step_get: 3750.0000 - val_loss: 0.1382 - val_accuracy: 0.9294 - val_KL_term: 0.0186 - val_loglikelihood_term: 0.1185 - val_evidential_success: 66.0699 - val_evidential_fail: 5.7938 - val_acc: 0.9300 - val_annealing_coef: 0.1867 - val_global_step_get: 700.0000 - val_annealing_step_get: 3750.0000

Epoch 00002: val_loss improved from 0.19177 to 0.13817, saving model to D:/Jorge/datasets/deforestation/experiments/exp155/models\resunet_0.h5
Epoch 3/100
self.global_step 700.0
351/351 [==============================] - 32s 90ms/step - loss: 0.1293 - accuracy: 0.9316 - KL_term: 0.0144 - loglikelihood_term: 0.1147 - evidential_success: 91.1030 - evidential_fail: 9.3434 - acc: 0.9317 - annealing_coef: 0.1400 - global_step_get:

ic| self.path_models+ '/' + self.method +'_'+str(0)+'.h5': 'D:/Jorge/datasets/deforestation/experiments/exp155/models/resunet_0.h5'


time:  0
(54236371,)
(array([0, 1], dtype=uint8), array([53470765,   765606], dtype=int64))
(17730, 9200)
(array([0., 1.], dtype=float32), array([161262430,   1853570], dtype=int64))


ic| self.predicted_unpad.shape: (17730, 9200)
    self.predicted.shape: (17730, 9200)
ic| predicted_test.shape: (81558000,)
ic| predicted_test.shape: (54236371,)
ic| np.unique(predicted, return_counts=True): (array([0., 1.], dtype=float32), array([161262430,   1853570], dtype=int64))
    np.unique(predicted_larger_than_min_area, return_counts=True): (array([0., 1.], dtype=float32), array([161469212,   1646788], dtype=int64))
ic| np.unique(ignored_polygons, return_counts=True): (array([0., 1.], dtype=float32), array([162909218,    206782], dtype=int64))
ic| self.f1: 84.63, self.precision: 90.32, self.recall: 79.61
ic| self.label_mask_val.shape: (16311600,)
ic| self.label_mask_val_valid.shape: (9430457,)
ic| f1_val: 87.48
    precision_val: 85.74
    recall_val: 89.3
    mAP_val: 91.66


(array([0., 1.], dtype=float32), array([162499084,    616916], dtype=int64))


ic| self.label_mask.shape: (17730, 9200)
ic| self.mask_amazon_ts.shape: (17730, 9200)
ic| self.label_mask_test.shape: (81558000,)
ic| self.error_mask_test.shape: (54132127,)
ic| bounds: (0.0015, 0.9985)
c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\scipy\optimize\_minimize.py:783: RuntimeWarning: Method 'bounded' does not support relative tolerance in x; defaulting to absolute tolerance.
  warn("Method 'bounded' does not support relative tolerance in x; "


0.38232011321635484
threshold 0.38232011321635484
(52672094,) (52672094,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1460033,)
    predicted_test_classified_incorrect.shape: (1460033,)
ic| TP_H + FN_H + FP_H

cm_correct [[52103219    26811]
 [   42653   499411]]
cm_incorrect [[1233161   35730]
 [ 106827   84315]]


 + TN_H: 1460033
    len(label_mask_current_deforestation_test): 54132127
ic| TP_H + FN_H + FP_H + TN_H: 1460033
    len(label_mask_current_deforestation_test): 54132127


[0.94905002 0.92131372 0.68113327 0.02697165 0.70236161 0.44111184]
0.6176798867836452
threshold 0.6176798867836452
(53841259,) (53841259,)


ic| label_current_deforestation_test_classified_incorrect.shape: (290868,)
    predicted_test_classified_incorrect.shape: (290868,)
ic| TP_H + FN_H + FP_H + TN_H: 290868
    len(label_mask_current_deforestation_test): 54132127
ic| TP_H + FN_H + FP_H + TN_H: 290868
    len(label_mask_current_deforestation_test): 54132127


cm_correct [[53120440    53963]
 [   99301   567555]]
cm_incorrect [[215940   8578]
 [ 50179  16171]]
[0.91317548 0.85109079 0.77407304 0.0053733  0.65340014 0.24372268]
0.23685977356729035
threshold 0.23685977356729035
(51395646,) (51395646,)


ic| label_current_deforestation_test_classified_incorrect.shape: (2736481,)
    predicted_test_classified_incorrect.shape: (2736481,)


cm_correct [[50940604    10880]
 [   26237   417925]]


ic| TP_H + FN_H + FP_H + TN_H: 2736481
    len(label_mask_current_deforestation_test): 54132127
ic| TP_H + FN_H + FP_H + TN_H: 2736481
    len(label_mask_current_deforestation_test): 54132127


cm_incorrect [[2395776   51661]
 [ 123243  165801]]
[0.97462716 0.94092921 0.5699967  0.05055188 0.76243666 0.57361855]
0.41767013676121123
threshold 0.41767013676121123
(52918263,) (52918263,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1213864,)
    predicted_test_classified_incorrect.shape: (1213864,)
ic| TP_H + FN_H + FP_H + TN_H: 1213864
    len(label_mask_current_deforestation_test): 54132127
ic| TP_H + FN_H + FP_H + TN_H: 1213864
    len(label_mask_current_deforestation_test): 54132127


cm_correct [[52329003    30707]
 [   47074   511479]]
cm_incorrect [[1007377   31834]
 [ 102406   72247]]
[0.94336445 0.91572152 0.69759249 0.0224241  0.69414206 0.41366023]
0.3533092952641373
threshold 0.3533092952641373
(52455688,) (52455688,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1676439,)
    predicted_test_classified_incorrect.shape: (1676439,)


cm_correct [[51904826    23536]
 [   39211   488115]]


ic| TP_H + FN_H + FP_H + TN_H: 1676439
    len(label_mask_current_deforestation_test): 54132127
ic| TP_H + FN_H + FP_H + TN_H: 1676439
    len(label_mask_current_deforestation_test): 54132127


cm_incorrect [[1431554   39005]
 [ 110269   95611]]
[0.95399989 0.92564182 0.66572696 0.03096939 0.7102499  0.46440159]
0.3088295359496101
threshold 0.3088295359496101
(52098475,) (52098475,)


ic| label_current_deforestation_test_classified_incorrect.shape: (2033652,)
    predicted_test_classified_incorrect.shape: (2033652,)


cm_correct [[51578245    18562]
 [   33860   467808]]


ic| TP_H + FN_H + FP_H + TN_H: 2033652
    len(label_mask_current_deforestation_test): 54132127
ic| TP_H + FN_H + FP_H + TN_H: 2033652
    len(label_mask_current_deforestation_test): 54132127


cm_incorrect [[1758135   43979]
 [ 115620  115918]]
[0.96183564 0.93250516 0.63803079 0.0375683  0.72495419 0.50064352]
0.3559244426172324
threshold 0.3559244426172324
(52475733,) (52475733,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1656394,)
    predicted_test_classified_incorrect.shape: (1656394,)
ic

cm_correct [[51923238    23816]
 [   39505   489174]]
cm_incorrect [[1413142   38725]
 [ 109975   94552]]


| TP_H + FN_H + FP_H + TN_H: 1656394
    len(label_mask_current_deforestation_test): 54132127
ic| TP_H + FN_H + FP_H + TN_H: 1656394
    len(label_mask_current_deforestation_test): 54132127


[0.95357414 0.92527602 0.6671713  0.03059909 0.70943974 0.46229593]
0.3634082503872609
threshold 0.3634082503872609
(52532195,) (52532195,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1599932,)
    predicted_test_classified_incorrect.shape: (1599932,)
ic

cm_correct [[51974927    24658]
 [   40387   492223]]
cm_incorrect [[1361453   37883]
 [ 109093   91503]]


| TP_H + FN_H + FP_H + TN_H: 1599932
    len(label_mask_current_deforestation_test): 54132127
ic| TP_H + FN_H + FP_H + TN_H: 1599932
    len(label_mask_current_deforestation_test): 54132127


[0.95229463 0.92417153 0.67132975 0.02955605 0.70720944 0.45615566]
0.370631939197399
threshold 0.370631939197399
(52586284,) (52586284,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1545843,)
    predicted_test_classified_incorrect.shape: (1545843,)
ic

cm_correct [[52024597    25498]
 [   41231   494958]]
cm_incorrect [[1311783   37043]
 [ 108249   88768]]


| TP_H + FN_H + FP_H + TN_H: 1545843
    len(label_mask_current_deforestation_test): 54132127
ic| TP_H + FN_H + FP_H + TN_H: 1545843
    len(label_mask_current_deforestation_test): 54132127


[0.95100835 0.92310361 0.67505994 0.02855685 0.70556629 0.4505601 ]
0.3605324280827617
threshold 0.3605324280827617
(52510897,) (52510897,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1621230,)
    predicted_test_classified_incorrect.shape: (1621230,)


cm_correct [[51955405    24340]
 [   40066   491086]]


ic| TP_H + FN_H + FP_H + TN_H: 1621230
    len(label_mask_current_deforestation_test): 54132127
ic| TP_H + FN_H + FP_H + TN_H: 1621230
    len(label_mask_current_deforestation_test): 54132127


cm_incorrect [[1380975   38201]
 [ 109414   92640]]
[0.95277693 0.92456773 0.66977903 0.0299495  0.70803494 0.45849129]
0.3599695277246931
threshold 0.3599695277246931
(52506623,) (52506623,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1625504,)
    predicted_test_classified_incorrect.shape: (1625504,)
ic

cm_correct [[51951522    24273]
 [   39990   490838]]
cm_incorrect [[1384858   38268]
 [ 109490   92888]]


| TP_H + FN_H + FP_H + TN_H: 1625504
    len(label_mask_current_deforestation_test): 54132127
ic| TP_H + FN_H + FP_H + TN_H: 1625504
    len(label_mask_current_deforestation_test): 54132127


[0.95287812 0.92466486 0.66944078 0.03002845 0.70822532 0.4589827 ]
0.35956117683320693
threshold 0.35956117683320693
(52503502,) (52503502,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1628625,)
    predicted_test_classified_incorrect.shape: (1628625,)
ic

cm_correct [[51948655    24230]
 [   39933   490684]]
cm_incorrect [[1387725   38311]
 [ 109547   93042]]


| TP_H + FN_H + FP_H + TN_H: 1628625
    len(label_mask_current_deforestation_test): 54132127
ic| TP_H + FN_H + FP_H + TN_H: 1628625
    len(label_mask_current_deforestation_test): 54132127


[0.9529436  0.92474233 0.66923075 0.03008611 0.70833555 0.45926482]
0.36014550661548866
threshold 0.36014550661548866
(52507951,) (52507951,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1624176,)
    predicted_test_classified_incorrect.shape: (1624176,)
ic

cm_correct [[51952728    24293]
 [   40016   490914]]
cm_incorrect [[1383652   38248]
 [ 109464   92812]]


| TP_H + FN_H + FP_H + TN_H: 1624176
    len(label_mask_current_deforestation_test): 54132127
ic| TP_H + FN_H + FP_H + TN_H: 1624176
    len(label_mask_current_deforestation_test): 54132127


[0.95284808 0.92463037 0.66954444 0.03000392 0.7081642  0.45883842]
0.36020854108747064
threshold 0.36020854108747064
(52508405,) (52508405,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1623722,)
    predicted_test_classified_incorrect.shape: (1623722,)
ic

cm_correct [[51953150    24298]
 [   40023   490934]]
cm_incorrect [[1383230   38243]
 [ 109457   92792]]


| TP_H + FN_H + FP_H + TN_H: 1623722
    len(label_mask_current_deforestation_test): 54132127
ic| TP_H + FN_H + FP_H + TN_H: 1623722
    len(label_mask_current_deforestation_test): 54132127


[0.95284066 0.92462101 0.66957172 0.02999553 0.70814668 0.45880079]
0.3601121679403342
threshold 0.3601121679403342
(52507693,) (52507693,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1624434,)
    predicted_test_classified_incorrect.shape: (1624434,)
ic

cm_correct [[51952486    24291]
 [   40014   490902]]
cm_incorrect [[1383894   38250]
 [ 109466   92824]]


| TP_H + FN_H + FP_H + TN_H: 1624434
    len(label_mask_current_deforestation_test): 54132127
ic| TP_H + FN_H + FP_H + TN_H: 1624434
    len(label_mask_current_deforestation_test): 54132127
ic| self.threshold_optimal: 0.36014550661548866


[0.95285068 0.92463215 0.66952807 0.03000869 0.70818011 0.45886598]
threshold 0.36014550661548866
(52507951,) (52507951,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1624176,)
    predicted_test_classified_incorrect.shape: (1624176,)
ic

cm_correct [[51952728    24293]
 [   40016   490914]]
cm_incorrect [[1383652   38248]
 [ 109464   92812]]


| TP_H + FN_H + FP_H + TN_H: 1624176
    len(label_mask_current_deforestation_test): 54132127
ic| TP_H + FN_H + FP_H + TN_H: 1624176
    len(label_mask_current_deforestation_test): 54132127


[0.95284808 0.92463037 0.66954444 0.03000392 0.7081642  0.45883842]
threshold 0.36014550661548866
(54132127,) (54132127,)


ic| self.m_optimal: {'AA': array([0.03000392]),
                     'f1': 84.63,
                     'f1_H': array([0.55686755]),
                     'f1_L': array([0.93852717]),
                     'precision_H': array([0.7081642]),
                     'precision_L': array([0.95284808]),
                     'recall_H': array([0.45883842]),
                     'recall_L': array([0.92463037]),
                     'recall_Ltotal': array([0.66954444])}
ic| self.m_audited_optimal: {'f1': array([0.95567003]),
                             'precision': array([0.96614136]),
                             'recall': array([0.94542325])}


cm_audited [[53374628    24293]
 [   40016   693190]]
[0.96614136 0.94542325]
D:/Jorge/datasets/deforestation/Para/deforestation_past_years.tif
Loaded deforestation past years


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Label where deforestation past years is actual date (2019) = 1


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation different from 0 (no deforestation)


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation before 2008 is 2
D:/Jorge/datasets/deforestation/deforestation_before_2008/deforestation_before_2008_para.tif


ic| np.unique(label_past_deforestation_before_2008, return_counts=True): (array([  0, 215], dtype=uint8), array([124211220,  38957970], dtype=int64))
ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))
ic| label_per_date.shape: (17730, 9203, 1)


Mask label shape:  
 (17730, 9203, 1) 
 Unique values:  
 [0 1 2]
Tiles size:  3546 2300
Mask size:  (17730, 9200)


ic| image_stack.shape: (17730, 9203, 21)


Image shape:  (17730, 9203, 21)
mask:  (17730, 9200)
image stack:  (17730, 9200, 21)
ref : (17730, 9200, 1)
Training tiles:  [1, 3, 5, 8, 11, 13, 14, 20]
Validation tiles:  [6, 19]
Test tiles:  [2, 4, 7, 9, 10, 12, 15, 16, 17, 18]


ic| im_idx_row.shape: (17730, 9200, 1)
    im_idx_col.shape: (17730, 9200, 1)
ic| im_idx_row.dtype: dtype('uint16')
    im_idx_col.dtype: dtype('uint16')
ic| im_idx.shape: (17730, 9200, 2), im_idx.dtype: dtype('uint16')
ic| coords.shape: (464, 239, 1, 128, 128, 2)
    coords.dtype: dtype('uint16')
ic| coords.shape: (110896, 2), coords.dtype: dtype('uint16')
ic| self.coords_train.shape: (41812, 3)
    self.coords_val.shape: (10260, 3)


training samples:  (3753, 3) validation samples:  (1032, 3)
time:  0
Model: "model_2"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_enc_net (InputLayer)      [(None, 128, 128, 21 0                                            
__________________________________________________________________________________________________
res1_net1 (Conv2D)              (None, 128, 128, 16) 3040        input_enc_net[0][0]              
__________________________________________________________________________________________________
drop_net1 (Dropout)             (None, 128, 128, 16) 0           res1_net1[0][0]                  
__________________________________________________________________________________________________
res2_net1 (Conv2D)              (None, 128, 128, 16) 2320        drop_net1[0][0]                  
_______________________

c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\keras\optimizer_v2\optimizer_v2.py:374: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  warnings.warn(
c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\keras\engine\training.py:1969: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  warnings.warn('`Model.fit_generator` is deprecated and '


Epoch 1/100
self.global_step 0.0
alpha Tensor("loss/add:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("loss/truediv:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("add:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("truediv:0", shape=(None, 128, 128, 1), dtype=float32)
K.int_shape(KL_reg) Tensor("mul_6:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("add_7:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("truediv_5:0", shape=(None, 128, 128, 1), dtype=float32)
K.int_shape(KL_reg) Tensor("mul_12:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("loss/add:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("loss/truediv:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("add:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("truediv:0", shape=(None, 128, 128, 1), dtype=float32)
K.int_shape(KL_reg) Tensor("mul_6:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("add_7:0", shape=(None, 128, 128, 3), dtype=float

c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py:494: CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.
  warnings.warn('Custom mask layers require a config and must override '


351/351 [==============================] - 32s 91ms/step - loss: 0.1364 - accuracy: 0.9254 - KL_term: 0.0130 - loglikelihood_term: 0.1234 - evidential_success: 70.1498 - evidential_fail: 11.0263 - acc: 0.9253 - annealing_coef: 0.0933 - global_step_get: 350.0000 - annealing_step_get: 3750.0000 - val_loss: 0.1505 - val_accuracy: 0.9248 - val_KL_term: 0.0231 - val_loglikelihood_term: 0.1262 - val_evidential_success: 53.4664 - val_evidential_fail: 6.7649 - val_acc: 0.9254 - val_annealing_coef: 0.1867 - val_global_step_get: 700.0000 - val_annealing_step_get: 3750.0000

Epoch 00002: val_loss improved from 0.15645 to 0.15052, saving model to D:/Jorge/datasets/deforestation/experiments/exp156/models\resunet_0.h5
Epoch 3/100
self.global_step 700.0
351/351 [==============================] - 32s 91ms/step - loss: 0.1298 - accuracy: 0.9313 - KL_term: 0.0147 - loglikelihood_term: 0.1151 - evidential_success: 90.3696 - evidential_fail: 9.3550 - acc: 0.9313 - annealing_coef: 0.1400 - global_step_get:

ic| self.path_models+ '/' + self.method +'_'+str(0)+'.h5': 'D:/Jorge/datasets/deforestation/experiments/exp156/models/resunet_0.h5'


time:  0
(54236371,)
(array([0, 1], dtype=uint8), array([53470765,   765606], dtype=int64))
(17730, 9200)
(array([0., 1.], dtype=float32), array([160487227,   2628773], dtype=int64))


ic| self.predicted_unpad.shape: (17730, 9200)
    self.predicted.shape: (17730, 9200)
ic| predicted_test.shape: (81558000,)
ic| predicted_test.shape: (54236371,)
ic| np.unique(predicted, return_counts=True): (array([0., 1.], dtype=float32), array([160487227,   2628773], dtype=int64))
    np.unique(predicted_larger_than_min_area, return_counts=True): (array([0., 1.], dtype=float32), array([160751173,   2364827], dtype=int64))
ic| np.unique(ignored_polygons, return_counts=True): (array([0., 1.], dtype=float32), array([162852054,    263946], dtype=int64))
ic| self.f1: 72.65, self.precision: 63.0, self.recall: 85.8
ic| self.label_mask_val.shape: (16311600,)
ic| self.label_mask_val_valid.shape: (9417418,)
ic| f1_val: 81.31
    precision_val: 71.79
    recall_val: 93.73
    mAP_val: 79.15


(array([0., 1.], dtype=float32), array([162053571,   1062429], dtype=int64))


ic| self.label_mask.shape: (17730, 9200)
ic| self.mask_amazon_ts.shape: (17730, 9200)
ic| self.label_mask_test.shape: (81558000,)
ic| self.error_mask_test.shape: (54111444,)
ic| bounds: (0.0015, 0.9627519354820252)
c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\scipy\optimize\_minimize.py:783: RuntimeWarning: Method 'bounded' does not support relative tolerance in x; defaulting to absolute tolerance.
  warn("Method 'bounded' does not support relative tolerance in x; "


0.36866556760251257
threshold 0.36866556760251257
(51850888,) (51850888,)


ic| label_current_deforestation_test_classified_incorrect.shape: (2260556,)
    predicted_test_classified_incorrect.shape: (2260556,)


cm_correct [[51058633   193237]
 [   29055   569963]]


ic| TP_H + FN_H + FP_H + TN_H: 2260556
    len(label_mask_current_deforestation_test): 54111444
ic| TP_H + FN_H + FP_H + TN_H: 2260556
    len(label_mask_current_deforestation_test): 54111444


cm_incorrect [[1947524  177095]
 [  75313   60624]]
[0.74680687 0.95149561 0.77550734 0.04177593 0.25502379 0.4459713 ]
0.5955863678795126
threshold 0.5955863678795126
(53462796,) (53462796,)


ic| label_current_deforestation_test_classified_incorrect.shape: (648648,)
    predicted_test_classified_incorrect.shape: (648648,)
ic| TP_H + FN_H + FP_H + TN_H: 648648
    len(label_mask_current_deforestation_test): 54111444
ic| TP_H + FN_H + FP_H + TN_H: 648648
    len(label_mask_current_deforestation_test): 54111444


cm_correct [[52436679   339531]
 [   62080   624506]]
cm_incorrect [[569478  30801]
 [ 42288   6081]]
[0.64780294 0.90958161 0.84972005 0.01198726 0.16487718 0.12572102]
0.22842080027700004
threshold 0.22842080027700004
(50470578,) (50470578,)


ic| label_current_deforestation_test_classified_incorrect.shape: (3640866,)
    predicted_test_classified_incorrect.shape: (3640866,)


cm_correct [[49883468    94398]
 [   17789   474923]]


ic| TP_H + FN_H + FP_H + TN_H: 3640866
    len(label_mask_current_deforestation_test): 54111444
ic| TP_H + FN_H + FP_H + TN_H: 3640866
    len(label_mask_current_deforestation_test): 54111444


cm_incorrect [[3122689  275934]
 [  86579  155664]]
[0.83419196 0.96389574 0.6461933  0.06728458 0.36066896 0.64259442]
0.4580267425048464
threshold 0.4580267425048464
(52564516,) (52564516,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1546928,)
    predicted_test_classified_incorrect.shape: (1546928,)
ic

cm_correct [[51677362   250766]
 [   38098   598290]]
cm_incorrect [[1328795  119566]
 [  66270   32297]]


| TP_H + FN_H + FP_H + TN_H: 1546928
    len(label_mask_current_deforestation_test): 54111444
ic| TP_H + FN_H + FP_H + TN_H: 1546928
    len(label_mask_current_deforestation_test): 54111444


[0.70465317 0.94013401 0.81404984 0.02858782 0.21267195 0.32766545]
0.4689489614601085
threshold 0.4689489614601085
(52649210,) (52649210,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1462234,)
    predicted_test_classified_incorrect.shape: (1462234,)
ic

cm_correct [[51750577   258250]
 [   39422   600961]]
cm_incorrect [[1255580  112082]
 [  64946   29626]]


| TP_H + FN_H + FP_H + TN_H: 1462234
    len(label_mask_current_deforestation_test): 54111444
ic| TP_H + FN_H + FP_H + TN_H: 1462234
    len(label_mask_current_deforestation_test): 54111444


[0.69943355 0.93843996 0.81768408 0.02702264 0.20906371 0.31326397]
0.4357747042281399
threshold 0.4357747042281399
(52390779,) (52390779,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1720665,)
    predicted_test_classified_incorrect.shape: (1720665,)


cm_correct [[51526656   236221]
 [   35589   592313]]


ic| TP_H + FN_H + FP_H + TN_H: 1720665
    len(label_mask_current_deforestation_test): 54111444
ic| TP_H + FN_H + FP_H + TN_H: 1720665
    len(label_mask_current_deforestation_test): 54111444


cm_incorrect [[1479501  134111]
 [  68779   38274]]
[0.71489281 0.94332077 0.80591737 0.03179854 0.22202628 0.35752384]
0.44952722020210817
threshold 0.44952722020210817
(52498610,) (52498610,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1612834,)
    predicted_test_classified_incorrect.shape: (1612834,)
ic

cm_correct [[51620342   245108]
 [   37102   596058]]
cm_incorrect [[1385815  125224]
 [  67266   34529]]


| TP_H + FN_H + FP_H + TN_H: 1612834
    len(label_mask_current_deforestation_test): 54111444
ic| TP_H + FN_H + FP_H + TN_H: 1612834
    len(label_mask_current_deforestation_test): 54111444


[0.70860924 0.94140186 0.81101292 0.02980578 0.21613992 0.33920134]
0.44764384638213434
threshold 0.44764384638213434
(52483758,) (52483758,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1627686,)
    predicted_test_classified_incorrect.shape: (1627686,)
ic

cm_correct [[51607387   243880]
 [   36917   595574]]
cm_incorrect [[1398770  126452]
 [  67451   35013]]


| TP_H + FN_H + FP_H + TN_H: 1627686
    len(label_mask_current_deforestation_test): 54111444
ic| TP_H + FN_H + FP_H + TN_H: 1627686
    len(label_mask_current_deforestation_test): 54111444


[0.70947783 0.94163237 0.81035438 0.03008025 0.21684576 0.34171026]
0.4447911697434479
threshold 0.4447911697434479
(52461510,) (52461510,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1649934,)
    predicted_test_classified_incorrect.shape: (1649934,)
ic

cm_correct [[51588090   241983]
 [   36592   594845]]
cm_incorrect [[1418067  128349]
 [  67776   35742]]


| TP_H + FN_H + FP_H + TN_H: 1649934
    len(label_mask_current_deforestation_test): 54111444
ic| TP_H + FN_H + FP_H + TN_H: 1649934
    len(label_mask_current_deforestation_test): 54111444


[0.71083305 0.94204964 0.80936248 0.03049141 0.21781816 0.34527329]
0.4478853309427654
threshold 0.4478853309427654
(52485583,) (52485583,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1625861,)
    predicted_test_classified_incorrect.shape: (1625861,)
ic

cm_correct [[51608984   244022]
 [   36936   595641]]
cm_incorrect [[1397173  126310]
 [  67432   34946]]


| TP_H + FN_H + FP_H + TN_H: 1625861
    len(label_mask_current_deforestation_test): 54111444
ic| TP_H + FN_H + FP_H + TN_H: 1625861
    len(label_mask_current_deforestation_test): 54111444


[0.70938103 0.94161027 0.81044554 0.03004653 0.21671132 0.34134287]
0.4483373740329075
threshold 0.4483373740329075
(52489141,) (52489141,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1622303,)
    predicted_test_classified_incorrect.shape: (1622303,)
ic

cm_correct [[51612102   244317]
 [   36977   595745]]
cm_incorrect [[1394055  126015]
 [  67391   34842]]


| TP_H + FN_H + FP_H + TN_H: 1622303
    len(label_mask_current_deforestation_test): 54111444
ic| TP_H + FN_H + FP_H + TN_H: 1622303
    len(label_mask_current_deforestation_test): 54111444


[0.70916789 0.94155885 0.81058704 0.02998077 0.21660232 0.34080972]
0.44837556930054917
threshold 0.44837556930054917
(52489468,) (52489468,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1621976,)
    predicted_test_classified_incorrect.shape: (1621976,)
ic

cm_correct [[51612385   244347]
 [   36980   595756]]
cm_incorrect [[1393772  125985]
 [  67388   34831]]


| TP_H + FN_H + FP_H + TN_H: 1621976
    len(label_mask_current_deforestation_test): 54111444
ic| TP_H + FN_H + FP_H + TN_H: 1621976
    len(label_mask_current_deforestation_test): 54111444


[0.70914638 0.9415554  0.81060201 0.02997473 0.21658915 0.34074878]
0.4481790728220913
threshold 0.4481790728220913
(52487852,) (52487852,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1623592,)
    predicted_test_classified_incorrect.shape: (1623592,)
ic

cm_correct [[51610981   244204]
 [   36964   595703]]
cm_incorrect [[1395176  126128]
 [  67404   34884]]


| TP_H + FN_H + FP_H + TN_H: 1623592
    len(label_mask_current_deforestation_test): 54111444
ic| TP_H + FN_H + FP_H + TN_H: 1623592
    len(label_mask_current_deforestation_test): 54111444


[0.70924876 0.94157432 0.8105299  0.0300046  0.21665466 0.34103707]
0.4480668734081081
threshold 0.4480668734081081
(52486998,) (52486998,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1624446,)
    predicted_test_classified_incorrect.shape: (1624446,)
ic

cm_correct [[51610228   244131]
 [   36956   595683]]
cm_incorrect [[1395929  126201]
 [  67412   34904]]


| TP_H + FN_H + FP_H + TN_H: 1624446
    len(label_mask_current_deforestation_test): 54111444
ic| TP_H + FN_H + FP_H + TN_H: 1624446
    len(label_mask_current_deforestation_test): 54111444


[0.70930349 0.94158438 0.81050268 0.03002038 0.21665374 0.34113922]
0.44821241280299456
threshold 0.44821241280299456
(52488120,) (52488120,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1623324,)
    predicted_test_classified_incorrect.shape: (1623324,)
ic

cm_correct [[51611213   244227]
 [   36965   595715]]
cm_incorrect [[1394944  126105]
 [  67403   34872]]


| TP_H + FN_H + FP_H + TN_H: 1623324
    len(label_mask_current_deforestation_test): 54111444
ic| TP_H + FN_H + FP_H + TN_H: 1623324
    len(label_mask_current_deforestation_test): 54111444


[0.70923349 0.94157394 0.81054622 0.02999964 0.21662722 0.34096309]
0.4482457527843923
threshold 0.4482457527843923
(52488383,) (52488383,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1623061,)
    predicted_test_classified_incorrect.shape: (1623061,)
ic

cm_correct [[51611438   244253]
 [   36969   595723]]
cm_incorrect [[1394719  126079]
 [  67399   34864]]


| TP_H + FN_H + FP_H + TN_H: 1623061
    len(label_mask_current_deforestation_test): 54111444
ic| TP_H + FN_H + FP_H + TN_H: 1623061
    len(label_mask_current_deforestation_test): 54111444
ic| self.threshold_optimal: 0.44821241280299456


[0.70921431 0.94156873 0.81055711 0.02999478 0.21662328 0.34092487]
threshold 0.44821241280299456
(52488120,) (52488120,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1623324,)
    predicted_test_classified_incorrect.shape: (1623324,)
ic

cm_correct [[51611213   244227]
 [   36965   595715]]
cm_incorrect [[1394944  126105]
 [  67403   34872]]


| TP_H + FN_H + FP_H + TN_H: 1623324
    len(label_mask_current_deforestation_test): 54111444
ic| TP_H + FN_H + FP_H + TN_H: 1623324
    len(label_mask_current_deforestation_test): 54111444


[0.70923349 0.94157394 0.81054622 0.02999964 0.21662722 0.34096309]
threshold 0.44821241280299456
(54111444,) (54111444,)


ic| self.m_optimal: {'AA': array([0.02999964]),
                     'f1': 72.65,
                     'f1_H': array([0.26493246]),
                     'f1_L': array([0.80905351]),
                     'precision_H': array([0.21662722]),
                     'precision_L': array([0.70923349]),
                     'recall_H': array([0.34096309]),
                     'recall_L': array([0.94157394]),
                     'recall_Ltotal': array([0.81054622])}
ic| self.m_audited_optimal: {'f1': array([0.83234158]),
                             'precision': array([0.74079538]),
                             'recall': array([0.9497044])}


cm_audited [[53132262   244227]
 [   36965   697990]]
[0.74079538 0.9497044 ]
D:/Jorge/datasets/deforestation/Para/deforestation_past_years.tif
Loaded deforestation past years


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Label where deforestation past years is actual date (2019) = 1


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation different from 0 (no deforestation)


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation before 2008 is 2
D:/Jorge/datasets/deforestation/deforestation_before_2008/deforestation_before_2008_para.tif


ic| np.unique(label_past_deforestation_before_2008, return_counts=True): (array([  0, 215], dtype=uint8), array([124211220,  38957970], dtype=int64))
ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))
ic| label_per_date.shape: (17730, 9203, 1)


Mask label shape:  
 (17730, 9203, 1) 
 Unique values:  
 [0 1 2]
Tiles size:  3546 2300
Mask size:  (17730, 9200)


ic| image_stack.shape: (17730, 9203, 21)


Image shape:  (17730, 9203, 21)
mask:  (17730, 9200)
image stack:  (17730, 9200, 21)
ref : (17730, 9200, 1)
Training tiles:  [1, 3, 5, 8, 11, 13, 14, 20]
Validation tiles:  [6, 19]
Test tiles:  [2, 4, 7, 9, 10, 12, 15, 16, 17, 18]


ic| im_idx_row.shape: (17730, 9200, 1)
    im_idx_col.shape: (17730, 9200, 1)
ic| im_idx_row.dtype: dtype('uint16')
    im_idx_col.dtype: dtype('uint16')
ic| im_idx.shape: (17730, 9200, 2), im_idx.dtype: dtype('uint16')
ic| coords.shape: (464, 239, 1, 128, 128, 2)
    coords.dtype: dtype('uint16')
ic| coords.shape: (110896, 2), coords.dtype: dtype('uint16')
ic| self.coords_train.shape: (41812, 3)
    self.coords_val.shape: (10260, 3)


training samples:  (3753, 3) validation samples:  (1032, 3)
time:  0
Model: "model_4"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_enc_net (InputLayer)      [(None, 128, 128, 21 0                                            
__________________________________________________________________________________________________
res1_net1 (Conv2D)              (None, 128, 128, 16) 3040        input_enc_net[0][0]              
__________________________________________________________________________________________________
drop_net1 (Dropout)             (None, 128, 128, 16) 0           res1_net1[0][0]                  
__________________________________________________________________________________________________
res2_net1 (Conv2D)              (None, 128, 128, 16) 2320        drop_net1[0][0]                  
_______________________

c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\keras\optimizer_v2\optimizer_v2.py:374: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  warnings.warn(
c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\keras\engine\training.py:1969: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  warnings.warn('`Model.fit_generator` is deprecated and '


Epoch 1/100
self.global_step 0.0
alpha Tensor("loss/add:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("loss/truediv:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("add:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("truediv:0", shape=(None, 128, 128, 1), dtype=float32)
K.int_shape(KL_reg) Tensor("mul_6:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("add_7:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("truediv_5:0", shape=(None, 128, 128, 1), dtype=float32)
K.int_shape(KL_reg) Tensor("mul_12:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("loss/add:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("loss/truediv:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("add:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("truediv:0", shape=(None, 128, 128, 1), dtype=float32)
K.int_shape(KL_reg) Tensor("mul_6:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("add_7:0", shape=(None, 128, 128, 3), dtype=float

c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py:494: CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.
  warnings.warn('Custom mask layers require a config and must override '


351/351 [==============================] - 32s 90ms/step - loss: 0.1383 - accuracy: 0.9245 - KL_term: 0.0129 - loglikelihood_term: 0.1256 - evidential_success: 81.2897 - evidential_fail: 11.4574 - acc: 0.9244 - annealing_coef: 0.0933 - global_step_get: 350.0000 - annealing_step_get: 3750.0000 - val_loss: 0.1398 - val_accuracy: 0.9293 - val_KL_term: 0.0184 - val_loglikelihood_term: 0.1205 - val_evidential_success: 73.6986 - val_evidential_fail: 5.9821 - val_acc: 0.9298 - val_annealing_coef: 0.1867 - val_global_step_get: 700.0000 - val_annealing_step_get: 3750.0000

Epoch 00002: val_loss improved from 0.15620 to 0.13984, saving model to D:/Jorge/datasets/deforestation/experiments/exp157/models\resunet_0.h5
Epoch 3/100
self.global_step 700.0
351/351 [==============================] - 31s 90ms/step - loss: 0.1310 - accuracy: 0.9308 - KL_term: 0.0149 - loglikelihood_term: 0.1161 - evidential_success: 96.1280 - evidential_fail: 10.2653 - acc: 0.9308 - annealing_coef: 0.1400 - global_step_get

ic| self.path_models+ '/' + self.method +'_'+str(0)+'.h5': 'D:/Jorge/datasets/deforestation/experiments/exp157/models/resunet_0.h5'


time:  0
(54236371,)
(array([0, 1], dtype=uint8), array([53470765,   765606], dtype=int64))
(17730, 9200)
(array([0., 1.], dtype=float32), array([161120387,   1995613], dtype=int64))


ic| self.predicted_unpad.shape: (17730, 9200)
    self.predicted.shape: (17730, 9200)
ic| predicted_test.shape: (81558000,)
ic| predicted_test.shape: (54236371,)
ic| np.unique(predicted, return_counts=True): (array([0., 1.], dtype=float32), array([161120387,   1995613], dtype=int64))
    np.unique(predicted_larger_than_min_area, return_counts=True): (array([0., 1.], dtype=float32), array([161327831,   1788169], dtype=int64))
ic| np.unique(ignored_polygons, return_counts=True): (array([0., 1.], dtype=float32), array([162908556,    207444], dtype=int64))
ic| self.f1: 82.86, self.precision: 82.79, self.recall: 82.93
ic| self.label_mask_val.shape: (16311600,)
ic| self.label_mask_val_valid.shape: (9428827,)
ic| f1_val: 86.22
    precision_val: 83.36
    recall_val: 89.28
    mAP_val: 91.67


(array([0., 1.], dtype=float32), array([162464107,    651893], dtype=int64))


ic| self.label_mask.shape: (17730, 9200)
ic| self.mask_amazon_ts.shape: (17730, 9200)
ic| self.label_mask_test.shape: (81558000,)
ic| self.error_mask_test.shape: (54135853,)
ic| bounds: (0.0015, 0.9985)
c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\scipy\optimize\_minimize.py:783: RuntimeWarning: Method 'bounded' does not support relative tolerance in x; defaulting to absolute tolerance.
  warn("Method 'bounded' does not support relative tolerance in x; "


0.38232011321635484
threshold 0.38232011321635484
(52271923,) (52271923,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1863930,)
    predicted_test_classified_incorrect.shape: (1863930,)


cm_correct [[51673499    49000]
 [   33925   515499]]


ic| TP_H + FN_H + FP_H + TN_H: 1863930
    len(label_mask_current_deforestation_test): 54135853
ic| TP_H + FN_H + FP_H + TN_H: 1863930
    len(label_mask_current_deforestation_test): 54135853


cm_incorrect [[1600099   77817]
 [  91628   94386]]
[0.91319737 0.93825352 0.70094148 0.0344306  0.54810892 0.50741342]
0.6176798867836452
threshold 0.6176798867836452
(53655178,) (53655178,)


ic| label_current_deforestation_test_classified_incorrect.shape: (480675,)
    predicted_test_classified_incorrect.shape: (480675,)
ic| TP_H + FN_H + FP_H + TN_H: 480675
    len(label_mask_current_deforestation_test): 54135853
ic| TP_H + FN_H + FP_H + TN_H: 480675
    len(label_mask_current_deforestation_test): 54135853


cm_correct [[52893203   105259]
 [   68673   588043]]
cm_incorrect [[380395  21558]
 [ 56880  21842]]
[0.84817727 0.89542968 0.79958202 0.00887905 0.50327189 0.27745738]
0.23685977356729035
threshold 0.23685977356729035
(50788794,) (50788794,)


ic| label_current_deforestation_test_classified_incorrect.shape: (3347059,)
    predicted_test_classified_incorrect.shape: (3347059,)


cm_correct [[50307225    17406]
 [   21770   442393]]


ic| TP_H + FN_H + FP_H + TN_H: 3347059
    len(label_mask_current_deforestation_test): 54135853
ic| TP_H + FN_H + FP_H + TN_H: 3347059
    len(label_mask_current_deforestation_test): 54135853


cm_incorrect [[2966373  109411]
 [ 103783  167492]]
[0.96214433 0.95309837 0.60153677 0.06182703 0.60487608 0.61742512]
0.4479174416098163
threshold 0.4479174416098163
(52756758,) (52756758,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1379095,)
    predicted_test_classified_incorrect.shape: (1379095,)
ic| TP_H + FN_H + FP_H + TN_H: 1379095
    len(label_mask_current_deforestation_test): 54135853
ic| TP_H + FN_H + FP_H + TN_H: 1379095
    len(label_mask_current_deforestation_test): 54135853


cm_correct [[52114165    64227]
 [   39855   538511]]
cm_incorrect [[1159433   62590]
 [  85698   71374]]
[0.89344126 0.93109035 0.73223168 0.02547471 0.53278493 0.45440308]
0.41335504430569175
threshold 0.41335504430569175
(52514142,) (52514142,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1621711,)
    predicted_test_classified_incorrect.shape: (1621711,)
ic

cm_correct [[51894494    56130]
 [   36611   526907]]
cm_incorrect [[1379104   70687]
 [  88942   82978]]


| TP_H + FN_H + FP_H + TN_H: 1621711
    len(label_mask_current_deforestation_test): 54135853
ic| TP_H + FN_H + FP_H + TN_H: 1621711
    len(label_mask_current_deforestation_test): 54135853


[0.90372824 0.93503136 0.71645332 0.02995632 0.53999284 0.48265472]
0.4149440846961599
threshold 0.4149440846961599
(52525909,) (52525909,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1609944,)
    predicted_test_classified_incorrect.shape: (1609944,)
ic

cm_correct [[51905227    56515]
 [   36743   527424]]
cm_incorrect [[1368371   70302]
 [  88810   82461]]


| TP_H + FN_H + FP_H + TN_H: 1609944
    len(label_mask_current_deforestation_test): 54135853
ic| TP_H + FN_H + FP_H + TN_H: 1609944
    len(label_mask_current_deforestation_test): 54135853


[0.90321763 0.93487212 0.71715631 0.02973896 0.53979694 0.48146505]
0.4061274919356681
threshold 0.4061274919356681
(52459948,) (52459948,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1675905,)
    predicted_test_classified_incorrect.shape: (1675905,)
ic

cm_correct [[51845170    54418]
 [   35993   524367]]
cm_incorrect [[1428428   72399]
 [  89560   85518]]


| TP_H + FN_H + FP_H + TN_H: 1675905
    len(label_mask_current_deforestation_test): 54135853
ic| TP_H + FN_H + FP_H + TN_H: 1675905
    len(label_mask_current_deforestation_test): 54135853


[0.9059789  0.93576808 0.7129996  0.0309574  0.54153764 0.48845657]
0.4105943649558126
threshold 0.4105943649558126
(52493581,) (52493581,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1642272,)
    predicted_test_classified_incorrect.shape: (1642272,)
ic

cm_correct [[51875823    55447]
 [   36396   525915]]
cm_incorrect [[1397775   71370]
 [  89157   83970]]


| TP_H + FN_H + FP_H + TN_H: 1642272
    len(label_mask_current_deforestation_test): 54135853
ic| TP_H + FN_H + FP_H + TN_H: 1642272
    len(label_mask_current_deforestation_test): 54135853


[0.90462569 0.93527425 0.71510447 0.03033612 0.5405562  0.48501967]
0.4129239000697429
threshold 0.4129239000697429
(52510934,) (52510934,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1624919,)
    predicted_test_classified_incorrect.shape: (1624919,)
ic

cm_correct [[51891596    56004]
 [   36582   526752]]
cm_incorrect [[1382002   70813]
 [  88971   83133]]


| TP_H + FN_H + FP_H + TN_H: 1624919
    len(label_mask_current_deforestation_test): 54135853
ic| TP_H + FN_H + FP_H + TN_H: 1624919
    len(label_mask_current_deforestation_test): 54135853


[0.90389803 0.93506162 0.71624257 0.03001558 0.54001403 0.48303933]
0.41222021064130643
threshold 0.41222021064130643
(52505760,) (52505760,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1630093,)
    predicted_test_classified_incorrect.shape: (1630093,)
ic

cm_correct [[51886882    55819]
 [   36536   526523]]
cm_incorrect [[1386716   70998]
 [  89017   83362]]


| TP_H + FN_H + FP_H + TN_H: 1630093
    len(label_mask_current_deforestation_test): 54135853
ic| TP_H + FN_H + FP_H + TN_H: 1630093
    len(label_mask_current_deforestation_test): 54135853


[0.90414739 0.9351116  0.71593119 0.03011115 0.54004924 0.48359719]
0.41295723952772745
threshold 0.41295723952772745
(52511180,) (52511180,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1624673,)
    predicted_test_classified_incorrect.shape: (1624673,)
ic

cm_correct [[51891822    56011]
 [   36585   526762]]
cm_incorrect [[1381776   70806]
 [  88968   83123]]


| TP_H + FN_H + FP_H + TN_H: 1624673
    len(label_mask_current_deforestation_test): 54135853
ic| TP_H + FN_H + FP_H + TN_H: 1624673
    len(label_mask_current_deforestation_test): 54135853


[0.90388882 0.93505779 0.71625616 0.03001104 0.54000871 0.48301771]
0.4130751297739797
threshold 0.4130751297739797
(52512039,) (52512039,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1623814,)
    predicted_test_classified_incorrect.shape: (1623814,)
ic

cm_correct [[51892585    56050]
 [   36593   526811]]
cm_incorrect [[1381013   70767]
 [  88960   83074]]


| TP_H + FN_H + FP_H + TN_H: 1623814
    len(label_mask_current_deforestation_test): 54135853
ic| TP_H + FN_H + FP_H + TN_H: 1623814
    len(label_mask_current_deforestation_test): 54135853


[0.90383642 0.93505016 0.71632279 0.02999517 0.53999909 0.48289292]
0.4131820476111487
threshold 0.4131820476111487
(52512826,) (52512826,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1623027,)
    predicted_test_classified_incorrect.shape: (1623027,)
ic

cm_correct [[51893309    56076]
 [   36599   526842]]
cm_incorrect [[1380289   70741]
 [  88954   83043]]


| TP_H + FN_H + FP_H + TN_H: 1623027
    len(label_mask_current_deforestation_test): 54135853
ic| TP_H + FN_H + FP_H + TN_H: 1623027
    len(label_mask_current_deforestation_test): 54135853


[0.90380122 0.93504378 0.71636494 0.02998063 0.53999766 0.48281656]
0.41304179031375204
threshold 0.41304179031375204
(52511785,) (52511785,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1624068,)
    predicted_test_classified_incorrect.shape: (1624068,)
ic

cm_correct [[51892363    56041]
 [   36591   526790]]
cm_incorrect [[1381235   70776]
 [  88962   83095]]


| TP_H + FN_H + FP_H + TN_H: 1624068
    len(label_mask_current_deforestation_test): 54135853
ic| TP_H + FN_H + FP_H + TN_H: 1624068
    len(label_mask_current_deforestation_test): 54135853


[0.90384691 0.93505106 0.71629424 0.02999986 0.54003029 0.48295042]
0.4130084508540189
threshold 0.4130084508540189
(52511558,) (52511558,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1624295,)
    predicted_test_classified_incorrect.shape: (1624295,)
ic

cm_correct [[51892159    56028]
 [   36589   526782]]
cm_incorrect [[1381439   70789]
 [  88964   83103]]


| TP_H + FN_H + FP_H + TN_H: 1624295
    len(label_mask_current_deforestation_test): 54135853
ic| TP_H + FN_H + FP_H + TN_H: 1624295
    len(label_mask_current_deforestation_test): 54135853
ic| self.threshold_optimal: 0.41304179031375204


[0.90386575 0.93505346 0.71628336 0.03000405 0.54000858 0.48296884]
threshold 0.41304179031375204
(52511785,) (52511785,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1624068,)
    predicted_test_classified_incorrect.shape: (1624068,)
ic

cm_correct [[51892363    56041]
 [   36591   526790]]
cm_incorrect [[1381235   70776]
 [  88962   83095]]


| TP_H + FN_H + FP_H + TN_H: 1624068
    len(label_mask_current_deforestation_test): 54135853
ic| TP_H + FN_H + FP_H + TN_H: 1624068
    len(label_mask_current_deforestation_test): 54135853


[0.90384691 0.93505106 0.71629424 0.02999986 0.54003029 0.48295042]
threshold 0.41304179031375204
(54135853,) (54135853,)


ic| self.m_optimal: {'AA': array([0.02999986]),
                     'f1': 82.86,
                     'f1_H': array([0.50989789]),
                     'f1_L': array([0.91918423]),
                     'precision_H': array([0.54003029]),
                     'precision_L': array([0.90384691]),
                     'recall_H': array([0.48295042]),
                     'recall_L': array([0.93505106]),
                     'recall_Ltotal': array([0.71629424])}
ic| self.m_audited_optimal: {'f1': array([0.93784447]),
                             'precision': array([0.9257625]),
                             'recall': array([0.95024598])}


cm_audited [[53344374    56041]
 [   36591   698847]]
[0.9257625  0.95024598]
D:/Jorge/datasets/deforestation/Para/deforestation_past_years.tif
Loaded deforestation past years


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Label where deforestation past years is actual date (2019) = 1


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation different from 0 (no deforestation)


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation before 2008 is 2
D:/Jorge/datasets/deforestation/deforestation_before_2008/deforestation_before_2008_para.tif


ic| np.unique(label_past_deforestation_before_2008, return_counts=True): (array([  0, 215], dtype=uint8), array([124211220,  38957970], dtype=int64))
ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))
ic| label_per_date.shape: (17730, 9203, 1)


Mask label shape:  
 (17730, 9203, 1) 
 Unique values:  
 [0 1 2]
Tiles size:  3546 2300
Mask size:  (17730, 9200)


ic| image_stack.shape: (17730, 9203, 21)


Image shape:  (17730, 9203, 21)
mask:  (17730, 9200)
image stack:  (17730, 9200, 21)
ref : (17730, 9200, 1)
Training tiles:  [1, 3, 5, 8, 11, 13, 14, 20]
Validation tiles:  [6, 19]
Test tiles:  [2, 4, 7, 9, 10, 12, 15, 16, 17, 18]


ic| im_idx_row.shape: (17730, 9200, 1)
    im_idx_col.shape: (17730, 9200, 1)
ic| im_idx_row.dtype: dtype('uint16')
    im_idx_col.dtype: dtype('uint16')
ic| im_idx.shape: (17730, 9200, 2), im_idx.dtype: dtype('uint16')
ic| coords.shape: (464, 239, 1, 128, 128, 2)
    coords.dtype: dtype('uint16')
ic| coords.shape: (110896, 2), coords.dtype: dtype('uint16')
ic| self.coords_train.shape: (41812, 3)
    self.coords_val.shape: (10260, 3)


training samples:  (3753, 3) validation samples:  (1032, 3)
time:  0
Model: "model_6"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_enc_net (InputLayer)      [(None, 128, 128, 21 0                                            
__________________________________________________________________________________________________
res1_net1 (Conv2D)              (None, 128, 128, 16) 3040        input_enc_net[0][0]              
__________________________________________________________________________________________________
drop_net1 (Dropout)             (None, 128, 128, 16) 0           res1_net1[0][0]                  
__________________________________________________________________________________________________
res2_net1 (Conv2D)              (None, 128, 128, 16) 2320        drop_net1[0][0]                  
_______________________

c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\keras\optimizer_v2\optimizer_v2.py:374: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  warnings.warn(
c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\keras\engine\training.py:1969: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  warnings.warn('`Model.fit_generator` is deprecated and '


Epoch 1/100
self.global_step 0.0
alpha Tensor("loss/add:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("loss/truediv:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("add:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("truediv:0", shape=(None, 128, 128, 1), dtype=float32)
K.int_shape(KL_reg) Tensor("mul_6:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("add_7:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("truediv_5:0", shape=(None, 128, 128, 1), dtype=float32)
K.int_shape(KL_reg) Tensor("mul_12:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("loss/add:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("loss/truediv:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("add:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("truediv:0", shape=(None, 128, 128, 1), dtype=float32)
K.int_shape(KL_reg) Tensor("mul_6:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("add_7:0", shape=(None, 128, 128, 3), dtype=float

c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py:494: CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.
  warnings.warn('Custom mask layers require a config and must override '


351/351 [==============================] - 32s 91ms/step - loss: 0.1355 - accuracy: 0.9259 - KL_term: 0.0136 - loglikelihood_term: 0.1218 - evidential_success: 70.6629 - evidential_fail: 11.7266 - acc: 0.9260 - annealing_coef: 0.0933 - global_step_get: 350.0000 - annealing_step_get: 3750.0000 - val_loss: 0.1372 - val_accuracy: 0.9309 - val_KL_term: 0.0169 - val_loglikelihood_term: 0.1191 - val_evidential_success: 57.1152 - val_evidential_fail: 4.9578 - val_acc: 0.9314 - val_annealing_coef: 0.1867 - val_global_step_get: 700.0000 - val_annealing_step_get: 3750.0000

Epoch 00002: val_loss improved from 0.14830 to 0.13720, saving model to D:/Jorge/datasets/deforestation/experiments/exp158/models\resunet_0.h5
Epoch 3/100
self.global_step 700.0
351/351 [==============================] - 32s 91ms/step - loss: 0.1292 - accuracy: 0.9318 - KL_term: 0.0150 - loglikelihood_term: 0.1142 - evidential_success: 89.2670 - evidential_fail: 9.4995 - acc: 0.9317 - annealing_coef: 0.1400 - global_step_get:

ic| self.path_models+ '/' + self.method +'_'+str(0)+'.h5': 'D:/Jorge/datasets/deforestation/experiments/exp158/models/resunet_0.h5'


time:  0
(54236371,)
(array([0, 1], dtype=uint8), array([53470765,   765606], dtype=int64))
(17730, 9200)
(array([0., 1.], dtype=float32), array([160842871,   2273129], dtype=int64))


ic| self.predicted_unpad.shape: (17730, 9200)
    self.predicted.shape: (17730, 9200)
ic| predicted_test.shape: (81558000,)
ic| predicted_test.shape: (54236371,)
ic| np.unique(predicted, return_counts=True): (array([0., 1.], dtype=float32), array([160842871,   2273129], dtype=int64))
    np.unique(predicted_larger_than_min_area, return_counts=True): (array([0., 1.], dtype=float32), array([161099998,   2016002], dtype=int64))
ic| np.unique(ignored_polygons, return_counts=True): (array([0., 1.], dtype=float32), array([162858873,    257127], dtype=int64))
ic| self.f1: 81.49, self.precision: 77.25, self.recall: 86.23
ic| self.label_mask_val.shape: (16311600,)
ic| self.label_mask_val_valid.shape: (9419709,)
ic| f1_val: 85.15
    precision_val: 78.56
    recall_val: 92.94
    mAP_val: 89.14


(array([0., 1.], dtype=float32), array([162378944,    737056], dtype=int64))


ic| self.label_mask.shape: (17730, 9200)
ic| self.mask_amazon_ts.shape: (17730, 9200)
ic| self.label_mask_test.shape: (81558000,)
ic| self.error_mask_test.shape: (54111151,)
ic| bounds: (0.0015, 0.9985)
c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\scipy\optimize\_minimize.py:783: RuntimeWarning: Method 'bounded' does not support relative tolerance in x; defaulting to absolute tolerance.
  warn("Method 'bounded' does not support relative tolerance in x; "


0.38232011321635484
threshold 0.38232011321635484
(52251277,) (52251277,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1859874,)
    predicted_test_classified_incorrect.shape: (1859874,)


cm_correct [[51612167    70226]
 [   26699   542185]]


ic| TP_H + FN_H + FP_H + TN_H: 1859874
    len(label_mask_current_deforestation_test): 54111151
ic| TP_H + FN_H + FP_H + TN_H: 1859874
    len(label_mask_current_deforestation_test): 54111151


cm_incorrect [[1573875  117130]
 [  74893   93976]]
[0.88532864 0.95306776 0.73491399 0.03437136 0.44516025 0.55650238]
0.6176798867836452
threshold 0.6176798867836452
(53771150,) (53771150,)


ic| label_current_deforestation_test_classified_incorrect.shape: (340001,)
    predicted_test_classified_incorrect.shape: (340001,)
ic| TP_H + FN_H + FP_H + TN_H: 340001
    len(label_mask_current_deforestation_test): 54111151
ic| TP_H + FN_H + FP_H + TN_H: 340001
    len(label_mask_current_deforestation_test): 54111151


cm_correct [[52898897   173716]
 [   73028   625509]]
cm_incorrect [[287145  13640]
 [ 28564  10652]]
[0.78264444 0.89545579 0.84785694 0.00628338 0.43849827 0.27162383]
0.23685977356729035
threshold 0.23685977356729035
(50615607,) (50615607,)


ic| label_current_deforestation_test_classified_incorrect.shape: (3495544,)
    predicted_test_classified_incorrect.shape: (3495544,)


cm_correct [[50144243    20246]
 [   15792   435326]]


ic| TP_H + FN_H + FP_H + TN_H: 3495544
    len(label_mask_current_deforestation_test): 54111151
ic| TP_H + FN_H + FP_H + TN_H: 3495544
    len(label_mask_current_deforestation_test): 54111151


cm_incorrect [[3041799  167110]
 [  85800  200835]]
[0.95555917 0.96499364 0.59007012 0.06459933 0.54582886 0.70066461]
0.4460329034354955
threshold 0.4460329034354955
(52747803,) (52747803,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1363348,)
    predicted_test_classified_incorrect.shape: (1363348,)
ic| TP_H + FN_H + FP_H + TN_H: 1363348
    len(label_mask_current_deforestation_test): 54111151


cm_correct [[52052312    94336]
 [   32327   568828]]
cm_incorrect [[1133730   93020]
 [  69265   67333]]


ic| TP_H + FN_H + FP_H + TN_H: 1363348
    len(label_mask_current_deforestation_test): 54111151


[0.85774861 0.94622518 0.7710277  0.02519532 0.41990483 0.49292815]
0.4064345997657033
threshold 0.4064345997657033
(52452910,) (52452910,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1658241,)
    predicted_test_classified_incorrect.shape: (1658241,)
ic

cm_correct [[51792572    78819]
 [   28677   552842]]
cm_incorrect [[1393470  108537]
 [  72915   83319]]


| TP_H + FN_H + FP_H + TN_H: 1658241
    len(label_mask_current_deforestation_test): 54111151
ic| TP_H + FN_H + FP_H + TN_H: 1658241
    len(label_mask_current_deforestation_test): 54111151


[0.87521946 0.95068605 0.7493592  0.03064509 0.43427883 0.53329621]
0.4133418303104436
threshold 0.4133418303104436
(52507974,) (52507974,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1603177,)
    predicted_test_classified_incorrect.shape: (1603177,)
ic

cm_correct [[51841622    81387]
 [   29315   555650]]
cm_incorrect [[1344420  105969]
 [  72277   80511]]


| TP_H + FN_H + FP_H + TN_H: 1603177
    len(label_mask_current_deforestation_test): 54111151
ic| TP_H + FN_H + FP_H + TN_H: 1603177
    len(label_mask_current_deforestation_test): 54111151


[0.87224133 0.94988589 0.75316535 0.02962748 0.43174067 0.52694583]
0.4152077018237977
threshold 0.4152077018237977
(52522662,) (52522662,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1588489,)
    predicted_test_classified_incorrect.shape: (1588489,)
ic

cm_correct [[51854665    82083]
 [   29479   556435]]
cm_incorrect [[1331377  105273]
 [  72113   79726]]


| TP_H + FN_H + FP_H + TN_H: 1588489
    len(label_mask_current_deforestation_test): 54111151
ic| TP_H + FN_H + FP_H + TN_H: 1588489
    len(label_mask_current_deforestation_test): 54111151


[0.87144763 0.94968716 0.7542294  0.02935604 0.43095368 0.52506932]
0.41082419559803857
threshold 0.41082419559803857
(52487853,) (52487853,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1623298,)
    predicted_test_classified_incorrect.shape: (1623298,)
ic

cm_correct [[51823742    80436]
 [   29069   554606]]
cm_incorrect [[1362300  106920]
 [  72523   81555]]


| TP_H + FN_H + FP_H + TN_H: 1623298
    len(label_mask_current_deforestation_test): 54111151
ic| TP_H + FN_H + FP_H + TN_H: 1623298
    len(label_mask_current_deforestation_test): 54111151


[0.87333751 0.9501966  0.75175025 0.02999932 0.43270991 0.52930983]
0.40914751918696135
threshold 0.40914751918696135
(52474802,) (52474802,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1636349,)
    predicted_test_classified_incorrect.shape: (1636349,)
ic

cm_correct [[51812096    79818]
 [   28930   553958]]
cm_incorrect [[1373946  107538]
 [  72662   82203]]


| TP_H + FN_H + FP_H + TN_H: 1636349
    len(label_mask_current_deforestation_test): 54111151
ic| TP_H + FN_H + FP_H + TN_H: 1636349
    len(label_mask_current_deforestation_test): 54111151


[0.8740596  0.95036782 0.7508719  0.03024051 0.43323794 0.53080425]
0.41101765584570055
threshold 0.41101765584570055
(52489432,) (52489432,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1621719,)
    predicted_test_classified_incorrect.shape: (1621719,)
ic

cm_correct [[51825140    80516]
 [   29091   554685]]
cm_incorrect [[1360902  106840]
 [  72501   81476]]


| TP_H + FN_H + FP_H + TN_H: 1621719
    len(label_mask_current_deforestation_test): 54111151
ic| TP_H + FN_H + FP_H + TN_H: 1621719
    len(label_mask_current_deforestation_test): 54111151


[0.87324327 0.95016753 0.75185733 0.02997014 0.43265575 0.52914396]
0.4104409960468209
threshold 0.4104409960468209
(52484919,) (52484919,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1626232,)
    predicted_test_classified_incorrect.shape: (1626232,)


cm_correct [[51821136    80301]
 [   29028   554454]]


ic| TP_H + FN_H + FP_H + TN_H: 1626232
    len(label_mask_current_deforestation_test): 54111151
ic| TP_H + FN_H + FP_H + TN_H: 1626232
    len(label_mask_current_deforestation_test): 54111151


cm_incorrect [[1364906  107055]
 [  72564   81707]]
[0.87349292 0.95025039 0.75154422 0.03005355 0.43285725 0.52963292]
0.4107703406480584
threshold 0.4107703406480584
(52487462,) (52487462,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1623689,)
    predicted_test_classified_incorrect.shape: (1623689,)
ic

cm_correct [[51823399    80410]
 [   29061   554592]]
cm_incorrect [[1362643  106946]
 [  72531   81569]]


| TP_H + FN_H + FP_H + TN_H: 1623689
    len(label_mask_current_deforestation_test): 54111151
ic| TP_H + FN_H + FP_H + TN_H: 1623689
    len(label_mask_current_deforestation_test): 54111151


[0.87337048 0.95020843 0.75173127 0.03000655 0.43269236 0.52932511]
0.41085753502487943
threshold 0.41085753502487943
(52488124,) (52488124,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1623027,)
    predicted_test_classified_incorrect.shape: (1623027,)
ic

cm_correct [[51823987    80451]
 [   29070   554616]]
cm_incorrect [[1362055  106905]
 [  72522   81545]]


| TP_H + FN_H + FP_H + TN_H: 1623027
    len(label_mask_current_deforestation_test): 54111151
ic| TP_H + FN_H + FP_H + TN_H: 1623027
    len(label_mask_current_deforestation_test): 54111151
ic| self.threshold_optimal: 0.41082419559803857


[0.87331888 0.95019582 0.7517638  0.02999432 0.43271425 0.52928271]
threshold 0.41082419559803857
(52487853,) (52487853,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1623298,)
    predicted_test_classified_incorrect.shape: (1623298,)
ic

cm_correct [[51823742    80436]
 [   29069   554606]]
cm_incorrect [[1362300  106920]
 [  72523   81555]]


| TP_H + FN_H + FP_H + TN_H: 1623298
    len(label_mask_current_deforestation_test): 54111151
ic| TP_H + FN_H + FP_H + TN_H: 1623298
    len(label_mask_current_deforestation_test): 54111151


[0.87333751 0.9501966  0.75175025 0.02999932 0.43270991 0.52930983]
threshold 0.41082419559803857
(54111151,) (54111151,)


ic| self.m_optimal: {'AA': array([0.02999932]),
                     'f1': 81.49,
                     'f1_H': array([0.47615989]),
                     'f1_L': array([0.91014731]),
                     'precision_H': array([0.43270991]),
                     'precision_L': array([0.87333751]),
                     'recall_H': array([0.52930983]),
                     'recall_L': array([0.9501966]),
                     'recall_Ltotal': array([0.75175025])}
ic| self.m_audited_optimal: {'f1': array([0.92828153]),
                             'precision': array([0.89806873]),
                             'recall': array([0.96059792])}


cm_audited [[53292962    80436]
 [   29069   708684]]
[0.89806873 0.96059792]
D:/Jorge/datasets/deforestation/Para/deforestation_past_years.tif
Loaded deforestation past years


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Label where deforestation past years is actual date (2019) = 1


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation different from 0 (no deforestation)


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation before 2008 is 2
D:/Jorge/datasets/deforestation/deforestation_before_2008/deforestation_before_2008_para.tif


ic| np.unique(label_past_deforestation_before_2008, return_counts=True): (array([  0, 215], dtype=uint8), array([124211220,  38957970], dtype=int64))
ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))
ic| label_per_date.shape: (17730, 9203, 1)


Mask label shape:  
 (17730, 9203, 1) 
 Unique values:  
 [0 1 2]
Tiles size:  3546 2300
Mask size:  (17730, 9200)


ic| image_stack.shape: (17730, 9203, 21)


Image shape:  (17730, 9203, 21)
mask:  (17730, 9200)
image stack:  (17730, 9200, 21)
ref : (17730, 9200, 1)
Training tiles:  [1, 3, 5, 8, 11, 13, 14, 20]
Validation tiles:  [6, 19]
Test tiles:  [2, 4, 7, 9, 10, 12, 15, 16, 17, 18]


ic| im_idx_row.shape: (17730, 9200, 1)
    im_idx_col.shape: (17730, 9200, 1)
ic| im_idx_row.dtype: dtype('uint16')
    im_idx_col.dtype: dtype('uint16')
ic| im_idx.shape: (17730, 9200, 2), im_idx.dtype: dtype('uint16')
ic| coords.shape: (464, 239, 1, 128, 128, 2)
    coords.dtype: dtype('uint16')
ic| coords.shape: (110896, 2), coords.dtype: dtype('uint16')
ic| self.coords_train.shape: (41812, 3)
    self.coords_val.shape: (10260, 3)


training samples:  (3753, 3) validation samples:  (1032, 3)
time:  0
Model: "model_8"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_enc_net (InputLayer)      [(None, 128, 128, 21 0                                            
__________________________________________________________________________________________________
res1_net1 (Conv2D)              (None, 128, 128, 16) 3040        input_enc_net[0][0]              
__________________________________________________________________________________________________
drop_net1 (Dropout)             (None, 128, 128, 16) 0           res1_net1[0][0]                  
__________________________________________________________________________________________________
res2_net1 (Conv2D)              (None, 128, 128, 16) 2320        drop_net1[0][0]                  
_______________________

c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\keras\optimizer_v2\optimizer_v2.py:374: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  warnings.warn(
c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\keras\engine\training.py:1969: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  warnings.warn('`Model.fit_generator` is deprecated and '


Epoch 1/100
self.global_step 0.0
alpha Tensor("loss/add:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("loss/truediv:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("add:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("truediv:0", shape=(None, 128, 128, 1), dtype=float32)
K.int_shape(KL_reg) Tensor("mul_6:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("add_7:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("truediv_5:0", shape=(None, 128, 128, 1), dtype=float32)
K.int_shape(KL_reg) Tensor("mul_12:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("loss/add:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("loss/truediv:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("add:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("truediv:0", shape=(None, 128, 128, 1), dtype=float32)
K.int_shape(KL_reg) Tensor("mul_6:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("add_7:0", shape=(None, 128, 128, 3), dtype=float

c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py:494: CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.
  warnings.warn('Custom mask layers require a config and must override '


351/351 [==============================] - 32s 90ms/step - loss: 0.8333 - accuracy: 0.4023 - KL_term: -1.1126e-07 - loglikelihood_term: 0.8333 - evidential_success: 0.0000e+00 - evidential_fail: 0.0000e+00 - acc: 0.4028 - annealing_coef: 0.0933 - global_step_get: 350.0000 - annealing_step_get: 3750.0000 - val_loss: 0.8333 - val_accuracy: 0.3097 - val_KL_term: -2.2252e-07 - val_loglikelihood_term: 0.8333 - val_evidential_success: 0.0000e+00 - val_evidential_fail: 0.0000e+00 - val_acc: 0.3060 - val_annealing_coef: 0.1867 - val_global_step_get: 700.0000 - val_annealing_step_get: 3750.0000

Epoch 00002: val_loss did not improve from 0.83333
Epoch 3/100
self.global_step 700.0
351/351 [==============================] - 32s 90ms/step - loss: 0.8333 - accuracy: 0.4007 - KL_term: -1.6689e-07 - loglikelihood_term: 0.8333 - evidential_success: 0.0000e+00 - evidential_fail: 0.0000e+00 - acc: 0.4001 - annealing_coef: 0.1400 - global_step_get: 525.0000 - annealing_step_get: 3750.0000 - val_loss: 0.8

ic| self.path_models+ '/' + self.method +'_'+str(0)+'.h5': 'D:/Jorge/datasets/deforestation/experiments/exp159/models/resunet_0.h5'


time:  0
(54236371,)
(array([0, 1], dtype=uint8), array([53470765,   765606], dtype=int64))
(17730, 9200)
(array([0.], dtype=float32), array([163116000], dtype=int64))


ic| self.predicted_unpad.shape: (17730, 9200)
    self.predicted.shape: (17730, 9200)
ic| predicted_test.shape: (81558000,)
ic| predicted_test.shape: (54236371,)
ic| np.unique(predicted, return_counts=True): (array([0.], dtype=float32), array([163116000], dtype=int64))
    np.unique(predicted_larger_than_min_area, return_counts=True): (array([0.], dtype=float32), array([163116000], dtype=int64))
ic| np.unique(ignored_polygons, return_counts=True): (array([0.], dtype=float32), array([163116000], dtype=int64))
c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
ic| self.f1: 0.0, self.precision: 0.0, self.recall: 0.0
ic| self.label_mask_val.shape: (16311600,)
ic| self.label_mask_val_valid.shape: (9450701,)
c:\Users\jchamorro\Anaconda3\env

(array([0., 1.], dtype=float32), array([161277492,   1838508], dtype=int64))


ic| self.label_mask.shape: (17730, 9200)
ic| self.mask_amazon_ts.shape: (17730, 9200)
ic| self.label_mask_test.shape: (81558000,)
ic| self.error_mask_test.shape: (54236371,)
ic| bounds: (0.0015, 0.9985)
c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\scipy\optimize\_minimize.py:783: RuntimeWarning: Method 'bounded' does not support relative tolerance in x; defaulting to absolute tolerance.
  warn("Method 'bounded' does not support relative tolerance in x; "


0.38232011321635484
threshold 0.38232011321635484
(0,) (0,)
cm_correct []


IndexError: index 0 is out of bounds for axis 0 with size 0

In [7]:
print(results)

[{'metrics': {'precision_L': array([0.95284808]), 'recall_L': array([0.92463037]), 'recall_Ltotal': array([0.66954444]), 'AA': array([0.03000392]), 'precision_H': array([0.7081642]), 'recall_H': array([0.45883842]), 'f1_L': array([0.93852717]), 'f1_H': array([0.55686755]), 'f1': 84.63}, 'metrics_audited': {'precision': array([0.96614136]), 'recall': array([0.94542325]), 'f1': array([0.95567003])}}, {'metrics': {'precision_L': array([0.70923349]), 'recall_L': array([0.94157394]), 'recall_Ltotal': array([0.81054622]), 'AA': array([0.02999964]), 'precision_H': array([0.21662722]), 'recall_H': array([0.34096309]), 'f1_L': array([0.80905351]), 'f1_H': array([0.26493246]), 'f1': 72.65}, 'metrics_audited': {'precision': array([0.74079538]), 'recall': array([0.9497044]), 'f1': array([0.83234158])}}, {'metrics': {'precision_L': array([0.90384691]), 'recall_L': array([0.93505106]), 'recall_Ltotal': array([0.71629424]), 'AA': array([0.02999986]), 'precision_H': array([0.54003029]), 'recall_H': ar

In [12]:
trainer.f1

0.0

In [11]:
print(trainer.f1)

0.0
