In [1]:
from utils_v1 import *


In [ ]:
from icecream import ic

import numpy as np
from src.dataset import (
    MultipleDates,
    PA, PADeforestationTime, PADistanceMap, PAMultipleDates,
    MTDeforestationTime,
    MTMultipleDates
)

# from src.dataset_legacy import MTDeforestationTime
from src import training_generator as generator
from src.patchesHandler import PatchesHandler, PatchesHandlerMultipleDates, PatchesHandlerEvidential

from src.trainer.evidential import TrainerEvidential

from mpl_toolkits.axes_grid1 import make_axes_locatable

import cv2
from src import metrics as _metric
import json
import pickle 
import src.trainer.evidential as evidential


In [ ]:
'''
if config["training"] == True:
	dates = [2017, 2018]
else:
	dates = [2018, 2019]
if config["training"] == True:
	dates = [2018, 2019]
else:
	dates = [2019, 2020]
'''

	
dates = [2018, 2019]

dataset = PAMultipleDates(dates = dates, # dates = [2016,2017,2018,2019]
	addPastDeforestationInput = True,
	borderBuffer = 2)	


ic(dates)

if issubclass(type(dataset), MultipleDates):
	patchesHandler = PatchesHandlerEvidential(
		dataset)
else:
	patchesHandler = PatchesHandler()



ic| list(self.date_ids): [0]
ic| self.image_channels: [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]]
ic| dates: [2018, 2019]
ic| self.input_image_shape: 21
ic| self.dataset.image_channels: [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]]


In [ ]:
repetition_n = 6
experiment_values = np.ones(repetition_n).astype(np.uint8)


# experiment_values = [int(x) for x in experiment_values]
results = []

#exp_id_base = 148
# exp_id_base = 155
exp_id_base = 194
exp_id_base = 198


exp_ids = range(exp_id_base, exp_id_base+len(experiment_values))


In [ ]:
exp_ids

range(194, 204)

In [ ]:
from enum import Enum
UncertaintyMethod = Enum('Predictor', 'pred_var MI pred_entropy KL pred_entropy_single evidential')
uncertaintyMethod = "evidential"


In [ ]:
idx = 0
while idx < len(exp_ids):
# for experiment_value, exp_id in zip(experiment_values, exp_ids):
    try:
        config = {
        "training": True,
        "learning_rate": 1e-4,
        "weights": [0.1, 0.9, 0],
        "save_probabilities": False,
        "loadInference": False,
        "addPastDeforestationInput": True,
        "inference_times": 1,
        "Uncertainty": {
            "annealing_step": 10*375 # 1875
        },
        "uncertainty_method": uncertaintyMethod,
        "evidence_function": evidential.relu_evidence
        }
        print("Beginning run number {}".format(idx))
        trainer = TrainerEvidential(config, dataset, patchesHandler)

        trainer.defineExperiment(exp_ids[idx])

        trainer.setExperimentPath()
        trainer.createLogFolders()

        trainer.loadDataset()

        # %%
        if config["training"] == True:
            trainer.run()

        # %%
        result = trainer.run_predictor()
        print("Result idx {}: {}".format(idx, result))
        results.append(result)


        with open('log.pkl', 'wb') as f:
            pickle.dump(results, f)
        idx += 1
        print("Grid execution idx: {}".format(idx))
    except Exception as e: 
        print(e)
        print("Execution error in idx {}. Retrying...".format(idx))
        continue

Beginning run number 0
D:/Jorge/datasets/deforestation/Para/deforestation_past_years.tif
Loaded deforestation past years


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Label where deforestation past years is actual date (2019) = 1


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation different from 0 (no deforestation)


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation before 2008 is 2
D:/Jorge/datasets/deforestation/deforestation_before_2008/deforestation_before_2008_para.tif


ic| np.unique(label_past_deforestation_before_2008, return_counts=True): (array([  0, 215], dtype=uint8), array([124211220,  38957970], dtype=int64))
ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))
ic| label_per_date.shape: (17730, 9203, 1)


Mask label shape:  
 (17730, 9203, 1) 
 Unique values:  
 [0 1 2]
Tiles size:  3546 2300
Mask size:  (17730, 9200)


ic| image_stack.shape: (17730, 9203, 21)


Image shape:  (17730, 9203, 21)
mask:  (17730, 9200)
image stack:  (17730, 9200, 21)
ref : (17730, 9200, 1)
Training tiles:  [1, 3, 5, 8, 11, 13, 14, 20]
Validation tiles:  [6, 19]
Test tiles:  [2, 4, 7, 9, 10, 12, 15, 16, 17, 18]


ic| im_idx_row.shape: (17730, 9200, 1)
    im_idx_col.shape: (17730, 9200, 1)
ic| im_idx_row.dtype: dtype('uint16')
    im_idx_col.dtype: dtype('uint16')
ic| im_idx.shape: (17730, 9200, 2), im_idx.dtype: dtype('uint16')
ic| coords.shape: (464, 239, 1, 128, 128, 2)
    coords.dtype: dtype('uint16')
ic| coords.shape: (110896, 2), coords.dtype: dtype('uint16')
ic| self.coords_train.shape: (41812, 3)
    self.coords_val.shape: (10260, 3)


training samples:  (3753, 3) validation samples:  (1032, 3)
time:  0
Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_enc_net (InputLayer)      [(None, 128, 128, 21 0                                            
__________________________________________________________________________________________________
res1_net1 (Conv2D)              (None, 128, 128, 16) 3040        input_enc_net[0][0]              
__________________________________________________________________________________________________
drop_net1 (Dropout)             (None, 128, 128, 16) 0           res1_net1[0][0]                  
__________________________________________________________________________________________________
res2_net1 (Conv2D)              (None, 128, 128, 16) 2320        drop_net1[0][0]                  
_________________________

c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\keras\optimizer_v2\optimizer_v2.py:374: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  warnings.warn(
c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\keras\engine\training.py:1969: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  warnings.warn('`Model.fit_generator` is deprecated and '


Epoch 1/100
self.global_step 0.0
alpha Tensor("loss/add:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("loss/truediv:0", shape=(None, 128, 128, 1), dtype=float32)
A Tensor("loss/Sum_3:0", shape=(None, 3), dtype=float32)
B Tensor("loss/Sum_4:0", shape=(None, 1, 1, 3), dtype=float32)
term1 Tensor("loss/truediv_7:0", shape=(None, 1, 1, 3), dtype=float32)
term2 Tensor("loss/mul_5:0", shape=(None, 1, 1, 3), dtype=float32)
Tensor("loss/Repeat_1/Reshape_1:0", shape=(None, None, None, 1), dtype=float32)
alpha Tensor("add:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("truediv:0", shape=(None, 128, 128, 1), dtype=float32)
K.int_shape(KL_reg) Tensor("mul_6:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("add_7:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("truediv_5:0", shape=(None, 128, 128, 1), dtype=float32)
K.int_shape(KL_reg) Tensor("mul_12:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("add_16:0", shape=(None, 128, 128, 3), dtype=float32)
u T

c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py:494: CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.
  warnings.warn('Custom mask layers require a config and must override '


351/351 [==============================] - 32s 91ms/step - loss: 0.8026 - accuracy: 0.8789 - KL_term: 0.0159 - loglikelihood_term: 0.2052 - evidential_success: 30.3942 - evidential_fail: 7.9433 - acc: 0.8789 - annealing_coef: 0.0933 - global_step_get: 350.0000 - annealing_step_get: 3750.0000 - UEO_term: 0.3818 - val_loss: 0.9303 - val_accuracy: 0.5278 - val_KL_term: 0.0762 - val_loglikelihood_term: 0.6221 - val_evidential_success: 18.9896 - val_evidential_fail: 3.5484 - val_acc: 0.5190 - val_annealing_coef: 0.1867 - val_global_step_get: 700.0000 - val_annealing_step_get: 3750.0000 - val_UEO_term: 0.4936

Epoch 00002: val_loss improved from 0.93336 to 0.93030, saving model to D:/Jorge/datasets/deforestation/experiments/exp194/models\resunet_0.h5
Epoch 3/100
self.global_step 700.0
351/351 [==============================] - 32s 91ms/step - loss: 0.7953 - accuracy: 0.8979 - KL_term: 0.0174 - loglikelihood_term: 0.1761 - evidential_success: 35.9400 - evidential_fail: 7.0291 - acc: 0.8978 - 

ic| self.path_models+ '/' + self.method +'_'+str(0)+'.h5': 'D:/Jorge/datasets/deforestation/experiments/exp194/models/resunet_0.h5'


time:  0
(54236371,)
(array([0, 1], dtype=uint8), array([53470765,   765606], dtype=int64))
(17730, 9200)
(array([0., 1.], dtype=float32), array([161359966,   1756034], dtype=int64))


ic| self.predicted_unpad.shape: (17730, 9200)
    self.predicted.shape: (17730, 9200)
ic| predicted_test.shape: (81558000,)
ic| predicted_test.shape: (54236371,)
ic| np.unique(predicted, return_counts=True): (array([0., 1.], dtype=float32), array([161359966,   1756034], dtype=int64))
    np.unique(predicted_larger_than_min_area, return_counts=True): (array([0., 1.], dtype=float32), array([161681613,   1434387], dtype=int64))
ic| np.unique(ignored_polygons, return_counts=True): (array([0., 1.], dtype=float32), array([162794353,    321647], dtype=int64))
ic| self.f1: 77.05, self.precision: 86.96, self.recall: 69.16
ic| self.label_mask_val.shape: (16311600,)
ic| self.label_mask_val_valid.shape: (9417288,)
ic| f1_val: 78.85
    precision_val: 85.01
    recall_val: 73.53
    mAP_val: 88.17


(array([0., 1.], dtype=float32), array([162297181,    818819], dtype=int64))
[0. 1.]


ic| self.label_mask.shape: (17730, 9200)
ic| self.mask_amazon_ts.shape: (17730, 9200)
ic| self.label_mask_test.shape: (81558000,)
ic| self.error_mask_test.shape: (54079850,)


(54079850,) (54079850,)


ic| bounds: (0.0015, 0.9985)


0.3845722890780702
0
0.38232011321635484
threshold 0.38232011321635484


c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\scipy\optimize\_minimize.py:783: RuntimeWarning: Method 'bounded' does not support relative tolerance in x; defaulting to absolute tolerance.
  warn("Method 'bounded' does not support relative tolerance in x; "


(51707761,) (51707761,)


ic| label_current_deforestation_test_classified_incorrect.shape: (2372089,)
    predicted_test_classified_incorrect.shape: (2372089,)


cm_correct [[51222549    42344]
 [   19989   422879]]


ic| TP_H + FN_H + FP_H + TN_H: 2372089
    len(label_mask_current_deforestation_test): 54079850
ic| TP_H + FN_H + FP_H + TN_H: 2372089
    len(label_mask_current_deforestation_test): 54079850


cm_incorrect [[2056630   32860]
 [ 203744   78855]]
[0.90898128 0.95486465 0.58290591 0.04386271 0.70585866 0.27903496
 0.09719104]
0.6176798867836452
threshold 0.6176798867836452
(52624483,) (52624483,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1455367,)
    predicted_test_classified_incorrect.shape: (1455367,)
ic| TP_H + FN_H + FP_H + TN_H: 1455367
    len(label_mask_current_deforestation_test): 54079850
ic|

cm_correct [[52063531    62943]
 [   26200   471809]]
cm_incorrect [[1215648   12261]
 [ 197533   29925]]


 TP_H + FN_H + FP_H + TN_H: 1455367
    len(label_mask_current_deforestation_test): 54079850


[0.88229497 0.94739051 0.65035212 0.02691145 0.70935855 0.13156275
 0.13583208]
0.7631402264327096
threshold 0.7631402264327096
(53003500,) (53003500,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1076350,)
    predicted_test_classified_incorrect.shape: (1076350,)
d:\Jorge\deforestation_uncertainty\src\metrics.py:295: RuntimeWarning: invalid value encountered in longlong_scalars
  precision_H = TP_H / (TP_H + FP_H)
ic| TP_H + FN_H + FP_H + TN_H: 1076350
    len(label_mask_current_deforestation_test): 54079850
ic| TP_H + FN_H + FP_H + TN_H: 1076350
    len(label_mask_current_deforestation_test): 54079850


cm_correct [[52391680    75204]
 [   34882   501734]]
cm_incorrect [[887499      0]
 [188851      0]]
[0.86964977 0.93499635 0.69160141 0.01990298        nan 0.
 0.15917504]
0.5927692406058288
threshold 0.5927692406058288
(52547493,) (52547493,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1532357,)
    predicted_test_classified_incorrect.shape: (1532357,)
ic

cm_correct [[51994902    60790]
 [   25554   466247]]
cm_incorrect [[1284277   14414]
 [ 198179   35487]]


| TP_H + FN_H + FP_H + TN_H: 1532357
    len(label_mask_current_deforestation_test): 54079850
ic| TP_H + FN_H + FP_H + TN_H: 1532357
    len(label_mask_current_deforestation_test): 54079850


[0.88465705 0.94803996 0.64268533 0.02833508 0.71114807 0.15187062
 0.13133556]
0.5123848268458062
threshold 0.5123848268458062
(52272916,) (52272916,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1806934,)
    predicted_test_classified_incorrect.shape: (1806934,)


cm_correct [[51745329    54008]
 [   23576   450003]]


ic| TP_H + FN_H + FP_H + TN_H: 1806934
    len(label_mask_current_deforestation_test): 54079850
ic| TP_H + FN_H + FP_H + TN_H: 1806934
    len(label_mask_current_deforestation_test): 54079850


cm_incorrect [[1533850   21196]
 [ 200157   51731]]
[0.89284361 0.95021739 0.62029424 0.03341233 0.70935319 0.20537302
 0.11745868]
0.5670845115586073
threshold 0.5670845115586073
(52464159,) (52464159,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1615691,)
    predicted_test_classified_incorrect.shape: (1615691,)
ic

cm_correct [[51919800    58596]
 [   24902   460861]]
cm_incorrect [[1359379   16608]
 [ 198831   40873]]


| TP_H + FN_H + FP_H + TN_H: 1615691
    len(label_mask_current_deforestation_test): 54079850
ic| TP_H + FN_H + FP_H + TN_H: 1615691
    len(label_mask_current_deforestation_test): 54079850


[0.88719759 0.94873632 0.63526115 0.02987603 0.71106974 0.17051447
 0.12678931]
0.5461910911722203
threshold 0.5461910911722203
(52393086,) (52393086,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1686764,)
    predicted_test_classified_incorrect.shape: (1686764,)


cm_correct [[51855279    56797]
 [   24385   456625]]


ic| TP_H + FN_H + FP_H + TN_H: 1686764
    len(label_mask_current_deforestation_test): 54079850
ic| TP_H + FN_H + FP_H + TN_H: 1686764
    len(label_mask_current_deforestation_test): 54079850


cm_incorrect [[1423900   18407]
 [ 199348   45109]]
[0.8893756  0.94930459 0.62942215 0.03119025 0.710199   0.18452734
 0.12316835]
0.5673425696059541
threshold 0.5673425696059541
(52465026,) (52465026,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1614824,)
    predicted_test_classified_incorrect.shape: (1614824,)
ic

cm_correct [[51920580    58619]
 [   24908   460919]]
cm_incorrect [[1358599   16585]
 [ 198825   40815]]


| TP_H + FN_H + FP_H + TN_H: 1614824
    len(label_mask_current_deforestation_test): 54079850
ic| TP_H + FN_H + FP_H + TN_H: 1614824
    len(label_mask_current_deforestation_test): 54079850


[0.88717091 0.94873072 0.6353411  0.02985999 0.71106272 0.17031798
 0.12683479]
0.5614073954440004
threshold 0.5614073954440004
(52445361,) (52445361,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1634489,)
    predicted_test_classified_incorrect.shape: (1634489,)
ic

cm_correct [[51902757    58086]
 [   24771   459747]]
cm_incorrect [[1376422   17118]
 [ 198962   41987]]


| TP_H + FN_H + FP_H + TN_H: 1634489
    len(label_mask_current_deforestation_test): 54079850
ic| TP_H + FN_H + FP_H + TN_H: 1634489
    len(label_mask_current_deforestation_test): 54079850


[0.8878287  0.94887496 0.63372559 0.03022362 0.71037983 0.17425679
 0.12582205]
0.5649160461609072
threshold 0.5649160461609072
(52456962,) (52456962,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1622888,)
    predicted_test_classified_incorrect.shape: (1622888,)
ic

cm_correct [[51913272    58405]
 [   24848   460437]]
cm_incorrect [[1365907   16799]
 [ 198885   41297]]


| TP_H + FN_H + FP_H + TN_H: 1622888
    len(label_mask_current_deforestation_test): 54079850
ic| TP_H + FN_H + FP_H + TN_H: 1622888
    len(label_mask_current_deforestation_test): 54079850


[0.88743201 0.9487971  0.6346767  0.03000911 0.71084068 0.17194045
 0.12641628]
0.5635758608417005
threshold 0.5635758608417005
(52452627,) (52452627,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1627223,)
    predicted_test_classified_incorrect.shape: (1627223,)
ic

cm_correct [[51909350    58284]
 [   24822   460171]]
cm_incorrect [[1369829   16920]
 [ 198911   41563]]


| TP_H + FN_H + FP_H + TN_H: 1627223
    len(label_mask_current_deforestation_test): 54079850
ic| TP_H + FN_H + FP_H + TN_H: 1627223
    len(label_mask_current_deforestation_test): 54079850


[0.88758137 0.94881988 0.63431004 0.03008927 0.71068516 0.17283781
 0.12619268]
0.565176316739369
threshold 0.565176316739369
(52457818,) (52457818,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1622032,)
    predicted_test_classified_incorrect.shape: (1622032,)
ic

cm_correct [[51914035    58433]
 [   24860   460490]]
cm_incorrect [[1365144   16771]
 [ 198873   41244]]


| TP_H + FN_H + FP_H + TN_H: 1622032
    len(label_mask_current_deforestation_test): 54079850
ic| TP_H + FN_H + FP_H + TN_H: 1622032
    len(label_mask_current_deforestation_test): 54079850


[0.88739563 0.94877923 0.63474975 0.02999328 0.71091959 0.17176626
 0.12645332]
0.5652096584556218
threshold 0.5652096584556218
(52457939,) (52457939,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1621911,)
    predicted_test_classified_incorrect.shape: (1621911,)
ic

cm_correct [[51914143    58436]
 [   24862   460498]]
cm_incorrect [[1365036   16768]
 [ 198871   41236]]


| TP_H + FN_H + FP_H + TN_H: 1621911
    len(label_mask_current_deforestation_test): 54079850
ic| TP_H + FN_H + FP_H + TN_H: 1621911
    len(label_mask_current_deforestation_test): 54079850


[0.88739223 0.94877617 0.63476078 0.02999104 0.71091649 0.1717401
 0.12645899]
0.5650638220697976
threshold 0.5650638220697976
(52457454,) (52457454,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1622396,)
    predicted_test_classified_incorrect.shape: (1622396,)
ic

cm_correct [[51913707    58423]
 [   24857   460467]]
cm_incorrect [[1365472   16781]
 [ 198876   41267]]


| TP_H + FN_H + FP_H + TN_H: 1622396
    len(label_mask_current_deforestation_test): 54079850
ic| TP_H + FN_H + FP_H + TN_H: 1622396
    len(label_mask_current_deforestation_test): 54079850


[0.88740774 0.94878267 0.63471805 0.03000001 0.71091166 0.17184344
 0.12643491]
0.5650073766953199
threshold 0.5650073766953199
(52457264,) (52457264,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1622586,)
    predicted_test_classified_incorrect.shape: (1622586,)
ic

cm_correct [[51913540    58414]
 [   24852   460458]]
cm_incorrect [[1365639   16790]
 [ 198881   41276]]


| TP_H + FN_H + FP_H + TN_H: 1622586
    len(label_mask_current_deforestation_test): 54079850
ic| TP_H + FN_H + FP_H + TN_H: 1622586
    len(label_mask_current_deforestation_test): 54079850


[0.88742118 0.94879149 0.63470564 0.03000352 0.71084628 0.1718709
 0.12643008]
0.5650971637843818
threshold 0.5650971637843818
(52457577,) (52457577,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1622273,)
    predicted_test_classified_incorrect.shape: (1622273,)
ic

cm_correct [[51913818    58424]
 [   24859   460476]]
cm_incorrect [[1365361   16780]
 [ 198874   41258]]


| TP_H + FN_H + FP_H + TN_H: 1622273
    len(label_mask_current_deforestation_test): 54079850
ic| TP_H + FN_H + FP_H + TN_H: 1622273
    len(label_mask_current_deforestation_test): 54079850
ic| self.threshold_optimal: 0.5650638220697976


[0.88740798 0.94877971 0.63473046 0.02999773 0.71087908 0.17181384
 0.12644205]
threshold 0.5650638220697976
(52457454,) (52457454,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1622396,)
    predicted_test_classified_incorrect.shape: (1622396,)
ic

cm_correct [[51913707    58423]
 [   24857   460467]]
cm_incorrect [[1365472   16781]
 [ 198876   41267]]


| TP_H + FN_H + FP_H + TN_H: 1622396
    len(label_mask_current_deforestation_test): 54079850
ic| TP_H + FN_H + FP_H + TN_H: 1622396
    len(label_mask_current_deforestation_test): 54079850


[0.88740774 0.94878267 0.63471805 0.03000001 0.71091166 0.17184344
 0.12643491]
threshold 0.5650638220697976
(54079850,) (54079850,)


ic| self.m_optimal: {'AA': array([0.03000001]),
                     'UEO': array([0.12643491]),
                     'f1': 77.05,
                     'f1_H': array([0.27678233]),
                     'f1_L': array([0.91706947]),
                     'precision_H': array([0.71091166]),
                     'precision_L': array([0.88740774]),
                     'recall_H': array([0.17184344]),
                     'recall_L': array([0.94878267]),
                     'recall_Ltotal': array([0.63471805])}
ic| self.m_audited_optimal: {'f1': array([0.9439003]),
                             'precision': array([0.9230297]),
                             'recall': array([0.96573655])}


cm_audited [[53295960    58423]
 [   24857   700610]]
[0.9230297  0.96573655]
Result idx 0: {'other_uncertainty_metrics': {'sUEO': 0.3845722890780702, 'ece_score': 0}, 'snippet_poi_results': [{'snippet_id': 0, 'coords': [550, 550], 'reference': 0, 'predicted': 0.0, 'alpha': array([132.42505,   1.     ,   1.     ], dtype=float32)}, {'snippet_id': 0, 'coords': [210, 610], 'reference': 1, 'predicted': 0.0, 'alpha': array([1., 1., 1.], dtype=float32)}, {'snippet_id': 0, 'coords': [207, 617], 'reference': 1, 'predicted': 0.0, 'alpha': array([1., 1., 1.], dtype=float32)}, {'snippet_id': 0, 'coords': [800, 200], 'reference': 1, 'predicted': 1.0, 'alpha': array([ 1.     , 49.57395,  1.     ], dtype=float32)}, {'snippet_id': 1, 'coords': [550, 115], 'reference': 1, 'predicted': 0.0, 'alpha': array([1.       , 1.5210117, 1.       ], dtype=float32)}, {'snippet_id': 1, 'coords': [430, 950], 'reference': 0, 'predicted': 0.0, 'alpha': array([1., 1., 1.], dtype=float32)}], 'uncertainty_result': {'met

ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Label where deforestation past years is actual date (2019) = 1


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation different from 0 (no deforestation)


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation before 2008 is 2
D:/Jorge/datasets/deforestation/deforestation_before_2008/deforestation_before_2008_para.tif


ic| np.unique(label_past_deforestation_before_2008, return_counts=True): (array([  0, 215], dtype=uint8), array([124211220,  38957970], dtype=int64))
ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))
ic| label_per_date.shape: (17730, 9203, 1)


Mask label shape:  
 (17730, 9203, 1) 
 Unique values:  
 [0 1 2]
Tiles size:  3546 2300
Mask size:  (17730, 9200)


ic| image_stack.shape: (17730, 9203, 21)


Image shape:  (17730, 9203, 21)
mask:  (17730, 9200)
image stack:  (17730, 9200, 21)
ref : (17730, 9200, 1)
Training tiles:  [1, 3, 5, 8, 11, 13, 14, 20]
Validation tiles:  [6, 19]
Test tiles:  [2, 4, 7, 9, 10, 12, 15, 16, 17, 18]


ic| im_idx_row.shape: (17730, 9200, 1)
    im_idx_col.shape: (17730, 9200, 1)
ic| im_idx_row.dtype: dtype('uint16')
    im_idx_col.dtype: dtype('uint16')
ic| im_idx.shape: (17730, 9200, 2), im_idx.dtype: dtype('uint16')
ic| coords.shape: (464, 239, 1, 128, 128, 2)
    coords.dtype: dtype('uint16')
ic| coords.shape: (110896, 2), coords.dtype: dtype('uint16')
ic| self.coords_train.shape: (41812, 3)
    self.coords_val.shape: (10260, 3)


training samples:  (3753, 3) validation samples:  (1032, 3)
time:  0
Model: "model_2"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_enc_net (InputLayer)      [(None, 128, 128, 21 0                                            
__________________________________________________________________________________________________
res1_net1 (Conv2D)              (None, 128, 128, 16) 3040        input_enc_net[0][0]              
__________________________________________________________________________________________________
drop_net1 (Dropout)             (None, 128, 128, 16) 0           res1_net1[0][0]                  
__________________________________________________________________________________________________
res2_net1 (Conv2D)              (None, 128, 128, 16) 2320        drop_net1[0][0]                  
_______________________

c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\keras\optimizer_v2\optimizer_v2.py:374: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  warnings.warn(
c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\keras\engine\training.py:1969: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  warnings.warn('`Model.fit_generator` is deprecated and '


Epoch 1/100
self.global_step 0.0
alpha Tensor("loss/add:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("loss/truediv:0", shape=(None, 128, 128, 1), dtype=float32)
A Tensor("loss/Sum_3:0", shape=(None, 3), dtype=float32)
B Tensor("loss/Sum_4:0", shape=(None, 1, 1, 3), dtype=float32)
term1 Tensor("loss/truediv_7:0", shape=(None, 1, 1, 3), dtype=float32)
term2 Tensor("loss/mul_5:0", shape=(None, 1, 1, 3), dtype=float32)
Tensor("loss/Repeat_1/Reshape_1:0", shape=(None, None, None, 1), dtype=float32)
alpha Tensor("add:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("truediv:0", shape=(None, 128, 128, 1), dtype=float32)
K.int_shape(KL_reg) Tensor("mul_6:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("add_7:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("truediv_5:0", shape=(None, 128, 128, 1), dtype=float32)
K.int_shape(KL_reg) Tensor("mul_12:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("add_16:0", shape=(None, 128, 128, 3), dtype=float32)
u T

c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py:494: CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.
  warnings.warn('Custom mask layers require a config and must override '


351/351 [==============================] - 32s 92ms/step - loss: 0.8090 - accuracy: 0.8860 - KL_term: 0.0158 - loglikelihood_term: 0.1991 - evidential_success: 31.7483 - evidential_fail: 8.1952 - acc: 0.8860 - annealing_coef: 0.0933 - global_step_get: 350.0000 - annealing_step_get: 3750.0000 - UEO_term: 0.3896 - val_loss: 0.8129 - val_accuracy: 0.8946 - val_KL_term: 0.0318 - val_loglikelihood_term: 0.1846 - val_evidential_success: 34.4563 - val_evidential_fail: 7.4932 - val_acc: 0.8958 - val_annealing_coef: 0.1867 - val_global_step_get: 700.0000 - val_annealing_step_get: 3750.0000 - val_UEO_term: 0.3886

Epoch 00002: val_loss improved from 0.87933 to 0.81290, saving model to D:/Jorge/datasets/deforestation/experiments/exp195/models\resunet_0.h5
Epoch 3/100
self.global_step 700.0
351/351 [==============================] - 32s 91ms/step - loss: 0.7955 - accuracy: 0.9030 - KL_term: 0.0172 - loglikelihood_term: 0.1697 - evidential_success: 38.7231 - evidential_fail: 7.3930 - acc: 0.9030 - 

ic| self.path_models+ '/' + self.method +'_'+str(0)+'.h5': 'D:/Jorge/datasets/deforestation/experiments/exp195/models/resunet_0.h5'


time:  0
(54236371,)
(array([0, 1], dtype=uint8), array([53470765,   765606], dtype=int64))
(17730, 9200)
(array([0., 1.], dtype=float32), array([161465114,   1650886], dtype=int64))


ic| self.predicted_unpad.shape: (17730, 9200)
    self.predicted.shape: (17730, 9200)
ic| predicted_test.shape: (81558000,)
ic| predicted_test.shape: (54236371,)
ic| np.unique(predicted, return_counts=True): (array([0., 1.], dtype=float32), array([161465114,   1650886], dtype=int64))
    np.unique(predicted_larger_than_min_area, return_counts=True): (array([0., 1.], dtype=float32), array([161736422,   1379578], dtype=int64))
ic| np.unique(ignored_polygons, return_counts=True): (array([0., 1.], dtype=float32), array([162844692,    271308], dtype=int64))
ic| self.f1: 78.78, self.precision: 88.6, self.recall: 70.91
ic| self.label_mask_val.shape: (16311600,)
ic| self.label_mask_val_valid.shape: (9418680,)
ic| f1_val: 78.96
    precision_val: 87.89
    recall_val: 71.68
    mAP_val: 86.7


(array([0., 1.], dtype=float32), array([162316504,    799496], dtype=int64))
[0. 1.]


ic| self.label_mask.shape: (17730, 9200)
ic| self.mask_amazon_ts.shape: (17730, 9200)
ic| self.label_mask_test.shape: (81558000,)
ic| self.error_mask_test.shape: (54102424,)


(54102424,) (54102424,)


ic| bounds: (0.0015, 0.9985)


0.4216257755386668
0
0.38232011321635484
threshold 0.38232011321635484


c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\scipy\optimize\_minimize.py:783: RuntimeWarning: Method 'bounded' does not support relative tolerance in x; defaulting to absolute tolerance.
  warn("Method 'bounded' does not support relative tolerance in x; "


(52069355,) (52069355,)


ic| label_current_deforestation_test_classified_incorrect.shape: (2033069,)
    predicted_test_classified_incorrect.shape: (2033069,)


cm_correct [[51617474    26174]
 [   28566   397141]]


ic| TP_H + FN_H + FP_H + TN_H: 2033069
    len(label_mask_current_deforestation_test): 54102424
ic| TP_H + FN_H + FP_H + TN_H: 2033069
    len(label_mask_current_deforestation_test): 54102424


cm_incorrect [[1687657   40458]
 [ 183981  120973]]
[0.93816898 0.93289751 0.54353661 0.03757815 0.74937899 0.39669262
 0.10749978]
0.6176798867836452
threshold 0.6176798867836452
(52918904,) (52918904,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1183520,)
    predicted_test_classified_incorrect.shape: (1183520,)
ic| TP_H + FN_H + FP_H + TN_H: 1183520
    len(label_mask_current_deforestation_test): 54102424
ic| TP_H + FN_H + FP_H + TN_H: 1183520
    len(label_mask_current_deforestation_test): 54102424


cm_correct [[52357567    49698]
 [   35666   475973]]
cm_incorrect [[947564  16934]
 [176881  42141]]
[0.90545798 0.93029069 0.65142795 0.02187554 0.71334744 0.19240533
 0.15274446]
0.23685977356729035
threshold 0.23685977356729035
(51165547,) (51165547,)


ic| label_current_deforestation_test_classified_incorrect.shape: (2936877,)
    predicted_test_classified_incorrect.shape: (2936877,)


cm_correct [[50827195     9787]
 [   23008   305557]]


ic| TP_H + FN_H + FP_H + TN_H: 2936877
    len(label_mask_current_deforestation_test): 54102424
ic| TP_H + FN_H + FP_H + TN_H: 2936877
    len(label_mask_current_deforestation_test): 54102424


cm_incorrect [[2477936   56845]
 [ 189539  212557]]
[0.96896405 0.92997428 0.41819257 0.05428365 0.78899563 0.52862252
 0.08296674]
0.49622785679192494
threshold 0.49622785679192494
(52509697,) (52509697,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1592727,)
    predicted_test_classified_incorrect.shape: (1592727,)
ic

cm_correct [[52000666    37375]
 [   31919   439737]]
cm_incorrect [[1304465   29257]
 [ 180628   78377]]


| TP_H + FN_H + FP_H + TN_H: 1592727
    len(label_mask_current_deforestation_test): 54102424
ic| TP_H + FN_H + FP_H + TN_H: 1592727
    len(label_mask_current_deforestation_test): 54102424


[0.9216641  0.93232568 0.6018345  0.02943911 0.72818069 0.30260806
 0.126283  ]
0.4977950374501111
threshold 0.4977950374501111
(52514959,) (52514959,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1587465,)
    predicted_test_classified_incorrect.shape: (1587465,)
ic

cm_correct [[52005259    37526]
 [   31963   440211]]
cm_incorrect [[1299872   29106]
 [ 180584   77903]]


| TP_H + FN_H + FP_H + TN_H: 1587465
    len(label_mask_current_deforestation_test): 54102424
ic| TP_H + FN_H + FP_H + TN_H: 1587465
    len(label_mask_current_deforestation_test): 54102424


[0.92145051 0.93230673 0.60248323 0.02934185 0.72800419 0.30138073
 0.12655149]
0.46803632747768253
threshold 0.46803632747768253
(52412780,) (52412780,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1689644,)
    predicted_test_classified_incorrect.shape: (1689644,)
ic

cm_correct [[51916506    34713]
 [   31110   430451]]
cm_incorrect [[1388625   31919]
 [ 181437   87663]]


| TP_H + FN_H + FP_H + TN_H: 1689644
    len(label_mask_current_deforestation_test): 54102424
ic| TP_H + FN_H + FP_H + TN_H: 1689644
    len(label_mask_current_deforestation_test): 54102424


[0.92537471 0.93259829 0.58912546 0.03123047 0.73307856 0.32576366
 0.12153803]
0.48545965078872333
threshold 0.48545965078872333
(52473097,) (52473097,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1629327,)
    predicted_test_classified_incorrect.shape: (1629327,)
ic

cm_correct [[51968899    36365]
 [   31618   436215]]
cm_incorrect [[1336232   30267]
 [ 180929   81899]]


| TP_H + FN_H + FP_H + TN_H: 1629327
    len(label_mask_current_deforestation_test): 54102424
ic| TP_H + FN_H + FP_H + TN_H: 1629327
    len(label_mask_current_deforestation_test): 54102424


[0.92305007 0.93241605 0.59701421 0.0301156  0.73015887 0.31160683
 0.12442983]
0.4785271845547386
threshold 0.4785271845547386
(52449264,) (52449264,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1653160,)
    predicted_test_classified_incorrect.shape: (1653160,)
ic

cm_correct [[51948215    35691]
 [   31403   433955]]
cm_incorrect [[1356916   30941]
 [ 181144   84159]]


| TP_H + FN_H + FP_H + TN_H: 1653160
    len(label_mask_current_deforestation_test): 54102424
ic| TP_H + FN_H + FP_H + TN_H: 1653160
    len(label_mask_current_deforestation_test): 54102424


[0.92400446 0.93251862 0.59392112 0.03055612 0.73118158 0.31721843
 0.12328703]
0.48735475125940236
threshold 0.48735475125940236
(52479647,) (52479647,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1622777,)
    predicted_test_classified_incorrect.shape: (1622777,)
ic

cm_correct [[51974582    36545]
 [   31682   436838]]
cm_incorrect [[1330549   30087]
 [ 180865   81276]]


| TP_H + FN_H + FP_H + TN_H: 1622777
    len(label_mask_current_deforestation_test): 54102424
ic| TP_H + FN_H + FP_H + TN_H: 1622777
    len(label_mask_current_deforestation_test): 54102424


[0.92280035 0.93237855 0.59786686 0.02999453 0.72982948 0.31004688
 0.12474956]
0.49074397598706126
threshold 0.49074397598706126
(52491066,) (52491066,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1611358,)
    predicted_test_classified_incorrect.shape: (1611358,)
ic

cm_correct [[51984444    36891]
 [   31768   437963]]
cm_incorrect [[1320687   29741]
 [ 180779   80151]]


| TP_H + FN_H + FP_H + TN_H: 1611358
    len(label_mask_current_deforestation_test): 54102424
ic| TP_H + FN_H + FP_H + TN_H: 1611358
    len(label_mask_current_deforestation_test): 54102424


[0.92231086 0.9323698  0.59940656 0.02978347 0.72936155 0.30717434
 0.12530826]
0.48768264362685876
threshold 0.48768264362685876
(52480734,) (52480734,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1621690,)
    predicted_test_classified_incorrect.shape: (1621690,)
ic

cm_correct [[51975517    36581]
 [   31692   436944]]
cm_incorrect [[1329614   30051]
 [ 180855   81170]]


| TP_H + FN_H + FP_H + TN_H: 1621690
    len(label_mask_current_deforestation_test): 54102424
ic| TP_H + FN_H + FP_H + TN_H: 1621690
    len(label_mask_current_deforestation_test): 54102424


[0.92274748 0.93237395 0.59801194 0.02997444 0.72980822 0.3097796
 0.12479918]
0.48694824354176974
threshold 0.48694824354176974
(52478206,) (52478206,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1624218,)
    predicted_test_classified_incorrect.shape: (1624218,)
ic

cm_correct [[51973311    36504]
 [   31666   436725]]
cm_incorrect [[1331820   30128]
 [ 180881   81389]]


| TP_H + FN_H + FP_H + TN_H: 1624218
    len(label_mask_current_deforestation_test): 54102424
ic| TP_H + FN_H + FP_H + TN_H: 1624218
    len(label_mask_current_deforestation_test): 54102424


[0.92286187 0.93239409 0.59771221 0.03002117 0.72983491 0.31032524
 0.12468122]
0.4872934787818929
threshold 0.4872934787818929
(52479420,) (52479420,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1623004,)
    predicted_test_classified_incorrect.shape: (1623004,)
ic

cm_correct [[51974389    36531]
 [   31678   436822]]
cm_incorrect [[1330742   30101]
 [ 180869   81292]]


| TP_H + FN_H + FP_H + TN_H: 1623004
    len(label_mask_current_deforestation_test): 54102424
ic| TP_H + FN_H + FP_H + TN_H: 1623004
    len(label_mask_current_deforestation_test): 54102424


[0.92282504 0.9323842  0.59784497 0.02999873 0.72977656 0.31008426
 0.12474478]
0.4872137535562624
threshold 0.4872137535562624
(52479140,) (52479140,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1623284,)
    predicted_test_classified_incorrect.shape: (1623284,)
ic

cm_correct [[51974138    36526]
 [   31675   436801]]
cm_incorrect [[1330993   30106]
 [ 180872   81313]]


| TP_H + FN_H + FP_H + TN_H: 1623284
    len(label_mask_current_deforestation_test): 54102424
ic| TP_H + FN_H + FP_H + TN_H: 1623284
    len(label_mask_current_deforestation_test): 54102424


[0.92283136 0.93238714 0.59781622 0.03000391 0.72979474 0.31013597
 0.12472945]
0.48726013822082925
threshold 0.48726013822082925
(52479297,) (52479297,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1623127,)
    predicted_test_classified_incorrect.shape: (1623127,)
ic

cm_correct [[51974282    36529]
 [   31676   436810]]
cm_incorrect [[1330849   30103]
 [ 180871   81304]]


| TP_H + FN_H + FP_H + TN_H: 1623127
    len(label_mask_current_deforestation_test): 54102424
ic| TP_H + FN_H + FP_H + TN_H: 1623127
    len(label_mask_current_deforestation_test): 54102424
ic| self.threshold_optimal: 0.48726013822082925


[0.92282698 0.93238645 0.59782854 0.030001   0.72979256 0.31011347
 0.12473837]
threshold 0.48726013822082925
(52479297,) (52479297,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1623127,)
    predicted_test_classified_incorrect.shape: (1623127,)
ic

cm_correct [[51974282    36529]
 [   31676   436810]]
cm_incorrect [[1330849   30103]
 [ 180871   81304]]


| TP_H + FN_H + FP_H + TN_H: 1623127
    len(label_mask_current_deforestation_test): 54102424
ic| TP_H + FN_H + FP_H + TN_H: 1623127
    len(label_mask_current_deforestation_test): 54102424


[0.92282698 0.93238645 0.59782854 0.030001   0.72979256 0.31011347
 0.12473837]
threshold 0.48726013822082925
(54102424,) (54102424,)


ic| self.m_optimal: {'AA': array([0.030001]),
                     'UEO': array([0.12473837]),
                     'f1': 78.78,
                     'f1_H': array([0.43526722]),
                     'f1_L': array([0.92758209]),
                     'precision_H': array([0.72979256]),
                     'precision_L': array([0.92282698]),
                     'recall_H': array([0.31011347]),
                     'recall_L': array([0.93238645]),
                     'recall_Ltotal': array([0.59782854])}
ic| self.m_audited_optimal: {'f1': array([0.953481]),
                             'precision': array([0.95033541]),
                             'recall': array([0.95664747])}


cm_audited [[53335234    36529]
 [   31676   698985]]
[0.95033541 0.95664747]
Result idx 1: {'other_uncertainty_metrics': {'sUEO': 0.4216257755386668, 'ece_score': 0}, 'snippet_poi_results': [{'snippet_id': 0, 'coords': [550, 550], 'reference': 0, 'predicted': 0.0, 'alpha': array([136.90787,   1.     ,   1.     ], dtype=float32)}, {'snippet_id': 0, 'coords': [210, 610], 'reference': 1, 'predicted': 0.0, 'alpha': array([1., 1., 1.], dtype=float32)}, {'snippet_id': 0, 'coords': [207, 617], 'reference': 1, 'predicted': 0.0, 'alpha': array([1., 1., 1.], dtype=float32)}, {'snippet_id': 0, 'coords': [800, 200], 'reference': 1, 'predicted': 1.0, 'alpha': array([1.     , 5.56545, 1.     ], dtype=float32)}, {'snippet_id': 1, 'coords': [550, 115], 'reference': 1, 'predicted': 0.0, 'alpha': array([1., 1., 1.], dtype=float32)}, {'snippet_id': 1, 'coords': [430, 950], 'reference': 0, 'predicted': 0.0, 'alpha': array([1., 1., 1.], dtype=float32)}], 'uncertainty_result': {'metrics': {'precision_L': a

ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Label where deforestation past years is actual date (2019) = 1


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation different from 0 (no deforestation)


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation before 2008 is 2
D:/Jorge/datasets/deforestation/deforestation_before_2008/deforestation_before_2008_para.tif


ic| np.unique(label_past_deforestation_before_2008, return_counts=True): (array([  0, 215], dtype=uint8), array([124211220,  38957970], dtype=int64))
ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))
ic| label_per_date.shape: (17730, 9203, 1)


Mask label shape:  
 (17730, 9203, 1) 
 Unique values:  
 [0 1 2]
Tiles size:  3546 2300
Mask size:  (17730, 9200)


ic| image_stack.shape: (17730, 9203, 21)


Image shape:  (17730, 9203, 21)
mask:  (17730, 9200)
image stack:  (17730, 9200, 21)
ref : (17730, 9200, 1)
Training tiles:  [1, 3, 5, 8, 11, 13, 14, 20]
Validation tiles:  [6, 19]
Test tiles:  [2, 4, 7, 9, 10, 12, 15, 16, 17, 18]


ic| im_idx_row.shape: (17730, 9200, 1)
    im_idx_col.shape: (17730, 9200, 1)
ic| im_idx_row.dtype: dtype('uint16')
    im_idx_col.dtype: dtype('uint16')
ic| im_idx.shape: (17730, 9200, 2), im_idx.dtype: dtype('uint16')
ic| coords.shape: (464, 239, 1, 128, 128, 2)
    coords.dtype: dtype('uint16')
ic| coords.shape: (110896, 2), coords.dtype: dtype('uint16')
ic| self.coords_train.shape: (41812, 3)
    self.coords_val.shape: (10260, 3)


training samples:  (3753, 3) validation samples:  (1032, 3)
time:  0
Model: "model_4"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_enc_net (InputLayer)      [(None, 128, 128, 21 0                                            
__________________________________________________________________________________________________
res1_net1 (Conv2D)              (None, 128, 128, 16) 3040        input_enc_net[0][0]              
__________________________________________________________________________________________________
drop_net1 (Dropout)             (None, 128, 128, 16) 0           res1_net1[0][0]                  
__________________________________________________________________________________________________
res2_net1 (Conv2D)              (None, 128, 128, 16) 2320        drop_net1[0][0]                  
_______________________

c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\keras\optimizer_v2\optimizer_v2.py:374: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  warnings.warn(
c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\keras\engine\training.py:1969: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  warnings.warn('`Model.fit_generator` is deprecated and '


Epoch 1/100
self.global_step 0.0
alpha Tensor("loss/add:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("loss/truediv:0", shape=(None, 128, 128, 1), dtype=float32)
A Tensor("loss/Sum_3:0", shape=(None, 3), dtype=float32)
B Tensor("loss/Sum_4:0", shape=(None, 1, 1, 3), dtype=float32)
term1 Tensor("loss/truediv_7:0", shape=(None, 1, 1, 3), dtype=float32)
term2 Tensor("loss/mul_5:0", shape=(None, 1, 1, 3), dtype=float32)
Tensor("loss/Repeat_1/Reshape_1:0", shape=(None, None, None, 1), dtype=float32)
alpha Tensor("add:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("truediv:0", shape=(None, 128, 128, 1), dtype=float32)
K.int_shape(KL_reg) Tensor("mul_6:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("add_7:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("truediv_5:0", shape=(None, 128, 128, 1), dtype=float32)
K.int_shape(KL_reg) Tensor("mul_12:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("add_16:0", shape=(None, 128, 128, 3), dtype=float32)
u T

c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py:494: CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.
  warnings.warn('Custom mask layers require a config and must override '


351/351 [==============================] - 32s 91ms/step - loss: 0.8432 - accuracy: 0.5462 - KL_term: 0.0159 - loglikelihood_term: 0.5527 - evidential_success: 23.5257 - evidential_fail: 3.8706 - acc: 0.5463 - annealing_coef: 0.0933 - global_step_get: 350.0000 - annealing_step_get: 3750.0000 - UEO_term: 0.8976 - val_loss: 0.8431 - val_accuracy: 0.6397 - val_KL_term: 0.0233 - val_loglikelihood_term: 0.3986 - val_evidential_success: 23.2289 - val_evidential_fail: 1.8940 - val_acc: 0.6441 - val_annealing_coef: 0.1867 - val_global_step_get: 700.0000 - val_annealing_step_get: 3750.0000 - val_UEO_term: 0.9610 0.0159 - loglikelihood_term: 0.5528 - evidential_success: 23.6266 - evidential_fail: 3.9083 - acc: 0.5469 - annealing_coef: 0.0923 - global_step_get: 346.0000 - annealing_step_get: 3750.0000 - UEO_term: 0

Epoch 00002: val_loss did not improve from 0.83667
Epoch 3/100
self.global_step 700.0
351/351 [==============================] - 32s 90ms/step - loss: 0.8421 - accuracy: 0.5526 - KL_t

ic| self.path_models+ '/' + self.method +'_'+str(0)+'.h5': 'D:/Jorge/datasets/deforestation/experiments/exp196/models/resunet_0.h5'


time:  0
(54236371,)
(array([0, 1], dtype=uint8), array([53470765,   765606], dtype=int64))
(17730, 9200)
(array([0., 1.], dtype=float32), array([161358252,   1757748], dtype=int64))


ic| self.predicted_unpad.shape: (17730, 9200)
    self.predicted.shape: (17730, 9200)
ic| predicted_test.shape: (81558000,)
ic| predicted_test.shape: (54236371,)
ic| np.unique(predicted, return_counts=True): (array([0., 1.], dtype=float32), array([161358252,   1757748], dtype=int64))
    np.unique(predicted_larger_than_min_area, return_counts=True): (array([0., 1.], dtype=float32), array([161579182,   1536818], dtype=int64))
ic| np.unique(ignored_polygons, return_counts=True): (array([0., 1.], dtype=float32), array([162895070,    220930], dtype=int64))
ic| self.f1: 79.16, self.precision: 84.93, self.recall: 74.12
ic| self.label_mask_val.shape: (16311600,)
ic| self.label_mask_val_valid.shape: (9428331,)
ic| f1_val: 80.8
    precision_val: 82.73
    recall_val: 78.96
    mAP_val: 86.92


(array([0., 1.], dtype=float32), array([162388438,    727562], dtype=int64))
[0. 1.]


ic| self.label_mask.shape: (17730, 9200)
ic| self.mask_amazon_ts.shape: (17730, 9200)
ic| self.label_mask_test.shape: (81558000,)
ic| self.error_mask_test.shape: (54122584,)


(54122584,) (54122584,)


ic| bounds: (0.0015, 0.9985)


0.35993511082351887
0
0.38232011321635484
threshold 0.38232011321635484


c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\scipy\optimize\_minimize.py:783: RuntimeWarning: Method 'bounded' does not support relative tolerance in x; defaulting to absolute tolerance.
  warn("Method 'bounded' does not support relative tolerance in x; "


(51502180,) (51502180,)


ic| label_current_deforestation_test_classified_incorrect.shape: (2620404,)
    predicted_test_classified_incorrect.shape: (2620404,)


cm_correct [[51091339    14465]
 [   27868   368508]]


ic| TP_H + FN_H + FP_H + TN_H: 2620404
    len(label_mask_current_deforestation_test): 54122584
ic| TP_H + FN_H + FP_H + TN_H: 2620404
    len(label_mask_current_deforestation_test): 54122584


cm_incorrect [[2200045   82125]
 [ 162240  175994]]
[0.96222971 0.92969302 0.5016376  0.04841609 0.6818328  0.52033208
 0.09177211]
0.6176798867836452
threshold 0.6176798867836452
(52585215,) (52585215,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1537369,)
    predicted_test_classified_incorrect.shape: (1537369,)
ic| 

cm_correct [[51997378    63752]
 [   37092   486993]]
cm_incorrect [[1294006   32838]
 [ 153016   57509]]


TP_H + FN_H + FP_H + TN_H: 1537369
    len(label_mask_current_deforestation_test): 54122584
ic| TP_H + FN_H + FP_H + TN_H: 1537369
    len(label_mask_current_deforestation_test): 54122584


[0.88424407 0.92922522 0.66292727 0.02840531 0.63653469 0.27316946
 0.11344923]
0.7631402264327096
threshold 0.7631402264327096
(53003421,) (53003421,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1119163,)
    predicted_test_classified_incorrect.shape: (1119163,)
d:\Jorge\deforestation_uncertainty\src\metrics.py:295: RuntimeWarning: invalid value encountered in longlong_scalars
  precision_H = TP_H / (TP_H + FP_H)
ic| TP_H + FN_H + FP_H + TN_H: 1119163
    len(label_mask_current_deforestation_test): 54122584
ic| TP_H + FN_H + FP_H + TN_H: 1119163
    len(label_mask_current_deforestation_test): 54122584


cm_correct [[52313551    96590]
 [   48778   544502]]
cm_incorrect [[977833      0]
 [141330      0]]
[0.8493352  0.9177825  0.74121234 0.0206783         nan 0.
 0.11176476]
0.6092268187988832
threshold 0.6092268187988832
(52557574,) (52557574,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1565010,)
    predicted_test_classified_incorrect.shape: (1565010,)
ic

cm_correct [[51976129    61817]
 [   36742   482886]]
cm_incorrect [[1315255   34773]
 [ 153366   61616]]


| TP_H + FN_H + FP_H + TN_H: 1565010
    len(label_mask_current_deforestation_test): 54122584
ic| TP_H + FN_H + FP_H + TN_H: 1565010
    len(label_mask_current_deforestation_test): 54122584


[0.88651247 0.92929172 0.65733655 0.02891603 0.63924307 0.28661004
 0.1130936 ]
0.5225561695416229
threshold 0.5225561695416229
(52231731,) (52231731,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1890853,)
    predicted_test_classified_incorrect.shape: (1890853,)


cm_correct [[51714760    41962]
 [   33448   441561]]


ic| TP_H + FN_H + FP_H + TN_H: 1890853
    len(label_mask_current_deforestation_test): 54122584
ic| TP_H + FN_H + FP_H + TN_H: 1890853
    len(label_mask_current_deforestation_test): 54122584


cm_incorrect [[1576624   54628]
 [ 156660  102941]]
[0.91321612 0.92958449 0.60108221 0.03493649 0.65330744 0.39653545
 0.10745663]
0.5860515127235045
threshold 0.5860515127235045
(52479186,) (52479186,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1643398,)
    predicted_test_classified_incorrect.shape: (1643398,)
ic

cm_correct [[51915127    56678]
 [   35875   471506]]
cm_incorrect [[1376257   39912]
 [ 154233   72996]]


| TP_H + FN_H + FP_H + TN_H: 1643398
    len(label_mask_current_deforestation_test): 54122584
ic| TP_H + FN_H + FP_H + TN_H: 1643398
    len(label_mask_current_deforestation_test): 54122584


[0.8926927  0.92929377 0.64184533 0.03036437 0.64650866 0.32124421
 0.11183783]
0.5809181142977544
threshold 0.5809181142977544
(52461063,) (52461063,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1661521,)
    predicted_test_classified_incorrect.shape: (1661521,)
ic

cm_correct [[51900833    55526]
 [   35669   469035]]
cm_incorrect [[1390551   41064]
 [ 154439   75467]]


| TP_H + FN_H + FP_H + TN_H: 1661521
    len(label_mask_current_deforestation_test): 54122584
ic| TP_H + FN_H + FP_H + TN_H: 1661521
    len(label_mask_current_deforestation_test): 54122584


[0.89414768 0.92932689 0.63848164 0.03069922 0.64761308 0.32825155
 0.11154289]
0.5930743626550092
threshold 0.5930743626550092
(52503604,) (52503604,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1618980,)
    predicted_test_classified_incorrect.shape: (1618980,)
ic

cm_correct [[51934348    58228]
 [   36141   474887]]
cm_incorrect [[1357036   38362]
 [ 153967   69615]]


| TP_H + FN_H + FP_H + TN_H: 1618980
    len(label_mask_current_deforestation_test): 54122584
ic| TP_H + FN_H + FP_H + TN_H: 1618980
    len(label_mask_current_deforestation_test): 54122584


[0.89077779 0.92927785 0.64644778 0.02991321 0.64472063 0.31136227
 0.11225325]
0.599244051900177
threshold 0.599244051900177
(52524408,) (52524408,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1598176,)
    predicted_test_classified_incorrect.shape: (1598176,)
ic

cm_correct [[51950456    59614]
 [   36386   477952]]
cm_incorrect [[1340928   36976]
 [ 153722   66550]]


| TP_H + FN_H + FP_H + TN_H: 1598176
    len(label_mask_current_deforestation_test): 54122584
ic| TP_H + FN_H + FP_H + TN_H: 1598176
    len(label_mask_current_deforestation_test): 54122584


[0.88910385 0.92925664 0.65062006 0.02952882 0.64283368 0.30212646
 0.11256091]
0.5921232939472567
threshold 0.5921232939472567
(52500226,) (52500226,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1622358,)
    predicted_test_classified_incorrect.shape: (1622358,)
ic

cm_correct [[51931719    58026]
 [   36098   474383]]
cm_incorrect [[1359665   38564]
 [ 154010   70119]]


| TP_H + FN_H + FP_H + TN_H: 1622358
    len(label_mask_current_deforestation_test): 54122584
ic| TP_H + FN_H + FP_H + TN_H: 1622358
    len(label_mask_current_deforestation_test): 54122584


[0.89101236 0.9292863  0.6457617  0.02997562 0.6451699  0.31285108
 0.1121911 ]
0.5907040899841175
threshold 0.5907040899841175
(52495258,) (52495258,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1627326,)
    predicted_test_classified_incorrect.shape: (1627326,)
ic

cm_correct [[51927795    57705]
 [   36048   473710]]
cm_incorrect [[1363589   38885]
 [ 154060   70792]]


| TP_H + FN_H + FP_H + TN_H: 1627326
    len(label_mask_current_deforestation_test): 54122584
ic| TP_H + FN_H + FP_H + TN_H: 1627326
    len(label_mask_current_deforestation_test): 54122584


[0.89141255 0.92928409 0.64484556 0.03006741 0.64545894 0.3148382
 0.112107  ]
0.5917882177452318
threshold 0.5917882177452318
(52499059,) (52499059,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1623525,)
    predicted_test_classified_incorrect.shape: (1623525,)
ic

cm_correct [[51930802    57950]
 [   36085   474222]]
cm_incorrect [[1360582   38640]
 [ 154023   70280]]


| TP_H + FN_H + FP_H + TN_H: 1623525
    len(label_mask_current_deforestation_test): 54122584
ic| TP_H + FN_H + FP_H + TN_H: 1623525
    len(label_mask_current_deforestation_test): 54122584


[0.89110663 0.92928766 0.64554253 0.02999718 0.64524422 0.31332617
 0.1121725 ]
0.5915873015147046
threshold 0.5915873015147046
(52498339,) (52498339,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1624245,)
    predicted_test_classified_incorrect.shape: (1624245,)
ic

cm_correct [[51930234    57894]
 [   36082   474129]]
cm_incorrect [[1361150   38696]
 [ 154026   70373]]


| TP_H + FN_H + FP_H + TN_H: 1624245
    len(label_mask_current_deforestation_test): 54122584
ic| TP_H + FN_H + FP_H + TN_H: 1624245
    len(label_mask_current_deforestation_test): 54122584


[0.8911814  0.92928024 0.64541593 0.03001049 0.64521541 0.31360657
 0.11216369]
0.5917548756342608
threshold 0.5917548756342608
(52498962,) (52498962,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1623622,)
    predicted_test_classified_incorrect.shape: (1623622,)
ic

cm_correct [[51930721    57941]
 [   36085   474215]]
cm_incorrect [[1360663   38649]
 [ 154023   70287]]


| TP_H + FN_H + FP_H + TN_H: 1623622
    len(label_mask_current_deforestation_test): 54122584
ic| TP_H + FN_H + FP_H + TN_H: 1623622
    len(label_mask_current_deforestation_test): 54122584


[0.89112027 0.92928669 0.645533   0.02999897 0.6452137  0.3133476
 0.11217199]
0.5917215335237842
threshold 0.5917215335237842
(52498842,) (52498842,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1623742,)
    predicted_test_classified_incorrect.shape: (1623742,)
ic

cm_correct [[51930626    57932]
 [   36085   474199]]
cm_incorrect [[1360758   38658]
 [ 154023   70303]]


| TP_H + FN_H + FP_H + TN_H: 1623742
    len(label_mask_current_deforestation_test): 54122584
ic| TP_H + FN_H + FP_H + TN_H: 1623742
    len(label_mask_current_deforestation_test): 54122584
ic| self.threshold_optimal: 0.5917548756342608


[0.89113207 0.92928448 0.64551122 0.03000119 0.64521251 0.31339657
 0.11216998]
threshold 0.5917548756342608
(52498962,) (52498962,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1623622,)
    predicted_test_classified_incorrect.shape: (1623622,)
ic

cm_correct [[51930721    57941]
 [   36085   474215]]
cm_incorrect [[1360663   38649]
 [ 154023   70287]]


| TP_H + FN_H + FP_H + TN_H: 1623622
    len(label_mask_current_deforestation_test): 54122584
ic| TP_H + FN_H + FP_H + TN_H: 1623622
    len(label_mask_current_deforestation_test): 54122584


[0.89112027 0.92928669 0.645533   0.02999897 0.6452137  0.3133476
 0.11217199]
threshold 0.5917548756342608
(54122584,) (54122584,)


ic| self.m_optimal: {'AA': array([0.02999897]),
                     'UEO': array([0.11217199]),
                     'f1': 79.16,
                     'f1_H': array([0.42183252]),
                     'f1_L': array([0.90980339]),
                     'precision_H': array([0.6452137]),
                     'precision_L': array([0.89112027]),
                     'recall_H': array([0.3133476]),
                     'recall_L': array([0.92928669]),
                     'recall_Ltotal': array([0.645533])}
ic| self.m_audited_optimal: {'f1': array([0.93694084]),
                             'precision': array([0.92340568]),
                             'recall': array([0.9508787])}


cm_audited [[53330033    57941]
 [   36085   698525]]
[0.92340568 0.9508787 ]
Result idx 2: {'other_uncertainty_metrics': {'sUEO': 0.35993511082351887, 'ece_score': 0}, 'snippet_poi_results': [{'snippet_id': 0, 'coords': [550, 550], 'reference': 0, 'predicted': 0.0, 'alpha': array([168.6423,   1.    ,   1.    ], dtype=float32)}, {'snippet_id': 0, 'coords': [210, 610], 'reference': 1, 'predicted': 0.0, 'alpha': array([1., 1., 1.], dtype=float32)}, {'snippet_id': 0, 'coords': [207, 617], 'reference': 1, 'predicted': 0.0, 'alpha': array([1., 1., 1.], dtype=float32)}, {'snippet_id': 0, 'coords': [800, 200], 'reference': 1, 'predicted': 1.0, 'alpha': array([1.       , 7.0894217, 1.       ], dtype=float32)}, {'snippet_id': 1, 'coords': [550, 115], 'reference': 1, 'predicted': 0.0, 'alpha': array([1., 1., 1.], dtype=float32)}, {'snippet_id': 1, 'coords': [430, 950], 'reference': 0, 'predicted': 1.0, 'alpha': array([1.      , 2.757742, 1.      ], dtype=float32)}], 'uncertainty_result': {'metri

ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Label where deforestation past years is actual date (2019) = 1


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation different from 0 (no deforestation)


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation before 2008 is 2
D:/Jorge/datasets/deforestation/deforestation_before_2008/deforestation_before_2008_para.tif


ic| np.unique(label_past_deforestation_before_2008, return_counts=True): (array([  0, 215], dtype=uint8), array([124211220,  38957970], dtype=int64))
ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))
ic| label_per_date.shape: (17730, 9203, 1)


Mask label shape:  
 (17730, 9203, 1) 
 Unique values:  
 [0 1 2]
Tiles size:  3546 2300
Mask size:  (17730, 9200)


ic| image_stack.shape: (17730, 9203, 21)


Image shape:  (17730, 9203, 21)
mask:  (17730, 9200)
image stack:  (17730, 9200, 21)
ref : (17730, 9200, 1)
Training tiles:  [1, 3, 5, 8, 11, 13, 14, 20]
Validation tiles:  [6, 19]
Test tiles:  [2, 4, 7, 9, 10, 12, 15, 16, 17, 18]


ic| im_idx_row.shape: (17730, 9200, 1)
    im_idx_col.shape: (17730, 9200, 1)
ic| im_idx_row.dtype: dtype('uint16')
    im_idx_col.dtype: dtype('uint16')
ic| im_idx.shape: (17730, 9200, 2), im_idx.dtype: dtype('uint16')
ic| coords.shape: (464, 239, 1, 128, 128, 2)
    coords.dtype: dtype('uint16')
ic| coords.shape: (110896, 2), coords.dtype: dtype('uint16')
ic| self.coords_train.shape: (41812, 3)
    self.coords_val.shape: (10260, 3)


training samples:  (3753, 3) validation samples:  (1032, 3)
time:  0
Model: "model_6"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_enc_net (InputLayer)      [(None, 128, 128, 21 0                                            
__________________________________________________________________________________________________
res1_net1 (Conv2D)              (None, 128, 128, 16) 3040        input_enc_net[0][0]              
__________________________________________________________________________________________________
drop_net1 (Dropout)             (None, 128, 128, 16) 0           res1_net1[0][0]                  
__________________________________________________________________________________________________
res2_net1 (Conv2D)              (None, 128, 128, 16) 2320        drop_net1[0][0]                  
_______________________

c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\keras\optimizer_v2\optimizer_v2.py:374: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  warnings.warn(
c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\keras\engine\training.py:1969: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  warnings.warn('`Model.fit_generator` is deprecated and '


Epoch 1/100
self.global_step 0.0
alpha Tensor("loss/add:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("loss/truediv:0", shape=(None, 128, 128, 1), dtype=float32)
A Tensor("loss/Sum_3:0", shape=(None, 3), dtype=float32)
B Tensor("loss/Sum_4:0", shape=(None, 1, 1, 3), dtype=float32)
term1 Tensor("loss/truediv_7:0", shape=(None, 1, 1, 3), dtype=float32)
term2 Tensor("loss/mul_5:0", shape=(None, 1, 1, 3), dtype=float32)
Tensor("loss/Repeat_1/Reshape_1:0", shape=(None, None, None, 1), dtype=float32)
alpha Tensor("add:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("truediv:0", shape=(None, 128, 128, 1), dtype=float32)
K.int_shape(KL_reg) Tensor("mul_6:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("add_7:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("truediv_5:0", shape=(None, 128, 128, 1), dtype=float32)
K.int_shape(KL_reg) Tensor("mul_12:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("add_16:0", shape=(None, 128, 128, 3), dtype=float32)
u T

c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py:494: CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.
  warnings.warn('Custom mask layers require a config and must override '


351/351 [==============================] - 33s 93ms/step - loss: 0.8388 - accuracy: 0.5504 - KL_term: 0.0166 - loglikelihood_term: 0.5492 - evidential_success: 26.6284 - evidential_fail: 5.1849 - acc: 0.5502 - annealing_coef: 0.0933 - global_step_get: 350.0000 - annealing_step_get: 3750.0000 - UEO_term: 0.8861 - val_loss: 0.8342 - val_accuracy: 0.6493 - val_KL_term: 0.0167 - val_loglikelihood_term: 0.3850 - val_evidential_success: 20.9813 - val_evidential_fail: 1.3259 - val_acc: 0.6536 - val_annealing_coef: 0.1867 - val_global_step_get: 700.0000 - val_annealing_step_get: 3750.0000 - val_UEO_term: 0.9752

Epoch 00002: val_loss improved from 0.83519 to 0.83420, saving model to D:/Jorge/datasets/deforestation/experiments/exp197/models\resunet_0.h5
Epoch 3/100
self.global_step 700.0
351/351 [==============================] - 32s 92ms/step - loss: 0.8400 - accuracy: 0.5529 - KL_term: 0.0163 - loglikelihood_term: 0.5171 - evidential_success: 30.7874 - evidential_fail: 2.8828 - acc: 0.5530 - 

ic| self.path_models+ '/' + self.method +'_'+str(0)+'.h5': 'D:/Jorge/datasets/deforestation/experiments/exp197/models/resunet_0.h5'


time:  0
(54236371,)
(array([0, 1], dtype=uint8), array([53470765,   765606], dtype=int64))
(17730, 9200)
(array([0., 1.], dtype=float32), array([161611284,   1504716], dtype=int64))


ic| self.predicted_unpad.shape: (17730, 9200)
    self.predicted.shape: (17730, 9200)
ic| predicted_test.shape: (81558000,)
ic| predicted_test.shape: (54236371,)
ic| np.unique(predicted, return_counts=True): (array([0., 1.], dtype=float32), array([161611284,   1504716], dtype=int64))
    np.unique(predicted_larger_than_min_area, return_counts=True): (array([0., 1.], dtype=float32), array([161820575,   1295425], dtype=int64))
ic| np.unique(ignored_polygons, return_counts=True): (array([0., 1.], dtype=float32), array([162906709,    209291], dtype=int64))
ic| self.f1: 76.28, self.precision: 91.0, self.recall: 65.66
ic| self.label_mask_val.shape: (16311600,)
ic| self.label_mask_val_valid.shape: (9429314,)
ic| f1_val: 78.5
    precision_val: 88.0
    recall_val: 70.84
    mAP_val: 88.06


(array([0., 1.], dtype=float32), array([162353865,    762135], dtype=int64))
[0. 1.]


ic| self.label_mask.shape: (17730, 9200)
ic| self.mask_amazon_ts.shape: (17730, 9200)
ic| self.label_mask_test.shape: (81558000,)
ic| self.error_mask_test.shape: (54135156,)


(54135156,) (54135156,)


ic| bounds: (0.0015, 0.9985)


0.39539940415724506
0
0.38232011321635484
threshold 0.38232011321635484


c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\scipy\optimize\_minimize.py:783: RuntimeWarning: Method 'bounded' does not support relative tolerance in x; defaulting to absolute tolerance.
  warn("Method 'bounded' does not support relative tolerance in x; "


(52011154,) (52011154,)


ic| label_current_deforestation_test_classified_incorrect.shape: (2124002,)
    predicted_test_classified_incorrect.shape: (2124002,)


cm_correct [[51596587    20188]
 [   35170   359209]]


ic| TP_H + FN_H + FP_H + TN_H: 2124002
    len(label_mask_current_deforestation_test): 54135156
ic| TP_H + FN_H + FP_H + TN_H: 2124002
    len(label_mask_current_deforestation_test): 54135156


cm_incorrect [[1756822   27462]
 [ 216927  122791]]
[0.94678925 0.91082182 0.48932089 0.03923517 0.81722827 0.36144979
 0.11213797]
0.6176798867836452
threshold 0.6176798867836452
(52835410,) (52835410,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1299746,)
    predicted_test_classified_incorrect.shape: (1299746,)
ic| TP_H + FN_H + FP_H + TN_H: 1299746
    len(label_mask_current_deforestation_test): 54135156
ic| TP_H + FN_H + FP_H + TN_H: 1299746
    len(label_mask_current_deforestation_test

cm_correct [[52316997    37759]
 [   42695   437959]]
cm_incorrect [[1036412    9891]
 [ 209402   44041]]


): 54135156


[0.92062735 0.91117311 0.59659555 0.02400928 0.81660239 0.17377083
 0.15888494]
0.7631402264327096
threshold 0.7631402264327096
(53237495,) (53237495,)


ic| label_current_deforestation_test_classified_incorrect.shape: (897661,)
    predicted_test_classified_incorrect.shape: (897661,)
d:\Jorge\deforestation_uncertainty\src\metrics.py:295: RuntimeWarning: invalid value encountered in longlong_scalars
  precision_H = TP_H / (TP_H + FP_H)
ic| TP_H + FN_H + FP_H + TN_H: 897661
    len(label_mask_current_deforestation_test): 54135156
ic| TP_H + FN_H + FP_H + TN_H: 897661
    len(label_mask_current_deforestation_test): 54135156


cm_correct [[52654166    47650]
 [   53679   482000]]
cm_incorrect [[699243      0]
 [198418      0]]
[0.91003493 0.8997926  0.65658898 0.01658185        nan 0.
 0.1986186 ]
0.5404772665208066
threshold 0.5404772665208066
(52593437,) (52593437,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1541719,)
    predicted_test_classified_incorrect.shape: (1541719,)
ic

cm_correct [[52109373    31968]
 [   40224   411872]]
cm_incorrect [[1244036   15682]
 [ 211873   70128]]


| TP_H + FN_H + FP_H + TN_H: 1541719
    len(label_mask_current_deforestation_test): 54135156
ic| TP_H + FN_H + FP_H + TN_H: 1541719
    len(label_mask_current_deforestation_test): 54135156


[0.92797404 0.91102775 0.56105937 0.02847907 0.81724741 0.24867997
 0.140996  ]
0.5152074822255608
threshold 0.5152074822255608
(52509604,) (52509604,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1625552,)
    predicted_test_classified_incorrect.shape: (1625552,)
ic

cm_correct [[52036511    30130]
 [   39465   403498]]
cm_incorrect [[1316898   17520]
 [ 212632   78502]]


| TP_H + FN_H + FP_H + TN_H: 1625552
    len(label_mask_current_deforestation_test): 54135156
ic| TP_H + FN_H + FP_H + TN_H: 1625552
    len(label_mask_current_deforestation_test): 54135156


[0.93051648 0.91090678 0.54965216 0.03002766 0.81754181 0.26964216
 0.13577112]
0.46444902393959353
threshold 0.46444902393959353
(52334199,) (52334199,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1800957,)
    predicted_test_classified_incorrect.shape: (1800957,)


cm_correct [[51882658    26413]
 [   38000   387128]]


ic| TP_H + FN_H + FP_H + TN_H: 1800957
    len(label_mask_current_deforestation_test): 54135156
ic| TP_H + FN_H + FP_H + TN_H: 1800957
    len(label_mask_current_deforestation_test): 54135156


cm_incorrect [[1470751   21237]
 [ 214097   94872]]
[0.93612967 0.91061516 0.52735265 0.03326779 0.81709428 0.30705993
 0.12615942]
0.5095684047604685
threshold 0.5095684047604685
(52490595,) (52490595,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1644561,)
    predicted_test_classified_incorrect.shape: (1644561,)


cm_correct [[52019973    29707]
 [   39294   401621]]
cm_incorrect [[1333436   17943]
 [ 212803   80379]]


ic| TP_H + FN_H + FP_H + TN_H: 1644561
    len(label_mask_current_deforestation_test): 54135156
ic| TP_H + FN_H + FP_H + TN_H: 1644561
    len(label_mask_current_deforestation_test): 54135156


[0.93112666 0.91088078 0.54709527 0.0303788  0.81750778 0.27416076
 0.13465868]
0.5203173720359255
threshold 0.5203173720359255
(52526502,) (52526502,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1608654,)
    predicted_test_classified_incorrect.shape: (1608654,)
ic

cm_correct [[52051182    30510]
 [   39624   405186]]
cm_incorrect [[1302227   17140]
 [ 212473   76814]]


| TP_H + FN_H + FP_H + TN_H: 1608654
    len(label_mask_current_deforestation_test): 54135156
ic| TP_H + FN_H + FP_H + TN_H: 1608654
    len(label_mask_current_deforestation_test): 54135156


[0.92997411 0.91091927 0.55195158 0.02971551 0.8175703  0.2655287
 0.13677308]
0.5153619458265504
threshold 0.5153619458265504
(52510100,) (52510100,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1625056,)
    predicted_test_classified_incorrect.shape: (1625056,)
ic

cm_correct [[52036940    30149]
 [   39469   403542]]
cm_incorrect [[1316469   17501]
 [ 212628   78458]]


| TP_H + FN_H + FP_H + TN_H: 1625056
    len(label_mask_current_deforestation_test): 54135156
ic| TP_H + FN_H + FP_H + TN_H: 1625056
    len(label_mask_current_deforestation_test): 54135156


[0.93048276 0.9109074  0.5497121  0.0300185  0.81762003 0.26953546
 0.13579544]
0.5166259539603189
threshold 0.5166259539603189
(52514245,) (52514245,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1620911,)
    predicted_test_classified_incorrect.shape: (1620911,)
ic

cm_correct [[52040590    30238]
 [   39505   403912]]
cm_incorrect [[1312819   17412]
 [ 212592   78088]]


| TP_H + FN_H + FP_H + TN_H: 1620911
    len(label_mask_current_deforestation_test): 54135156
ic| TP_H + FN_H + FP_H + TN_H: 1620911
    len(label_mask_current_deforestation_test): 54135156


[0.93035126 0.91090779 0.55021612 0.02994193 0.81767539 0.26863905
 0.13604439]
0.5158447539715936
threshold 0.5158447539715936
(52511698,) (52511698,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1623458,)
    predicted_test_classified_incorrect.shape: (1623458,)


cm_correct [[52038341    30188]
 [   39487   403682]]


ic| TP_H + FN_H + FP_H + TN_H: 1623458
    len(label_mask_current_deforestation_test): 54135156
ic| TP_H + FN_H + FP_H + TN_H: 1623458
    len(label_mask_current_deforestation_test): 54135156


cm_incorrect [[1315068   17462]
 [ 212610   78318]]
[0.93042155 0.91089855 0.54990281 0.02998898 0.81768636 0.26920063
 0.13588537]
0.5157158850752975
threshold 0.5157158850752975
(52511261,) (52511261,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1623895,)
    predicted_test_classified_incorrect.shape: (1623895,)
ic

cm_correct [[52037969    30176]
 [   39481   403635]]
cm_incorrect [[1315440   17474]
 [ 212616   78365]]


| TP_H + FN_H + FP_H + TN_H: 1623895
    len(label_mask_current_deforestation_test): 54135156
ic| TP_H + FN_H + FP_H + TN_H: 1623895
    len(label_mask_current_deforestation_test): 54135156


[0.93043975 0.91090143 0.54983878 0.02999705 0.81767339 0.26931312
 0.13586238]
0.5156384203119062
threshold 0.5156384203119062
(52511026,) (52511026,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1624130,)
    predicted_test_classified_incorrect.shape: (1624130,)
ic

cm_correct [[52037762    30168]
 [   39481   403615]]
cm_incorrect [[1315647   17482]
 [ 212616   78385]]


| TP_H + FN_H + FP_H + TN_H: 1624130
    len(label_mask_current_deforestation_test): 54135156
ic| TP_H + FN_H + FP_H + TN_H: 1624130
    len(label_mask_current_deforestation_test): 54135156


[0.93045371 0.91089741 0.54981154 0.03000139 0.81764319 0.26936334
 0.13584889]
0.5156050793304191
threshold 0.5156050793304191
(52510903,) (52510903,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1624253,)
    predicted_test_classified_incorrect.shape: (1624253,)
ic

cm_correct [[52037653    30164]
 [   39477   403609]]
cm_incorrect [[1315756   17486]
 [ 212620   78391]]


| TP_H + FN_H + FP_H + TN_H: 1624253
    len(label_mask_current_deforestation_test): 54135156
ic| TP_H + FN_H + FP_H + TN_H: 1624253
    len(label_mask_current_deforestation_test): 54135156


[0.93046132 0.91090443 0.54980336 0.03000366 0.81762049 0.2693747
 0.13584439]
0.5156717612933933
threshold 0.5156717612933933
(52511131,) (52511131,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1624025,)
    predicted_test_classified_incorrect.shape: (1624025,)
ic

cm_correct [[52037854    30170]
 [   39481   403626]]
cm_incorrect [[1315555   17480]
 [ 212616   78374]]


| TP_H + FN_H + FP_H + TN_H: 1624025
    len(label_mask_current_deforestation_test): 54135156
ic| TP_H + FN_H + FP_H + TN_H: 1624025
    len(label_mask_current_deforestation_test): 54135156
ic| self.threshold_optimal: 0.5156717612933933


[0.93045118 0.91089962 0.54982652 0.02999945 0.81763933 0.26933572
 0.13585597]
threshold 0.5156717612933933
(52511131,) (52511131,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1624025,)
    predicted_test_classified_incorrect.shape: (1624025,)
ic

cm_correct [[52037854    30170]
 [   39481   403626]]
cm_incorrect [[1315555   17480]
 [ 212616   78374]]


| TP_H + FN_H + FP_H + TN_H: 1624025
    len(label_mask_current_deforestation_test): 54135156
ic| TP_H + FN_H + FP_H + TN_H: 1624025
    len(label_mask_current_deforestation_test): 54135156


[0.93045118 0.91089962 0.54982652 0.02999945 0.81763933 0.26933572
 0.13585597]
threshold 0.5156717612933933
(54135156,) (54135156,)


ic| self.m_optimal: {'AA': array([0.02999945]),
                     'UEO': array([0.13585597]),
                     'f1': 76.28,
                     'f1_H': array([0.40519693]),
                     'f1_L': array([0.9205716]),
                     'precision_H': array([0.81763933]),
                     'precision_L': array([0.93045118]),
                     'recall_H': array([0.26933572]),
                     'recall_L': array([0.91089962]),
                     'recall_Ltotal': array([0.54982652])}
ic| self.m_audited_optimal: {'f1': array([0.95225731]),
                             'precision': array([0.95837392]),
                             'recall': array([0.94621828])}


cm_audited [[53370889    30170]
 [   39481   694616]]
[0.95837392 0.94621828]
Result idx 3: {'other_uncertainty_metrics': {'sUEO': 0.39539940415724506, 'ece_score': 0}, 'snippet_poi_results': [{'snippet_id': 0, 'coords': [550, 550], 'reference': 0, 'predicted': 0.0, 'alpha': array([445.66052,   1.     ,   1.     ], dtype=float32)}, {'snippet_id': 0, 'coords': [210, 610], 'reference': 1, 'predicted': 0.0, 'alpha': array([1., 1., 1.], dtype=float32)}, {'snippet_id': 0, 'coords': [207, 617], 'reference': 1, 'predicted': 0.0, 'alpha': array([1., 1., 1.], dtype=float32)}, {'snippet_id': 0, 'coords': [800, 200], 'reference': 1, 'predicted': 1.0, 'alpha': array([ 1.     , 36.08136,  1.     ], dtype=float32)}, {'snippet_id': 1, 'coords': [550, 115], 'reference': 1, 'predicted': 0.0, 'alpha': array([1., 1., 1.], dtype=float32)}, {'snippet_id': 1, 'coords': [430, 950], 'reference': 0, 'predicted': 0.0, 'alpha': array([1., 1., 1.], dtype=float32)}], 'uncertainty_result': {'metrics': {'precision_L

ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Label where deforestation past years is actual date (2019) = 1


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation different from 0 (no deforestation)


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation before 2008 is 2
D:/Jorge/datasets/deforestation/deforestation_before_2008/deforestation_before_2008_para.tif


ic| np.unique(label_past_deforestation_before_2008, return_counts=True): (array([  0, 215], dtype=uint8), array([124211220,  38957970], dtype=int64))
ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))
ic| label_per_date.shape: (17730, 9203, 1)


Mask label shape:  
 (17730, 9203, 1) 
 Unique values:  
 [0 1 2]
Tiles size:  3546 2300
Mask size:  (17730, 9200)


ic| image_stack.shape: (17730, 9203, 21)


Image shape:  (17730, 9203, 21)
mask:  (17730, 9200)
image stack:  (17730, 9200, 21)
ref : (17730, 9200, 1)
Training tiles:  [1, 3, 5, 8, 11, 13, 14, 20]
Validation tiles:  [6, 19]
Test tiles:  [2, 4, 7, 9, 10, 12, 15, 16, 17, 18]


ic| im_idx_row.shape: (17730, 9200, 1)
    im_idx_col.shape: (17730, 9200, 1)
ic| im_idx_row.dtype: dtype('uint16')
    im_idx_col.dtype: dtype('uint16')
ic| im_idx.shape: (17730, 9200, 2), im_idx.dtype: dtype('uint16')
ic| coords.shape: (464, 239, 1, 128, 128, 2)
    coords.dtype: dtype('uint16')
ic| coords.shape: (110896, 2), coords.dtype: dtype('uint16')
ic| self.coords_train.shape: (41812, 3)
    self.coords_val.shape: (10260, 3)


training samples:  (3753, 3) validation samples:  (1032, 3)
time:  0
Model: "model_8"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_enc_net (InputLayer)      [(None, 128, 128, 21 0                                            
__________________________________________________________________________________________________
res1_net1 (Conv2D)              (None, 128, 128, 16) 3040        input_enc_net[0][0]              
__________________________________________________________________________________________________
drop_net1 (Dropout)             (None, 128, 128, 16) 0           res1_net1[0][0]                  
__________________________________________________________________________________________________
res2_net1 (Conv2D)              (None, 128, 128, 16) 2320        drop_net1[0][0]                  
_______________________

c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\keras\optimizer_v2\optimizer_v2.py:374: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  warnings.warn(
c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\keras\engine\training.py:1969: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  warnings.warn('`Model.fit_generator` is deprecated and '


Epoch 1/100
self.global_step 0.0
alpha Tensor("loss/add:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("loss/truediv:0", shape=(None, 128, 128, 1), dtype=float32)
A Tensor("loss/Sum_3:0", shape=(None, 3), dtype=float32)
B Tensor("loss/Sum_4:0", shape=(None, 1, 1, 3), dtype=float32)
term1 Tensor("loss/truediv_7:0", shape=(None, 1, 1, 3), dtype=float32)
term2 Tensor("loss/mul_5:0", shape=(None, 1, 1, 3), dtype=float32)
Tensor("loss/Repeat_1/Reshape_1:0", shape=(None, None, None, 1), dtype=float32)
alpha Tensor("add:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("truediv:0", shape=(None, 128, 128, 1), dtype=float32)
K.int_shape(KL_reg) Tensor("mul_6:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("add_7:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("truediv_5:0", shape=(None, 128, 128, 1), dtype=float32)
K.int_shape(KL_reg) Tensor("mul_12:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("add_16:0", shape=(None, 128, 128, 3), dtype=float32)
u T

c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py:494: CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.
  warnings.warn('Custom mask layers require a config and must override '


351/351 [==============================] - 32s 91ms/step - loss: 0.8411 - accuracy: 0.5495 - KL_term: 0.0171 - loglikelihood_term: 0.5547 - evidential_success: 22.7891 - evidential_fail: 4.5554 - acc: 0.5501 - annealing_coef: 0.0933 - global_step_get: 350.0000 - annealing_step_get: 3750.0000 - UEO_term: 0.8800 - val_loss: 0.8658 - val_accuracy: 0.6511 - val_KL_term: 0.0522 - val_loglikelihood_term: 0.3994 - val_evidential_success: 44.8080 - val_evidential_fail: 6.9092 - val_acc: 0.6553 - val_annealing_coef: 0.1867 - val_global_step_get: 700.0000 - val_annealing_step_get: 3750.0000 - val_UEO_term: 0.8958m: 0.0180 - loglikelihood_term: 0.5788 - evidential_success: 23.8546 - evidential_fail: 5.8117 - acc: 0.5500 - annealing_c

Epoch 00002: val_loss did not improve from 0.84956
Epoch 3/100
self.global_step 700.0
351/351 [==============================] - 32s 91ms/step - loss: 0.8403 - accuracy: 0.5560 - KL_term: 0.0171 - loglikelihood_term: 0.5213 - evidential_success: 26.5687 - evidential

In [ ]:
print(results)

[{'metrics': {'precision_L': array([nan]), 'recall_L': array([0.]), 'recall_Ltotal': array([0.]), 'AA': array([0.03000046]), 'precision_H': array([nan]), 'recall_H': array([0.]), 'f1_L': array([nan]), 'f1_H': array([nan]), 'f1': 0.0}, 'metrics_audited': {'precision': array([1.]), 'recall': array([0.88574556]), 'f1': array([0.93941153])}, 'exp': 175}, {'metrics': {'precision_L': array([0.53704756]), 'recall_L': array([0.9351188]), 'recall_Ltotal': array([0.85489489]), 'AA': array([0.02999747]), 'precision_H': array([0.16052591]), 'recall_H': array([0.41546518]), 'f1_L': array([0.68226429]), 'f1_H': array([0.23157625]), 'f1': 63.3}, 'metrics_audited': {'precision': array([0.56072183]), 'recall': array([0.94068496]), 'f1': array([0.70262449])}, 'exp': 176}, {'metrics': {'precision_L': array([0.70278881]), 'recall_L': array([0.93463832]), 'recall_Ltotal': array([0.76870477]), 'AA': array([0.02999925]), 'precision_H': array([0.36952487]), 'recall_H': array([0.37348836]), 'f1_L': array([0.80

In [ ]:
print(len(results))

10


In [ ]:
results[9]

NameError: name 'results' is not defined

In [ ]:
trainer.f1

64.55

In [ ]:
print(trainer.f1)

64.55
