In [1]:
from utils_v1 import *


In [2]:
from icecream import ic

import numpy as np
from src.dataset import (
    MultipleDates,
    PA, PADeforestationTime, PADistanceMap, PAMultipleDates,
    MTDeforestationTime,
    MTMultipleDates
)

# from src.dataset_legacy import MTDeforestationTime
from src import training_generator as generator
from src.patchesHandler import PatchesHandler, PatchesHandlerMultipleDates, PatchesHandlerEvidential

from src.trainer.evidential import TrainerEvidential

from mpl_toolkits.axes_grid1 import make_axes_locatable

import cv2
from src import metrics as _metric
import json
import pickle 
import src.trainer.evidential as evidential


In [3]:

config = {
	"training": False,
	"save_probabilities": False,
	"loadInference": False,
	"addPastDeforestationInput": True,
	"inference_times": 1,
	"Uncertainty": {
		"annealing_step": 10*375/2 # 1875
	}
}




'''
if config["training"] == True:
	dates = [2017, 2018]
else:
	dates = [2018, 2019]
if config["training"] == True:
	dates = [2018, 2019]
else:
	dates = [2019, 2020]
'''
# dates = [2018, 2019]
# dates = [2017, 2018]

# dataset = PAMultipleDates(dates = dates, # dates = [2017, 2018, 2019]. [2018, 2019]. [2015, 2016, 2017, 2018]
# 	addPastDeforestationInput = config['addPastDeforestationInput'],
# 	borderBuffer = 2)	
dates = [2018, 2019]
# dates = [2019, 2020]

dataset = MTMultipleDates(dates = dates, # dates = [2016,2017,2018,2019]
	addPastDeforestationInput = config['addPastDeforestationInput'],
	borderBuffer = 2)	
# dataset = MTDeforestationTime()	
# [2016, 2017, 2018]

ic(dates)

if issubclass(type(dataset), MultipleDates):
	patchesHandler = PatchesHandlerEvidential(
		dataset)
else:
	patchesHandler = PatchesHandler()



ic| list(self.date_ids): [0]
ic| self.image_channels: [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]]
ic| dates: [2018, 2019]
ic| self.input_image_shape: 21
ic| self.dataset.image_channels: [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]]


In [4]:
[10*375//1, 10*375//1.5, 10*375//2, 10*375//3, 10*375//4]


[3750, 2500.0, 1875, 1250, 937]

In [5]:
# if config["training"] == True:
# experiment_values = [10*375//1, 10*375//1.5, 10*375//2, 10*375//3, 10*375//4]
# experiment_values = [10*375//3, 10*375//3, 10*375//3, 10*375//3, 10*375//3]
# experiment_values = [10*375//2, 10*375//2, 10*375//2, 10*375//2, 10*375//2, 10*375//2, 10*375//2]
# experiment_values = [10*375, 10*375, 10*375, 10*375, 10*375, 10*375, 10*375, 10*375, 10*375, 10*375]
experiment_values = [10*375, 10*375, 10*375, 10*375, 10*375, 10*375, 10*375, 10*375, 10*375, 10*375]

experiment_values = [int(x) for x in experiment_values]
results = []

#exp_id_base = 148
# exp_id_base = 155
exp_id_base = 175


exp_ids = range(exp_id_base, exp_id_base+len(experiment_values))


In [6]:
exp_ids

range(191, 201)

In [ ]:
from enum import Enum
UncertaintyMethod = Enum('Predictor', 'pred_var MI pred_entropy KL pred_entropy_single evidential')
uncertaintyMethod = "evidential"


In [7]:


for experiment_value, exp_id in zip(experiment_values, exp_ids):
    config = {
        "training": True,
    	"learning_rate": 1e-4,
        "weights": [0.1, 0.9, 0],
        "save_probabilities": False,
        "loadInference": False,
        "addPastDeforestationInput": True,
        "inference_times": 1,
        "Uncertainty": {
            "annealing_step": experiment_value# 10*375/2 # 1875
        },
    	"uncertainty_method": uncertaintyMethod,
        "evidence_function": evidential.relu_evidence
    }

    trainer = TrainerEvidential(config, dataset, patchesHandler)

    trainer.defineExperiment(exp_id)

    trainer.setExperimentPath()
    trainer.createLogFolders()

    trainer.loadDataset()

    # %%
    if config["training"] == True:
        trainer.run()

    # %%
    result = trainer.run_predictor()
    results.append(result)


    with open('log.pkl', 'wb') as f:
        pickle.dump(results, f)

D:/Jorge/datasets/deforestation/MT/deforestation_past_years.tif
Loaded deforestation past years


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([161124576,   1332784,    240796,    338545,    313901,    287191,
                                                                       708581,    648966,    876898,   1007787,   1098901,   1054092,
                                                                      2096062,   2473828,   1400992], dtype=int64))


Label where deforestation past years is actual date (2019) = 1


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([161124576,   1332784,    240796,    338545,    313901,    287191,
                                                                       708581,    648966,    876898,   1007787,   1098901,   1054092,
                                                                      2096062,   2473828,   1400992], dtype=int64))


Past deforestation different from 0 (no deforestation)


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([161124576,   1332784,    240796,    338545,    313901,    287191,
                                                                       708581,    648966,    876898,   1007787,   1098901,   1054092,
                                                                      2096062,   2473828,   1400992], dtype=int64))


Past deforestation before 2008 is 2
D:/Jorge/datasets/deforestation/MT/deforestation_before_2008/deforestation_before_2008_MT.tif


ic| np.unique(label_past_deforestation_before_2008, return_counts=True): (array([  0, 215], dtype=uint8), array([122623260,  52380640], dtype=int64))
ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([161124576,   1332784,    240796,    338545,    313901,    287191,
                                                                       708581,    648966,    876898,   1007787,   1098901,   1054092,
                                                                      2096062,   2473828,   1400992], dtype=int64))
ic| label_per_date.shape: (16795, 10420, 1)


Mask label shape:  
 (16795, 10420, 1) 
 Unique values:  
 [0 1 2]
Tiles size:  3359 2084
Mask size:  (16795, 10420)


ic| image_stack.shape: (16795, 10420, 21)


Image shape:  (16795, 10420, 21)
mask:  (16795, 10420)
image stack:  (16795, 10420, 21)
ref : (16795, 10420, 1)
Training tiles:  [2, 4, 5, 6, 7, 12, 14, 15, 18, 21, 23, 24]
Validation tiles:  [9, 11, 25]
Test tiles:  [1, 3, 8, 10, 13, 16, 17, 19, 20, 22]


ic| im_idx_row.shape: (16795, 10420, 1)
    im_idx_col.shape: (16795, 10420, 1)
ic| im_idx_row.dtype: dtype('uint16')
    im_idx_col.dtype: dtype('uint16')
ic| im_idx.shape: (16795, 10420, 2), im_idx.dtype: dtype('uint16')
ic| coords.shape: (439, 271, 1, 128, 128, 2)
    coords.dtype: dtype('uint16')
ic| coords.shape: (118969, 2), coords.dtype: dtype('uint16')
ic| self.coords_train.shape: (54516, 3)
    self.coords_val.shape: (13175, 3)


training samples:  (2962, 3) validation samples:  (623, 3)
time:  0
Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_enc_net (InputLayer)      [(None, 128, 128, 21 0                                            
__________________________________________________________________________________________________
res1_net1 (Conv2D)              (None, 128, 128, 16) 3040        input_enc_net[0][0]              
__________________________________________________________________________________________________
drop_net1 (Dropout)             (None, 128, 128, 16) 0           res1_net1[0][0]                  
__________________________________________________________________________________________________
res2_net1 (Conv2D)              (None, 128, 128, 16) 2320        drop_net1[0][0]                  
__________________________

c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\keras\optimizer_v2\optimizer_v2.py:374: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  warnings.warn(
c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\keras\engine\training.py:1969: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  warnings.warn('`Model.fit_generator` is deprecated and '


Epoch 1/100
self.global_step 0.0
alpha Tensor("loss/add:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("loss/truediv:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("add:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("truediv:0", shape=(None, 128, 128, 1), dtype=float32)
K.int_shape(KL_reg) Tensor("mul_6:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("add_7:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("truediv_5:0", shape=(None, 128, 128, 1), dtype=float32)
K.int_shape(KL_reg) Tensor("mul_12:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("loss/add:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("loss/truediv:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("add:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("truediv:0", shape=(None, 128, 128, 1), dtype=float32)
K.int_shape(KL_reg) Tensor("mul_6:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("add_7:0", shape=(None, 128, 128, 3), dtype=float

c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py:494: CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.
  warnings.warn('Custom mask layers require a config and must override '


277/277 [==============================] - 24s 86ms/step - loss: 0.1612 - accuracy: 0.9125 - KL_term: 0.0148 - loglikelihood_term: 0.1463 - evidential_success: 48.3302 - evidential_fail: 15.4146 - acc: 0.9126 - annealing_coef: 0.0736 - global_step_get: 276.0000 - annealing_step_get: 3750.0000 - val_loss: 0.1232 - val_accuracy: 0.9445 - val_KL_term: 0.0120 - val_loglikelihood_term: 0.1104 - val_evidential_success: 38.7166 - val_evidential_fail: 7.1284 - val_acc: 0.9446 - val_annealing_coef: 0.1472 - val_global_step_get: 552.0000 - val_annealing_step_get: 3750.0000

Epoch 00002: val_loss did not improve from 0.11625
Epoch 3/100
self.global_step 552.0
277/277 [==============================] - 24s 86ms/step - loss: 0.1586 - accuracy: 0.9167 - KL_term: 0.0175 - loglikelihood_term: 0.1409 - evidential_success: 55.6426 - evidential_fail: 12.5242 - acc: 0.9168 - annealing_coef: 0.1104 - global_step_get: 414.0000 - annealing_step_get: 3750.0000 - val_loss: 0.1348 - val_accuracy: 0.9323 - val_K

ic| self.path_models+ '/' + self.method +'_'+str(0)+'.h5': 'D:/Jorge/datasets/deforestation/experiments/MT/exp191/models/resunet_0.h5'


time:  0
(39774655,)
(array([0, 1], dtype=uint8), array([39234711,   539944], dtype=int64))
(16795, 10420)
(array([0., 1.], dtype=float32), array([173041282,   1962618], dtype=int64))


ic| self.predicted_unpad.shape: (16795, 10420)
    self.predicted.shape: (16795, 10420)
ic| predicted_test.shape: (70001560,)
ic| predicted_test.shape: (39774655,)
ic| np.unique(predicted, return_counts=True): (array([0., 1.], dtype=float32), array([173041282,   1962618], dtype=int64))
    np.unique(predicted_larger_than_min_area, return_counts=True): (array([0., 1.], dtype=float32), array([173163506,   1840394], dtype=int64))
ic| np.unique(ignored_polygons, return_counts=True): (array([0., 1.], dtype=float32), array([174881676,    122224], dtype=int64))
ic| self.f1: 82.14, self.precision: 80.48, self.recall: 83.87
ic| self.label_mask_val.shape: (21000468,)
ic| self.label_mask_val_valid.shape: (10890035,)
ic| f1_val: 96.52
    precision_val: 97.3
    recall_val: 95.75
    mAP_val: 98.73


(array([0., 1.], dtype=float32), array([174516896,    487004], dtype=int64))


ic| self.label_mask.shape: (16795, 10420)
ic| self.mask_amazon_ts.shape: (16795, 10420)
ic| self.label_mask_test.shape: (70001560,)
ic| self.error_mask_test.shape: (39725070,)
ic| bounds: (0.0015, 0.8637791976928711)
c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\scipy\optimize\_minimize.py:783: RuntimeWarning: Method 'bounded' does not support relative tolerance in x; defaulting to absolute tolerance.
  warn("Method 'bounded' does not support relative tolerance in x; "


0.33086134572668685
threshold 0.33086134572668685
(39034420,) (39034420,)


ic| label_current_deforestation_test_classified_incorrect.shape: (690650,)
    predicted_test_classified_incorrect.shape: (690650,)
ic| TP_H + FN_H + FP_H + TN_H: 690650
    len(label_mask_current_deforestation_test): 39725070
ic| TP_H + FN_H + FP_H + TN_H: 690650
    len(label_mask_current_deforestation_test): 39725070


cm_correct [[38584502    21701]
 [   46518   381699]]
cm_incorrect [[504187  85884]
 [ 38764  61815]]
[0.94620476 0.89136816 0.72182656 0.01738575 0.4185201  0.61459152]
0.5344178519661843
threshold 0.5344178519661843
(39635116,) (39635116,)


ic| label_current_deforestation_test_classified_incorrect.shape: (89954,)
    predicted_test_classified_incorrect.shape: (89954,)
ic| TP_H + FN_H + FP_H + TN_H: 89954
    len(label_mask_current_deforestation_test): 39725070
ic| TP_H + FN_H + FP_H + TN_H: 89954
    len(label_mask_current_deforestation_test): 39725070


cm_correct [[39018384    94970]
 [   80283   441479]]
cm_incorrect [[70305 12615]
 [ 4999  2035]]
[0.82296546 0.84613099 0.83487583 0.00226441 0.13890785 0.28930907]
0.20505650623949742
threshold 0.20505650623949742
(37929713,) (37929713,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1795357,)
    predicted_test_classified_incorrect.shape: (1795357,)


cm_correct [[37654010     1416]
 [   24966   249321]]


ic| TP_H + FN_H + FP_H + TN_H: 1795357
    len(label_mask_current_deforestation_test): 39725070
ic| TP_H + FN_H + FP_H + TN_H: 1795357
    len(label_mask_current_deforestation_test): 39725070


cm_incorrect [[1434679  106169]
 [  60316  194193]]
[0.99435265 0.90897855 0.47148806 0.04519456 0.64652985 0.76301035]
0.30358976691725426
threshold 0.30358976691725426
(38875737,) (38875737,)


ic| label_current_deforestation_test_classified_incorrect.shape: (849333,)
    predicted_test_classified_incorrect.shape: (849333,)
ic| TP_H + FN_H + FP_H + TN_H: 849333
    len(label_mask_current_deforestation_test): 39725070
ic| TP_H + FN_H + FP_H + TN_H: 849333
    len(label_mask_current_deforestation_test): 39725070


cm_correct [[38459482    13289]
 [   42158   360808]]
cm_incorrect [[629207  94296]
 [ 43124  82706]]
[0.96447713 0.89538075 0.68231984 0.02138028 0.46726026 0.65728364]
0.27401031657870056
threshold 0.27401031657870056
(38659707,) (38659707,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1065363,)
    predicted_test_classified_incorrect.shape: (1065363,)
ic| TP_H + FN_H + FP_H + TN_H: 1065363
    len(label_mask_current_deforestation_test): 39725070
ic| TP_H + FN_H + FP_H + TN_H: 1065363
    len(label_mask_current_deforestation_test): 39725070


cm_correct [[38280235     7622]
 [   37257   334593]]
cm_incorrect [[808454  99963]
 [ 48025 108921]]
[0.97772745 0.89980637 0.63274495 0.0268184  0.52144252 0.69400303]
0.24767230468293888
threshold 0.24767230468293888
(38420355,) (38420355,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1304715,)
    predicted_test_classified_incorrect.shape: (1304715,)
ic| TP_H + FN_H + FP_H + TN_H: 1304715
    len(label_mask_current_deforestation_test): 39725070
ic| TP_H + FN_H + FP_H + TN_H: 1304715
    len(label_mask_current_deforestation_test): 39725070

cm_correct [[38076140     4527]
 [   32547   307141]]
cm_incorrect [[1012549  103058]
 [  52735  136373]]


[0.98547493 0.90418561 0.58083079 0.03284362 0.56957119 0.72113819]
0.25874340193292333
threshold 0.25874340193292333
(38525981,) (38525981,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1199089,)
    predicted_test_classified_incorrect.shape: (1199089,)
ic| TP_H + FN_H + FP_H + TN_H: 1199089
    len(label_mask_current_deforestation_test): 39725070
ic| TP_H + FN_H + FP_H + TN_H: 1199089
    len(label_mask_current_deforestation_test): 39725070


cm_correct [[38166414     5718]
 [   34610   319239]]
cm_incorrect [[922275 101867]
 [ 50672 124275]]
[0.98240383 0.90218992 0.60370918 0.03018469 0.54954409 0.71035799]
0.26045413740934
threshold 0.26045413740934
(38541724,) (38541724,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1183346,)
    predicted_test_classified_incorrect.shape: (1183346,)
ic| TP_H + FN_H + FP_H + TN_H: 1183346
    len(label_mask_current_deforestation_test): 39725070
ic| TP_H + FN_H + FP_H + TN_H: 1183346
    len(label_mask_current_deforestation_test): 39725070


cm_correct [[38179845     5918]
 [   34912   321049]]
cm_incorrect [[908844 101667]
 [ 50370 122465]]
[0.98190031 0.90192184 0.60713205 0.02978839 0.54639677 0.70856597]
0.25920585138359103
threshold 0.25920585138359103
(38530361,) (38530361,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1194709,)
    predicted_test_classified_incorrect.shape: (1194709,)
ic| TP_H + FN_H + FP_H + TN_H: 1194709
    len(label_mask_current_deforestation_test): 39725070
ic| TP_H + FN_H + FP_H + TN_H: 1194709
    len(label_mask_current_deforestation_test): 39725070


cm_correct [[38170164     5778]
 [   34695   319724]]
cm_incorrect [[918525 101807]
 [ 50587 123790]]
[0.98224896 0.90210739 0.60462636 0.03007443 0.54872184 0.70989867]
0.25956013315457216
threshold 0.25956013315457216
(38533567,) (38533567,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1191503,)
    predicted_test_classified_incorrect.shape: (1191503,)
ic| TP_H + FN_H + FP_H + TN_H: 1191503
    len(label_mask_current_deforestation_test): 39725070
ic| TP_H + FN_H + FP_H + TN_H: 1191503
    len(label_mask_current_deforestation_test): 39725070


cm_correct [[38172911     5812]
 [   34759   320085]]
cm_incorrect [[915778 101773]
 [ 50523 123429]]
[0.98216614 0.90204428 0.60530904 0.02999373 0.54808128 0.70955781]
0.25990161239380644
threshold 0.25990161239380644
(38536614,) (38536614,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1188456,)
    predicted_test_classified_incorrect.shape: (1188456,)
ic| TP_H + FN_H + FP_H + TN_H: 1188456
    len(label_mask_current_deforestation_test): 39725070
ic| TP_H + FN_H + FP_H + TN_H: 1188456
    len(label_mask_current_deforestation_test): 39725070


cm_correct [[38175507     5844]
 [   34819   320444]]
cm_incorrect [[913182 101741]
 [ 50463 123070]]
[0.98208944 0.90199092 0.60598794 0.02991703 0.54743763 0.70920228]
0.2595267959713399
threshold 0.2595267959713399
(38533276,) (38533276,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1191794,)
    predicted_test_classified_incorrect.shape: (1191794,)
ic| TP_H + FN_H + FP_H + TN_H: 1191794
    len(label_mask_current_deforestation_test): 39725070
ic| TP_H + FN_H + FP_H + TN_H: 1191794
    len(label_mask_current_deforestation_test): 39725070


cm_correct [[38172660     5811]
 [   34753   320052]]
cm_incorrect [[916029 101774]
 [ 50529 123462]]
[0.98216735 0.90205042 0.60524664 0.03000105 0.54814506 0.70958843]
0.2594714949197063
threshold 0.2594714949197063
(38532771,) (38532771,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1192299,)
    predicted_test_classified_incorrect.shape: (1192299,)
ic| TP_H + FN_H + FP_H + TN_H: 1192299
    len(label_mask_current_deforestation_test): 39725070
ic| TP_H + FN_H + FP_H + TN_H: 1192299
    len(label_mask_current_deforestation_test): 39725070
ic| self.threshold_optimal: 0.2595267959713399


cm_correct [[38172227     5803]
 [   34748   319993]]
cm_incorrect [[916462 101782]
 [ 50534 123521]]
[0.98218824 0.90204685 0.60513506 0.03001377 0.54824392 0.70966648]
threshold 0.2595267959713399
(38533276,) (38533276,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1191794,)
    predicted_test_classified_incorrect.shape: (1191794,)
ic| TP_H + FN_H + FP_H + TN_H: 1191794
    len(label_mask_current_deforestation_test): 39725070
ic| TP_H + FN_H + FP_H + TN_H: 1191794
    len(label_mask_current_deforestation_test): 39725070


cm_correct [[38172660     5811]
 [   34753   320052]]
cm_incorrect [[916029 101774]
 [ 50529 123462]]
[0.98216735 0.90205042 0.60524664 0.03000105 0.54814506 0.70958843]
threshold 0.2595267959713399
(39725070,) (39725070,)


ic| self.m_optimal: {'AA': array([0.03000105]),
                     'f1': 82.14,
                     'f1_H': array([0.61850526]),
                     'f1_L': array([0.9404056]),
                     'precision_H': array([0.54814506]),
                     'precision_L': array([0.98216735]),
                     'recall_H': array([0.70958843]),
                     'recall_L': array([0.90205042]),
                     'recall_Ltotal': array([0.60524664])}
ic| self.m_audited_optimal: {'f1': array([0.96056579]),
                             'precision': array([0.98837461]),
                             'recall': array([0.934279])}


cm_audited [[39190463     5811]
 [   34753   494043]]
[0.98837461 0.934279  ]
D:/Jorge/datasets/deforestation/MT/deforestation_past_years.tif
Loaded deforestation past years


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([161124576,   1332784,    240796,    338545,    313901,    287191,
                                                                       708581,    648966,    876898,   1007787,   1098901,   1054092,
                                                                      2096062,   2473828,   1400992], dtype=int64))


Label where deforestation past years is actual date (2019) = 1


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([161124576,   1332784,    240796,    338545,    313901,    287191,
                                                                       708581,    648966,    876898,   1007787,   1098901,   1054092,
                                                                      2096062,   2473828,   1400992], dtype=int64))


Past deforestation different from 0 (no deforestation)


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([161124576,   1332784,    240796,    338545,    313901,    287191,
                                                                       708581,    648966,    876898,   1007787,   1098901,   1054092,
                                                                      2096062,   2473828,   1400992], dtype=int64))


Past deforestation before 2008 is 2
D:/Jorge/datasets/deforestation/MT/deforestation_before_2008/deforestation_before_2008_MT.tif


ic| np.unique(label_past_deforestation_before_2008, return_counts=True): (array([  0, 215], dtype=uint8), array([122623260,  52380640], dtype=int64))
ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([161124576,   1332784,    240796,    338545,    313901,    287191,
                                                                       708581,    648966,    876898,   1007787,   1098901,   1054092,
                                                                      2096062,   2473828,   1400992], dtype=int64))
ic| label_per_date.shape: (16795, 10420, 1)


Mask label shape:  
 (16795, 10420, 1) 
 Unique values:  
 [0 1 2]
Tiles size:  3359 2084
Mask size:  (16795, 10420)


ic| image_stack.shape: (16795, 10420, 21)


Image shape:  (16795, 10420, 21)
mask:  (16795, 10420)
image stack:  (16795, 10420, 21)
ref : (16795, 10420, 1)
Training tiles:  [2, 4, 5, 6, 7, 12, 14, 15, 18, 21, 23, 24]
Validation tiles:  [9, 11, 25]
Test tiles:  [1, 3, 8, 10, 13, 16, 17, 19, 20, 22]


ic| im_idx_row.shape: (16795, 10420, 1)
    im_idx_col.shape: (16795, 10420, 1)
ic| im_idx_row.dtype: dtype('uint16')
    im_idx_col.dtype: dtype('uint16')
ic| im_idx.shape: (16795, 10420, 2), im_idx.dtype: dtype('uint16')
ic| coords.shape: (439, 271, 1, 128, 128, 2)
    coords.dtype: dtype('uint16')
ic| coords.shape: (118969, 2), coords.dtype: dtype('uint16')
ic| self.coords_train.shape: (54516, 3)
    self.coords_val.shape: (13175, 3)


training samples:  (2962, 3) validation samples:  (623, 3)
time:  0
Model: "model_2"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_enc_net (InputLayer)      [(None, 128, 128, 21 0                                            
__________________________________________________________________________________________________
res1_net1 (Conv2D)              (None, 128, 128, 16) 3040        input_enc_net[0][0]              
__________________________________________________________________________________________________
drop_net1 (Dropout)             (None, 128, 128, 16) 0           res1_net1[0][0]                  
__________________________________________________________________________________________________
res2_net1 (Conv2D)              (None, 128, 128, 16) 2320        drop_net1[0][0]                  
________________________

c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\keras\optimizer_v2\optimizer_v2.py:374: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  warnings.warn(
c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\keras\engine\training.py:1969: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  warnings.warn('`Model.fit_generator` is deprecated and '


Epoch 1/100
self.global_step 0.0
alpha Tensor("loss/add:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("loss/truediv:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("add:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("truediv:0", shape=(None, 128, 128, 1), dtype=float32)
K.int_shape(KL_reg) Tensor("mul_6:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("add_7:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("truediv_5:0", shape=(None, 128, 128, 1), dtype=float32)
K.int_shape(KL_reg) Tensor("mul_12:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("loss/add:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("loss/truediv:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("add:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("truediv:0", shape=(None, 128, 128, 1), dtype=float32)
K.int_shape(KL_reg) Tensor("mul_6:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("add_7:0", shape=(None, 128, 128, 3), dtype=float

c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py:494: CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.
  warnings.warn('Custom mask layers require a config and must override '


277/277 [==============================] - 24s 87ms/step - loss: 0.1606 - accuracy: 0.9124 - KL_term: 0.0141 - loglikelihood_term: 0.1466 - evidential_success: 53.0892 - evidential_fail: 13.6169 - acc: 0.9123 - annealing_coef: 0.0736 - global_step_get: 276.0000 - annealing_step_get: 3750.0000 - val_loss: 0.1219 - val_accuracy: 0.9428 - val_KL_term: 0.0149 - val_loglikelihood_term: 0.1065 - val_evidential_success: 44.6723 - val_evidential_fail: 7.8990 - val_acc: 0.9429 - val_annealing_coef: 0.1472 - val_global_step_get: 552.0000 - val_annealing_step_get: 3750.0000

Epoch 00002: val_loss improved from 0.14539 to 0.12195, saving model to D:/Jorge/datasets/deforestation/experiments/MT/exp192/models\resunet_0.h5
Epoch 3/100
self.global_step 552.0
277/277 [==============================] - 24s 87ms/step - loss: 0.1438 - accuracy: 0.9251 - KL_term: 0.0165 - loglikelihood_term: 0.1274 - evidential_success: 61.8927 - evidential_fail: 13.1384 - acc: 0.9250 - annealing_coef: 0.1104 - global_step_

ic| self.path_models+ '/' + self.method +'_'+str(0)+'.h5': 'D:/Jorge/datasets/deforestation/experiments/MT/exp192/models/resunet_0.h5'


time:  0
(39774655,)
(array([0, 1], dtype=uint8), array([39234711,   539944], dtype=int64))
(16795, 10420)
(array([0., 1.], dtype=float32), array([173037749,   1966151], dtype=int64))


ic| self.predicted_unpad.shape: (16795, 10420)
    self.predicted.shape: (16795, 10420)
ic| predicted_test.shape: (70001560,)
ic| predicted_test.shape: (39774655,)
ic| np.unique(predicted, return_counts=True): (array([0., 1.], dtype=float32), array([173037749,   1966151], dtype=int64))
    np.unique(predicted_larger_than_min_area, return_counts=True): (array([0., 1.], dtype=float32), array([173107891,   1896009], dtype=int64))
ic| np.unique(ignored_polygons, return_counts=True): (array([0., 1.], dtype=float32), array([174933758,     70142], dtype=int64))
ic| self.f1: 77.4, self.precision: 73.49, self.recall: 81.75
ic| self.label_mask_val.shape: (21000468,)
ic| self.label_mask_val_valid.shape: (10899563,)
ic| f1_val: 94.36
    precision_val: 96.82
    recall_val: 92.01
    mAP_val: 98.64


(array([0., 1.], dtype=float32), array([174478637,    525263], dtype=int64))


ic| self.label_mask.shape: (16795, 10420)
ic| self.mask_amazon_ts.shape: (16795, 10420)
ic| self.label_mask_test.shape: (70001560,)
ic| self.error_mask_test.shape: (39745021,)
ic| bounds: (0.0015, 0.9985)
c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\scipy\optimize\_minimize.py:783: RuntimeWarning: Method 'bounded' does not support relative tolerance in x; defaulting to absolute tolerance.
  warn("Method 'bounded' does not support relative tolerance in x; "


0.38232011321635484
threshold 0.38232011321635484
(38867732,) (38867732,)


ic| label_current_deforestation_test_classified_incorrect.shape: (877289,)
    predicted_test_classified_incorrect.shape: (877289,)
ic| TP_H + FN_H + FP_H + TN_H: 877289
    len(label_mask_current_deforestation_test): 39745021
ic| TP_H + FN_H + FP_H + TN_H: 877289
    len(label_mask_current_deforestation_test): 39745021


cm_correct [[38348850   103851]
 [   25401   389630]]
cm_incorrect [[709082  52604]
 [ 71462  44141]]
[0.78955421 0.93879734 0.73427259 0.02207293 0.45626131 0.38183265]
0.6176798867836452
threshold 0.6176798867836452
(39487027,) (39487027,)


ic| label_current_deforestation_test_classified_incorrect.shape: (257994,)
    predicted_test_classified_incorrect.shape: (257994,)
ic| TP_H + FN_H + FP_H + TN_H: 257994
    len(label_mask_current_deforestation_test): 39745021
ic| TP_H + FN_H + FP_H + TN_H: 257994
    len(label_mask_current_deforestation_test): 39745021


cm_correct [[38858682   146942]
 [   54323   427080]]
cm_incorrect [[199250   9513]
 [ 42540   6691]]
[0.7440133  0.88715691 0.80484854 0.00649123 0.41292274 0.1359103 ]
0.23685977356729035
threshold 0.23685977356729035
(37678774,) (37678774,)


ic| label_current_deforestation_test_classified_incorrect.shape: (2066247,)
    predicted_test_classified_incorrect.shape: (2066247,)


cm_correct [[37271810    54641]
 [   11151   341172]]


ic| TP_H + FN_H + FP_H + TN_H: 2066247
    len(label_mask_current_deforestation_test): 39745021
ic| TP_H + FN_H + FP_H + TN_H: 2066247
    len(label_mask_current_deforestation_test): 39745021


cm_incorrect [[1786122  101814]
 [  85712   92599]]
[0.86195249 0.96835007 0.64295164 0.05198757 0.47630045 0.51931176]
0.42259971768922056
threshold 0.42259971768922056
(39039417,) (39039417,)


ic| label_current_deforestation_test_classified_incorrect.shape: (705604,)
    predicted_test_classified_incorrect.shape: (705604,)
ic| TP_H + FN_H + FP_H + TN_H: 705604
    len(label_mask_current_deforestation_test): 39745021
ic| TP_H + FN_H + FP_H + TN_H: 705604
    len(label_mask_current_deforestation_test): 39745021


cm_correct [[38498722   113356]
 [   28439   398900]]
cm_incorrect [[559210  43099]
 [ 68424  34871]]
[0.77871221 0.93345096 0.75174226 0.01775327 0.44723612 0.33758652]
0.3536155908821139
threshold 0.3536155908821139
(38708529,) (38708529,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1036492,)
    predicted_test_classified_incorrect.shape: (1036492,)
ic| TP_H + FN_H + FP_H + TN_H: 1036492
    len(label_mask_current_deforestation_test): 39745021
ic| TP_H + FN_H + FP_H + TN_H: 1036492
    len(label_mask_current_deforestation_test): 39745021


cm_correct [[38207258    95978]
 [   23470   381823]]
cm_incorrect [[850674  60477]
 [ 73393  51948]]
[0.79912558 0.94209128 0.71956    0.02607854 0.46206805 0.41445337]
0.3090188370521248
threshold 0.3090188370521248
(38393272,) (38393272,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1351749,)
    predicted_test_classified_incorrect.shape: (1351749,)
ic| TP_H + FN_H + FP_H + TN_H: 1351749
    len(label_mask_current_deforestation_test): 39745021
ic| TP_H + FN_H + 

cm_correct [[37922238    82328]
 [   19928   368778]]
cm_incorrect [[1135694   74127]
 [  76935   64993]]


FP_H + TN_H: 1351749
    len(label_mask_current_deforestation_test): 39745021


[0.81749744 0.94873246 0.6949762  0.03401052 0.46717223 0.45792937]
0.3318343176569557
threshold 0.3318343176569557
(38566199,) (38566199,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1178822,)
    predicted_test_classified_incorrect.shape: (1178822,)
ic| TP_H + FN_H + FP_H + TN_H: 1178822
    len(label_mask_current_deforestation_test): 39745021
ic| TP_H + FN_H + FP_H + TN_H: 1178822
    len(label_mask_current_deforestation_test): 39745021


cm_correct [[38079064    89651]
 [   21876   375608]]
cm_incorrect [[978868  66804]
 [ 74987  58163]]
[0.80730948 0.94496382 0.70784759 0.02965961 0.46542687 0.43682313]
0.331454116389318
threshold 0.331454116389318
(38563407,) (38563407,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1181614,)
    predicted_test_classified_incorrect.shape: (1181614,)
ic| TP_H + FN_H + FP_H + TN_H: 1181614
    len(label_mask_current_deforestation_test): 39745021
ic| TP_H + FN_H + FP_H + TN_H: 1181614
    len(label_mask_current_deforestation_test): 39745021


cm_correct [[38076544    89517]
 [   21852   375494]]
cm_incorrect [[981388  66938]
 [ 75011  58277]]
[0.80749488 0.94500511 0.70763276 0.02972986 0.46541549 0.43722616]
0.3228846022296084
threshold 0.3228846022296084
(38501588,) (38501588,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1243433,)
    predicted_test_classified_incorrect.shape: (1243433,)
ic| TP_H + FN_H + FP_H + TN_H: 1243433
    len(label_mask_current_deforestation_test): 39745021
ic| TP_H + FN_H + FP_H + TN_H: 1243433
    len(label_mask_current_deforestation_test): 39745021


cm_correct [[38020476    86919]
 [   21158   373035]]
cm_incorrect [[1037456   69536]
 [  75705   60736]]
[0.81102675 0.94632578 0.70299868 0.03128525 0.46622451 0.44514479]
0.32891750814079973
threshold 0.32891750814079973
(38545618,) (38545618,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1199403,)
    predicted_test_classified_incorrect.shape: (1199403,)
ic| TP_H + FN_H + FP_H + TN_H: 1199403
    len(label_mask_current_deforestation_test): 39745021
ic| TP_H + FN_H + FP_H + TN_H: 1199403
    len(label_mask_current_deforestation_test): 39745021


cm_correct [[38060344    88828]
 [   21660   374786]]
cm_incorrect [[997588  67627]
 [ 75203  58985]]
[0.80840095 0.94536456 0.7062985  0.03017744 0.46587211 0.43956986]
0.32982624286777135
threshold 0.32982624286777135
(38552087,) (38552087,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1192934,)
    predicted_test_classified_incorrect.shape: (1192934,)
ic| TP_H + FN_H + FP_H + TN_H: 1192934
    len(label_mask_current_deforestation_test): 39745021
ic| TP_H + FN_H + FP_H + TN_H: 1192934
    len(label_mask_current_deforestation_test): 39745021


cm_correct [[38066233    89082]
 [   21728   375044]]
cm_incorrect [[991699  67373]
 [ 75135  58727]]
[0.80806505 0.94523807 0.70678471 0.03001468 0.46571768 0.438713  ]
0.33004788512768396
threshold 0.33004788512768396
(38553662,) (38553662,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1191359,)
    predicted_test_classified_incorrect.shape: (1191359,)
ic| TP_H + FN_H + FP_H + TN_H: 1191359
    len(label_mask_current_deforestation_test): 39745021
ic| TP_H + FN_H + FP_H + TN_H: 1191359
    len(label_mask_current_deforestation_test): 39745021


cm_correct [[38067657    89149]
 [   21749   375107]]
cm_incorrect [[990275  67306]
 [ 75114  58664]]
[0.80797448 0.94519675 0.70690344 0.02997505 0.46569818 0.43851754]
0.32979290464232425
threshold 0.32979290464232425
(38551855,) (38551855,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1193166,)
    predicted_test_classified_incorrect.shape: (1193166,)
ic| TP_H + FN_H + FP_H + TN_H: 1193166
    len(label_mask_current_deforestation_test): 39745021
ic| TP_H + FN_H + FP_H + TN_H: 1193166
    len(label_mask_current_deforestation_test): 39745021


cm_correct [[38066023    89070]
 [   21724   375038]]
cm_incorrect [[991909  67385]
 [ 75139  58733]]
[0.80808346 0.94524677 0.70677341 0.03002052 0.46569879 0.43872505]
0.3299103812000415
threshold 0.3299103812000415
(38552684,) (38552684,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1192337,)
    predicted_test_classified_incorrect.shape: (1192337,)
ic| TP_H + FN_H + FP_H + TN_H: 1192337
    len(label_mask_current_deforestation_test): 39745021
ic| TP_H + FN_H + FP_H + TN_H: 1192337
    len(label_mask_current_deforestation_test): 39745021


cm_correct [[38066765    89111]
 [   21741   375067]]
cm_incorrect [[991167  67344]
 [ 75122  58704]]
[0.80802408 0.94521028 0.70682806 0.02999966 0.46572734 0.43865915]
0.3299629030268143
threshold 0.3299629030268143
(38553053,) (38553053,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1191968,)
    predicted_test_classified_incorrect.shape: (1191968,)
ic| TP_H + FN_H + FP_H + TN_H: 1191968
    len(label_mask_current_deforestation_test): 39745021
ic| TP_H + FN_H + FP_H + TN_H: 1191968
    len(label_mask_current_deforestation_test): 39745021


cm_correct [[38067106    89122]
 [   21744   375081]]
cm_incorrect [[990826  67333]
 [ 75119  58690]]
[0.80801072 0.94520507 0.70685444 0.02999037 0.46570864 0.43861026]
0.32987704297334647
threshold 0.32987704297334647
(38552444,) (38552444,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1192577,)
    predicted_test_classified_incorrect.shape: (1192577,)
ic| TP_H + FN_H + FP_H + TN_H: 1192577
    len(label_mask_current_deforestation_test): 39745021

cm_correct [[38066550    89104]
 [   21733   375057]]
cm_incorrect [[991382  67351]
 [ 75130  58714]]



ic| TP_H + FN_H + FP_H + TN_H: 1192577
    len(label_mask_current_deforestation_test): 39745021
ic| self.threshold_optimal: 0.3299103812000415


[0.80803213 0.94522795 0.70680921 0.0300057  0.46574386 0.43867488]
threshold 0.3299103812000415
(38552684,) (38552684,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1192337,)
    predicted_test_classified_incorrect.shape: (1192337,)
ic| TP_H + FN_H + FP_H + TN_H: 1192337
    len(label_mask_current_deforestation_test): 39745021
ic| TP_H + FN_H + FP_H + TN_H: 1192337
    len(label_mask_current_deforestation_test): 

cm_correct [[38066765    89111]
 [   21741   375067]]
cm_incorrect [[991167  67344]
 [ 75122  58704]]


39745021


[0.80802408 0.94521028 0.70682806 0.02999966 0.46572734 0.43865915]
threshold 0.3299103812000415
(39745021,) (39745021,)


ic| self.m_optimal: {'AA': array([0.02999966]),
                     'f1': 77.4,
                     'f1_H': array([0.45178817]),
                     'f1_L': array([0.87124994]),
                     'precision_H': array([0.46572734]),
                     'precision_L': array([0.80802408]),
                     'recall_H': array([0.43865915]),
                     'recall_L': array([0.94521028]),
                     'recall_Ltotal': array([0.70682806])}
ic| self.m_audited_optimal: {'f1': array([0.9017825]),
                             'precision': array([0.85098595]),
                             'recall': array([0.95902826])}


cm_audited [[39125276    89111]
 [   21741   508893]]
[0.85098595 0.95902826]
D:/Jorge/datasets/deforestation/MT/deforestation_past_years.tif
Loaded deforestation past years


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([161124576,   1332784,    240796,    338545,    313901,    287191,
                                                                       708581,    648966,    876898,   1007787,   1098901,   1054092,
                                                                      2096062,   2473828,   1400992], dtype=int64))


Label where deforestation past years is actual date (2019) = 1


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([161124576,   1332784,    240796,    338545,    313901,    287191,
                                                                       708581,    648966,    876898,   1007787,   1098901,   1054092,
                                                                      2096062,   2473828,   1400992], dtype=int64))


Past deforestation different from 0 (no deforestation)


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([161124576,   1332784,    240796,    338545,    313901,    287191,
                                                                       708581,    648966,    876898,   1007787,   1098901,   1054092,
                                                                      2096062,   2473828,   1400992], dtype=int64))


Past deforestation before 2008 is 2
D:/Jorge/datasets/deforestation/MT/deforestation_before_2008/deforestation_before_2008_MT.tif


ic| np.unique(label_past_deforestation_before_2008, return_counts=True): (array([  0, 215], dtype=uint8), array([122623260,  52380640], dtype=int64))
ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([161124576,   1332784,    240796,    338545,    313901,    287191,
                                                                       708581,    648966,    876898,   1007787,   1098901,   1054092,
                                                                      2096062,   2473828,   1400992], dtype=int64))
ic| label_per_date.shape: (16795, 10420, 1)


Mask label shape:  
 (16795, 10420, 1) 
 Unique values:  
 [0 1 2]
Tiles size:  3359 2084
Mask size:  (16795, 10420)


ic| image_stack.shape: (16795, 10420, 21)


Image shape:  (16795, 10420, 21)
mask:  (16795, 10420)
image stack:  (16795, 10420, 21)
ref : (16795, 10420, 1)
Training tiles:  [2, 4, 5, 6, 7, 12, 14, 15, 18, 21, 23, 24]
Validation tiles:  [9, 11, 25]
Test tiles:  [1, 3, 8, 10, 13, 16, 17, 19, 20, 22]


ic| im_idx_row.shape: (16795, 10420, 1)
    im_idx_col.shape: (16795, 10420, 1)
ic| im_idx_row.dtype: dtype('uint16')
    im_idx_col.dtype: dtype('uint16')
ic| im_idx.shape: (16795, 10420, 2), im_idx.dtype: dtype('uint16')
ic| coords.shape: (439, 271, 1, 128, 128, 2)
    coords.dtype: dtype('uint16')
ic| coords.shape: (118969, 2), coords.dtype: dtype('uint16')
ic| self.coords_train.shape: (54516, 3)
    self.coords_val.shape: (13175, 3)


training samples:  (2962, 3) validation samples:  (623, 3)
time:  0
Model: "model_4"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_enc_net (InputLayer)      [(None, 128, 128, 21 0                                            
__________________________________________________________________________________________________
res1_net1 (Conv2D)              (None, 128, 128, 16) 3040        input_enc_net[0][0]              
__________________________________________________________________________________________________
drop_net1 (Dropout)             (None, 128, 128, 16) 0           res1_net1[0][0]                  
__________________________________________________________________________________________________
res2_net1 (Conv2D)              (None, 128, 128, 16) 2320        drop_net1[0][0]                  
________________________

c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\keras\optimizer_v2\optimizer_v2.py:374: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  warnings.warn(
c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\keras\engine\training.py:1969: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  warnings.warn('`Model.fit_generator` is deprecated and '


Epoch 1/100
self.global_step 0.0
alpha Tensor("loss/add:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("loss/truediv:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("add:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("truediv:0", shape=(None, 128, 128, 1), dtype=float32)
K.int_shape(KL_reg) Tensor("mul_6:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("add_7:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("truediv_5:0", shape=(None, 128, 128, 1), dtype=float32)
K.int_shape(KL_reg) Tensor("mul_12:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("loss/add:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("loss/truediv:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("add:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("truediv:0", shape=(None, 128, 128, 1), dtype=float32)
K.int_shape(KL_reg) Tensor("mul_6:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("add_7:0", shape=(None, 128, 128, 3), dtype=float

c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py:494: CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.
  warnings.warn('Custom mask layers require a config and must override '


277/277 [==============================] - 24s 85ms/step - loss: 0.4912 - accuracy: 0.6144 - KL_term: 0.0065 - loglikelihood_term: 0.4848 - evidential_success: 43.3738 - evidential_fail: 1.9848 - acc: 0.6144 - annealing_coef: 0.0736 - global_step_get: 276.0000 - annealing_step_get: 3750.0000 - val_loss: 0.4947 - val_accuracy: 0.7055 - val_KL_term: 0.0100 - val_loglikelihood_term: 0.4881 - val_evidential_success: 20.8141 - val_evidential_fail: 1.4216 - val_acc: 0.7064 - val_annealing_coef: 0.1472 - val_global_step_get: 552.0000 - val_annealing_step_get: 3750.0000

Epoch 00002: val_loss did not improve from 0.49406
Epoch 3/100
self.global_step 552.0
277/277 [==============================] - 24s 86ms/step - loss: 0.3727 - accuracy: 0.6884 - KL_term: 0.0150 - loglikelihood_term: 0.3579 - evidential_success: 38.0267 - evidential_fail: 3.0131 - acc: 0.6882 - annealing_coef: 0.1104 - global_step_get: 414.0000 - annealing_step_get: 3750.0000 - val_loss: 0.3622 - val_accuracy: 0.6692 - val_KL_

ic| self.path_models+ '/' + self.method +'_'+str(0)+'.h5': 'D:/Jorge/datasets/deforestation/experiments/MT/exp193/models/resunet_0.h5'


time:  0
(39774655,)
(array([0, 1], dtype=uint8), array([39234711,   539944], dtype=int64))
(16795, 10420)
(array([0., 1.], dtype=float32), array([172570182,   2433718], dtype=int64))


ic| self.predicted_unpad.shape: (16795, 10420)
    self.predicted.shape: (16795, 10420)
ic| predicted_test.shape: (70001560,)
ic| predicted_test.shape: (39774655,)
ic| np.unique(predicted, return_counts=True): (array([0., 1.], dtype=float32), array([172570182,   2433718], dtype=int64))
    np.unique(predicted_larger_than_min_area, return_counts=True): (array([0., 1.], dtype=float32), array([172649769,   2354131], dtype=int64))
ic| np.unique(ignored_polygons, return_counts=True): (array([0., 1.], dtype=float32), array([174924313,     79587], dtype=int64))
ic| self.f1: 64.79, self.precision: 52.1, self.recall: 85.67
ic| self.label_mask_val.shape: (21000468,)
ic| self.label_mask_val_valid.shape: (10901852,)
ic| f1_val: 90.83
    precision_val: 93.24
    recall_val: 88.55
    mAP_val: 90.07


(array([0., 1.], dtype=float32), array([174173601,    830299], dtype=int64))


ic| self.label_mask.shape: (16795, 10420)
ic| self.mask_amazon_ts.shape: (16795, 10420)
ic| self.label_mask_test.shape: (70001560,)
ic| self.error_mask_test.shape: (39740011,)
ic| bounds: (0.0015, 0.9985)
c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\scipy\optimize\_minimize.py:783: RuntimeWarning: Method 'bounded' does not support relative tolerance in x; defaulting to absolute tolerance.
  warn("Method 'bounded' does not support relative tolerance in x; "


0.38232011321635484
threshold 0.38232011321635484
(37828204,) (37828204,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1911807,)
    predicted_test_classified_incorrect.shape: (1911807,)


cm_correct [[37081236   322671]
 [   19070   405227]]


ic| TP_H + FN_H + FP_H + TN_H: 1911807
    len(label_mask_current_deforestation_test): 39740011
ic| TP_H + FN_H + FP_H + TN_H: 1911807
    len(label_mask_current_deforestation_test): 39740011


cm_incorrect [[1710978   94936]
 [  56903   48990]]
[0.55670849 0.95505507 0.76430525 0.04810786 0.34038325 0.46263681]
0.6176798867836452
threshold 0.6176798867836452
(38764704,) (38764704,)


ic| label_current_deforestation_test_classified_incorrect.shape: (975307,)
    predicted_test_classified_incorrect.shape: (975307,)
ic| TP_H + FN_H + FP_H + TN_H: 975307
    len(label_mask_current_deforestation_test): 39740011
ic| TP_H + FN_H + FP_H + TN_H: 975307
    len(label_mask_current_deforestation_test): 39740011


cm_correct [[37899189   395589]
 [   28958   440968]]
cm_incorrect [[893025  22018]
 [ 47015  13249]]
[0.52712248 0.93837753 0.83171693 0.02454219 0.37567698 0.21984933]
0.7631402264327096
threshold 0.7631402264327096
(39399509,) (39399509,)


ic| label_current_deforestation_test_classified_incorrect.shape: (340502,)
    predicted_test_classified_incorrect.shape: (340502,)
d:\Jorge\deforestation_uncertainty\src\metrics.py:299: RuntimeWarning: invalid value encountered in longlong_scalars
  precision_H = TP_H / (TP_H + FP_H)
ic| TP_H + FN_H + FP_H + TN_H: 340502
    len(label_mask_current_deforestation_test): 39740011
ic| TP_H + FN_H + FP_H + TN_H: 340502
    len(label_mask_current_deforestation_test): 39740011


cm_correct [[38487598   417607]
 [   40087   454217]]
cm_incorrect [[304616      0]
 [ 35886      0]]
[0.52099621 0.91890213 0.85670609 0.00856824        nan 0.        ]
0.5625693451508236
threshold 0.5625693451508236
(38553510,) (38553510,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1186501,)
    predicted_test_classified_incorrect.shape: (1186501,)
ic| TP_H + FN_H + FP_H + TN_H: 1186501
    len(label_mask_current_deforestation_test): 39740011
ic| TP_H + FN_H + FP_H + TN_H: 1186501
    len(label_mask_current_deforestation_test): 39740011


cm_correct [[37711715   381251]
 [   26958   433586]]
cm_incorrect [[1080499   36356]
 [  49015   20631]]
[0.53211378 0.94146488 0.81779362 0.02985658 0.36202994 0.29622663]
0.5322547534432517
threshold 0.5322547534432517
(38439791,) (38439791,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1300220,)
    predicted_test_classified_incorrect.shape: (1300220,)
ic| TP_H + FN_H + FP_H + TN_H: 1300220
    len(label_mask_current_deforestation_test): 39740011
ic| TP_H + FN_H + FP_H + TN_H: 1300220
    len(label_mask_current_deforestation_test

cm_correct [[37611922   372423]
 [   25975   429471]]
cm_incorrect [[1180292   45184]
 [  49998   24746]]


): 39740011


[0.53557079 0.94296799 0.81003225 0.03271816 0.35386815 0.33107674]
0.5674144877071775
threshold 0.5674144877071775
(38572008,) (38572008,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1168003,)
    predicted_test_classified_incorrect.shape: (1168003,)
ic| TP_H + FN_H + FP_H + TN_H: 1168003
    len(label_mask_current_deforestation_test): 39740011
ic| TP_H + FN_H + FP_H + TN_H: 1168003
    len(label_mask_current_deforestation_test): 39740011


cm_correct [[37728074   382626]
 [   27101   434207]]
cm_incorrect [[1064140   34981]
 [  48872   20010]]
[0.53157377 0.94125183 0.8189649  0.02939111 0.36387773 0.29049679]
0.5556611777093843
threshold 0.5556611777093843
(38527075,) (38527075,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1212936,)
    predicted_test_classified_incorrect.shape: (1212936,)
ic| TP_H + FN_H + FP_H + TN_H: 1212936
    len(label_mask_current_deforestation_test): 39740011
ic| TP_H + FN_H + FP_H + TN_H: 1212936
    len(label_mask_current_deforestation_test): 39740011


cm_correct [[37688493   379216]
 [   26731   432635]]
cm_incorrect [[1103721   38391]
 [  49242   21582]]
[0.53289951 0.94180893 0.81599992 0.03052178 0.35986194 0.30472721]
0.5612490938433985
threshold 0.5612490938433985
(38548450,) (38548450,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1191561,)
    predicted_test_classified_incorrect.shape: (1191561,)
ic| TP_H + FN_H + FP_H + TN_H: 1191561
    len(label_mask_current_deforestation_test): 39740011
ic| TP_H + FN_H + FP_H + TN_H: 1191561


cm_correct [[37707213   380890]
 [   26925   433422]]
cm_incorrect [[1085001   36717]
 [  49048   20795]]


    len(label_mask_current_deforestation_test): 39740011


[0.53225545 0.94151151 0.8174843  0.02998391 0.36157671 0.29773922]
0.5601272649059197
threshold 0.5601272649059197
(38544083,) (38544083,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1195928,)
    predicted_test_classified_incorrect.shape: (1195928,)
ic| TP_H + FN_H + FP_H + TN_H: 1195928
    len(label_mask_current_deforestation_test): 39740011
ic| TP_H + FN_H + FP_H + TN_H: 1195928
    len(label_mask_current_deforestation_test): 39740011


cm_correct [[37703375   380570]
 [   26879   433259]]
cm_incorrect [[1088839   37037]
 [  49094   20958]]
[0.53237105 0.94158492 0.81717686 0.0300938  0.36137598 0.29917775]
0.5611986092073195
threshold 0.5611986092073195
(38548233,) (38548233,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1191778,)
    predicted_test_classified_incorrect.shape: (1191778,)
ic| TP_H + FN_H + FP_H + TN_H: 1191778
    len(label_mask_current_deforestation_test): 39740011
ic| TP_H + FN_H + FP_H + TN_H: 1191778
    len(label_mask_current_deforestation_test): 39740011


cm_correct [[37707026   380870]
 [   26923   433414]]
cm_incorrect [[1085188   36737]
 [  49050   20803]]
[0.53226393 0.94151459 0.81746921 0.02998937 0.3615398  0.29781112]
0.5608973155025561
threshold 0.5608973155025561
(38546981,) (38546981,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1193030,)
    predicted_test_classified_incorrect.shape: (1193030,)
ic| TP_H + FN_H + FP_H + TN_H: 1193030
    len(label_mask_current_deforestation_test): 39740011
ic| TP_H + FN_H + FP_H + TN_H: 1193030
    len(label_mask_current_deforestation_test): 39740011


cm_correct [[37705929   380777]
 [   26910   433365]]
cm_incorrect [[1086285   36830]
 [  49063   20852]]
[0.53229658 0.94153495 0.81737679 0.03002088 0.36149925 0.29824787]
0.5610835252526962
threshold 0.5610835252526962
(38547761,) (38547761,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1192250,)
    predicted_test_classified_incorrect.shape: (1192250,)
ic| TP_H + FN_H + FP_H + TN_H: 1192250
    len(label_mask_current_deforestation_test): 39740011
ic| TP_H + FN_H + FP_H + TN_H: 1192250
    len(label_mask_current_deforestation_test): 39740011


cm_correct [[37706619   380827]
 [   26918   433397]]
cm_incorrect [[1085595   36780]
 [  49055   20820]]
[0.53228227 0.94152265 0.81743715 0.03000125 0.36145833 0.29796064]
0.5610123994571793
threshold 0.5610123994571793
(38547433,) (38547433,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1192578,)
    predicted_test_classified_incorrect.shape: (1192578,)
ic| TP_H + FN_H + FP_H + TN_H: 1192578
    len(label_mask_current_deforestation_test): 39740011
ic| TP_H + FN_H + FP_H + TN_H: 1192578
    len(label_mask_current_deforestation_test): 39740011


cm_correct [[37706324   380808]
 [   26915   433386]]
cm_incorrect [[1085890   36799]
 [  49058   20831]]
[0.53228837 0.94152739 0.8174164  0.0300095  0.36146104 0.29805835]
0.5611168669082431
threshold 0.5611168669082431
(38547909,) (38547909,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1192102,)
    predicted_test_classified_incorrect.shape: (1192102,)
ic| TP_H + FN_H + FP_H + TN_H: 1192102
    len(label_mask_current_deforestation_test): 39740011
ic| TP_H + FN_H + FP_H + TN_H:

cm_correct [[37706742   380843]
 [   26921   433403]]
cm_incorrect [[1085472   36764]
 [  49052   20814]]


 1192102
    len(label_mask_current_deforestation_test): 39740011


[0.53227526 0.94151728 0.81744846 0.02999753 0.36149224 0.29791315]
0.5610501835971493
threshold 0.5610501835971493
(38547602,) (38547602,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1192409,)
    predicted_test_classified_incorrect.shape: (1192409,)
ic| TP_H + FN_H + FP_H + TN_H: 1192409
    len(label_mask_current_deforestation_test): 39740011
ic| TP_H + FN_H + FP_H + TN_H: 1192409
    len(label_mask_current_deforestation_test): 39740011
ic| self.threshold_optimal: 0.5610835252526962


cm_correct [[37706476   380818]
 [   26916   433392]]
cm_incorrect [[1085738   36789]
 [  49057   20825]]
[0.53228528 0.94152611 0.81742771 0.03000525 0.36145728 0.29800235]
threshold 0.5610835252526962
(38547761,) (38547761,)


ic| label_current_deforestation_test_classified_incorrect.shape: (1192250,)
    predicted_test_classified_incorrect.shape: (1192250,)
ic| TP_H + FN_H + FP_H + TN_H: 1192250
    len(label_mask_current_deforestation_test): 39740011
ic| TP_H + FN_H + FP_H + TN_H: 1192250
    len(label_mask_current_deforestation_test): 39740011


cm_correct [[37706619   380827]
 [   26918   433397]]
cm_incorrect [[1085595   36780]
 [  49055   20820]]
[0.53228227 0.94152265 0.81743715 0.03000125 0.36145833 0.29796064]
threshold 0.5610835252526962
(39740011,) (39740011,)


ic| self.m_optimal: {'AA': array([0.03000125]),
                     'f1': 64.79,
                     'f1_H': array([0.32665228]),
                     'f1_L': array([0.68008433]),
                     'precision_H': array([0.36145833]),
                     'precision_L': array([0.53228227]),
                     'recall_H': array([0.29796064]),
                     'recall_L': array([0.94152265]),
                     'recall_Ltotal': array([0.81743715])}
ic| self.m_audited_optimal: {'f1': array([0.71169612]),
                             'precision': array([0.56924847]),
                             'recall': array([0.94922952])}


cm_audited [[38828994   380827]
 [   26918   503272]]
[0.56924847 0.94922952]
D:/Jorge/datasets/deforestation/MT/deforestation_past_years.tif
Loaded deforestation past years


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([161124576,   1332784,    240796,    338545,    313901,    287191,
                                                                       708581,    648966,    876898,   1007787,   1098901,   1054092,
                                                                      2096062,   2473828,   1400992], dtype=int64))


Label where deforestation past years is actual date (2019) = 1


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([161124576,   1332784,    240796,    338545,    313901,    287191,
                                                                       708581,    648966,    876898,   1007787,   1098901,   1054092,
                                                                      2096062,   2473828,   1400992], dtype=int64))


Past deforestation different from 0 (no deforestation)


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([161124576,   1332784,    240796,    338545,    313901,    287191,
                                                                       708581,    648966,    876898,   1007787,   1098901,   1054092,
                                                                      2096062,   2473828,   1400992], dtype=int64))


Past deforestation before 2008 is 2
D:/Jorge/datasets/deforestation/MT/deforestation_before_2008/deforestation_before_2008_MT.tif


ic| np.unique(label_past_deforestation_before_2008, return_counts=True): (array([  0, 215], dtype=uint8), array([122623260,  52380640], dtype=int64))
ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([161124576,   1332784,    240796,    338545,    313901,    287191,
                                                                       708581,    648966,    876898,   1007787,   1098901,   1054092,
                                                                      2096062,   2473828,   1400992], dtype=int64))
ic| label_per_date.shape: (16795, 10420, 1)


Mask label shape:  
 (16795, 10420, 1) 
 Unique values:  
 [0 1 2]
Tiles size:  3359 2084
Mask size:  (16795, 10420)


ic| image_stack.shape: (16795, 10420, 21)


Image shape:  (16795, 10420, 21)
mask:  (16795, 10420)
image stack:  (16795, 10420, 21)
ref : (16795, 10420, 1)
Training tiles:  [2, 4, 5, 6, 7, 12, 14, 15, 18, 21, 23, 24]
Validation tiles:  [9, 11, 25]
Test tiles:  [1, 3, 8, 10, 13, 16, 17, 19, 20, 22]


ic| im_idx_row.shape: (16795, 10420, 1)
    im_idx_col.shape: (16795, 10420, 1)
ic| im_idx_row.dtype: dtype('uint16')
    im_idx_col.dtype: dtype('uint16')
ic| im_idx.shape: (16795, 10420, 2), im_idx.dtype: dtype('uint16')
ic| coords.shape: (439, 271, 1, 128, 128, 2)
    coords.dtype: dtype('uint16')
ic| coords.shape: (118969, 2), coords.dtype: dtype('uint16')
ic| self.coords_train.shape: (54516, 3)
    self.coords_val.shape: (13175, 3)


training samples:  (2962, 3) validation samples:  (623, 3)
time:  0
Model: "model_6"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_enc_net (InputLayer)      [(None, 128, 128, 21 0                                            
__________________________________________________________________________________________________
res1_net1 (Conv2D)              (None, 128, 128, 16) 3040        input_enc_net[0][0]              
__________________________________________________________________________________________________
drop_net1 (Dropout)             (None, 128, 128, 16) 0           res1_net1[0][0]                  
__________________________________________________________________________________________________
res2_net1 (Conv2D)              (None, 128, 128, 16) 2320        drop_net1[0][0]                  
________________________

c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\keras\optimizer_v2\optimizer_v2.py:374: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  warnings.warn(
c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\keras\engine\training.py:1969: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  warnings.warn('`Model.fit_generator` is deprecated and '


Epoch 1/100
self.global_step 0.0
alpha Tensor("loss/add:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("loss/truediv:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("add:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("truediv:0", shape=(None, 128, 128, 1), dtype=float32)
K.int_shape(KL_reg) Tensor("mul_6:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("add_7:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("truediv_5:0", shape=(None, 128, 128, 1), dtype=float32)
K.int_shape(KL_reg) Tensor("mul_12:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("loss/add:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("loss/truediv:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("add:0", shape=(None, 128, 128, 3), dtype=float32)
u Tensor("truediv:0", shape=(None, 128, 128, 1), dtype=float32)
K.int_shape(KL_reg) Tensor("mul_6:0", shape=(None, 128, 128, 1), dtype=float32)
alpha Tensor("add_7:0", shape=(None, 128, 128, 3), dtype=float

c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py:494: CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.
  warnings.warn('Custom mask layers require a config and must override '


277/277 [==============================] - 24s 86ms/step - loss: 0.8333 - accuracy: 0.3026 - KL_term: -8.7738e-08 - loglikelihood_term: 0.8333 - evidential_success: 0.0000e+00 - evidential_fail: 0.0000e+00 - acc: 0.3027 - annealing_coef: 0.0736 - global_step_get: 276.0000 - annealing_step_get: 3750.0000 - val_loss: 0.8333 - val_accuracy: 0.2543 - val_KL_term: -1.7548e-07 - val_loglikelihood_term: 0.8333 - val_evidential_success: 0.0000e+00 - val_evidential_fail: 0.0000e+00 - val_acc: 0.2526 - val_annealing_coef: 0.1472 - val_global_step_get: 552.0000 - val_annealing_step_get: 3750.0000

Epoch 00002: val_loss did not improve from 0.83333
Epoch 3/100
self.global_step 552.0
277/277 [==============================] - 24s 86ms/step - loss: 0.8333 - accuracy: 0.3037 - KL_term: -1.3161e-07 - loglikelihood_term: 0.8333 - evidential_success: 0.0000e+00 - evidential_fail: 0.0000e+00 - acc: 0.3036 - annealing_coef: 0.1104 - global_step_get: 414.0000 - annealing_step_get: 3750.0000 - val_loss: 0.8

ic| self.path_models+ '/' + self.method +'_'+str(0)+'.h5': 'D:/Jorge/datasets/deforestation/experiments/MT/exp194/models/resunet_0.h5'


time:  0
(39774655,)
(array([0, 1], dtype=uint8), array([39234711,   539944], dtype=int64))
(16795, 10420)
(array([0.], dtype=float32), array([175003900], dtype=int64))


ic| self.predicted_unpad.shape: (16795, 10420)
    self.predicted.shape: (16795, 10420)
ic| predicted_test.shape: (70001560,)
ic| predicted_test.shape: (39774655,)
ic| np.unique(predicted, return_counts=True): (array([0.], dtype=float32), array([175003900], dtype=int64))
    np.unique(predicted_larger_than_min_area, return_counts=True): (array([0.], dtype=float32), array([175003900], dtype=int64))
ic| np.unique(ignored_polygons, return_counts=True): (array([0.], dtype=float32), array([175003900], dtype=int64))
c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
ic| self.f1: 0.0, self.precision: 0.0, self.recall: 0.0
ic| self.label_mask_val.shape: (21000468,)
ic| self.label_mask_val_valid.shape: (10906966,)
c:\Users\jchamorro\Anaconda3\

(array([0., 1.], dtype=float32), array([173103734,   1900166], dtype=int64))


ic| self.label_mask.shape: (16795, 10420)
ic| self.mask_amazon_ts.shape: (16795, 10420)
ic| self.label_mask_test.shape: (70001560,)
ic| self.error_mask_test.shape: (39774655,)
ic| bounds: (0.0015, 0.9985)
c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\scipy\optimize\_minimize.py:783: RuntimeWarning: Method 'bounded' does not support relative tolerance in x; defaulting to absolute tolerance.
  warn("Method 'bounded' does not support relative tolerance in x; "


0.38232011321635484
threshold 0.38232011321635484
(0,) (0,)
cm_correct []


IndexError: index 0 is out of bounds for axis 0 with size 0

In [ ]:
print(results)

[{'metrics': {'precision_L': array([nan]), 'recall_L': array([0.]), 'recall_Ltotal': array([0.]), 'AA': array([0.03000042]), 'precision_H': array([nan]), 'recall_H': array([0.]), 'f1_L': array([nan]), 'f1_H': array([nan]), 'f1': 0.0}, 'metrics_audited': {'precision': array([1.]), 'recall': array([0.87966265]), 'f1': array([0.93597928])}, 'exp': 181}, {'metrics': {'precision_L': array([0.9266887]), 'recall_L': array([0.84085823]), 'recall_Ltotal': array([0.50764546]), 'AA': array([0.02999879]), 'precision_H': array([0.75952801]), 'recall_H': array([0.31876432]), 'f1_L': array([0.88168954]), 'f1_H': array([0.44906269]), 'f1': 73.97}, 'metrics_audited': {'precision': array([0.95746098]), 'recall': array([0.90392245]), 'f1': array([0.92992176])}, 'exp': 182}, {'metrics': {'precision_L': array([0.94748293]), 'recall_L': array([0.89449666]), 'recall_Ltotal': array([0.63664633]), 'AA': array([0.03000292]), 'precision_H': array([0.64688705]), 'recall_H': array([0.43562819]), 'f1_L': array([0.9

In [ ]:
trainer.f1

78.95

In [ ]:
print(trainer.f1)

78.95
