In [1]:
import tracemalloc

from utils_v1 import *


In [2]:
from icecream import ic

import numpy as np
from src.dataset import (
    MultipleDates,
    PA, PADeforestationTime, PADistanceMap, PAMultipleDates,
    MTDeforestationTime,
    MTMultipleDates
)

# from src.dataset_legacy import MTDeforestationTime
from src import training_generator as generator
from src.patchesHandler import PatchesHandler, PatchesHandlerMultipleDates, PatchesHandlerEvidential

from src.trainer.evidential import TrainerEvidential

from mpl_toolkits.axes_grid1 import make_axes_locatable

import cv2
from src import metrics as _metric
import json
import pickle 
import src.trainer.evidential as evidential
from src.backend.Logger import Logger



In [3]:
'''
if config["training"] == True:
	dates = [2017, 2018]
else:
	dates = [2018, 2019]
if config["training"] == True:
	dates = [2018, 2019]
else:
	dates = [2019, 2020]
'''

site = 'PA'
if site == 'PA':
	#dates = [2018, 2019]
	dates = [2018, 2019]

	dataset = PAMultipleDates(dates = dates, # dates = [2016,2017,2018,2019]
		addPastDeforestationInput = True,
		borderBuffer = 2)			

	#exp_id_base = 148
	# exp_id_base = 155
	exp_id_base = 194
	exp_id_base = 198
	exp_id_base = 214

	# earlier date
	exp_id_base = 224
	exp_id_base = 194


else:
	
	dates = [2019, 2020]

	dataset = MTMultipleDates(dates = dates, # dates = [2016,2017,2018,2019]
		addPastDeforestationInput = True,
		borderBuffer = 2)	
	
	# MT
	# exp_id_base = 196

ic(dates)

if issubclass(type(dataset), MultipleDates):
	patchesHandler = PatchesHandlerEvidential(
		dataset)
else:
	patchesHandler = PatchesHandler()



ic| list(self.date_ids): [0]
ic| self.image_channels: [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]]
ic| dates: [2018, 2019]
ic| self.input_image_shape: 21
ic| self.dataset.image_channels: [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]]


In [4]:
repetition_n = 10
experiment_values = np.ones(repetition_n).astype(np.uint8)


# experiment_values = [int(x) for x in experiment_values]
results = []



exp_ids = range(exp_id_base, exp_id_base+len(experiment_values))


In [5]:
exp_ids

range(194, 204)

In [6]:
from enum import Enum
UncertaintyMethod = Enum('Predictor', 'pred_var MI pred_entropy KL pred_entropy_single evidential')
uncertaintyMethod = "evidential"


In [7]:
idx = 0
while idx < len(exp_ids):
# for experiment_value, exp_id in zip(experiment_values, exp_ids):
    try:
        config = {
        "training": False,
        "learning_rate": 1e-4,
        "weights": [0.1, 0.9, 0],
        "save_probabilities": False,
        "loadInference": False,
        "addPastDeforestationInput": True,
        "inference_times": 1,
        "Uncertainty": {
            "annealing_step": 10*375 # 1875
        },
        "uncertainty_method": uncertaintyMethod,
        "evidence_function": evidential.relu_evidence
        }
        print("Beginning run number {}".format(idx))

        logger = Logger()
        trainer = TrainerEvidential(config, dataset, patchesHandler, logger)

        trainer.defineExperiment(exp_ids[idx])

        trainer.setExperimentPath()
        trainer.createLogFolders()

        trainer.loadDataset()

        # %%
        if config["training"] == True:
            trainer.run()

        # %%
        result = trainer.run_predictor()
        print("Result idx {}: {}".format(idx, result))
        results.append(result)


        with open('log.pkl', 'wb') as f:
            pickle.dump(results, f)
        idx += 1
        print("Grid execution idx: {}".format(idx))
    except Exception as e: 
        print(e)
        print("Execution error in idx {}. Retrying...".format(idx))
        continue

Beginning run number 0
D:/Jorge/datasets/deforestation/Para/deforestation_past_years.tif
Loaded deforestation past years


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Label where deforestation past years is actual date (2019) = 1


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation different from 0 (no deforestation)


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation before 2008 is 2
D:/Jorge/datasets/deforestation/deforestation_before_2008/deforestation_before_2008_para.tif


ic| np.unique(label_past_deforestation_before_2008, return_counts=True): (array([  0, 215], dtype=uint8), array([124211220,  38957970], dtype=int64))
ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))
ic| label_per_date.shape: (17730, 9203, 1)


Removing bufer................
Mask label shape:  
 (17730, 9203, 1) 
 Unique values:  
 [0 1 2]
Tiles size:  3546 2300
Mask size:  (17730, 9200)


ic| image_stack.shape: (17730, 9203, 21)


Image shape:  (17730, 9203, 21)
mask:  (17730, 9200)
image stack:  (17730, 9200, 21)
ref : (17730, 9200, 1)
Training tiles:  [1, 3, 5, 8, 11, 13, 14, 20]
Validation tiles:  [6, 19]
Test tiles:  [2, 4, 7, 9, 10, 12, 15, 16, 17, 18]
-30.0 -16.0


ic| self.path_models+ '/' + self.method +'_'+str(0)+'.h5': 'D:/Jorge/datasets/deforestation/experiments/exp194/models/resunet_0.h5'


time:  0
(54236371,)
(array([0, 1], dtype=uint8), array([53470765,   765606], dtype=int64))
(17730, 9200)
(array([0., 1.], dtype=float32), array([161359966,   1756034], dtype=int64))


ic| self.predicted_unpad.shape: (17730, 9200)
    self.predicted.shape: (17730, 9200)
ic| predicted_test.shape: (81558000,)
ic| predicted_test.shape: (54236371,)
ic| np.unique(predicted, return_counts=True): (array([0., 1.], dtype=float32), array([161359966,   1756034], dtype=int64))
    np.unique(predicted_larger_than_min_area, return_counts=True): (array([0., 1.], dtype=float32), array([161681613,   1434387], dtype=int64))
ic| np.unique(ignored_polygons, return_counts=True): (array([0., 1.], dtype=float32), array([162794353,    321647], dtype=int64))
ic| self.f1: 77.05, self.precision: 86.96, self.recall: 69.16
ic| self.label_mask_val.shape: (16311600,)
ic| self.label_mask_val_valid.shape: (9417288,)
ic| f1_val: 78.85
    precision_val: 85.01
    recall_val: 73.53
    mAP_val: 88.17


D:/Jorge/datasets/deforestation/Para/deforestation_past_years.tif
Loaded deforestation past years


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Label where deforestation past years is actual date (2019) = 1


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation different from 0 (no deforestation)


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation before 2008 is 2
D:/Jorge/datasets/deforestation/deforestation_before_2008/deforestation_before_2008_para.tif


ic| np.unique(label_past_deforestation_before_2008, return_counts=True): (array([  0, 215], dtype=uint8), array([124211220,  38957970], dtype=int64))
ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))
ic| label_per_date.shape: (17730, 9203, 1)


(array([0., 1.], dtype=float32), array([162297181,    818819], dtype=int64))
[0. 1.]


ic| self.label_mask.shape: (17730, 9200)
ic| self.mask_amazon_ts.shape: (17730, 9200)
ic| self.label_mask_test.shape: (81558000,)
ic| self.error_mask_test.shape: (54079850,)
ic| trainer.dataset.previewLims1: array([2200, 3200, 6900, 7900])
    trainer.dataset.previewLims2: array([ 500, 1500, 3500, 4500])
ic| np.unique(trainer.mask_amazon_ts[lims[0]:lims[1], lims[2]:lims[3]]): array([1], dtype=uint8)
ic| np.unique(trainer.mask_amazon_ts[lims[0]:lims[1], lims[2]:lims[3]], return_counts=True): (array([1], dtype=uint8), array([1000000], dtype=int64))
Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).
Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).
Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).


(54079850,) (54079850,)
0.3845722890780702


ic| bounds: (0.0015, 0.9985)


0.053347713360914366
0.38232011321635484
threshold 0.38232011321635484


c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\scipy\optimize\_minimize.py:783: RuntimeWarning: Method 'bounded' does not support relative tolerance in x; defaulting to absolute tolerance.
  warn("Method 'bounded' does not support relative tolerance in x; "
ic| label_current_deforestation_test_classified_incorrect.shape: (2372089,)
    predicted_test_classified_incorrect.shape: (2372089,)
ic| TP_H + FN_H + FP_H + TN_H: 2372089
    len(label_mask_current_deforestation_test): 54079850
ic| TP_H + FN_H + FP_H + TN_H: 2372089
    len(label_mask_current_deforestation_test): 54079850


[0.90898128 0.95486465 0.58290591 0.04386271 0.70585866 0.27903496
 0.09719104]
0.6176798867836452
threshold 0.6176798867836452


ic| label_current_deforestation_test_classified_incorrect.shape: (1455367,)
    predicted_test_classified_incorrect.shape: (1455367,)
ic| TP_H + FN_H + FP_H + TN_H: 1455367
    len(label_mask_current_deforestation_test): 54079850
ic| TP_H + FN_H + FP_H + TN_H: 1455367
    len(label_mask_current_deforestation_test): 54079850


[0.88229497 0.94739051 0.65035212 0.02691145 0.70935855 0.13156275
 0.13583208]
0.7631402264327096
threshold 0.7631402264327096


ic| label_current_deforestation_test_classified_incorrect.shape: (1076350,)
    predicted_test_classified_incorrect.shape: (1076350,)
d:\Jorge\deforestation_uncertainty\src\metrics.py:296: RuntimeWarning: invalid value encountered in longlong_scalars
  precision_H = TP_H / (TP_H + FP_H)
ic| TP_H + FN_H + FP_H + TN_H: 1076350
    len(label_mask_current_deforestation_test): 54079850
ic| TP_H + FN_H + FP_H + TN_H: 1076350
    len(label_mask_current_deforestation_test): 54079850


[0.86964977 0.93499635 0.69160141 0.01990298        nan 0.
 0.15917504]
0.5927692406058288
threshold 0.5927692406058288


ic| label_current_deforestation_test_classified_incorrect.shape: (1532357,)
    predicted_test_classified_incorrect.shape: (1532357,)
ic| TP_H + FN_H + FP_H + TN_H: 1532357
    len(label_mask_current_deforestation_test): 54079850
ic| TP_H + FN_H + FP_H + TN_H: 1532357
    len(label_mask_current_deforestation_test): 54079850


[0.88465705 0.94803996 0.64268533 0.02833508 0.71114807 0.15187062
 0.13133556]
0.5123848268458062
threshold 0.5123848268458062


ic| label_current_deforestation_test_classified_incorrect.shape: (1806934,)
    predicted_test_classified_incorrect.shape: (1806934,)
ic| TP_H + FN_H + FP_H + TN_H: 1806934
    len(label_mask_current_deforestation_test): 54079850
ic| TP_H + FN_H + FP_H + TN_H: 1806934
    len(label_mask_current_deforestation_test): 54079850


[0.89284361 0.95021739 0.62029424 0.03341233 0.70935319 0.20537302
 0.11745868]
0.5670845115586073
threshold 0.5670845115586073


ic| label_current_deforestation_test_classified_incorrect.shape: (1615691,)
    predicted_test_classified_incorrect.shape: (1615691,)
ic| TP_H + FN_H + FP_H + TN_H: 1615691
    len(label_mask_current_deforestation_test): 54079850
ic| TP_H + FN_H + FP_H + TN_H: 1615691
    len(label_mask_current_deforestation_test): 54079850


[0.88719759 0.94873632 0.63526115 0.02987603 0.71106974 0.17051447
 0.12678931]
0.5461910911722203
threshold 0.5461910911722203


ic| label_current_deforestation_test_classified_incorrect.shape: (1686764,)
    predicted_test_classified_incorrect.shape: (1686764,)
ic| TP_H + FN_H + FP_H + TN_H: 1686764
    len(label_mask_current_deforestation_test): 54079850
ic| TP_H + FN_H + FP_H + TN_H: 1686764
    len(label_mask_current_deforestation_test): 54079850


[0.8893756  0.94930459 0.62942215 0.03119025 0.710199   0.18452734
 0.12316835]
0.5673425696059541
threshold 0.5673425696059541


ic| label_current_deforestation_test_classified_incorrect.shape: (1614824,)
    predicted_test_classified_incorrect.shape: (1614824,)
ic| TP_H + FN_H + FP_H + TN_H: 1614824
    len(label_mask_current_deforestation_test): 54079850
ic| TP_H + FN_H + FP_H + TN_H: 1614824
    len(label_mask_current_deforestation_test): 54079850


[0.88717091 0.94873072 0.6353411  0.02985999 0.71106272 0.17031798
 0.12683479]
0.5614073954440004
threshold 0.5614073954440004


ic| label_current_deforestation_test_classified_incorrect.shape: (1634489,)
    predicted_test_classified_incorrect.shape: (1634489,)
ic| TP_H + FN_H + FP_H + TN_H: 1634489
    len(label_mask_current_deforestation_test): 54079850
ic| TP_H + FN_H + FP_H + TN_H: 1634489
    len(label_mask_current_deforestation_test): 54079850


[0.8878287  0.94887496 0.63372559 0.03022362 0.71037983 0.17425679
 0.12582205]
0.5649160461609072
threshold 0.5649160461609072


ic| label_current_deforestation_test_classified_incorrect.shape: (1622888,)
    predicted_test_classified_incorrect.shape: (1622888,)
ic| TP_H + FN_H + FP_H + TN_H: 1622888
    len(label_mask_current_deforestation_test): 54079850
ic| TP_H + FN_H + FP_H + TN_H: 1622888
    len(label_mask_current_deforestation_test): 54079850


[0.88743201 0.9487971  0.6346767  0.03000911 0.71084068 0.17194045
 0.12641628]
0.5635758608417005
threshold 0.5635758608417005


ic| label_current_deforestation_test_classified_incorrect.shape: (1627223,)
    predicted_test_classified_incorrect.shape: (1627223,)
ic| TP_H + FN_H + FP_H + TN_H: 1627223
    len(label_mask_current_deforestation_test): 54079850
ic| TP_H + FN_H + FP_H + TN_H: 1627223
    len(label_mask_current_deforestation_test): 54079850


[0.88758137 0.94881988 0.63431004 0.03008927 0.71068516 0.17283781
 0.12619268]
0.565176316739369
threshold 0.565176316739369


ic| label_current_deforestation_test_classified_incorrect.shape: (1622032,)
    predicted_test_classified_incorrect.shape: (1622032,)
ic| TP_H + FN_H + FP_H + TN_H: 1622032
    len(label_mask_current_deforestation_test): 54079850
ic| TP_H + FN_H + FP_H + TN_H: 1622032
    len(label_mask_current_deforestation_test): 54079850


[0.88739563 0.94877923 0.63474975 0.02999328 0.71091959 0.17176626
 0.12645332]
0.5652096584556218
threshold 0.5652096584556218


ic| label_current_deforestation_test_classified_incorrect.shape: (1621911,)
    predicted_test_classified_incorrect.shape: (1621911,)
ic| TP_H + FN_H + FP_H + TN_H: 1621911
    len(label_mask_current_deforestation_test): 54079850
ic| TP_H + FN_H + FP_H + TN_H: 1621911
    len(label_mask_current_deforestation_test): 54079850


[0.88739223 0.94877617 0.63476078 0.02999104 0.71091649 0.1717401
 0.12645899]
0.5650638220697976
threshold 0.5650638220697976


ic| label_current_deforestation_test_classified_incorrect.shape: (1622396,)
    predicted_test_classified_incorrect.shape: (1622396,)
ic| TP_H + FN_H + FP_H + TN_H: 1622396
    len(label_mask_current_deforestation_test): 54079850
ic| TP_H + FN_H + FP_H + TN_H: 1622396
    len(label_mask_current_deforestation_test): 54079850


[0.88740774 0.94878267 0.63471805 0.03000001 0.71091166 0.17184344
 0.12643491]
0.5650073766953199
threshold 0.5650073766953199


ic| label_current_deforestation_test_classified_incorrect.shape: (1622586,)
    predicted_test_classified_incorrect.shape: (1622586,)
ic| TP_H + FN_H + FP_H + TN_H: 1622586
    len(label_mask_current_deforestation_test): 54079850
ic| TP_H + FN_H + FP_H + TN_H: 1622586
    len(label_mask_current_deforestation_test): 54079850


[0.88742118 0.94879149 0.63470564 0.03000352 0.71084628 0.1718709
 0.12643008]
0.5650971637843818
threshold 0.5650971637843818


ic| label_current_deforestation_test_classified_incorrect.shape: (1622273,)
    predicted_test_classified_incorrect.shape: (1622273,)
ic| TP_H + FN_H + FP_H + TN_H: 1622273
    len(label_mask_current_deforestation_test): 54079850
ic| TP_H + FN_H + FP_H + TN_H: 1622273
    len(label_mask_current_deforestation_test): 54079850
ic| self.threshold_optimal: 0.5650638220697976


[0.88740798 0.94877971 0.63473046 0.02999773 0.71087908 0.17181384
 0.12644205]
threshold 0.5650638220697976


ic| label_current_deforestation_test_classified_incorrect.shape: (1622396,)
    predicted_test_classified_incorrect.shape: (1622396,)
ic| TP_H + FN_H + FP_H + TN_H: 1622396
    len(label_mask_current_deforestation_test): 54079850
ic| TP_H + FN_H + FP_H + TN_H: 1622396
    len(label_mask_current_deforestation_test): 54079850


[0.88740774 0.94878267 0.63471805 0.03000001 0.71091166 0.17184344
 0.12643491]
threshold 0.5650638220697976
(54079850,) (54079850,)


ic| self.m_optimal: {'AA': array([0.03000001]),
                     'UEO': array([0.12643491]),
                     'f1': 77.05,
                     'f1_H': array([0.27678233]),
                     'f1_L': array([0.91706947]),
                     'precision_H': array([0.71091166]),
                     'precision_L': array([0.88740774]),
                     'recall_H': array([0.17184344]),
                     'recall_L': array([0.94878267]),
                     'recall_Ltotal': array([0.63471805])}
ic| self.m_audited_optimal: {'f1': array([0.9439003]),
                             'precision': array([0.9230297]),
                             'recall': array([0.96573655])}


cm_audited [[53295960    58423]
 [   24857   700610]]
[0.9230297  0.96573655]
Result idx 0: {'other_uncertainty_metrics': {'sUEO': 0.3845722890780702, 'ece_score': 0.053347713360914366}, 'snippet_poi_results': [{'snippet_id': 0, 'coords': [550, 550], 'reference': 0, 'predicted': 0.0, 'alpha': array([132.42505,   1.     ,   1.     ], dtype=float32)}, {'snippet_id': 0, 'coords': [210, 610], 'reference': 1, 'predicted': 0.0, 'alpha': array([1., 1., 1.], dtype=float32)}, {'snippet_id': 0, 'coords': [207, 617], 'reference': 1, 'predicted': 0.0, 'alpha': array([1., 1., 1.], dtype=float32)}, {'snippet_id': 0, 'coords': [800, 200], 'reference': 1, 'predicted': 1.0, 'alpha': array([ 1.     , 49.57395,  1.     ], dtype=float32)}, {'snippet_id': 1, 'coords': [550, 115], 'reference': 1, 'predicted': 0.0, 'alpha': array([1.       , 1.5210117, 1.       ], dtype=float32)}, {'snippet_id': 1, 'coords': [430, 950], 'reference': 0, 'predicted': 0.0, 'alpha': array([1., 1., 1.], dtype=float32)}], 'uncerta

ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Label where deforestation past years is actual date (2019) = 1


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation different from 0 (no deforestation)


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation before 2008 is 2
D:/Jorge/datasets/deforestation/deforestation_before_2008/deforestation_before_2008_para.tif


ic| np.unique(label_past_deforestation_before_2008, return_counts=True): (array([  0, 215], dtype=uint8), array([124211220,  38957970], dtype=int64))
ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))
ic| label_per_date.shape: (17730, 9203, 1)


Removing bufer................
Mask label shape:  
 (17730, 9203, 1) 
 Unique values:  
 [0 1 2]
Tiles size:  3546 2300
Mask size:  (17730, 9200)


ic| image_stack.shape: (17730, 9203, 21)


Image shape:  (17730, 9203, 21)
mask:  (17730, 9200)
image stack:  (17730, 9200, 21)
ref : (17730, 9200, 1)
Training tiles:  [1, 3, 5, 8, 11, 13, 14, 20]
Validation tiles:  [6, 19]
Test tiles:  [2, 4, 7, 9, 10, 12, 15, 16, 17, 18]
-30.0 -16.0


ic| self.path_models+ '/' + self.method +'_'+str(0)+'.h5': 'D:/Jorge/datasets/deforestation/experiments/exp195/models/resunet_0.h5'


time:  0
(54236371,)
(array([0, 1], dtype=uint8), array([53470765,   765606], dtype=int64))
(17730, 9200)
(array([0., 1.], dtype=float32), array([161465114,   1650886], dtype=int64))


ic| self.predicted_unpad.shape: (17730, 9200)
    self.predicted.shape: (17730, 9200)
ic| predicted_test.shape: (81558000,)
ic| predicted_test.shape: (54236371,)
ic| np.unique(predicted, return_counts=True): (array([0., 1.], dtype=float32), array([161465114,   1650886], dtype=int64))
    np.unique(predicted_larger_than_min_area, return_counts=True): (array([0., 1.], dtype=float32), array([161736422,   1379578], dtype=int64))
ic| np.unique(ignored_polygons, return_counts=True): (array([0., 1.], dtype=float32), array([162844692,    271308], dtype=int64))
ic| self.f1: 78.78, self.precision: 88.6, self.recall: 70.91
ic| self.label_mask_val.shape: (16311600,)
ic| self.label_mask_val_valid.shape: (9418680,)
ic| f1_val: 78.96
    precision_val: 87.89
    recall_val: 71.68
    mAP_val: 86.7


D:/Jorge/datasets/deforestation/Para/deforestation_past_years.tif
Loaded deforestation past years


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Label where deforestation past years is actual date (2019) = 1


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation different from 0 (no deforestation)


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation before 2008 is 2
D:/Jorge/datasets/deforestation/deforestation_before_2008/deforestation_before_2008_para.tif


ic| np.unique(label_past_deforestation_before_2008, return_counts=True): (array([  0, 215], dtype=uint8), array([124211220,  38957970], dtype=int64))
ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))
ic| label_per_date.shape: (17730, 9203, 1)


(array([0., 1.], dtype=float32), array([162316504,    799496], dtype=int64))
[0. 1.]


ic| self.label_mask.shape: (17730, 9200)
ic| self.mask_amazon_ts.shape: (17730, 9200)
ic| self.label_mask_test.shape: (81558000,)
ic| self.error_mask_test.shape: (54102424,)
ic| trainer.dataset.previewLims1: array([2200, 3200, 6900, 7900])
    trainer.dataset.previewLims2: array([ 500, 1500, 3500, 4500])
ic| np.unique(trainer.mask_amazon_ts[lims[0]:lims[1], lims[2]:lims[3]]): array([1], dtype=uint8)
ic| np.unique(trainer.mask_amazon_ts[lims[0]:lims[1], lims[2]:lims[3]], return_counts=True): (array([1], dtype=uint8), array([1000000], dtype=int64))
Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).
Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).
Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).


(54102424,) (54102424,)
0.4216257755386668


ic| bounds: (0.0015, 0.9985)


0.048271416877271794
0.38232011321635484
threshold 0.38232011321635484


c:\Users\jchamorro\Anaconda3\envs\tf2\lib\site-packages\scipy\optimize\_minimize.py:783: RuntimeWarning: Method 'bounded' does not support relative tolerance in x; defaulting to absolute tolerance.
  warn("Method 'bounded' does not support relative tolerance in x; "
ic| label_current_deforestation_test_classified_incorrect.shape: (2033069,)
    predicted_test_classified_incorrect.shape: (2033069,)
ic| TP_H + FN_H + FP_H + TN_H: 2033069
    len(label_mask_current_deforestation_test): 54102424
ic| TP_H + FN_H + FP_H + TN_H: 2033069
    len(label_mask_current_deforestation_test): 54102424


[0.93816898 0.93289751 0.54353661 0.03757815 0.74937899 0.39669262
 0.10749978]
0.6176798867836452
threshold 0.6176798867836452


ic| label_current_deforestation_test_classified_incorrect.shape: (1183520,)
    predicted_test_classified_incorrect.shape: (1183520,)
ic| TP_H + FN_H + FP_H + TN_H: 1183520
    len(label_mask_current_deforestation_test): 54102424
ic| TP_H + FN_H + FP_H + TN_H: 1183520
    len(label_mask_current_deforestation_test): 54102424


[0.90545798 0.93029069 0.65142795 0.02187554 0.71334744 0.19240533
 0.15274446]
0.23685977356729035
threshold 0.23685977356729035


ic| label_current_deforestation_test_classified_incorrect.shape: (2936877,)
    predicted_test_classified_incorrect.shape: (2936877,)
ic| TP_H + FN_H + FP_H + TN_H: 2936877
    len(label_mask_current_deforestation_test): 54102424
ic| TP_H + FN_H + FP_H + TN_H: 2936877
    len(label_mask_current_deforestation_test): 54102424


[0.96896405 0.92997428 0.41819257 0.05428365 0.78899563 0.52862252
 0.08296674]
0.49622785679192494
threshold 0.49622785679192494


ic| label_current_deforestation_test_classified_incorrect.shape: (1592727,)
    predicted_test_classified_incorrect.shape: (1592727,)
ic| TP_H + FN_H + FP_H + TN_H: 1592727
    len(label_mask_current_deforestation_test): 54102424
ic| TP_H + FN_H + FP_H + TN_H: 1592727
    len(label_mask_current_deforestation_test): 54102424


[0.9216641  0.93232568 0.6018345  0.02943911 0.72818069 0.30260806
 0.126283  ]
0.4977950374501111
threshold 0.4977950374501111


ic| label_current_deforestation_test_classified_incorrect.shape: (1587465,)
    predicted_test_classified_incorrect.shape: (1587465,)
ic| TP_H + FN_H + FP_H + TN_H: 1587465
    len(label_mask_current_deforestation_test): 54102424
ic| TP_H + FN_H + FP_H + TN_H: 1587465
    len(label_mask_current_deforestation_test): 54102424


[0.92145051 0.93230673 0.60248323 0.02934185 0.72800419 0.30138073
 0.12655149]
0.46803632747768253
threshold 0.46803632747768253


ic| label_current_deforestation_test_classified_incorrect.shape: (1689644,)
    predicted_test_classified_incorrect.shape: (1689644,)
ic| TP_H + FN_H + FP_H + TN_H: 1689644
    len(label_mask_current_deforestation_test): 54102424
ic| TP_H + FN_H + FP_H + TN_H: 1689644
    len(label_mask_current_deforestation_test): 54102424


[0.92537471 0.93259829 0.58912546 0.03123047 0.73307856 0.32576366
 0.12153803]
0.48545965078872333
threshold 0.48545965078872333


ic| label_current_deforestation_test_classified_incorrect.shape: (1629327,)
    predicted_test_classified_incorrect.shape: (1629327,)
ic| TP_H + FN_H + FP_H + TN_H: 1629327
    len(label_mask_current_deforestation_test): 54102424
ic| TP_H + FN_H + FP_H + TN_H: 1629327
    len(label_mask_current_deforestation_test): 54102424


[0.92305007 0.93241605 0.59701421 0.0301156  0.73015887 0.31160683
 0.12442983]
0.4785271845547386
threshold 0.4785271845547386


ic| label_current_deforestation_test_classified_incorrect.shape: (1653160,)
    predicted_test_classified_incorrect.shape: (1653160,)
ic| TP_H + FN_H + FP_H + TN_H: 1653160
    len(label_mask_current_deforestation_test): 54102424
ic| TP_H + FN_H + FP_H + TN_H: 1653160
    len(label_mask_current_deforestation_test): 54102424


[0.92400446 0.93251862 0.59392112 0.03055612 0.73118158 0.31721843
 0.12328703]
0.48735475125940236
threshold 0.48735475125940236


ic| label_current_deforestation_test_classified_incorrect.shape: (1622777,)
    predicted_test_classified_incorrect.shape: (1622777,)
ic| TP_H + FN_H + FP_H + TN_H: 1622777
    len(label_mask_current_deforestation_test): 54102424
ic| TP_H + FN_H + FP_H + TN_H: 1622777
    len(label_mask_current_deforestation_test): 54102424


[0.92280035 0.93237855 0.59786686 0.02999453 0.72982948 0.31004688
 0.12474956]
0.49074397598706126
threshold 0.49074397598706126


ic| label_current_deforestation_test_classified_incorrect.shape: (1611358,)
    predicted_test_classified_incorrect.shape: (1611358,)
ic| TP_H + FN_H + FP_H + TN_H: 1611358
    len(label_mask_current_deforestation_test): 54102424
ic| TP_H + FN_H + FP_H + TN_H: 1611358
    len(label_mask_current_deforestation_test): 54102424


[0.92231086 0.9323698  0.59940656 0.02978347 0.72936155 0.30717434
 0.12530826]
0.48768264362685876
threshold 0.48768264362685876


ic| label_current_deforestation_test_classified_incorrect.shape: (1621690,)
    predicted_test_classified_incorrect.shape: (1621690,)
ic| TP_H + FN_H + FP_H + TN_H: 1621690
    len(label_mask_current_deforestation_test): 54102424
ic| TP_H + FN_H + FP_H + TN_H: 1621690
    len(label_mask_current_deforestation_test): 54102424


[0.92274748 0.93237395 0.59801194 0.02997444 0.72980822 0.3097796
 0.12479918]
0.48694824354176974
threshold 0.48694824354176974


ic| label_current_deforestation_test_classified_incorrect.shape: (1624218,)
    predicted_test_classified_incorrect.shape: (1624218,)
ic| TP_H + FN_H + FP_H + TN_H: 1624218
    len(label_mask_current_deforestation_test): 54102424
ic| TP_H + FN_H + FP_H + TN_H: 1624218
    len(label_mask_current_deforestation_test): 54102424


[0.92286187 0.93239409 0.59771221 0.03002117 0.72983491 0.31032524
 0.12468122]
0.4872934787818929
threshold 0.4872934787818929


ic| label_current_deforestation_test_classified_incorrect.shape: (1623004,)
    predicted_test_classified_incorrect.shape: (1623004,)
ic| TP_H + FN_H + FP_H + TN_H: 1623004
    len(label_mask_current_deforestation_test): 54102424
ic| TP_H + FN_H + FP_H + TN_H: 1623004
    len(label_mask_current_deforestation_test): 54102424


[0.92282504 0.9323842  0.59784497 0.02999873 0.72977656 0.31008426
 0.12474478]
0.4872137535562624
threshold 0.4872137535562624


ic| label_current_deforestation_test_classified_incorrect.shape: (1623284,)
    predicted_test_classified_incorrect.shape: (1623284,)
ic| TP_H + FN_H + FP_H + TN_H: 1623284
    len(label_mask_current_deforestation_test): 54102424
ic| TP_H + FN_H + FP_H + TN_H: 1623284
    len(label_mask_current_deforestation_test): 54102424


[0.92283136 0.93238714 0.59781622 0.03000391 0.72979474 0.31013597
 0.12472945]
0.48726013822082925
threshold 0.48726013822082925


ic| label_current_deforestation_test_classified_incorrect.shape: (1623127,)
    predicted_test_classified_incorrect.shape: (1623127,)
ic| TP_H + FN_H + FP_H + TN_H: 1623127
    len(label_mask_current_deforestation_test): 54102424
ic| TP_H + FN_H + FP_H + TN_H: 1623127
    len(label_mask_current_deforestation_test): 54102424
ic| self.threshold_optimal: 0.48726013822082925


[0.92282698 0.93238645 0.59782854 0.030001   0.72979256 0.31011347
 0.12473837]
threshold 0.48726013822082925


ic| label_current_deforestation_test_classified_incorrect.shape: (1623127,)
    predicted_test_classified_incorrect.shape: (1623127,)
ic| TP_H + FN_H + FP_H + TN_H: 1623127
    len(label_mask_current_deforestation_test): 54102424
ic| TP_H + FN_H + FP_H + TN_H: 1623127
    len(label_mask_current_deforestation_test): 54102424


[0.92282698 0.93238645 0.59782854 0.030001   0.72979256 0.31011347
 0.12473837]
threshold 0.48726013822082925
(54102424,) (54102424,)


ic| self.m_optimal: {'AA': array([0.030001]),
                     'UEO': array([0.12473837]),
                     'f1': 78.78,
                     'f1_H': array([0.43526722]),
                     'f1_L': array([0.92758209]),
                     'precision_H': array([0.72979256]),
                     'precision_L': array([0.92282698]),
                     'recall_H': array([0.31011347]),
                     'recall_L': array([0.93238645]),
                     'recall_Ltotal': array([0.59782854])}
ic| self.m_audited_optimal: {'f1': array([0.953481]),
                             'precision': array([0.95033541]),
                             'recall': array([0.95664747])}


cm_audited [[53335234    36529]
 [   31676   698985]]
[0.95033541 0.95664747]
Result idx 1: {'other_uncertainty_metrics': {'sUEO': 0.4216257755386668, 'ece_score': 0.048271416877271794}, 'snippet_poi_results': [{'snippet_id': 0, 'coords': [550, 550], 'reference': 0, 'predicted': 0.0, 'alpha': array([136.90787,   1.     ,   1.     ], dtype=float32)}, {'snippet_id': 0, 'coords': [210, 610], 'reference': 1, 'predicted': 0.0, 'alpha': array([1., 1., 1.], dtype=float32)}, {'snippet_id': 0, 'coords': [207, 617], 'reference': 1, 'predicted': 0.0, 'alpha': array([1., 1., 1.], dtype=float32)}, {'snippet_id': 0, 'coords': [800, 200], 'reference': 1, 'predicted': 1.0, 'alpha': array([1.     , 5.56545, 1.     ], dtype=float32)}, {'snippet_id': 1, 'coords': [550, 115], 'reference': 1, 'predicted': 0.0, 'alpha': array([1., 1., 1.], dtype=float32)}, {'snippet_id': 1, 'coords': [430, 950], 'reference': 0, 'predicted': 0.0, 'alpha': array([1., 1., 1.], dtype=float32)}], 'uncertainty_result': {'metrics'

ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Label where deforestation past years is actual date (2019) = 1


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation different from 0 (no deforestation)


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation before 2008 is 2
D:/Jorge/datasets/deforestation/deforestation_before_2008/deforestation_before_2008_para.tif


ic| np.unique(label_past_deforestation_before_2008, return_counts=True): (array([  0, 215], dtype=uint8), array([124211220,  38957970], dtype=int64))
ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))
ic| label_per_date.shape: (17730, 9203, 1)


Removing bufer................
Mask label shape:  
 (17730, 9203, 1) 
 Unique values:  
 [0 1 2]
Tiles size:  3546 2300
Mask size:  (17730, 9200)


ic| image_stack.shape: (17730, 9203, 21)


Image shape:  (17730, 9203, 21)
mask:  (17730, 9200)
image stack:  (17730, 9200, 21)
ref : (17730, 9200, 1)
Training tiles:  [1, 3, 5, 8, 11, 13, 14, 20]
Validation tiles:  [6, 19]
Test tiles:  [2, 4, 7, 9, 10, 12, 15, 16, 17, 18]
-30.0 -16.0


ic| self.path_models+ '/' + self.method +'_'+str(0)+'.h5': 'D:/Jorge/datasets/deforestation/experiments/exp196/models/resunet_0.h5'


time:  0
(54236371,)
(array([0, 1], dtype=uint8), array([53470765,   765606], dtype=int64))
(17730, 9200)
(array([0., 1.], dtype=float32), array([160902353,   2213647], dtype=int64))


ic| self.predicted_unpad.shape: (17730, 9200)
    self.predicted.shape: (17730, 9200)
ic| predicted_test.shape: (81558000,)
ic| predicted_test.shape: (54236371,)
ic| np.unique(predicted, return_counts=True): (array([0., 1.], dtype=float32), array([160902353,   2213647], dtype=int64))
    np.unique(predicted_larger_than_min_area, return_counts=True): (array([0., 1.], dtype=float32), array([161505108,   1610892], dtype=int64))
ic| np.unique(ignored_polygons, return_counts=True): (array([0., 1.], dtype=float32), array([162513245,    602755], dtype=int64))
ic| self.f1: 78.28, self.precision: 80.64, self.recall: 76.06
ic| self.label_mask_val.shape: (16311600,)
ic| self.label_mask_val_valid.shape: (9393985,)
ic| f1_val: 86.43
    precision_val: 89.66
    recall_val: 83.42
    mAP_val: 86.01


D:/Jorge/datasets/deforestation/Para/deforestation_past_years.tif
Loaded deforestation past years


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Label where deforestation past years is actual date (2019) = 1


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation different from 0 (no deforestation)


ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))


Past deforestation before 2008 is 2
D:/Jorge/datasets/deforestation/deforestation_before_2008/deforestation_before_2008_para.tif


ic| np.unique(label_past_deforestation_before_2008, return_counts=True): (array([  0, 215], dtype=uint8), array([124211220,  38957970], dtype=int64))
ic| np.unique(deforestation_past_years, return_counts=True): (array([   0, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
                                                                    2018, 2019, 2020, 2021], dtype=uint16),
                                                              array([132185553,   3150503,   4571354,    864429,    903608,   1299506,
                                                                      2477971,   1561686,   1459696,    969060,    644976,   2209014,
                                                                      2100204,   5257014,   3514616], dtype=int64))
ic| label_per_date.shape: (17730, 9203, 1)


(array([0., 1.], dtype=float32), array([162296140,    819860], dtype=int64))
[0. 1.]


ic| self.label_mask.shape: (17730, 9200)
ic| self.mask_amazon_ts.shape: (17730, 9200)
ic| self.label_mask_test.shape: (81558000,)
ic| self.error_mask_test.shape: (53942169,)
ic| trainer.dataset.previewLims1: array([2200, 3200, 6900, 7900])
    trainer.dataset.previewLims2: array([ 500, 1500, 3500, 4500])
ic| np.unique(trainer.mask_amazon_ts[lims[0]:lims[1], lims[2]:lims[3]]): array([1], dtype=uint8)
ic| np.unique(trainer.mask_amazon_ts[lims[0]:lims[1], lims[2]:lims[3]], return_counts=True): (array([1], dtype=uint8), array([1000000], dtype=int64))
Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).
Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).
Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).


(53942169,) (53942169,)
0.2857458654145891


In [ ]:
print(results)

[{'other_uncertainty_metrics': {'sUEO': 0.3670126015642983, 'ece_score': 0.04906518334555479}, 'uncertainty_result': {'metrics': {'precision_L': array([0.8460478]), 'recall_L': array([0.92707223]), 'recall_Ltotal': array([0.55478324]), 'AA': array([0.03000072]), 'precision_H': array([nan]), 'recall_H': array([0.]), 'UEO': array([0.23447353]), 'f1_L': array([0.88470877]), 'f1_H': array([nan]), 'f1': 67.01}, 'metrics_audited': {'precision': array([0.90452009]), 'recall': array([0.9563582]), 'f1': array([0.92971712])}, 'exp': 196}}, {'other_uncertainty_metrics': {'sUEO': 0.0, 'ece_score': 0.01947295218764906}, 'uncertainty_result': {'metrics': {'precision_L': array([nan]), 'recall_L': array([0.]), 'recall_Ltotal': array([0.]), 'AA': array([0.03435077]), 'precision_H': array([nan]), 'recall_H': array([0.]), 'UEO': array([0.54008159]), 'f1_L': array([nan]), 'f1_H': array([nan]), 'f1': 0.0}, 'metrics_audited': {'precision': array([1.]), 'recall': array([0.96602314]), 'f1': array([0.98271797]

In [ ]:
print(len(results))

10


In [ ]:
results[9]

{'other_uncertainty_metrics': {'sUEO': 0.5404739587669327,
  'ece_score': 0.03641546979657238},
 'uncertainty_result': {'metrics': {'precision_L': array([0.92989761]),
   'recall_L': array([0.93764161]),
   'recall_Ltotal': array([0.503057]),
   'AA': array([0.02999948]),
   'precision_H': array([0.58242773]),
   'recall_H': array([0.18413217]),
   'UEO': array([0.26910476]),
   'f1_L': array([0.93375355]),
   'f1_H': array([0.27980509]),
   'f1': 69.74},
  'metrics_audited': {'precision': array([0.96224463]),
   'recall': array([0.9665439]),
   'f1': array([0.96438947])},
  'exp': 205}}

In [ ]:
trainer.f1

69.74

In [ ]:
print(trainer.f1)

69.74
